### ISSUE TITLE
xetex gobbles CPU with --new-chroot

### ISSUE THREAD

**Issue by pghmcfc** [rpm-software-management/mock#100]
If I try to build a package that pulls in the tetex stack at build time (such as `pari`) with `--new-chroot`, I find that a scriptlet invocation of `xetex` seems to get stuck, gobbling CPU, leading me eventually to have to kill it. With `--old-chroot` the scriptlets execute quickly and without issue.

Any ideas why this should be?

**Comment by xsuchy** [comment]
This is because networking is by default off with systemd-nspawn.

See this part in config:
```
# config_opts['use_nspawn'] = True
# If you're using nspawn, then by default networking will be turned off
# for rpmbuild.  This helps ensure more reproducible builds.                                                                                                                         
# config_opts['rpmbuild_networking'] = False
```

**Comment by pghmcfc** [comment]
> This is because networking is by default off with systemd-nspawn.

No, it isn't. Adding "`config_opts['rpmbuild_networking'] = True`" does not help, and the problem does not manifest in Fedora koji, where networking is also disabled.

**Comment by xsuchy** [comment]
I cannot reproduce it.
```
wget https://kojipkgs.fedoraproject.org//packages/pari/2.9.3/3.fc27/src/pari-2.9.3-3.fc27.src.rpm
mock -r fedora-26-x86_64 --new-chroot pari-2.9.3-3.fc27.src.rpm
```
works fine even with disabled networking.

**Comment by pghmcfc** [comment]
Hmm, I updated mock to 1.4.3 from updates-testing and now it works. I suspect it was the device nodes that did it.
Thanks for looking at it anyway.
