### ISSUE TITLE
The openmandriva-rolling-i686 chroot doesn't work

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/mock#1012]
### Short description of the problem

The `openmandriva-rolling-i686` chroot doesn't work.

### Output of `rpm -q mock`

```
OpenMandriva Rolling - i686                     306  B/s | 153  B     00:00    
Errors during downloading metadata for repository 'openmandriva-rolling':
  - Status code: 404 for http://distro.ibiblio.org/openmandriva/rolling/repository/i686/main/release/repodata/repomd.xml (IP: 152.19.134.43)
  - Status code: 404 for http://abf-downloads.openmandriva.org/rolling/repository/i686/main/release/repodata/repomd.xml (IP: 140.211.169.10)
Error: Failed to download metadata for repo 'openmandriva-rolling': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

### Steps to reproduce issue

1. `wget https://raw.githubusercontent.com/fedora-copr/test-data-copr-backend/main/to_prune/00999998-dummy-pkg/dummy-pkg-2-1.fc34.src.rpm`
2. `mock -r openmandriva-rolling-i686 dummy-pkg-2-1.fc34.src.rpm`

### Any additional notes

The rest of the openmandriva chroots such as the following, work fine

- `openmandriva-rolling-x86_64`
- `openmandriva-rolling-aarch64`
- `openmandriva-cooker-x86_64`
- `openmandriva-cooker-i686`
- `openmandriva-cooker-aarch64`

**Comment by Conan-Kudo** [comment]
@berolinux, do we still have a functioning i686 root for package builds?

**Comment by berolinux** [comment]
We have dropped i686 from rolling for the time being, since we aren't making i686 releases. It still exists in cooker (the development branch) and might come back to rolling at some point if someone volunteers to maintain it.

**Comment by FrostyX** [comment]
I just encountered the issue again. Also `openmandriva-cooker-i686` doesn't work. Should we retire those configs? I can send a PR moving them to the `eol` directory.

**Comment by berolinux** [comment]
Yes, we consider i686 a dead platform (but are keeping the files around just in case anyone wants to revive the port at some point).
