### ISSUE TITLE
Multiple mock instances interfering with each other's mounts

### ISSUE THREAD

**Issue by pghmcfc** [rpm-software-management/mock#103]
If I run multiple instances of mock at the same time on the same host (different buildroots), I often, but not always, end up with warnings like this at the end of one of their runs:
```
INFO: Done(/home/paul/cfo-build/perl-Net-SSLeay/trunk/perl-Net-SSLeay-1.81-4.0.cf.fc25.src.rpm) Config(city-fan-fedora-rawhide-i686) 0 minutes 32 seconds
INFO: Results and/or logs in: /var/lib/mock/city-fan-rawhide-i686/result
Finish: run
INFO: unmounting tmpfs.
WARNING: tmpfs-plugin: exception while umounting tmpfs! (cwd: /home/paul/cfo-build/perl-Net-SSLeay/trunk)
WARNING: tmpfs-plugin: exception while force umounting tmpfs! (cwd: /home/paul/cfo-build/perl-Net-SSLeay/trunk)
```
When this happens, I always find some bind-mounted filesystems still mounted in the target buildroot, e.g. in this case:
```
# mount | grep mock                                                                                                                  
mock_chroot_tmpfs on /var/lib/mock/city-fan-rawhide-i686/root type tmpfs (rw,relatime,seclabel,size=2097152k,nr_inodes=0,mode=755)
/dev/mapper/VgBuildSys-SrvNoBackup on /var/lib/mock/city-fan-rawhide-i686/root/srv/nb/distros type ext3 (rw,relatime,seclabel,data=ordered)
```
The former there is my buildroot and the latter is a bind mount for a local repo within the mock config.

This is particularly bad if I don't notice this problem and try to use the same buildroot again, whereupon mock may try to clean the buildroot before use and blow away the contents of my bind-mounted filesystem, since I haven't figured out any way of making this bind mount read-only.

**Comment by xsuchy** [comment]
I believe this has been resolved in commit cf8026f. Please try mock 1.4.8.
