### ISSUE TITLE
mock not re-using metadata and packages

### ISSUE THREAD

**Issue by istiak101** [rpm-software-management/mock#1037]
### Output of `rpm -q mock`

mock-3.5-1.el9.noarch

### Steps to reproduce issue

1. mock -r rhel+epel-9-x86_64 --init

2. mock doesn't use already fetched metadatas and packages from /var/cache/mock/rhel+epel-9-x86_64-bootstrap/dnf_cache

```
Complete!
Finish(bootstrap): dnf install
Start(bootstrap): creating root cache
Finish(bootstrap): creating root cache
Finish(bootstrap): chroot init
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start: cleaning package manager metadata
Finish: cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 3.5
INFO: Mock Version: 3.5
Start: dnf install
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Enterprise Linux - BaseO100% [================================] 714 kB/Red Hat Enterprise Linux Red Hat Enterprise Linux - BaseOS                                       170 kB/s | 7.8 MB     00:46    
Red Hat Enterprise Linux - AppStream                                    812 kB/s |  16 MB     00:20    
Red Hat Enterprise Linux - CodeReady Linux Builder                      638 kB/s | 4.5 MB     00:07    
Extra Packages for Enterprise Linux 9 - x86_64                           64 kB/s |  14 MB     03:43
```

Above metadata and some of the packages e.g (bash) were already downloaded in the bootstrap phase. Wouldn't it be efficient just to re-use the cache for available files?

**Comment by istiak101** [comment]
Also root cache rebuilds do not use cache from bootstrap cache and re-downloads everything in /var/cache/mock/rhel+epel-9-x86_64. This could be reused from /var/cache/mock/rhel+epel-9-x86_64-bootstrap if the cache didn't age out.

**Comment by praiskup** [comment]
Thank you for the report!

This is not an issue though.  These two {non-,}bootstrap cache directories
are generated using a completely different DNF/YUM/DNF5 stack version and
it is not considered safe to mixup the caches.

If you are _sure_ it is safe e.g. because the stacks don't differ (for
example building in EL9 chroot on EL9 host), we could have some "opt-in"
feature (patches are welcome, but this is not going to be trivial).
But it is perhaps easier to just turn-off the bootstrap chroot then via
`--no-bootstrap-chroot`.

**Comment by istiak101** [comment]
For workaround now I started using squid caching. I will try to send a patch.
