### ISSUE TITLE
Regression: Configure script not found in 1.4.2, works in 1.3.4

### ISSUE THREAD

**Issue by LorbusChris** [rpm-software-management/mock#104]
I'd like to report a possible regression:

When building an rpm for a project where [the configure script](https://github.com/coturn/coturn/blob/master/configure) is already included in the source (no autoconf)
it works in Koji (Mock 1.3.4, SRPM built on f26 with `rpmbuild --nodeps -bs turnserver.spec`)
but fails on COPR (Mock 1.4.2)
 
This is happening both when directly calling `./configure` or using the `%configure` macro.

Koji build log: https://kojipkgs.fedoraproject.org//work/tasks/6331/21086331/build.log

COPR build log: https://copr-be.cloud.fedoraproject.org/results/lorbus/turnserver/fedora-26-x86_64/00587455-turnserver/build.log.gz

Extract from COPR log:
```
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --confdir=/etc/turnserver --examplesdir=/usr/share/turnserver --schemadir=/usr/share/turnserver --manprefix=/usr/share --libdir=/usr/lib64
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --confdir=/etc/turnserver --examplesdir=/usr/share/turnserver --schemadir=/usr/share/turnserver --manprefix=/usr/share --libdir=/usr/lib64
/var/tmp/rpm-tmp.Eotw29: line 44: ./configure: No such file or directory
/var/tmp/rpm-tmp.Eotw29: line 44: ./configure: No such file or directory
RPM build errors:
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.Eotw29 (%build)
error: Bad exit status from /var/tmp/rpm-tmp.Eotw29 (%build)
    Bad exit status from /var/tmp/rpm-tmp.Eotw29 (%build)
    Bad exit status from /var/tmp/rpm-tmp.Eotw29 (%build)
```

The specfile used for both builds can be found here: https://github.com/LorbusChris/coturn-rpm

**Comment by xsuchy** [comment]
That is because your tar.gz contains only:
```
# tar zxvf turnserver-4.5.0.6.tar.gz 
  turnserver-4.5.0.6/
  turnserver-4.5.0.6/turnserver.spec
  turnserver-4.5.0.6/LICENSE
```

And that is because you submitted your build as mock-scm type. All params are just passed to mock-scm. Feel free to learn about it here:
  https://github.com/rpm-software-management/mock/wiki/Plugin-Scm
it does not download the tar.gz in SourceX for you.
