### ISSUE TITLE
Adjust centos-stream-8 mock configs for kojihub.stream.centos.org

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#1045]
CentOS Stream 8 is transitioning to be ahead of RHEL 8.
The Koji is changing from https://koji.mbox.centos.org to https://kojihub.stream.centos.org/

https://lists.centos.org/pipermail/centos-devel/2023-February/142762.html

The centos-stream-8 configs will need changes, at least for the Koji repo URL.

**Comment by xsuchy** [comment]
Hmm I still do not see the compose there https://kojihub.stream.centos.org/kojifiles/repos/dist-c8-stream-build/ :(

**Comment by hroncok** [comment]
it's https://kojihub.stream.centos.org/kojifiles/repos/c8s-build/latest/

**Comment by hroncok** [comment]
This has now been announced. https://lists.centos.org/pipermail/centos-devel/2023-March/142831.html

Could you please cut a new release of mock-core-configs?

**Comment by praiskup** [comment]
Yes, doing now.

**Comment by praiskup** [comment]
Released, added to [bodhi](https://bodhi.fedoraproject.org/updates/?search=mock-core-configs), tagged to [infra repositories](https://kojipkgs.fedoraproject.org/repos-dist/f37-infra/latest/) (so it will be auto-propagated to newly started Copr builders).
