### ISSUE TITLE
/usr/sbin/useradd: invalid option -- 'n'

### ISSUE THREAD

**Issue by kkzxak47** [rpm-software-management/mock#1050]
### Short description of the problem
koji 1.32.0
mock 3.5
shadow 4.7

"invalid option" error interrupted rpm build process in koji.
I guess the option should be '-N' ?

DEBUG util.py:540:  Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '82f34119fbf049ca8870178aa418431f', '-D', '/home/tmp_mock/testdrive-build-17-16/root', '-a', '--console=pipe', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=C.UTF-8', '--resolv-conf=off', '/usr/sbin/useradd', '-o', '-m', '-u', '974', '-g', '135', '-d', '/builddir', '-n', 'mockbuild'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8', 'SYSTEMD_NSPAWN_TMPFS_TMP': '0', 'SYSTEMD_SECCOMP': '0'} and shell False
DEBUG util.py:443:  /usr/sbin/useradd: invalid option -- 'n'

### Output of `rpm -q mock`
mock-3.5-1.ky10.noarch

OUTPUT HERE

### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

  PUT THE OUTPUT HERE
</details>

**Comment by xsuchy** [comment]
This is weird. On my system (F38), the command `useradd -n foobar` pass without error. But the `-n` option is not documented. And I even cannot find it the code of useradd. Not even in history. On the other hand Mock is using this option for ages - so I even cannot find why it was added in first place. 
@praiskup you are better in C - can you check the code https://github.com/shadow-maint/shadow/blob/master/src/useradd.c what -n actually does?

**Comment by xsuchy** [comment]
Ah, Pavel pointed out that it may be downstream patch. And indeed.
https://src.fedoraproject.org/rpms/shadow-utils/blob/rawhide/f/shadow-4.12.3-redhat.patch
In past we could not use -N because RHEL5 does not recognize -N and has -n. Starting with RHEL6+ there is -N available. I am going to change it. 
But that means if somebody is still building for RHEL5 they have to alter the config and change `config_opts['useradd']`.
