### ISSUE TITLE
The bootstap mode is stilll annoying (-i installs packages into boostrap buildroot)

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/mock#1053]
### Short description of the problem

I was just experimenting with Gtk3 build of doublecmd, which failed. So I went into the build root `mock shell --unpriv`, executing the build manually, tweaking the bits. Then I figured I need to have `gtk3-devel` installed. So I just did:

```
$ mock -i gtk3-devel
```

While the command succeeds, there is still no `gtk3-devel` in the buildroot. What is going on :cursing_face: Finally, I have realized that the package is installed into the boostrap chroot and finally, I was able to install the package at the right place via `mock --no-bootstrap-chroot -i gtk3-devel`. But I wish the experience was not so surprising.

### Output of `rpm -q mock`

$ rpm -q mock
mock-3.5-2.fc38.noarch

### Steps to reproduce issue

1. 
2.
3.

Do not forget to mention full commandline with the mock command you executed.

**Comment by praiskup** [comment]
Thank you for the report (and sorry for the late reply).

This is likely related to #627.  Can you confirm you had two concurrently running mock processes for the same buildroot?  Work-around would be to exit from the first one before starting the installation.

> Finally, I have realized that the package is installed into the boostrap chroot and finally

Good catch!  I haven't noticed.  I thought mock uses some separate nspawn-generated mountpoint and it is bootstrap...

**Comment by voxik** [comment]
> This is likely related to #627. Can you confirm you had two concurrently running mock processes for the same buildroot? Work-around would be to exit from the first one before starting the installation.

Hm, I'd say that was not the case, but I am not really sure. My typical workflow is to be in the shell on one terminal while installing the additional dependencies from the other terminal. So that might be the case.

**Comment by praiskup** [comment]
Thanks.  Then I believe Mock after #1073 fixes this.
