### ISSUE TITLE
DNS resolution in chroot during rpmbuild behavior change since 1.4.1

### ISSUE THREAD

**Issue by krackajak** [rpm-software-management/mock#106]
*flamesuit on*

I know that expecting network connectivity in a chroot environment is horrible and completely defeats the purpose of using a chroot. I am fully aware that it is bad practice and why it is considered such. I don't like this use case either. That said, there is large change in behavior that started in version 1.4.1

I have a spec file that during the install phase fetches a file using curl from a trusted internal server via domain name. Prior to mock 1.4.1 this worked without any issue. After 1.4.1 curl fails to resolve the domain name with the error: 

curl: (6) Could not resolve host: <my_server>; Unknown error

This appears to only happen during the rpm build as running the same command used in the spec file alone in a chroot works without issue:

mock --chroot 'curl <my_server> > <some_file>'

There does not appear to be any notes mentioning disallowed DNS requests in the 1.4.1/1.4.2 changelog. Due to this and the fact that behavior is inconsistent between an rpmbuild in a chroot and running the command in singularly in the chroot, I'm inclined to think there is a bug here. 

The workaround is to add "--old-chroot" to the command and everything is back as it was.

**Comment by Frodox** [comment]
Try with 
```
config_opts['rpmbuild_networking'] = True
```
in config, or smth like `--with=rpmbuild_networking` from cli.

Which version do you use? Do you use original config and with 1.4.1 it works fine?
In case of 1.4.2 I do not see any critical changes, if 1.4.1 is fine...
https://github.com/rpm-software-management/mock/compare/mock-1.4.1-1...mock-1.4.2-1
maybe @xsuchy knows it better and can clarify changelog with *note*.

**Comment by xsuchy** [comment]
It is in first line of https://github.com/rpm-software-management/mock/wiki/Release-Notes-1.4.1 :

> Mock previously used chroot technology. Few past releases Mock offered systemd-nspawn which is modern container technology for better isolation. This release use systemd-nspawn as default. If you want to preserve previous behaviour you can use --old-chroot option.

You either use --old-chroot or enable `config_opts['rpmbuild_networking'] = True` which will enable networking inside of container.

Note that --new-chroot have been presented from some oldish 2.1.x version.

**Comment by krackajak** [comment]
Thanks for getting back to me. I was unfamiliar with the differences in systemd-nspawn and chroot technology.

**Comment by jtagcat** [comment]
For anyone in the future, there's also `--enable-network`
