### ISSUE TITLE
Dead link in manual pages

### ISSUE THREAD

**Issue by Jakuje** [rpm-software-management/mock#1067]
The manual page for mock still contains a link to the old https://apps.fedoraproject.org/packages/mock/ which was decommissioned several years ago:

https://github.com/rpm-software-management/mock/blob/039145c165ee54f7075de3f555257f353e86ddeb/mock/docs/mock.1#L508

I think it should point to the https://src.fedoraproject.org/rpms/mock or directly to this github repository.

**Comment by praiskup** [comment]
Thank you for the report.  Fixing in #1068.
