### ISSUE TITLE
openeuler repositories are terribly slow

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1080]
openeuler builds are very slow with mock becuase of the connectivity to the repo.openeuler.org (tested from us-east AWS):
```
DEBUG: OS                                               49 kB/s | 3.5 MB     01:12
DEBUG: everything                                       20 kB/s |  15 MB     12:21    
DEBUG: EPOL                                             15 kB/s | 4.0 MB     04:29    
```
@pkking is this expected or is it fixable?

**Comment by pkking** [comment]
Hi @praiskup, currently `repo.openeuler.org` was located in Hong Kong with bandwidth about 1000M, from our lab and monitor it work as expected.

And yes the speed is not fluent from global, we are planning to setup a `metalink` service to speedup, before that for user in North American we have to manually change repo to [OCF mirror](https://mirrors.ocf.berkeley.edu/openeuler/) such as https://github.com/lxc/lxc-ci/pull/744.

**Comment by pkking** [comment]
@Conan-Kudo multi baseurls will work as round-robin or priority? For most our use cases, the `repo.openeuler.org` should be pick as a prefer.

**Comment by Conan-Kudo** [comment]
In order priority (first one will always be tried first, etc.)

**Comment by zengchen1024** [comment]
@praiskup Could you try again by refering to the #1085 . Thanks.

**Comment by zengchen1024** [comment]
@praiskup Sorry the site of [ocf](https://mirrors.ocf.berkeley.edu/openeuler/) has not been scanned yet. It may still be slow if that site is not available. I will test it first, if it works, I will leave a message. Thanks.

**Comment by zengchen1024** [comment]
@praiskup You can try now again. Thanks.
