### ISSUE TITLE
Prepare for DNF 5, don't depend on `dnf`

### ISSUE THREAD

**Issue by evan-goode** [rpm-software-management/mock#1084]
Hi, I know the maintainers here have already made efforts to support DNF 5 (#894, #1027), but I'm filing this issue so y'all are aware of our plan to obsolete `dnf` in Fedora Rawhide by the end of the month.

(I'm filing issues with all the packages that currently depend on `dnf`)

Starting in Fedora 39, the `dnf` command will be provided by the `dnf5` package rather than the `dnf` package, and `dnf5` will obsolete `dnf`. The old DNF 4 Python API will still be provided by `python3-dnf`, as well as the DNF 4 command, as `/usr/bin/dnf-3`.

To avoid breaking the Fedora upgrade, mock should switch to depending on `python3-dnf` rather than `dnf`.

And since `/usr/bin/dnf` will soon point to DNF 5, which has a slightly different command-line interface, any use of the `/usr/bin/dnf` binary should be replaced with calls to `/usr/bin/dnf-3`.

At some point, mock should adopt DNF 5, but the immediate issue is removing the dependency on `dnf`. We are planning to replace DNF with DNF5 in Fedora Rawhide very soon, by 2023-06-01, and the `mock` package will break as long as it still depends on the `dnf` package.

For more information about the switch to DNF 5, see https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5.

**Comment by praiskup** [comment]
The compat with `dnf-4` (not dnf-3?) will have to be implemented, still not there.

What are your plans WRT build systems?  Do you plan to build (in Koji, Copr) Fedora 39 since 
day one (202306-01)?  Have you discussed this with Fedora infra team?

**Comment by hroncok** [comment]
It is actually dnf-3.

**Comment by praiskup** [comment]
I see, `dnf-3` comes from the `dnf-2` vs `dnf-3` time (python2 vs python3).

**Comment by praiskup** [comment]
See also the discussion here: https://pagure.io/releng/issue/11441

The conclusion seems to be we'll build Rawhide with DNF4 for some transition period.
For this, we need to ship an updated fedora-rawhide configuration (mock-core-configs)
with

```
config_opts["dnf_command"] = "/usr/bin/dnf-3"
config_opts["dnf_install_command"] = "install python3-dnf dnf-plugins-core"
```

Without this, Copr (and local Mock) will fail to build once the Rawhide chroot is changed.

Since `python3-dnf` provides `dnf-3` since ever (even on EL8), we might even consider
doing this for all Fedora versions.

**Comment by praiskup** [comment]
And actually -> we should even consider changing `system_dnf_command` option,
because Mock on Rawhide would use `/bin/dnf` for installing the bootstrap chroot.

**Comment by evan-goode** [comment]
> I see, `dnf-3` comes from the `dnf-2` vs `dnf-3` time (python2 vs python3).

Yes! I should have mentioned that; it's confusing for sure.
