### ISSUE TITLE
Custom CA certificates copying is broken

### ISSUE THREAD

**Issue by ezamriy** [rpm-software-management/mock#1094]
### Short description of the problem

Custom CA certificates copying from a host system to a chroot doesn't work. I see the following error in a root.log:

```
DEBUG file_util.py:20:  creating dir: /var/lib/mock/inferit-9_2-bootstrap-build-side-84-repo_16246/root/etc/pki/ca-trust
DEBUG package_manager.py:379:  Couldn't copy /etc/pki/ca-trust certs from host: [Errno 17] File exists: '/var/lib/mock/inferit-9_2-bootstrap-build-side-84-repo_16246/root/etc/pki/ca-trust'
```

The bug was introduced by the adf58f0c172dd8d5493ca5e8dead5ade23caf711 commit: the `file_util.mkdirIfAbsent(pki_dir)` call creates a `pki_dir` directory but accordingly to the shutil.copytree [documentation](https://docs.python.org/3/library/shutil.html#shutil.copytree) a destination directory should not exist:

> If dirs_exist_ok is false (the default) and dst already exists, a [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) is raised.

This error is not reproducible with `mock-3.5-1.el9.noarch` previously installed from the EPEL repository. 
 
### Output of `rpm -q mock`

`mock-4.0-1.el9.noarch` installed from the EPEL repository.

### Steps to reproduce issue

1. Install any EL9 system, add the EPEL repository and install mock from it
2. Add a custom CA certificate to /etc/pki/ca-trust/. I did something like that for my Koji:
    ```
    cp koji-ca.crt /etc/pki/ca-trust/source/anchors/koji-ca.crt
    update-ca-trust extract
    ```
4. Initialize any chroot (in my case Koji is doing that) with the `mock -r CONFIG_NAME init` command and check the root.log, you will see the following error:
    ```
    DEBUG package_manager.py:379:  Couldn't copy /etc/pki/ca-trust certs from host: [Errno 17] File exists: '/var/lib/mock/CONFIG_NAME/root/etc/pki/ca-trust'
    ```
    The `/etc/pki/ca-trust` directory in the chroot will be empty as well.
    I think it should be reproducible with any config because the [copy_certs](https://github.com/rpm-software-management/mock/blob/afcf9c4192a1baac0cc27fa99393853f56ba98ab/mock/py/mockbuild/package_manager.py#L340) function should be called anyway.

### Any additional notes

The commit that introduced the problem: adf58f0c172dd8d5493ca5e8dead5ade23caf711
Related issue: #588

Possible fix: either add the `dirs_exist_ok=True` argument to the `shutil.copytree` function call or don't create the destination directory `pki_dir` beforehand. I think the second one is better because the `dirs_exist_ok` was introduced only in Python 3.8.

**Comment by praiskup** [comment]
Thank you for the report.  So we actually never copy anything :-(

> Possible fix: either add the dirs_exist_ok=True argument to the shutil.copytree function call or don't create the destination directory pki_dir beforehand. I think the second one is better because the dirs_exist_ok was introduced only in Python 3.8.

The second solution though doesn't lead to copying new files from the source tree, aka "updating" the destination directory for subsequent mock calls.  I think we need `dirs_exist_ok=True` with something more complicated for Python 3.6 :-( nah.

**Comment by ezamriy** [comment]
> This is a serious issue; for example, this breaks RHEL 9 builds in the Red Hat Copr instance.

Yeah, the same happened with my Koji instance after update to the latest mock. I had to create a  dirty patch to make it work again.

**Comment by praiskup** [comment]
Has the problem disappeared with Mock 4.1?  We still have troubles with rhel-8 --use-bootstrap-image feature in Copr
https://github.com/fedora-copr/copr/issues/2758

**Comment by praiskup** [comment]
No, this is a different problem - Copr testsuite explicitly tries fedora:38 image for building epel-8.
