### ISSUE TITLE
Unable to conditionalize BuildRequires due to chroot missing macros from "special" (systemd) packages, otherwise always present in that distro

### ISSUE THREAD

**Issue by jnpkrn** [rpm-software-management/mock#11]
The more one wants to achieve in the packaging regarding the versatility,
the more of the subtle differences between real non-chrooted building
and the mock-based building (i.e. chroot mimicing such real target
system) comes to the light.

For pacemaker project packaging, I'd want to conditionalize BuildRequires
of `pkgconfig(dbus-1)` but (for simplicity) only if the target
distribution is using systemd as its init system, because otherwise it
makes no sense to build with DBus libraries -- pacemaker uses DBus API
of systemd to manage live cycle of configured units when this is
available.

What seemed natural was to use:

```
%if %{defined _unitdir}
BuildRequires: pkgconfig(dbus-1)
%endif
```

which works when building the package in a standard way, but fails
in mock (with new Fedora releases, at least), as apparently `_unitdir`
is not available at the time BuildRequires are being evaluated.
Systemd (`rpm -qf /usr/lib*/pkgconfig/systemd.pc`) is, understandably,
not considered a minimal build root requirement.

Now, I fully understand that one cannot normally expect to conditionalize
BRs based on RPM macros introduced with arbitrary packages, but still,
I consider systemd somewhat special, and would be nice to have this
knowledge about systemd in minimal/start-point build roots to be able
to utilize that yet for reasoning about necessary BuildRequires.
Alternatives are checks based on:
- distro-specific macros (incl.  version comparisons), but that
  doesn't really scale (I have no idea beyond Fedora and RHEL)
- indirect (and unreliable!) traces such as:
  - `__transaction_systemd_inhibit` macro presence introduced with
    http://rpm.org/gitweb?p=rpm.git;a=commit;h=90463ac
  - existence of `/usr/lib/os-release` file, coming from `fedora-release`
    package in Fedora, but hopefully wide-spread enough, exactly because
    of systemd propagates that heavily:
    https://www.freedesktop.org/software/systemd/man/os-release.html

Is there any reasonable solution to the original desire, either existing
or something that we could add?  I am mostly interested in the package
build systems not under my control, such as COPR (apparently I could
tweak the system on my own was it under my control).

**Comment by xsuchy** [comment]
Yes. You cannot use _unitdir for the decision making as systemd is not in @buildsys-build group. Which is the minimal buildroot for mock. 

In Copr you can workaround it and put systemd in minimal root (your project -> settings -> click on Edit on selected chroot -> add systemd to minimal chroot; and yes you have to do it for each chroot).

On general level - I think it is nonsense to judge on presence of _unitdir. There is a lot of RPM based distributions:
  https://en.wikipedia.org/wiki/Category:RPM-based_Linux_distributions
and there is no way you can say "I support all of them". You can support only some of them. So I suggest you to use the distribution macro for judgement.

```
%if %{?fedora} ...
%if %{?rhel} ....
```
I think it does not have sense to over engineer the stuff just because you want to say "it works everywhere" while you actually never build nor tested your package on e.g. on Aisanux.

**Comment by jnpkrn** [comment]
Hmm, looks like what I'd make a good use of is some kind of distro-meta information incl. which init system is used to overcome this chicken-and-egg problem. Distro-specific macros are a very simplistic form of this, but with the burden of interpreting what it means in given context pushed to the spec author.

I just wish there were more thoughts on how to make spec files rather universal incl. conditional BuildRequires. Here, at the very least, that `_unitdir` macro was defined directly by `rpm` package when applicable, just as `_initddir` is.

**Comment by xsuchy** [comment]
> Hmm, looks like what I'd make a good use of is some kind of distro-meta information incl. which init system is used to overcome this chicken-and-egg problem.

This must be resolved on distributions level. This cannot be resolved by mock itself.

**Comment by jnpkrn** [comment]
> I just wish there were more thoughts on how to make spec files
> rather universal incl. conditional BuildRequires. 

Fast-forward a few years:
https://github.com/rpm-software-management/rpm/pull/593

\o/

Will any extra integration work be needed in mock itself?

**Comment by jnpkrn** [comment]
Aha, it shall be there already:
https://github.com/rpm-software-management/mock/pull/247

**Comment by xsuchy** [comment]
Yes, mock is ahead. Once the rpm will be released, it should start working.
