### ISSUE TITLE
Unable to use loop devices under mock using systemd-nspawn

### ISSUE THREAD

**Issue by iso70** [rpm-software-management/mock#111]
When using the mock 1.3 series of releases, I have been successfully able to use "losetup" to set up loop devices in the "/dev/" directory under a mock environment and connect them to image files. After upgrading to the 1.4 series, no loop devices or loop-control are present under the " /dev/" directory when I list this directory from the mock shell. When I try to run losetup, I get the following error:

losetup: /var/lmc/lmc-disk-kjuuhz4s.img: failed to set up loop device: No such file or directory.

With mock 1.4.3, When I list the files in "/var/lib/mock/fedora-26-x86_64/root/dev/" from outside the mock environment, I can see that the loop and loop control devices exit.
When I get the inode number of the "/dev/" directory from inside and outside a mock shell, I can easily see they are different directories. It is as if mock creates the loop device files successfully in the "/dev/" directory during the mock environment initialization, but another device file system is mounted later on to to obscure the created files.
I have noticed that on the host system a "devtmpfs" is mounted under "/dev/" while from the mock shell a "tmpfs" is mounted on the mock environment's "/dev/" directory.

When running "mount" under the host, I get the following:
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=4009868k,nr_inodes=1002467,mode=755)

While when running it from the mock shell I get the follwing:
tmpfs on /dev type tmpfs (rw,nosuid,seclabel,mode=755)

**Comment by xsuchy** [comment]
See https://github.com/rpm-software-management/mock/pull/107
