### ISSUE TITLE
 Unable to use loop devices under mock using --old-chroot

### ISSUE THREAD

**Issue by iso70** [rpm-software-management/mock#112]
Since I ran into problems trying to create loop devices in a mock environment using systemd-nspawn, I tried to use the --old-chroot to revert back to the old chroot approach.
When using the --old-chroot, the loop-control and loop devices present under the host's "/dev/" are mirrored in the chroot's "/dev/", but when I try to create new loop devices using "losetup" from the mock shell, the loop devices are created in the host's "/dev/ but are not mirrored in the chroot's "/dev/".
If I exit and restart the mock shell, I can see the newly created loop devices in the chroot's "/dev/".
To get applications using loop devices to work correctly, I have to create a sufficient number of loop devices under the host's /dev/ before I start the mock shell. In this case, when I run applications requiring loop devices in the mock environment, they don't complain of the lack of loop devices.

**Comment by xsuchy** [comment]
https://github.com/rpm-software-management/mock/pull/107
