### ISSUE TITLE
Set fedora-rawhide to use DNF5

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#1147]
See
https://pagure.io/fesco/issue/3039

It is about time to set 

config_opts['package_manager'] = 'dnf5'

for fedora rawhide configs.

**Comment by praiskup** [comment]
One of the issues tracked in #894 seems like blocker: https://github.com/rpm-software-management/dnf5/issues/617

**Comment by praiskup** [comment]
Related [Fedora change proposal](https://pagure.io/fesco/issue/3096) and [discussion](https://discussion.fedoraproject.org/t/f40-change-proposal-build-with-dnf5-self-contained/94937).
