### ISSUE TITLE
EPEL bootstrap images disable installation of localisation files

### ISSUE THREAD

**Issue by lzaoral** [rpm-software-management/mock#1181]
### Output of `rpm -q mock`

mock-5.0-1.fc38.noarch

### Steps to reproduce issue

1.  Download the following SRPM: https://download.copr.fedorainfracloud.org/results/packit/openscanhub-openscanhub-91/epel-9-x86_64/06266098-osh/osh-0.9.3.git.20230811.123248.0a7fc02-1.el9.src.rpm
2.  ln -s /etc/mock/centos-stream+epel-9-aarch64.cfg ~/.config/mock/epel-9-aarch64.cfg
3.  mock -r epel-9-aarch64 osh-0.9.3.git.20230811.123248.0a7fc02-1.el9.src.rpm
4.  The build fails due to missing localisation files for Django.

The built package is `noarch` and the result on `x86_64` is the same as witnessed by the following COPR build: https://copr.fedorainfracloud.org/coprs/packit/openscanhub-openscanhub-91/build/6266098/.  Just my local machine is `aarch64`. 

5.  mock -r epel-9-aarch64 --scrub=all
6.  mock -r epel-9-aarch64 --no-bootstrap-image
7.  The package builds fine.

We already hit this issue in the past with our UBI and CS based images in OpenScanHub CI and we fixed it with the following patch:  https://github.com/openscanhub/openscanhub/commit/68d15e4617cfeb5ba108016730c97913f3eb8a0e

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>
INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['additional_packages'] = []
config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:{{ releasever }}'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['chrootuid'] = 1000
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['description'] = 'Fedora {{ releasever }}'
config_opts['dist'] = 'fc{{ releasever }}'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f{{ releasever }}\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '# repos\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/f{{ releasever '
 '}}-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled={{ not mirrored }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if mirrored %}\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing]\n'
 'name=updates-testing\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=fedora-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-debuginfo]\n'
 'name=updates-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing-debuginfo]\n'
 'name=updates-testing-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-source]\n'
 'name=updates-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[fedora-modular]\n'
 'name=Fedora Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-source]\n'
 'name=Fedora Modular $releasever - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular]\n'
 'name=Fedora Modular $releasever - $basearch - Updates\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Updates - Debug\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-source]\n'
 'name=Fedora Modular $releasever - Updates Source\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/SRPMS/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('aarch64',)
config_opts['macros'] = {'%_buildhost': 'fedora',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
                                                             'AlmaLinux 8 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-8': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '8 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '8) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL 8 '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'circlelinux+epel-8': {'description': ['Builds '
                                                                    'against '
                                                                    'Circle '
                                                                    'Linux 8 '
                                                                    'repositories, '
                                                                    'together '
                                                                    'with the '
                                                                    'official '
                                                                    'EPEL '
                                                                    'repositories.',
                                                                    'Project '
                                                                    'page: '
                                                                    'https://cclinux.org/']},
                             'rhel+epel-8': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '8 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-8': {'description': ['Builds against '
                                                              'Rocky Linux 8 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}},
 'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
                                                             'AlmaLinux 9 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-9': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '9 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '9) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'rhel+epel-9': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '9 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-9': {'description': ['Builds against '
                                                              'Rocky Linux 9 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}}}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.f5fb2w8s:/etc/resolv.conf',
 '--bind=/dev/btrfs-control',
 '--bind=/dev/mapper/control',
 '--bind=/dev/fuse',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-aarch64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                     'root': 'fedora-38-aarch64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-38-aarch64',
                 'compress': None,
                 'dir': '/var/cache/mock/fedora-38-aarch64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                 'root': 'fedora-38-aarch64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/fedora-38-aarch64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                      'root': 'fedora-38-aarch64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-38-aarch64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                        'root': 'fedora-38-aarch64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-aarch64',
                  'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                  'root': 'fedora-38-aarch64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/fedora-38-aarch64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                   'root': 'fedora-38-aarch64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-38-aarch64',
                'dirs': [],
                'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                'root': 'fedora-38-aarch64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-38-aarch64',
                    'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                    'root': 'fedora-38-aarch64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/fedora-38-aarch64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-38-aarch64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                        'root': 'fedora-38-aarch64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-aarch64',
                     'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                     'root': 'fedora-38-aarch64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-aarch64',
                  'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                  'root': 'fedora-38-aarch64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/fedora-38-aarch64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-aarch64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/fedora-38-aarch64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                     'root': 'fedora-38-aarch64'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/fedora-38-aarch64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                            'root': 'fedora-38-aarch64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-aarch64',
                  'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                  'root': 'fedora-38-aarch64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-38-aarch64',
                 'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                 'root': 'fedora-38-aarch64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/fedora-38-aarch64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
               'root': 'fedora-38-aarch64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-38-aarch64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                'root': 'fedora-38-aarch64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-38-aarch64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-38-aarch64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/fedora-38-aarch64/result',
                    'root': 'fedora-38-aarch64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '38'
config_opts['root'] = 'fedora-{{ releasever }}-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'aarch64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'aarch64'
config_opts['verbose'] = 1
Finish: run
</details>

edit: typos

**Comment by xsuchy** [comment]
For convience - The build log is here:
https://download.copr.fedorainfracloud.org/results/packit/openscanhub-openscanhub-91/epel-9-x86_64/06266098-osh/builder-live.log.gz

The error is
```
+ osh/hub/manage.py collectstatic --noinput
Traceback (most recent call last):
  File "/builddir/build/BUILD/openscanhub-0.9.3.git.20230811.123248.0a7fc02/osh/hub/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/models.py", line 92, in <module>
    class Group(models.Model):
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib/python3.9/site-packages/django/db/models/fields/related.py", line 1635, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/usr/lib/python3.9/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/usr/lib/python3.9/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/usr/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/lib/python3.9/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/usr/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 360, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 273, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/lib/python3.9/site-packages/django/utils/translation/trans_real.py", line 165, in __init__
    raise OSError('No translation files found for default language %s.' % settings.LANGUAGE_CODE)
OSError: No translation files found for default language en-us.
error: Bad exit status from /var/tmp/rpm-tmp.bfzrJz (%build)
```

**Comment by xsuchy** [comment]
Hmm, interresting. When I compare installed packages from root.log then the failed root.log and succeeded root.log do not differ.  But the failure is in `%build` phase.

**Comment by lzaoral** [comment]
The `/etc/rpm/macros.image-language-conf` contains the following code to modify the behaviour of the installation of language support by `rpm`:

```
$ podman run -it registry.access.redhat.com/ubi8:latest cat /etc/rpm/macros.image-language-conf
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:f825592ec46cf199de55c2352d5108b8ab361ab118a11597d84ccc264814d498
Copying config sha256:08ffb9f4b3b0a5388ce5c215c76edd19614e19ceb16bff87406dae5c2c71f127
Writing manifest to image destination
Storing signatures
%_install_langs C.utf8
```

**Comment by praiskup** [comment]
So apparently, `%_install_langs` affects `dnf --installroot` feature.  Thank you for the report.

**Comment by lzaoral** [comment]
This has broken EPEL development builds and the subsequent testing through Testing Farm in OpenScanHub CI.  Is there any way to disable bootstrap images compatible with Packit that we can deploy in the meantime?

cc: @kdudka

**Comment by praiskup** [comment]
I don't think there's a way to pick "no bootstrap" in Packit :-( but rather asking, @lachmanfrantisek?

I'm not completely sure it actually makes sense to "fake" this in Mock:
```
$ rpm --eval %_install_langs 
all
```

I have asked [RPM folks](https://github.com/rpm-software-management/rpm/issues/2623) first.

**Comment by lachmanfrantisek** [comment]
> I don't think there's a way to pick "no bootstrap" in Packit :-( but rather asking, @lachmanfrantisek?

I don't see a way how to do this on Packit's side since the logic is in Copr/mock.

**Comment by lzaoral** [comment]
@praiskup @lachmanfrantisek Could you please temporarily implement a workaround to disable bootstrap for EPEL builds either in COPR or Packit?  The @openscanhub CI has been red for more than three weeks now and it is blocking some PRs to be merged or undrafted.  Thank you!

**Comment by lzaoral** [comment]
@praiskup Thank you!  I confirm that both Mock 5.1 and COPR can now build the package successfully!
