### ISSUE TITLE
bootstrap image isn't pulled by Podman in Docker environment

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#1184]
Previous $Subject:

    Error: creating overlay mount to /var/lib/containers/storage/overlay/.../merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/.../diff:/var/lib/containers/storage/overlay/.../empty,ro": using mount program /usr/bin/fuse-overlayfs: unknown argument ignored: lazytime

### Short description of the problem
Mock 5.0 (running in a docker container) now fails with:
```
[2023-08-14T14:12:35.433Z] INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
[2023-08-14T14:12:35.433Z] Start(bootstrap): init plugins
[2023-08-14T14:12:35.433Z] INFO: selinux disabled
[2023-08-14T14:12:35.433Z] Finish(bootstrap): init plugins
[2023-08-14T14:12:35.433Z] Start: init plugins
[2023-08-14T14:12:35.433Z] INFO: selinux disabled
[2023-08-14T14:12:35.433Z] Finish: init plugins
[2023-08-14T14:12:35.433Z] INFO: Signal handler active
[2023-08-14T14:12:35.433Z] Start: run
[2023-08-14T14:12:35.688Z] INFO: Start(_topdir/SRPMS/daos-2.5.100-8.9772.g0e087585.fc38.src.rpm)  Config(rocky+epel-8-x86_64)
[2023-08-14T14:12:35.688Z] Start: clean chroot
[2023-08-14T14:12:35.688Z] Finish: clean chroot
[2023-08-14T14:12:35.688Z] Mock Version: 5.0
[2023-08-14T14:12:35.688Z] INFO: Mock Version: 5.0
[2023-08-14T14:12:35.688Z] Start(bootstrap): chroot init
[2023-08-14T14:12:35.688Z] INFO: calling preinit hooks
[2023-08-14T14:12:35.688Z] INFO: enabled root cache
[2023-08-14T14:12:35.688Z] INFO: enabled package manager cache
[2023-08-14T14:12:35.688Z] Start(bootstrap): cleaning package manager metadata
[2023-08-14T14:12:35.688Z] Finish(bootstrap): cleaning package manager metadata
[2023-08-14T14:12:35.688Z] INFO: Using bootstrap image: quay.io/rockylinux/rockylinux:8
[2023-08-14T14:12:35.688Z] INFO: Pulling image: quay.io/rockylinux/rockylinux:8
[2023-08-14T14:12:39.866Z] INFO: Copy content of container quay.io/rockylinux/rockylinux:8 to /var/lib/mock/rocky+epel-8-x86_64-bootstrap/root
[2023-08-14T14:12:39.866Z] time="2023-08-14T14:12:39Z" level=error msg="Unmounting /var/lib/containers/storage/overlay/d6d602e436a8cf9a0c74e1562ce3a81a2d24fe2449abf186d9db9c5a7ebc7580/merged: invalid argument"
[2023-08-14T14:12:39.866Z] Error: creating overlay mount to /var/lib/containers/storage/overlay/d6d602e436a8cf9a0c74e1562ce3a81a2d24fe2449abf186d9db9c5a7ebc7580/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/d6d602e436a8cf9a0c74e1562ce3a81a2d24fe2449abf186d9db9c5a7ebc7580/diff:/var/lib/containers/storage/overlay/d6d602e436a8cf9a0c74e1562ce3a81a2d24fe2449abf186d9db9c5a7ebc7580/empty,ro": using mount program /usr/bin/fuse-overlayfs: unknown argument ignored: lazytime
[2023-08-14T14:12:39.866Z] fuse: device not found, try 'modprobe fuse' first
[2023-08-14T14:12:39.866Z] fuse-overlayfs: cannot mount: No such file or directory
[2023-08-14T14:12:39.866Z] : exit status 1
```

### Output of `rpm -q mock`
`mock-5.0-1.fc38.noarch`

### Steps to reproduce issue

1. Create docker container with `mock` installed in it
2. Try to run `mock`

My full command line was `+ mock --configdir /…/mock -r rocky+epel-8-x86_64 '--disablerepo=*' --enablerepo '*-artifactory' '--disablerepo=*-debug*' --config-opts=releasever=8.6 '--disablerepo=sclo*' --define 'relval .9773.gf5529b32' --define 'scons_args BUILD_TYPE=dev' _topdir/SRPMS/example-1.1.100-8.9773.g12345679.fc38.src.rpm` but that would require you do a bunch of pre-`mock` setup to use fully.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>
INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['additional_packages'] = []
config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:{{ releasever }}'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['chrootuid'] = 1101
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['description'] = 'Fedora {{ releasever }}'
config_opts['dist'] = 'fc{{ releasever }}'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f{{ releasever }}\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '# repos\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/f{{ releasever '
 '}}-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled={{ not mirrored }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if mirrored %}\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing]\n'
 'name=updates-testing\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=fedora-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-debuginfo]\n'
 'name=updates-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing-debuginfo]\n'
 'name=updates-testing-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-source]\n'
 'name=updates-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[fedora-modular]\n'
 'name=Fedora Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-source]\n'
 'name=Fedora Modular $releasever - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular]\n'
 'name=Fedora Modular $releasever - $basearch - Updates\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Updates - Debug\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-source]\n'
 'name=Fedora Modular $releasever - Updates Source\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/SRPMS/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'c731ea6b2196',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
                                                             'AlmaLinux 8 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-8': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '8 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '8) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL 8 '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'circlelinux+epel-8': {'description': ['Builds '
                                                                    'against '
                                                                    'Circle '
                                                                    'Linux 8 '
                                                                    'repositories, '
                                                                    'together '
                                                                    'with the '
                                                                    'official '
                                                                    'EPEL '
                                                                    'repositories.',
                                                                    'Project '
                                                                    'page: '
                                                                    'https://cclinux.org/']},
                             'rhel+epel-8': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '8 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-8': {'description': ['Builds against '
                                                              'Rocky Linux 8 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}},
 'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
                                                             'AlmaLinux 9 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-9': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '9 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '9) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'rhel+epel-9': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '9 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-9': {'description': ['Builds against '
                                                              'Rocky Linux 9 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}}}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.8b9qf0m5:/etc/resolv.conf']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                     'root': 'fedora-38-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-38-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/fedora-38-x86_64/ccache/u1101/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                 'root': 'fedora-38-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/fedora-38-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                      'root': 'fedora-38-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-38-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                        'root': 'fedora-38-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-x86_64',
                  'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                  'root': 'fedora-38-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/fedora-38-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                   'root': 'fedora-38-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-38-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                'root': 'fedora-38-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-38-x86_64',
                    'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                    'root': 'fedora-38-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/fedora-38-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-38-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                        'root': 'fedora-38-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-x86_64',
                     'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                     'root': 'fedora-38-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-x86_64',
                  'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                  'root': 'fedora-38-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/fedora-38-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-38-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/fedora-38-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                     'root': 'fedora-38-x86_64'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/fedora-38-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                            'root': 'fedora-38-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-38-x86_64',
                  'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                  'root': 'fedora-38-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-38-x86_64',
                 'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                 'root': 'fedora-38-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/fedora-38-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
               'root': 'fedora-38-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-38-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                'root': 'fedora-38-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-38-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-38-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/fedora-38-x86_64/result',
                    'root': 'fedora-38-x86_64'}}
config_opts['print_main_output'] = False
config_opts['releasever'] = '38'
config_opts['root'] = 'fedora-{{ releasever }}-{{ target_arch }}'
Finish: run
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
</details>

**Comment by praiskup** [comment]
Thank you for the report.

Debugging with Docker is rather a hard task for me (I don't want to run Docker daemon anywhere nowadays), and `podman run --privileged` works fine here.

Any idea how to fix this?  We'll have to ask Podman folks what they suggest for the "Podman in Docker" use-cases, and if this is not Podman (or Docker) bug, we should turn off bootstrap_image feature in Docker.

Can you work-around this with `--no-bootstrap-image` for now?

**Comment by brianjmurrell** [comment]
> Debugging with Docker is rather a hard task for me (I don't want to run Docker daemon anywhere nowadays), and podman run --privileged works fine here.

While I understand that you might have a _personal_ preference not to use Docker any more (as do I -- as difficult as it can be sometimes), that's not what's happening in the real world (yet).  As great as Podman is, it's not a 100% drop-in replacement for Docker.   
 It has it's own unique fiddling that needs to be done with it to even get it close to being a drop-in replacement.  There are cases where Podman just doesn't work the same as Docker and as such cannot be simply "dropped in" to tooling systems that were designed to use Docker and don't have any support for Podman's specific peculiarities.

This is the second ticket I have filed about mock in Docker in as many months.

So while you might not want to install Docker on your personal machines, surely this (second ticket in as many months) is an indication that your CI/QA/whatever needs to be validating mock changes in Docker.

> Can you work-around this with --no-bootstrap-image for now?

Yes.  That is already what I have been doing.

But frankly the more important issue is having our CI systems break every other month because mock changes are not tested in Docker and that use case is released broken.  This is making mock very unreliable in environments that use Docker as their staging platform to run building and testing.

**Comment by praiskup** [comment]
Also, if you already use some CI with Mock, don't you want to test the CI directly here?

**Comment by brianjmurrell** [comment]
> Also, if you already use some CI with Mock, don't you want to test the CI directly here?

If you are suggesting what I think you are suggesting, that doesn't really seem to be the right place to do that.  Our CI system is tooled to test our software stack not Mock.  That's not saying it couldn't be, but rather it just doesn't seem to make sense for our CI system to be replicating what your CI system is already tooled to be doing -- testing Mock.  It just needs more test cases, clearly.

What CI system are you using to test Mock with?  Is it and it's tests public, able to be extended by contributors, where they can see the results of their PRs to do testing updates?

**Comment by praiskup** [comment]
GH Actions are just supplementary ATM, we test using shell/behave: https://rpm-software-management.github.io/mock/Releasing-Mock

Nevermind, I think I was able to reproduce the problem on F38 host with `moby-engine` with Mock in `docker run --cap-add=SYS_ADMIN --rm -ti registry.fedoraproject.org/fedora:rawhide`.  This doesn't happen with `docker run --privileged` for some reason.  This is contrary to our docs where we suggest `--cap-add=SYS_ADMIN` is enough.

**Comment by praiskup** [comment]
@brianjmurrell can you confirm `docker run --privileged` helps?

**Comment by brianjmurrell** [comment]
> @brianjmurrell can you confirm `docker run --privileged` helps?

It does not.  We have always used `--privileged=true`.  Here is an example: https://github.com/daos-stack/daos/actions/runs/6029765492/job/16360085720 in the _Build RPM_ step:

```
…
+ docker run --name mock-build-6029765492-leap15 --user build -v /jenkins/gha_runners/actions-runner3/_work/daos/daos:/jenkins/gha_runners/actions-runner3/_work/daos/daos -w /jenkins/gha_runners/actions-runner3/_work/daos/daos -v /jenkins/gha_runners/actions-runner3/_work/daos/daos/mock_result:/var/lib/mock/opensuse-leap-15.4-x86_64/result --privileged=true -e DAOS_FULLNAME=daos-stack -e DAOS_EMAIL=[redacted] -e DISTRO_VERSION=15.4 -e 'STAGE_NAME=Build RPM on Leap 15.4' -e CHROOT_NAME=opensuse-leap-15.4-x86_64 -e ARTIFACTORY_URL=https://artifactory.dc.hpdd.intel.com/ -e REPO_FILE_URL=https://artifactory.dc.hpdd.intel.com/artifactory/repo-files/ -e JENKINS_URL=https://build.hpdd.intel.com/ -e TARGET=leap15 mock-build ci/rpm/build.sh
…
error: Verifying a signature using certificate FEAB502539D846DB2C0961CA70AF9E8139DB7C82 (SuSE Package Signing Key <build@suse.de>):
  1. Certificate 70AF9E8139DB7C82 invalid: policy violation
      because: No binding signature at time 2018-05-25T18:14:58Z
  2. Certificate has no valid binding signature as of the signature's creation time, but is valid now.  The certificate has probably been stripped or minimized.
error: Verifying a signature using certificate FEAB502539D846DB2C0961CA70AF9E8139DB7C82 (SuSE Package Signing Key <build@suse.de>):
  1. Certificate 70AF9E8139DB7C82 invalid: policy violation
      because: No binding signature at time 2018-05-25T18:14:58Z
  2. Certificate has no valid binding signature as of the signature's creation time, but is valid now.  The certificate has probably been stripped or minimized.
opensuse-oss-proxy-artifactory                  965 kB/s | 988  B     00:00    
GPG key at file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE (0x3DBDC284) is already installed
opensuse-oss-proxy-artifactory                  1.1 MB/s | 1.1 kB     00:00    
GPG key at file:///usr/share/distribution-gpg-keys/opensuse/RPM-GPG-KEY-openSUSE-Backports (0x65176565) is already installed
opensuse-oss-proxy-artifactory                  915 kB/s | 937  B     00:00    
GPG key at file:///usr/share/distribution-gpg-keys/suse/RPM-GPG-KEY-SuSE-SLE-15 (0x39DB7C82) is already installed
error: Verifying a signature using certificate FEAB502539D846DB2C0961CA70AF9E8139DB7C82 (SuSE Package Signing Key <build@suse.de>):
  1. Certificate 70AF9E8139DB7C82 invalid: policy violation
      because: No binding signature at time 2018-05-25T20:11:47Z
  2. Certificate has no valid binding signature as of the signature's creation time, but is valid now.  The certificate has probably been stripped or minimized.
error: Verifying a signature using certificate FEAB502539D846DB2C0961CA70AF9E8139DB7C82 (SuSE Package Signing Key <build@suse.de>):
  1. Certificate 70AF9E8139DB7C82 invalid: policy violation
      because: No binding signature at time 2018-05-25T20:11:47Z
  2. Certificate has no valid binding signature as of the signature's creation time, but is valid now.  The certificate has probably been stripped or minimized.
```

**Comment by brianjmurrell** [comment]
> @brianjmurrell Mock from #1205 should help. Can you test?

It does seem to work.  Here's a [root.log/build.log zip bundle](https://github.com/daos-stack/daos/suites/15886182627/artifacts/906882492) if you want to examine.

**Comment by praiskup** [comment]
> > @brianjmurrell Mock from #1205 should help. Can you test?
> But then again, it seems to be [working without #1205](https://github.com/daos-stack/daos/suites/15892038683/artifacts/907063590).

I don't see those logs.  Have you used the release Mock 5.0 here?

> Now I am just confused.

Well, indeed - if you always use --privileged, then even unpatched Mock 5.0
should work out-of-box (even with bootstrap image, without automatic
fallback to non-image bootstrap).

**Comment by praiskup** [comment]
I closed by accident, but perhaps things got into OK state?  Please reopen if needed.
