### ISSUE TITLE
random centos stream build failures on COPR environments

### ISSUE THREAD

**Issue by lsm5** [rpm-software-management/mock#1191]
### Short description of the problem

centos stream builds on copr flaking on `podman pull quay.io/centos/centos:stream[8,9]`

### Output of `rpm -q mock`

Happens on copr environments and @FrostyX suspects it could be a mock problem

### Steps to reproduce issue

1. Happens randomly on centos stream build envs and goes away with a build retrigger
2. See: https://download.copr.fedorainfracloud.org/results/packit/containers-podman-19683/centos-stream+epel-next-8-aarch64/06326478-podman/builder-live.log.gz for example

Occurred at least twice in centos stream copr builds triggered by packit. No mock command executed manually.

**Comment by lsm5** [comment]
another example: `centos-stream+epel-next-8-aarch64` failure at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6267034/

**Comment by praiskup** [comment]
Mock 5.1 will keep re-trying 395fc07f796579b2c8c0463a5361aec847d592db, and then fallback to "normal boostrap" 79c36e81be4535b8e45bd33ac95a5b98b2951e37.  Thank you for the report, @lsm5.
