### ISSUE TITLE
./autogen.sh doesn't seem to work (with my versions of autotools)

### ISSUE THREAD

**Issue by pavlix** [rpm-software-management/mock#12]
Just tried to run `./autogen.sh`:

    # ./autogen.sh 
    configure.ac:15: error: AC_INIT should be called with package and version arguments
    /usr/share/aclocal-1.15/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
    configure.ac:15: the top level
    autom4te-2.69: /usr/bin/m4 failed with exit status: 1
    aclocal-1.15: error: echo failed with exit status: 1

Uncommenting `AC_INIT` doesn't help:

    # ./autogen.sh 
    configure.ac:15: installing 'build/install-sh'
    configure.ac:15: installing 'build/missing'
    automake-1.15: error: no 'Makefile.am' found for any configure output

  * autoconf 2.69
  * automake 1.15

**Comment by xsuchy** [comment]
It is not used any more (I just deleted it, so people are not confused).
Just write `tito build --rpm --test` to get RPM of last commit or `tito build --rpm` to get last tagged RPM.

**Comment by pavlix** [comment]
Thanks for the cleanup in commit  0e26135c4fda145035f682c06909832901d534a8.
