### ISSUE TITLE
Exit code >0 when a build with --postinstall fails to install the resulting package

### ISSUE THREAD

**Issue by frenzymadness** [rpm-software-management/mock#1207]
I'd like to reopen #42 because I think that the proposed behavior is reasonable and the reason for which the issue was closed doesn't apply anymore.

When I build a new or updated package I usually use `--postinstall` in my scripts to verify that the result is installable. If it's not, mock shows me an error like:
```
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
fedora                                                         82 kB/s |  15 kB     00:00    
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: 
 Problem: conflicting requests
  - nothing provides python3.12dist(qtpy) >= 2.4 needed by python3-qtconsole-5.4.4-1.fc40.noarch from @commandline
WARNING: Failed install built packages
INFO: Cleaning up build root ('cleanup_on_success=True')
```
but the command ends with exit code 0 so my script continues even if it should not. I believe it's reasonable to end with exit code higher than zero in these cases so automation can see that something is not right and the exit code corresponds to the error message.

The mentioned issue was closed with the reason that this is a problem in yum and nothing can be done in mock. I think it's not true anymore because when I try to install the same package with dnf (both 4 and 5) the exit code is 1 so it should be easy to detect and exit with the same exit code.

What do you think?

**Comment by praiskup** [comment]
> What do you think?

Agreed, reopening.
