### ISSUE TITLE
Please make new version of mock-core-configs

### ISSUE THREAD

**Issue by katnatek** [rpm-software-management/mock#1211]
### Short description of the problem
The actual released version of mock-core-configs (39) still have cauldron information on mageia-9 config files
This is problematic now that mageia 9 is officially released and when you need build for mageia 9 using mock

Related mageia bug https://bugs.mageia.org/show_bug.cgi?id=32230

### Output of `rpm -q mock`

I don't have mock in my system

### Steps to reproduce issue

1. install current mock-core-configs on mageia 9 (its from version 38 but no matter in version 39 also is valid)
2. The .cfg files for mageia 9 have cauldron information instead of real mageia 9 information

**Comment by praiskup** [comment]
Thank you for the request, will do with #1204
