### ISSUE TITLE
network errors

### ISSUE THREAD

**Issue by CermakM** [rpm-software-management/mock#122]
Hi, I have been recently having troubles with the network-related stuff. (Not more then a week I think)
For example
curl command yields
[12/-1] curl error: Could not resolve host: github.com
ping github.com yields
Name or service not known 

mock-1.4.6-1.fc26.src.rpm

Thank you for any suggestions!

**Comment by xsuchy** [comment]
From last release notes:
https://github.com/rpm-software-management/mock/wiki/Release-Notes-1.4.6

Previously when you used --private-network then the isolated network was used only during rpm build phase. And, e.g., for shell command, it was not used. This caused some confusion. Now the network is always switched when you specify --private-network.

And see releant part in config:
```
# Mock uses systemd-nspawn(1) by default. When use_nspawn is set to False,
# simple os.chroot() is used instead.
# config_opts['use_nspawn'] = True
# If you're using nspawn, then by default networking will be turned off                                                                                                         
# for rpmbuild.  This helps ensure more reproducible builds.
# config_opts['rpmbuild_networking'] = False
```

**Comment by CermakM** [comment]
Aah, right. Thank you for the clarification.
