### ISSUE TITLE
ELN builds failing on copr

### ISSUE THREAD

**Issue by lsm5** [rpm-software-management/mock#1238]
### Short description of the problem

ELN builds on copr are failing consistently:
1. https://copr.fedorainfracloud.org/coprs/packit/containers-crun-1321/build/6508068/
2. https://copr.fedorainfracloud.org/coprs/packit/containers-buildah-5081/build/6507964/

### Output of `rpm -q mock`

ELN environments on COPR

### Steps to reproduce issue

1. any ELN build triggered via packit

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  
```
Error: 
 Problem: cannot install both python3-3.12.0-2.eln131.x86_64 from eln-baseos and python3-3.11.5-1.fc38.x86_64 from @System
  - package python3-dnf-4.17.0-6.fc38.noarch from @System requires python(abi) = 3.11, but none of the providers can be installed
  - package python3-dnf-plugins-core-4.4.3-1.eln131.noarch from eln-baseos requires python(abi) = 3.12, but none of the providers can be installed
  - cannot install the best candidate for the job
```
</details>

**Comment by praiskup** [comment]
ELN Image request: https://github.com/fedora-eln/eln/issues/164

**Comment by lsm5** [comment]
Thanks @praiskup for the quick response and the ELN image request. That will hopefully keep us from disabling ELN tasks in packit.

**Comment by praiskup** [comment]
@lsm5 work-around is to switch to switch bootstrap configuration from "default" to "Enable" in Copr chroot config, this will turn off bootstrap image feature for you.

**Comment by lsm5** [comment]
> @lsm5 work-around is to switch to switch bootstrap configuration from "default" to "Enable" in Copr chroot config, this will turn off bootstrap image feature for you.

hmm, is that doable in ephemeral copr builds triggered by packit?

**Comment by praiskup** [comment]
Ok, ELN folks actually provide ELN container, per the linked issue!

Fedora Copr should be fixed: https://pagure.io/fedora-infra/ansible/c/c27aab6c3bbafd31649a84a663ce61b52c1087cb

**Comment by lachmanfrantisek** [comment]
> I'm not 100% sure, @lachmanfrantisek can you answer this question?

Ups, sorry for missing the ping.

So, is the ask for Packit to set the Copr config option and/or make it configurable via Packit config?

If it's in the Copr's API, we can try, but chroot-specific options are not as simple to use as the project ones.

**Comment by lsm5** [comment]
> Ok, ELN folks actually provide ELN container, per the linked issue!
> 
> Fedora Copr should be fixed: https://pagure.io/fedora-infra/ansible/c/c27aab6c3bbafd31649a84a663ce61b52c1087cb

@praiskup has the change landed already?

**Comment by praiskup** [comment]
Yes.

**Comment by lsm5** [comment]
> Yes.

eln failed few minutes ago on packit triggered build: https://copr.fedorainfracloud.org/coprs/packit/containers-aardvark-dns-394/build/6520711/

**Comment by lsm5** [comment]
ohh nvm, looks like some other unrelated issue.

**Comment by lsm5** [comment]
ELN builds succeeded at: https://github.com/containers/skopeo/pull/1960 . Closing this issue. Thanks!
