### ISSUE TITLE
Disable cleaning of /tmp when using systemd-nspawn

### ISSUE THREAD

**Issue by CermakM** [rpm-software-management/mock#124]
Hi,

When using mock with 'use_nspawn' = True, a clean /tmp directory is mounted whenever I mock --shell and unmounted on logout. Is it possible to disable this behavior and prevent /tmp from being cleaned? This was default using the old chroot. 
Tried using tmpfs:keep_mounted=True, but this has no effect. Also tried to find some tmp.conf in */tmpfiles.d/ but failed. 

Thanks.

**Comment by xsuchy** [comment]
AFAIK this is not possible. See https://bbs.archlinux.org/viewtopic.php?id=226438 Maybe @msekletar can comment on this.

**Comment by CermakM** [comment]
Ok, thanks.
