### ISSUE TITLE
Error: Unable to find a match: python3-dnf python3-dnf-plugins-core

### ISSUE THREAD

**Issue by denisgolius** [rpm-software-management/mock#1251]
### Short description of the problem
```console
Copr repository                                  76 kB/s | 5.1 kB     00:00    
determining the fastest mirror (17 hosts).. done.
OpenMandriva Rolling - x86_64                   5.6 MB/s |  20 MB     00:03    
No match for argument: python3-dnf
No match for argument: python3-dnf-plugins-core
Error: Unable to find a match: python3-dnf python3-dnf-plugins-core
WARNING: DNF command failed, retrying, attempt #2, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Updating Subscription Management repositories.
Unable to read consumer identity
```

### Output of `rpm -q mock`
`INFO: mock.py version 5.2 starting (python version = 3.11.3, NVR = mock-5.2-1.fc38`

### Steps to reproduce issue

1. Add new release tag of VictoriaMetrics to https://github.com/VictoriaMetrics/victoriametrics-lts-rpm/blob/master/vmsingle.spec#L2 or to other spec files
2. Wait while Fedora COPR finished build process
3. See results at https://copr.fedorainfracloud.org/coprs/victoriametrics/VictoriaMetrics-LTS/builds/

We use COPR to build VictoriaMetrics Single, Cluster and vmtools binaries. But builds for OpenMandriva OS can't compile for two months - see https://copr.fedorainfracloud.org/coprs/victoriametrics/VictoriaMetrics-LTS/package/vmsingle/ . The same issue is for all packages. Does anybody have any suggestions to resolve this issue?

**Comment by praiskup** [comment]
Thank you for the report.  #1252 should fix this.

**Comment by denisgolius** [comment]
Hey @praiskup , maybe I missed something but is #1252 should fix my issue or I need to wait for mock release?

**Comment by praiskup** [comment]
Yes, please allow us some time to wrap up the release.
