### ISSUE TITLE
Problem: conflicting requests: package is filtered out by modular filtering

### ISSUE THREAD

**Issue by k0ste** [rpm-software-management/mock#1284]
Hi, I can't resolve problem with `mock` 5.3. I need dependency `golang 1.21`, but in `appstream` [official repo version is 1.20](https://centos.pkgs.org/8-stream/centos-appstream-x86_64/golang-1.20.6-2.module_el8+658+f14b2092.x86_64.rpm.html). In spec defined:

```rpm
BuildRequires: golang >= 1.21
```

And 1.21 version was pushed to `<my_custom_repo>`. But by some reason this package is "filtered".

Mock cmd:

```
/usr/bin/mock --config-opts='cache_topdir=/rpmbuild/cache' --enable-network --addrepo https://<my_custom_repo>  -r centos-stream-8-x86_64 --buildsrpm --spec=/rpmbuild/netdata.spec --resultdir=/rpmbuild/output/centos-stream-8-x86_64 --sources=/rpmbuild/sources
```

Actual error
```
DEBUG util.py:461:  Error:
DEBUG util.py:461:   Problem: conflicting requests
DEBUG util.py:461:    - package golang-1.21.3-4.el8.x86_64 from <my_custom_repo> is filtered out by modular filtering
```

Is there possible solution to turn off this filter?

**Comment by k0ste** [comment]
Also created [CS-1932](https://issues.redhat.com/browse/CS-1932) on JIRA

**Comment by praiskup** [comment]
Thank you for the question!

> Is there possible solution to turn off this filter?

Yes, if you want to use modular packages at the package build time, you probably want to enable the module by Mock, see the site-defaults documentation file:

```
# List of module commands to be executed when initializing chroot, before
# `chroot_setup_cmd`.  Each command is a pair like `(action, module_specs)`
# where `module_specs` is a comma-separated list of module specifications.
# The commands are executed in order they are configured here, and each
# `action` can be executed multiple times.
#
## Artificial example: (a) Disable any potentially enabled postgresql module
## stream, (b) enable _specific_ postgresql and ruby module streams,
## (c) install the development nodejs profile and (d) disable it immediately.
#config_opts['module_setup_commands'] = [
#  ('disable', 'postgresql'),
#  ('enable',  'postgresql:12, ruby:2.6'),
#  ('install', 'nodejs:13/development'),
#  ('disable', 'nodej
```

It is good idea to have a separate configuration option;  mock caches the modular configuration
into the root cache;  so anytime you change this config you should do --scrub=all (or similar).
