### ISSUE TITLE
Mageia 8, 9 and cauldron configuration files for aarch64 and armv7hl need to be updated

### ISSUE THREAD

**Issue by katnatek** [rpm-software-management/mock#1304]
### Short description of the problem
The users of mageia  9 and cauldron can't build for aarch64 and armv7hl  for mageia 8,9 & cauldron with the currtent configuration in mageia-8-aarch64.cfg , mageia-8- armv7hl.cfg , mageia-9-aarch64.cfg , mageia-9- armv7hl.cfg , mageia-cauldron-aarch64.cfg & mageia-cauldron- armv7hl.cfg

### Output of `rpm -q mock`

OUTPUT HERE
mock-5.1.1-1.mga9

### Steps to reproduce issue
See https://bugs.mageia.org/show_bug.cgi?id=32620

### Any additional notes
One of our packagers found the solution https://bugs.mageia.org/show_bug.cgi?id=32620#c44

The line 
config_opts['bootstrap_forcearch'] = '{{ target_arch }}'

Need to be added before the line
include('templates/mageia-branched.tpl')

**Comment by filochard** [comment]
Nota Bene : 
in mock-core-configs/etc/mock 
for each mageia version (n = 8, or  9, or cauldron) and each arch ({arch} = aarch64 , or  armv7hl)  there are 3 flavours
mageia -n-{arch}.cfg
mageia -n-{arch}-nonfree.cfg
mageia -n-{arch}-tainted.cfg

That means 18 cfg files to modify ....
Thanks

**Comment by Conan-Kudo** [comment]
The non-free/tainted configs are not in this repository, they are part of `mock-mageia-configs` that builds on top of `mock-core-configs`.

**Comment by filochard** [comment]
> The non-free/tainted configs are not in this repository, they are part of `mock-mageia-configs` that builds on top of `mock-core-configs`.

Sorry for the mistake

**Comment by wally-mageia** [comment]
During my local tests I didn't see any harm or drawbacks if only template files `templates/mageia-*.tpl` were modified with
`config_opts['bootstrap_forcearch'] = '{{ target_arch }}'`

In that way only a few files needs to be modified and native x86_64 builds works as well as i586/armv7hl/aarch64 builds on x86_64 host.

**Comment by filochard** [comment]
> During my local tests I didn't see any harm or drawbacks if only template files `templates/mageia-*.tpl` were modified with `config_opts['bootstrap_forcearch'] = '{{ target_arch }}'`
> 
> In that way only a few files needs to be modified and native x86_64 builds works as well as i586/armv7hl/aarch64 builds on x86_64 host.

Thanks to Wally for his work on this : 
he simplified widely the correction to bring
I have tested the additionof this line : 
`config_opts['bootstrap_forcearch'] = '{{ target_arch }}'`
 in mageia-branched.tpl 
 and in mageia-cauldron.tpl 

Mock works now for Mageia-9 and Mageia-cauldron for all the arches and for all the flavors (core, nonfree and tainted)

**Comment by katnatek** [comment]
> Thank you for the discussion here, folks!
> 
> We should first identify the reason why we need to override `bootstrap_forcearch` because it is a really weird requirement. Typically you install a native bootstrap chroot, and using the native tooling in bootstrap you install the --forcearch target chroot.

Maybe I need to explain better the issue, sorry bug reporting and english redaction are my kryptonite :dagger: 

In Mageia 9 we can't build for aarch64 and armv7hl from x86_64 systems since the update to mock 5.1.1, so is not native build, Jani Välimaa find why https://bugs.mageia.org/show_bug.cgi?id=32620#c33 , https://bugs.mageia.org/show_bug.cgi?id=32620#c35 , https://bugs.mageia.org/show_bug.cgi?id=32620#c44

**Comment by wally-mageia** [comment]
> Thank you for the discussion here, folks!
> 
> We should first identify the reason why we need to override `bootstrap_forcearch` because it is a really weird requirement. Typically you install a native bootstrap chroot, and using the native tooling in bootstrap you install the --forcearch target chroot.

Can it be because we are not using bootstrap image with Mageia?

**Comment by praiskup** [comment]
> Can it be because we are not using bootstrap image with Mageia?

I don't think this is the reason...?   bootstrap is always native, no matter if `--no-bootstrap-image` is used.

**Comment by praiskup** [comment]
Is this because `mageia-branched.tpl` is using `{{ target_arch }}` instead of `$basearch`?  At least that's how `fedora-branched.tpl` is created and it works(TM).

**Comment by wally-mageia** [comment]
> Is this because `mageia-branched.tpl` is using `{{ target_arch }}` instead of `$basearch`? At least that's how `fedora-branched.tpl` is created and it works(TM).

I did some local tests and using `$basearch` in repo URLs seems to be working in **x86_64** host with **aarch64** build without overriding `bootstrap_forcearch`. However in **i586** and **armv7hl** build `$basearch` translates to **i386** and mirrors aren't found.

In **aarch64** host `$basearch` translates in **armv7hl** build to **armhfp**, and again mirrors aren't found.
