### ISSUE TITLE
Group mock is preserved

### ISSUE THREAD

**Issue by leoleovich** [rpm-software-management/mock#132]
Hi there,
I am running commands in mock chroot like this:
```
mock -r /data/mock/<config>.cfg --chroot 'yum install <something>'
```
Version is 1.4.4
For whatever reason group of these files stays as `mock`.
```
~ ls -ld /data/mock/chroot/root/boot/efi
drwxr-sr-x. 3 root mock 4096 Oct 27 13:00 /data/mock/chroot/root/boot/efi
```
Any hint on this?
Thank you!

**Comment by xsuchy** [comment]
1)  You should rather use: `mock -r /data/mock/<config>.cfg install something'

2) No, I have no idea. But when I try it with something=zsh and then:
```
[root@dri<mock-chroot>//]#ls -l /usr/share/zsh/5.3.1/help/whence
-rw-r--r--. 1 root root 2393 14. čen 23.36 /usr/share/zsh/5.3.1/help/whence
....
$ ls -l /var/lib/mock/fedora-26-x86_64/root//usr/share/zsh/5.3.1/help/whence
-rw-r--r--. 1 root root 2393 14. čen 23.36 /var/lib/mock/fedora-26-x86_64/root//usr/share/zsh/5.3.1/help/whence
```

Closing till there is some reproducer.

**Comment by leoleovich** [comment]
To be fair it is actually happening during `mock --cleanup-after --init -v -r <config>`. Still checkin where exactly it is happening.

**Comment by leoleovich** [comment]
```
write(2, "DEBUG: ensuring that dir exists:"..., 71DEBUG: ensuring that dir exists: /data/mock/chroot
) = 71
stat("/data/mock/chroot", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
getuid()                                = 0
chown("/data/mock/chroot", 0, 156) = 0
chmod("/data/mock/chroot", 02775) = 0
```

**Comment by leoleovich** [comment]
if I has out this lines - everything works fine:
https://github.com/rpm-software-management/mock/blob/5fe79617c43e390390f03856fff7c72004be5835/mock/py/mockbuild/buildroot.py#L118-L119

**Comment by xsuchy** [comment]
1) you should not run mock as root. You should rather add yourself to group 'mock'

2) even if I try your command I get:

```
$ ls -ld /var/lib/mock/fedora-26-x86_64/
drwxrwsr-x 4 root mock 4096 31. říj 20.22 /var/lib/mock/fedora-26-x86_64/
$ ls -ld /var/lib/mock/fedora-26-x86_64/root
dr-xr-xr-x 18 root root 4096 31. říj 20.22 /var/lib/mock/fedora-26-x86_64/root
```
And everything under that root/ directory is owned as root:root

That chown() you mentioned just change ownership of base dir which in my case is `/var/lib/mock/fedora-26-x86_64`

**Comment by leoleovich** [comment]
In this case root is in mock group. So during this change it gets set group
id and is not getting removed, as you demonstrated in your paste:

drwxrwsr-x

Set group id on directory means all files created later will inherit group
mock, which is exactly our problem as it does not get unset afterwards.
Please try to install packages to chroot and run find with "-perm -2000".
The problem is when these files are used in tar with preserve permission
option specified. During unpacking it on server it tries to assign user
group which does not exist.
Right now I have to run ugly find to determinate all these files with set
group id and group mock and change it back.

On 31 Oct 2017 7:26 PM, "Miroslav Suchý" <notifications@github.com> wrote:


   1.

   you should not run mock as root. You should rather add yourself to group
   'mock'
   2.

   even if I try your command I get:

$ ls -ld /var/lib/mock/fedora-26-x86_64/
drwxrwsr-x 4 root mock 4096 31. říj 20.22 /var/lib/mock/fedora-26-x86_64/
$ ls -ld /var/lib/mock/fedora-26-x86_64/root
dr-xr-xr-x 18 root root 4096 31. říj 20.22 /var/lib/mock/fedora-26-x86_64/root

And everything under that root/ directory is owned as root:root

That chown() you mentioned just change ownership of base dir which in my
case is /var/lib/mock/fedora-26-x86_64

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rpm-software-management/mock/issues/132#issuecomment-340880237>,
or mute the thread

**Comment by leoleovich** [comment]
@xsuchy any thoughts on this?
