### ISSUE TITLE
ERROR building aircrack-ng

### ISSUE THREAD

**Issue by xosevp** [rpm-software-management/mock#134]
https://koji.fedoraproject.org/koji/taskinfo?taskID=22871098

-- https://koji.fedoraproject.org/koji/getfile?taskID=22871118&volume=DEFAULT&name=build.log&offset=-4000 --
[...]
+ make check
make -C src check
make[1]: Entering directory '/builddir/build/BUILD/aircrack-ng-1.2-rc4/src'
./aircrack-ng -w ../test/password.lst -a 2 -e Harkonen -q ../test/wpa2.eapol.cap | grep 'KEY FOUND! \[ 12345678 \]' 
make[1]: *** [Makefile:290: check] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/aircrack-ng-1.2-rc4/src'
make: *** [Makefile:77: check] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.DWWHGE (%check)
RPM build errors:
    Macro expanded in comment on line 6: %{?dist}
    Macro expanded in comment on line 15: %{version}%{alphatag}.tar.gz
    Macro expanded in comment on line 19: %{version}%{alphatag}.tar.bz2
    Macro expanded in comment on line 20: %{version}-%{alphatag}.tar.gz
    Macro expanded in comment on line 21: %{version}-%{alphatag}.tar.gz
    Macro expanded in comment on line 22: %{name}-tarball
    Bad exit status from /var/tmp/rpm-tmp.DWWHGE (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps /builddir/build/SPECS/aircrack-ng.spec
--end--

**Comment by xsuchy** [comment]
This is not mock related problem. You have two problems there:

1) 
```
make -C src check
make[1]: Entering directory '/builddir/build/BUILD/aircrack-ng-1.2-rc4/src'
./aircrack-ng -w ../test/password.lst -a 2 -e Harkonen -q ../test/wpa2.eapol.cap | grep 'KEY FOUND! [ 12345678 ]'
make[1]: *** [Makefile:290: check] Error 1
```
So your makefile dufing %check phase found some error and exited with exit code 1. So did mock.

2)
```
RPM build errors:
    Macro expanded in comment on line 6: %{?dist}
    Macro expanded in comment on line 15: %{version}%{alphatag}.tar.gz
    Macro expanded in comment on line 19: %{version}%{alphatag}.tar.bz2
....
```
Macros are always expanded. Even in comments. This is a feature for long long time. If you want to silent macro use `%%`
