### ISSUE TITLE
Calculate spec/srpm (dynamic) build requires as a separate build mode

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1358]
There should be a Mock mode that provides **just** the src.rpm with expanded BuildRequires, after successfully iterating the %generate_buildrequires specfile section.

The point is to **not** perform the whole package build, just %prep and %generate_buildrequires.

**Comment by kdudka** [comment]
This would certainly be useful for implementing the support for dynamic build requires in [csmock](https://github.com/csutils/csmock/) (without the need to reimplement everything from scratch).

**Comment by praiskup** [comment]
In progress, see PR
