### ISSUE TITLE
Enabling tty in mock building process

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/mock#136]
Hello,

A package `rubygem-bundler` has tests that needs opened tty device to stdout and stderr.
Is it possible to enable it in mock building process?
It is enabled on mock shell environment.

## mock building process (in `bulid.log`).

```
+ test -t 1
=> Exist status: Non zero

+ ruby -e 'puts $stdout.tty?'
false
```

## On mock shell environment,

```
<mock-chroot> sh-4.4# test -t 1
=> Exist status: zero

<mock-chroot> sh-4.4# ruby -e 'puts $stdout.tty?'
true
```

**Comment by praiskup** [comment]
You can never rely on the fact that 0/1/2 devices are attached to terminal in rpmbuild .. (not only mock, but koji/copr and any other script in chain can redirect the output to file, or even close the descriptor).
It doesn't mean that mock isn't working badly with descriptors (known issue):  
https://bugzilla.redhat.com/show_bug.cgi?id=1166609

You should use /bin/unbuffer or /bin/script to alloc pty.

**Comment by xsuchy** [comment]
I agree with @praiskup  you should not expect it. Use of unbuffer or script is a good suggestion.

**Comment by junaruga** [comment]
ok, thanks for the explanation. I am fine for that.
