### ISSUE TITLE
provide --setopt=opt=val option

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#138]
It would be nice to be able to set any option by, e.g. --setopt=option=value, for example
--setupt=rpmbuild_networking=False, etc.

**Comment by xsuchy** [comment]
I am pretty sure we already have issue or BZ for that. The "problem" is how to differ "False" and False and how to implement lists. This is for a long time on my TODO list. And I am afraid it will stay there few more years. If anyone wants to implement I will happily review it.

**Comment by xsuchy** [comment]
Done in commit:
* 80273e1 (HEAD -> devel) add new option --config-opts [GH#138]

You can:

run:
  mock --config-opts yum_command=/usr/bin/yum-deprecated --enable-network
which will set:
  config_opts['system_yum_command'] = '/usr/bin/yum'

or for list:
  mock --config-opts extra_chroot_dirs=/mnt/b --config-opts extra_chroot_dirs=/mnt/a
which will set
  config_opts['extra_chroot_dirs'] = ['/mnt/b', '/mnt/a']

or list with single item:
  mock --config-opts extra_chroot_dirs=/mnt/b --config-opts extra_chroot_dirs=
which will set
  config_opts['extra_chroot_dirs'] = ['/mnt/b']

It can detect boolean:
  mock --config-opts nosync=False  --debug-config |grep nosync
  config_opts['nosync'] = False

Specialized option has priority. Therefore:
  mock --config-opts rpmbuild_networking=False --enable-network --debug-config |grep rpmbuild_networking
config_opts['rpmbuild_networking'] = True

It is unable to set complicated variables. Like config_opts['plugin_conf']['package_state_opts'] or anything which has dictionary as value

**Comment by praiskup** [comment]
FTR https://bugzilla.redhat.com/show_bug.cgi?id=1544810
