### ISSUE TITLE
Install packages using --no-docs

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#1389]
We can make the buildroot (and bootstrap chroot) smaller by calling DNF with --no-docs. Documentation should not be used for anything in runtime. And I do not recall any package breaking this rule. IMHO it should not harm anyone.

**Comment by Conan-Kudo** [comment]
It is mainly a problem if you are using the mock chroot interactively (ie. `mock --shell`). Otherwise, it's probably fine.

**Comment by xsuchy** [comment]
Closing as not a good idea. See the linked PR for counter examples.

**Comment by praiskup** [comment]
Anyway, thank you very much for this experiment!

**Comment by xsuchy** [comment]
Here is a link mailing list archive with more examples https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/TFEDXFQIXK6MCOXMTXIH74AAJ7YULLEX/
