### ISSUE TITLE
The do function should always check timeout even when running yum

### ISSUE THREAD

**Issue by xning** [rpm-software-management/mock#14]
Now when running _yum_ mock does not check timeout because the timeout parameter's value is zero. In this case if _yum_ encounters a dead lock, and this situation will hit  _mock_  In a infinite loop.

    do('/usr/bin/yum --installroot /var/lib/mock/RHEL-6-build-repo_latest/root/  groupinstall build', True, None, None, 0, True, 1, None, None, None)

What if we have the _timeout_ parameter has a default non-zero value?

**Comment by xning** [comment]
To make sure that the _timeout_ logic always could be available and will be run, I think we also need a _watchdog_ which should be a standalone process or a handler of the SIGALARM signal, hence even mock process is hit in endless loop or encounters a dead lock, the _timeout_ logic still could work.

**Comment by xsuchy** [comment]
I think it is hard to set some timeout value as some lines can be slow and this command can last quite long.
I will be happy to review patch which adds this option to site-defaults.cfg and which will be used in code and propagated to do().

**Comment by xsuchy** [comment]
I beleive this is resolved now with `config_opts['opstimeout'] = 0` See https://github.com/rpm-software-management/mock/wiki/Release-Notes-1.4.9
