### ISSUE TITLE
Branch main for epel8 releases

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#1418]
We should branch main and have epel8 branch for major fixes for RHEL8. And from main branch we will only do releases for el9+ (and Fedoras).

It will mean that RHEL8 releases will be stabilizing and get only bug fixes and not new features. While the main branch will get all features (and new bugs).

This is actually a long-time tradition that the last stable RHEL release gets its stable branch. Last time it happened for RHEL7 https://github.com/rpm-software-management/mock/issues/755 and with the EOL of RHEL7 it is time to move.

Both builds from main and epel8 branch will still be able to build packages for RHEL8.

**Comment by praiskup** [comment]
-1. Please don't :(

**Comment by praiskup** [comment]
2024 seems too early IMVHO, and #755 stopped hurting once we stopped committing to mock-2 branch.

**Comment by praiskup** [comment]
triage time: let's delay this decision by a few months
