### ISSUE TITLE
cleanup_on_* shouldn't wipe out contents from bind_mount plugin

### ISSUE THREAD

**Issue by d3matt** [rpm-software-management/mock#143]
I didn't notice that cleanup_on_failure now defaults to True (or maybe I just haven't had a build fail in a long time). Regardless, if you use the bind_mount plugin to bind mount directories into the container and one of cleanup_on_* runs, it wipes out everything in the bind mount.

**Comment by xsuchy** [comment]
Cannot reproduce with mock 1.4.7

I put in config:
```
config_opts['plugin_conf']['bind_mount_enable'] = True                                                                  
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/tmp/foo', '/foo' )) 
```
Then 
```
mkdir /tmp/foo
touch /tmp/foo/bar
mock /tmp/tito/mock-core-configs-27.4-1.fc27.src.rpm --cleanup-after
```

And the file `/tmp/foo/bar` is still there.

Please provide full reproducer (with your config).
