### ISSUE TITLE
Why Google dislikes our documentation?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1434]
When I google "mock package state plugin", I get this with DDG:
![Screenshot_20240829_090217](https://github.com/user-attachments/assets/b629f24a-b1fd-44ca-a35a-d672a89508b3)

But with google:
![Screenshot_20240829_091455](https://github.com/user-attachments/assets/c7e9c87a-b123-42f7-b66f-0a8065a48ea9)

Can we do something about this?

**Comment by praiskup** [comment]
DuckDuckGo still prefers the dead fedoraproject.org wiki, even though we use GitHub Pages for years.

**Comment by xsuchy** [comment]
GH Pages are not so old. And I think we can have some negative points from past for using GH Wiki. Because it is not indexed by Google https://github.com/orgs/community/discussions/4992

**Comment by praiskup** [comment]
> GH Pages are not so old.

3 years

**Comment by praiskup** [comment]
Ok, we checked that most of the doc pages is indexed (not with high rank).  PackageState is not indexed for some weird reason, but we don't know what to do right now.
