### ISSUE TITLE
Update the feature-rhelchroots doc page for the Simple Content Accecss

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1486]
https://rpm-software-management.github.io/mock/Feature-rhelchroots.html

We just need to register the Fedora box, no `attach` is needed.

**Comment by FrostyX** [comment]
I think we can close this ticket because @carlwgeorge documented it perfectly a year ago, see a112fb85.
There are now two sections, describing both subscription with Simple Content Access and without it.

Or are we at the point when we want to remove the instructions without Simple Content Access?

**Comment by praiskup** [comment]
> Or are we at the point when we want to remove the instructions without Simple Content Access?

yes please :) that part would have no sense

**Comment by carlwgeorge** [comment]
I believe at some point SCA will become mandatory, but until it does it probably makes sense to keep the "without SCA" instructions.  If that already happened and I just missed it, then I fully support removing the obsolete instructions.

**Comment by praiskup** [comment]
> I believe at some point SCA will become mandatory

Happened already? At least per https://access.redhat.com/articles/simple-content-access :
> In Oct/Nov 2024, most Red Hat accounts which are NOT using Simple Content Access and the Hybrid Cloud Console will be migrated to these experiences. Learn more in the [Transition of Red Hat's subscription services to console.redhat.com](https://access.redhat.com/articles/transition_of_subscription_services_to_the_hybrid_cloud_console)

**Comment by carlwgeorge** [comment]
Ah, so it did, for _most_ users.  That page links to [this article](https://access.redhat.com/articles/transition_of_subscription_services_to_the_hybrid_cloud_console) which points out:

> Users of the Advanced Update Services add-on are excluded from the Oct/Nov 2024 deadline pending the release of support for reporting this addon in the subscriptions service. Migration dates for these users will be announced at a future date.

It also has this planned timeline:

> Oct/Nov 2025 - As support for AUS now exists within the subscriptions service (see [SWATCH-2743](https://issues.redhat.com/browse/SWATCH-2743)), users of RHSM who also use the AUS add-on will be converted to Simple Content Access & the Hybrid Cloud Console at/around Oct/Nov 2025 with a more exact date being announced in 2025.

I'm familiar with EUS and ELS, but not AUS, so I'm not sure how big this group of users would be.  Ultimately it's probably fine to remove those instructions now, but it would also be fine to wait till that Oct/Nov 2025 date.
