### ISSUE TITLE
Regression with `dnf_builddep_opts` option 

### ISSUE THREAD

**Issue by azeey** [rpm-software-management/mock#1496]
https://github.com/rpm-software-management/mock/commit/1237e2f9e6f0f0d5385d4d388bc21dc110e9b634 makes "dnf4" equivalent to "dnf", but the implementation skips `builddep_opts`
https://github.com/rpm-software-management/mock/blob/2fa2dbddffa664e55d627ac5625b0c61aed80b11/mock/py/mockbuild/config.py#L56-L58

This regression breaks build infrastructure that uses `dnf_builddep_opts`.

**Comment by praiskup** [comment]
Indeed, good catch.  Do you want to send a PR with fix, or shall I?

**Comment by azeey** [comment]
Created https://github.com/rpm-software-management/mock/pull/1497.
