### ISSUE TITLE
Please document how to add a 3rd party repo

### ISSUE THREAD

**Issue by usercz** [rpm-software-management/mock#16]
I've been trying to create an rpm which build depends on `mono-complete`, from the repo provided by mono-project.

However adding the repo in the mock configuration doesn't seem to work, and the build just fails because `mono-complete` can't be resolved.

To add the repository I just copied and pasted the file `/etc/yum.repos.d/download.mono.blablabla.repo` into the configuration for the chroot.

So, I guess there is a way to make this work, but I can't find any documentation about it.

**Comment by Frodox** [comment]
Could you paste your full configurations file? Which one do you changed, and do it looks like? 
And how do you run mock?

Your `myroot.cfg` could looks like [this](http://buildlogs.centos.org/c7.1511.u/bash/20160802154747/4.2.46-20.el7_2.x86_64/mock.cfg). So, you need to have ant least 2 repo - for default chroot and buildenv, and for your third party repo.

Just edit [custom-1-x86_64.cfg](https://github.com/rpm-software-management/mock/blob/devel/etc/mock/custom-1-x86_64.cfg) and and add repos, like in [epel7.cfg](https://github.com/rpm-software-management/mock/blob/devel/etc/mock/epel-7-x86_64.cfg#L22).

I can add it to docs, if it works for you.

**Comment by usercz** [comment]
```
config_opts['root'] = 'fedora-rawhide-x86_64'
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['chroot_setup_cmd'] = 'groupinstall buildsys-build'
config_opts['dist'] = 'rawhide'  # only useful for --resultdir variable subst

config_opts['yum.conf'] = """
[main]
cachedir=/var/cache/yum
debuglevel=1
reposdir=/dev/null
logfile=/var/log/yum.log
retries=20
obsoletes=1
gpgcheck=0
assumeyes=1
syslog_ident=mock
syslog_device=
exclude=[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefhijklmnopqrstuvwxyz]*.i?86 g[abcdefghijkmnopqrstuvwxyz]*.i?86 glib2*.i?86 glib-*.i?86 glib.i?86 *-devel.i?86 ruby-libs*.i?86

# repos

# ====== The mono one
[mono]
name=mono
baseurl=http://download.mono-project.com/repo/centos/
enabled=1

[fedora]                                                                                                                                                                               
name=fedora                                                                                                                                                                            
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64                                                                                                        
failovermethod=priority                                                                                                                                                                
                                                                                                                                                                                       
[local]
name=local
baseurl=http://kojipkgs.fedoraproject.org/repos/rawhide/latest/x86_64/
cost=2000
enabled=0

[debug]
name=Fedora Rawhide - x86_64 - Debug
failovermethod=priority
mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=rawhide-debug&arch=x86_64
enabled=0
"""
```

I know it says centos in the URL, but I tried in a fedora vm and seems okay. Their official instructions are the same for fedora/rh/centos.


```
mock -r conffile  --spec=specfile --sources=fedora/SOURCES --buildsrpm --resultdir=build-artifacts
mock -r conffile --installdeps --rebuild build-artifacts/*.rpm --resultdir build-artifacts
```

spec file contains `mono-complete` in the list, and the result is that it fails because package can't be found.

**Comment by Frodox** [comment]
You would be surprised, but it works for me :D 
Try to test this case
```
$ mock -r conffile --init
...
$ mock -r conffile --install mono-complete
...
Installed:
  mono-complete.x86_64 0:4.6.2.7-0.xamarin.1                                                                                                                  

Dependency Installed:
...
```

**Comment by usercz** [comment]
I'm using mock 1.2.18, shipped in debian. However after running a `--clean`, I have to say that it's working for me as well.

I can't say what changed. At the moment of writing that config file didn't work. I guess you can close this.

**Comment by Frodox** [comment]
@usercz hm, looks like something temporally repo-related.
Well, I can't close it - I am not maintainer. So, please, close it by yourself :)
