### ISSUE TITLE
what repos shoud have gpgcheck=1 ? 

### ISSUE THREAD

**Issue by sergiomb2** [rpm-software-management/mock#166]
for [1] in https://github.com/rpm-software-management/mock/tree/devel/mock-core-configs/etc/mock we miss gpgcheck=1 in updates-testing and in debuginfos repos at least 

[1]
https://github.com/rpmfusion-infra/mock-rpmfusion/issues/13

**Comment by xsuchy** [comment]
gpgcheck=1 have been used just recently (IIRC year ago), previously the signature was not checked. I added it for repos, which has a reliable signature. E.g., rawhide was not signed at all. Then it started with the signing, but the package has been signed few days after it has been built. And there can be a mixture of two signatures.... problems .... problems :)  In such situation I just fall back to old good days and not gpgcheck. Just to put you in picture.

And rpmfusion.... I just guest that there were some issues with signatures in those days. If it is reliable, we can enable it.

**Comment by sergiomb2** [comment]
OK , but at least all stable repos (f26 and f27, epels) should have gpgcheck=1 in testing , and debuginfo ,
I don't know how configurations are updated but from example [1] need it on testing and all debuginfo repos ... 
How the templates are maintained ? do you have any generator of templates ? 
Thanks,
[1]
https://github.com/rpm-software-management/mock/blob/devel/mock-core-configs/etc/mock/fedora-26-ppc64le.cfg

**Comment by xsuchy** [comment]
It is maintained by hand, no tools for that. So if you test and verify, feel free to send PR.
