### ISSUE TITLE
Add support for bsdtar

### ISSUE THREAD

**Issue by tpgxyz** [rpm-software-management/mock#169]
### Short description of the problem
Currently mock supports tar from GNU, while bsdtar from libarchive is not supported

### Steps to reproduce issue

1. Set up bsdtar as default tar
2. Observe mock failure
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by xsuchy** [comment]
What would be the benefit? I am afraid that this is soooo low prio, that it will not happen unless someone (you) send a patch.

**Comment by praiskup** [comment]
GNU tar is supposed to be the default on GNU/Linux distro.  Btw.:
```bash
$ rpm -q mock
mock-1.4.9-1.fc27.noarch
```

**Comment by praiskup** [comment]
Is this issue related to mock scm plugin?

**Comment by tpgxyz** [comment]
@xsuchy  @praiskup All calls to tar inside mock code are not compatible with bsdtar https://github.com/libarchive/libarchive

**Comment by Conan-Kudo** [comment]
To give a more detailed explanation here:

OpenMandriva is in the process of switching to rpm.org rpm and DNF. As a part of this, their build system build engine is changing to mock. However, they replaced GNU tar with libarchive's tar back in OpenMandriva Lx 3, and libarchive's `tar` works slightly differently.

A proper patch for this would probably involve making it configurable to use either `tar` (expecting GNU tar) or `bsdtar` for libarchive's `tar`. What would be required for that, I don't yet know, but that's what I think would be required.

**Comment by praiskup** [comment]
On Tuesday, April 24, 2018 11:21:42 AM CEST Neal Gompa (ニール・ゴンパ) wrote:
> > > What would be required for that, I don't yet ...
> >
> > Where this is discussed?
> 
> I'm not sure what you mean?

I thought that it is being discussed somewhere, and you'll know sooner or later.
Having some reference links would be nice.

**Comment by Conan-Kudo** [comment]
No, this was discussed on IRC in `#OpenMandriva-Cooker` some time ago. The switch to `bsdtar` occurred two years ago, and GNU tar is no longer in the base system package set at all.

There was an attempt to patch mock to forcibly switch it to `bsdtar`, but it didn't work, so currently we have a relatively unmaintained version of the [`gnutar`](https://github.com/OpenMandrivaAssociation/gnutar/blob/master/gnutar.spec) package providing it as `gtar` (like on macOS and BSD) and we patch `mock` to use `gtar` instead of `tar`.

**Comment by praiskup** [comment]
On Tuesday, April 24, 2018 11:36:41 AM CEST Neal Gompa (ニール・ゴンパ) wrote:
> No, this was discussed on IRC in `#OpenMandriva-Cooker` some time ago. The
> switch to `bsdtar` occurred two years ago, and GNU tar is no longer in the
> base system package set at all.

So at least `bsdtar` is generally available on every such box, which provides
`/bin/tar`, which is OK.

> There was an attempt to patch mock to forcibly switch it to `bsdtar`, but it
> didn't work, so currently we have a relatively unmaintained version of the
> [`gnutar`](https://github.com/OpenMandrivaAssociation/gnutar/blob/master/gnutar.spec)
> package providing it as `gtar` (like on macOS and BSD) and we patch `mock` to
> use `gtar` instead of `tar`.

I really need to see links to discussions about this, because otherwise I only
can guess what concrete problems with bsdtar are...  really really guessing now,
I grepped through mock's devel branch:

    $ git grep 'tar '
    mock/py/mockbuild/scm.py:        self.write_tar = opts['write_tar']
    mock/py/mockbuild/scm.py:            self.log.debug(".write_tar detected, will write tarball on the fly")
    mock/py/mockbuild/scm.py:            self.write_tar = True
    mock/py/mockbuild/scm.py:            cmd = "tar caf " + tarball + " " + taropts + " " + tardir

... so I see one portability problem, and that's 'taropts' which contains
'--exclude-vcs' option.  Is this this the core of the problem?

**Comment by Conan-Kudo** [comment]
I think so.

**Comment by Conan-Kudo** [comment]
I think so. @berolinux and @tpgxyz can give more details. I wasn't really there for most of it, as we operate in different time zones.

**Comment by praiskup** [comment]
On Tuesday, April 24, 2018 12:22:50 PM CEST Neal Gompa (ニール・ゴンパ) wrote:
> The thing is, we don't use `mock-scm`

That's even better.  /bin/yum would say, "Nothing to do.", or what am I missing?

**Comment by tpgxyz** [comment]
@praiskup @xsuchy Yes @Conan-Kudo well descibed what i had on my mind, when i filled this issue.

Problem is that mock uses switches from gnu's version of tar. Unfortunately these options does not exists in BSD's (or POSIX compiliant) tar from libarchive (https://www.libarchive.org/)

Mostly libarchive's tar does not support exclude-foo-bar. Instead of this option is support excludes pattern i.e
`--exclude='*foo*'`

Currently gtar compatible options were found in mock's root_cache.py

**Comment by praiskup** [comment]
Thanks, that makes it clear now. I forgot about `root_cache.py`.  Please consider
whether #180 fix is enough.

**Comment by xsuchy** [comment]
@praiskup  bsdtar exists even in fedora:
https://apps.fedoraproject.org/packages/bsdtar

so you can try it yourself (or compare man pages)

**Comment by praiskup** [comment]
On Tuesday, April 24, 2018 8:15:56 PM CEST Miroslav Suchý wrote:
> so you can try it yourself (or compare man pages)

I know something about those packages :-)
