### ISSUE TITLE
Need to add `newgrp -` to usermod instructions

### ISSUE THREAD

**Issue by taw00** [rpm-software-management/mock#174]
### Short description of the problem
On the home wiki page (https://github.com/rpm-software-management/mock/wiki) it really should be mentioned that after a `usermod` command to add the mock user group the user needs to either logout and log back in again, or run `newgrp -` in order for the group to take effect.

Even folks with tons of sysadmin experience grow tired of re-reading man pages for how stuff works cuz they have to re-re-re-relearn things over and over again. :)

Just a suggestion. Thanks. -taw (aka t0dd in other forums and venues)

**Comment by xsuchy** [comment]
Done https://github.com/rpm-software-management/mock/wiki#setup
Thank you for the suggestion Todd.

**Comment by taw00** [comment]
Not done. :)
To take this change effect you have to either log out and log in or run command `newgrp `
...that should be...
To take this change effect you have to either log out and log in or run command `newgrp -`

I'm editing it myself. Didn't realize I had the mojo. :)

**Comment by taw00** [comment]
And... I performed a followon edit to fix the grammar. :)

**Comment by xsuchy** [comment]
Yes, it is wiki. So anyone with GH account can edit it. Thank you for the corrections.
