### ISSUE TITLE
"Inappropriate ioctl for device" for only new chroot

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/mock#186]
### Short description of the problem

May I ask you a question?

### Output of `rpm -q mock`

mock-1.4.10-1.fc28.noarch

- Fedora 28.

```
$ rpm -qf /usr/bin/systemd-nspawn
systemd-container-238-8.git0e0aa59.fc28.x86_64
```

### Steps to reproduce issue

Below connection error happens on only new chroot (systemd nspawn) environment.
But does not happen on old-chroot environment, and koji environment.

In my mind, before upgrading f28, i was success even in the new chroot environment.
Did you recently change something for the new chroot environment?

1.  Download spec file to reproduce this issue.
https://src.fedoraproject.org/fork/jaruga/rpms/rubygem-mongo/tree/hotfix/mock-env

```
$ git clone https://src.fedoraproject.org/forks/jaruga/rpms/rubygem-mongo.git -b hotfix/mock-env
```

2. `cd rubygem-mongo`

3. `fedpkg --release master srpm`

4. 

```
$ mock -r fedora-rawhide-x86_64 *.src.rpm
...
BUILDSTDERR: ioctl(1, TCGETS, 0x7ffe94a72140)        = -1 ENOTTY (Inappropriate ioctl for device)
An error occurred in a `before(:suite)` hook. 
Failure/Error: raise Error::SocketError, e.message
Mongo::Error::SocketError:
  end of file reached
# ./lib/mongo/socket.rb:227:in `rescue in handle_errors'
...
# EOFError:
#   end of file reached
#   /usr/share/ruby/socket.rb:452:in `__read_nonblock'
```

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by xsuchy** [comment]
The error is:
```
Mongo::Error::SocketError:
  end of file reached
```
I.e., the test is trying to read from the socket while it was already closed. I have no idea who is opening and writing to the socket and as the bug is not in a mock, I cannot help you to debug it more.

But you can run mock with --no-clean and then run `mock shell` and go into /builddir and investigate the issue manually.

**Comment by junaruga** [comment]
Thank you for the comment.

> But does not happen on old-chroot environment, and koji environment.

The difference of new-chroot and old-chroot makes this issue.
Because when running it on old-chroot it works without error.
That' why I am asking here if `mock` or `systemd` changed something related to the network recently.

I will take a look to investigate it.
Thank you.

**Comment by xsuchy** [comment]
Thel old=chroot use plain chroot() system call. While new-chroot use system-nspawn, which is a container with all the isolation and a lot of restriction and separate name space.

**Comment by junaruga** [comment]
@xsuchy is it possible to implement adding `--capability=cap_ipc_lock` option in `mock` program to enable `@memlock`, considering @msekletar 's investigation?

**Comment by omajid** [comment]
I am hitting the same issue in another program: https://bugzilla.redhat.com/show_bug.cgi?id=1594397. I have verified that `--capability=cap_ipc_lock` works for me locally.

**Comment by junaruga** [comment]
@omajid thank you for the useful information to set the option in mock-config file!
I did not know the way. I will try it later.

**Comment by duritong** [comment]
I just wanted to note here, that libgcrypt in Fedora also only builds with adding `--capability=cap_ipc_lock` using systemd-nspawn, otherwise some tests can't be run during build process: https://lists.gnupg.org/pipermail/gcrypt-devel/2017-December/004351.html

**Comment by duritong** [comment]
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1580435

**Comment by praiskup** [comment]
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1598987
