### ISSUE TITLE
RFE: Support newest OpenSuse Leap versions

### ISSUE THREAD

**Issue by taw00** [rpm-software-management/mock#188]
### Short description of the problem

Supported OpenSuse Leap versions are 15.0, 42.1, 42.2, 42.3 -- Alas, mock, out of the box, only supports 15.0.

### Output of `rpm -q mock`

mock-1.4.10-1.fc28.noarch

### Steps to reproduce issue

`ls -l /etc/mock/opensuse*`

**Comment by xsuchy** [comment]
I do not use OpenSuse. So you had to provide me a config. Or at least repos url.

**Comment by Conan-Kudo** [comment]
Unfortunately, it's not possible to support openSUSE Leap 42.x, as the pieces we need for mock to function are missing in Leap 42.x, and I can't make that available without patching their rpm, which I can't do and get it upstreamed into openSUSE Leap 42.x.

**Comment by xsuchy** [comment]
:( then I am afraid  I had to close this. For now.
