### ISSUE TITLE
Require for docs: use mount_bind from command line

### ISSUE THREAD

**Issue by Frodox** [rpm-software-management/mock#19]
How can I use mock's `mount_bind` plugin from cmd line? 
I see there are lines in man page: `--plugin-option PLUGIN:KEY=VALUE`, but in case of `mount_bind` I have no ideas how to use it ;(

And if it is impossible, it would be cool to add wiki/man, or issue..

**Comment by xsuchy** [comment]
`
config_opts['plugin_conf']['root_cache_opts']['age_check'] = True`

can be written as:

`--plugin-option=root_cache:age_check=False`

And:

`config_opts['plugin_conf']['mount_opts']['dirs'] = ("/dev/device", "/mount/path/in/chroot/", "vfstype", "mount_options")`

can be written as:

`'--plugin-option=mount:dirs=("/dev/device", "/mount/path/in/chroot/", "vfstype", "mount_options")'`

Note that you cannot use the trick with append() on command line.

I will add those examples to man page.

**Comment by xsuchy** [comment]
Done in commit 001789e

**Comment by Frodox** [comment]
Thank you!!!
I spend a lot of time thinking about mount opts.
Yup, it it clear enough about plugin with standard `key: value` params, but not trivial with this one
