### ISSUE TITLE
EL7 hosts cannot create F28+ chroots

### ISSUE THREAD

**Issue by tmzullinger** [rpm-software-management/mock#191]
### Short description of the problem
When attempting to use a mock host on EL-7 to create F-28+ chroots, rich rpm dependencies in the minimal build root cause failures.

### Output of `rpm -q mock`
$ rpm -qa mock\*
mock-1.4.10-1.el7.noarch
mock-core-configs-28.4-1.el7.noarch

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

### Steps to reproduce issue

```
$ mock -r fedora-28-x86_64 --init
INFO: mock.py version 1.4.10 starting (python version = 2.7.5)...
WARNING! WARNING! WARNING!
You are building package for distribution which use DNF. However your system
does not support DNF. You can continue with YUM, which will likely succeed,
but the result may be little different.
You can suppress this warning when you put
  config_opts['dnf_warning'] = False
in Mock config.
Press Enter to continue.
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: /etc/mock/site-defaults.cfg newer than root cache; cache will be rebuilt
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.10
INFO: Mock Version: 1.4.10
Start: yum install
...
Resolving Dependencies
--> Running transaction check
...
---> Package make.x86_64 1:4.2.1-6.fc28 will be installed
--> Processing Dependency: libguile-2.0.so.22(GUILE_2.0)(64bit) for package: 1:make-4.2.1-6.fc28.x86_64
--> Processing Dependency: libgc.so.1()(64bit) for package: 1:make-4.2.1-6.fc28.x86_64
--> Processing Dependency: libguile-2.0.so.22()(64bit) for package: 1:make-4.2.1-6.fc28.x86_64
---> Package patch.x86_64 0:2.7.6-4.fc28 will be installed
---> Package redhat-rpm-config.noarch 0:108-1.fc28 will be installed
Error: Invalid version flag: if

$ echo $?
30
```

This affects Fedora >= 28.  Using `--bootstrap-chroot` or setting `config_opts['use_bootstrap_container'] = True` allows the chroot to be created and basic packages to build.  Is it worth changing the default for Fedora >= 28 chroot's to use the bootstrap chroot by default?  If not, the warning printed stating that yum "will likely succeed" should probably be adjusted.

**Comment by ausil** [comment]
this is expected, rpm on EL7 is too old for current fedora rpm features.

**Comment by tmzullinger** [comment]
And thus my question of whether we should default to using the bootstrap-chroot by default on those.  Or if not, we should drop the configs from the default.  Something, in any case.  Because it's not a good experience for users and there are a number of potential ways to improve it.

**Comment by tmzullinger** [comment]
@ausil Please reopen this issue so that we can discuss ways to improve the way this is handled.  I understand that EL7 hosts won't be gaining support in rpm for all the features required by newer Fedora releases.  What I want to address is how this is handled.  I would have supplied a patch but there's little point in doing so until there's some discussion of what the best outcome might be.

As I said in my initial comment, that might be enabling the `use_bootstrap_container` by default for newer releases when the host is EL7.  Or it might simply be changing the current warning that incorrectly suggests that using yum is likely to succeed.  We know that it won't for anything newer than F27 so we can avoid giving users bad information.

If this has been discussed to death somewhere already, I am sorry for not finding it.  I don't recall seeing it on the buildsys list and when searching the github issues for the current error nothing comes up.

**Comment by praiskup** [comment]
Dnf can be installed on EL7 https://wiki.centos.org/SpecialInterestGroup/ConfigManagementSIG/YUM4

**Comment by xsuchy** [comment]
The warning in the output is about depsolving. When you install F28 using yum you may get different dependencies because of different depsolving. The actuall error you are getting is something else (ausil already explained that one).
Enabling bootstrap by default is definitely the right way. However, there is still a lot bugs related to bootstrap (mainly: repos which has file:// urls, issue with --installdeps) so I do not want to enable it by default.

**Comment by xsuchy** [comment]
As nothing happened in past 11 days. I am closing this one. But if you have some ideas on how to solve, feel free to discuss here.
