### ISSUE TITLE
OSError: [Errno 39] Directory not empty: '/var/lib/mock/epel-7-x86_64/root/builddir'

### ISSUE THREAD

**Issue by juergenc** [rpm-software-management/mock#197]
### Short description of the problem
I installed the Debian package for Mock 1.3.2-2 on a Debian Stretch system. We use Mock on Debian OS build systems for years to build rpm packages. Mock stops with a Python traceback on deleting the build directory inside the chroot. The update of line 273 of the Python module `/usr/lib/python3/dist-packages/mockbuild/buildroot.py` solved the issue.

### Output of `dpkg --list mock`
This Mock installation package comes with the Debian OS Stretch distribution:
```
dpkg --list mock
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                Version                        Architecture                   Description
+++-===================================================-==============================-==============================-===========================================================================================================
ii  mock                                                1.3.2-2                        all                            Build rpm packages inside a chroot
```

### Steps to reproduce issue
1. Mock command line: `mock -D "dist .el7" -r epel-7-x86_64 --no-clean --rebuild /var/lib/jenkins/workspace/backup-3.2/packages/redhat/ehbackup-bkclientd-3.2.6.5.gba4cdc60d-1.el7.src.rpm --resultdir=/var/lib/jenkins/workspace/backup-3.2/packages/redhat`
2. output: 
INFO: mock.py version 1.3.2-2 starting (python version = 3.5.3)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(/var/lib/jenkins/workspace/backup-3.2/packages/redhat/ehbackup-bkclientd-3.2.6.5.gba4cdc60d-1.el7.src.rpm)  Config(epel-7-x86_64)
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
Mock Version: 1.3.2-2
INFO: Mock Version: 1.3.2-2
ERROR: Exception(/var/lib/jenkins/workspace/backup-3.2/packages/redhat/ehbackup-bkclientd-3.2.6.5.gba4cdc60d-1.el7.src.rpm) Config(epel-7-x86_64) 0 minutes 0 seconds
INFO: Results and/or logs in: /var/lib/jenkins/workspace/backup-3.2/packages/redhat
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
Traceback (most recent call last):
  File "/usr/sbin/mock", line 882, in <module>
    main()
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 698, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 780, in run_command
    do_rebuild(config_opts, commands, buildroot, args)
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 520, in do_rebuild
    post=post_build, clean=clean)
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/sbin/mock", line 464, in rebuild_generic
    commands.init(prebuild=not config_opts.get('short_circuit'))
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3/dist-packages/mockbuild/backend.py", line 124, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3/dist-packages/mockbuild/buildroot.py", line 90, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3/dist-packages/mockbuild/buildroot.py", line 156, in _init
    self._make_build_user()
  File "/usr/lib/python3/dist-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3/dist-packages/mockbuild/buildroot.py", line 274, in _make_build_user
    os.rmdir(homedir)
OSError: [Errno 39] Directory not empty: '/var/lib/mock/epel-7-x86_64/root/builddir'

### Any additional notes
Patch of /usr/lib/python3/dist-packages/mockbuild/buildroot.py:
```
273c273
<             os.rmdir(homedir)
---
>             shutil.rmtree(homedir)
```
`os.rmdir(homedir)` expects `homedir` to be empty which seems obviously not the case. Replacing it by recursive deleting `shutil.rmtree(homedir)` solves the problem. Same call is used on other places in the same script file.

**Comment by xsuchy** [comment]
1.3.2 is pretty old version. Devel version is now 1.4.9. Right now there is no instance of os.rmdir() in buildroot.py, but bunch of shutil.rmtree(). So I guess your issue have been resolved in upstream. If you want to get it backported to Debian, then you have to contact Debian maintainer.
