### ISSUE TITLE
[RFE] setuptools-based build

### ISSUE THREAD

**Issue by phmccarty** [rpm-software-management/mock#207]
This is a feature request to add a setup.py to enable a setuptools-based build for mock. I think this would, in general, ease packaging mock for other distributions.

Background:

My motivation for filing this feature request is to ease the packaging of mock for Clear Linux OS. The current version of mock in Clear Linux OS is very old (1.2.14), and I am planning to upgrade to the latest version.

For mock version 1.2.14, the automatic package creator (autospec) for Clear Linux OS automatically detected how to build the package, because 1.2.14 used autotools. Autospec has good support for building autotools-based projects, so mock packaging was easy.

However, since mock has moved to tito, I'm not seeing a good way to integrate tito-based projects for building with autospec, as autospec itself uses mock internally. I can see how tito is a convenient tool for managing releases, creating RPMs, etc when the mock.spec lives in-tree, but for other distributions that want to build mock from scratch, without relying on a preexisting mock.spec, it seems less convenient. Particularly, because autospec uses mock internally, I'm unsure how a build of this nature can be made to work.

Thus, considering other options, I thought that mock could adopt setuptools. This would ease the integration of mock for Clear Linux OS and other distributions as well.

**Comment by Conan-Kudo** [comment]
Setuptools is probably very inappropriate for mock, given that it's almost entirely system dependency based.

Something along the lines of CMake or even plain Makefiles is probably a better route.

**Comment by xsuchy** [comment]
The packaging for other distributions should be quite easy. You just copy `%build` and `%install` sections from mock.spec. And get tarball either from GitHub releases page or crate it using 'tito build --tgz'.

I am not willing to spend my time crafting setup.py (it would be complicated) and on maintaining it. 

If you are willing to do that (including the maintenance every release) then you can send PR and I can even give you write access. But I am not willing to do that myself. Sorry.

On the other hand I am willing to help you to package new mock for Clear Linux. I often hang on #fedora-buildsys channel Feel free to contact me there and do not hesitate to ask.

**Comment by Conan-Kudo** [comment]
@xsuchy Clear Linux doesn't allow spec files for their RPM builds. They require [autospec](https://github.com/clearlinux/autospec) builds, and autospec can't do anything with "pile of files".
