### ISSUE TITLE
Icon directive in spec file is underdocumented

### ISSUE THREAD

**Issue by usercz** [rpm-software-management/mock#21]
Hello,

There is an "Icon" directive in spec file, that can point to an icon. However, when building from mock, pointing to files inside the source directory do not work, and pointing to files with an absolute path and installing them with `config_opts['files']` doesn't seem to work either. In both cases the result is file not found.

Some more documentation about how to use this option, and how to use it with mock would be nice. I barely found anything about it.

Thanks

**Comment by xsuchy** [comment]
> There is an "Icon" directive in spec file, that can point to an icon.

What do you mean?

> However, when building from mock, pointing to files inside the source directory do not work, and pointing to files with an absolute path and 

Can you post sample of spec file and ellaborate more what you are trying to achieve?

**Comment by usercz** [comment]
```
BuildRoot: %{buildroot}
Name:      %{name}
Version:   %{_version}
Release:   %{release}
License:   GPL
Source0:   src.tar
BuildRequires: vala-devel%{?_isa}, libsecret-devel, mono-devel
Prefix:    /usr
Icon: app-icon.xpm
```

This is part of my spec file. The last line is the one that I'm trying to add.

The icon file is in the root directory of the .tar file, but trying passing different paths to `Icon` always makes the build fail with

```
error: Unable to open icon /builddir/build/SOURCES/app-icon.xpm: No such file or directory
```

**Comment by xsuchy** [comment]
Aha this:
  http://rpm.org/max-rpm-snapshot/s1-rpm-inside-tags.html#S3-RPM-INSIDE-ICON-TAG
See the documentation.
It expect the file in SOURCE directory.
Co you must first copy the file there using
  mock --copyin ICON /builddir/build/SOURCES/a
and then run your mock but with --no-clean

However I never seen usage of this tag. You may rather use icons specification as used by declared by freedesktop.org
  https://fedoraproject.org/wiki/Packaging:Scriptlets#Icon_Cache
  https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by usercz** [comment]
Yeah i know the freedesktop one, but that's for `.desktop` files, while I presume this tag is to make graphical rpm managers show an icon for the package.

But well the icon is inside the tar, with the sources, so shouldn't it get unpacked together with the rest and found there?

Probably not a mock issue, but perhaps a rpmbuild issue?
