### ISSUE TITLE
RFE: add `--list-commands` or `--help-cmds`

### ISSUE THREAD

**Issue by juhp** [rpm-software-management/mock#220]
### Short description of the problem
It would be nice to have an easy way to list all the mock commands.
(Since all mock commands are prefixed with '--' it is not easy to tell at glance what is a command or option.)
(I know --help and the manpage list the commands first, but they are harder to parse.:-)

**Comment by xsuchy** [comment]
In man page, it is divided to separate chapters. Do you need it parsable for a computer?

**Comment by juhp** [comment]
Well that was my idea at the time.
But maybe it's not needed - feel free to close.

**Comment by xsuchy** [comment]
I am going to close this as I will not have time for this. But if you want to actually implement this, then feel free to open pull request.
