### ISSUE TITLE
Please  make pm request safe

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/mock#224]
In https://pagure.io/fesco/issue/2004 mizdebsk worries that enabling the pm request mock extension on Fedora build systems (copr and koji) would lead to evil, and that attackers could use it to convince mock to pass dangerous commands to dnf.

Please add a restricted secure mode to pm request where it can only be used to
* install/upgrade packages to the mock chroot or container from the repositories configured in the *repo files
* executing the corresponding scriptlets with the mock chroot or container

And that, no matter what parameters an attacker manages to get passed through the pm request socket

Regardless of what FESCO decides in the pagure ticket the same config is running on packager systems today, the mock on those systems is the first line of defense against compromised upstream sources, so it needs to be secured properly.

**Comment by praiskup** [comment]
That's what I meant by security concerns in #160.  But I'm not sure what you mean by:

> executing the corresponding scriptlets with the mock chroot or container

**Comment by xsuchy** [comment]
Closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1642844
Please open only one issue - either in GH or in Bugzilla, but not in both.

**Comment by nim-nim** [comment]
Sorry about this, each upstream has his preferences, and I didn't know yours

**Comment by nim-nim** [comment]
> 
> 
> That's what I meant by security concerns in #160. But I'm not sure what you mean by:

> > executing the corresponding scriptlets with the mock chroot or container

basically, anything that  @mizdebsk warns against in
https://pagure.io/fesco/issue/2004

**Comment by praiskup** [comment]
> > executing the corresponding scriptlets with the mock chroot or container

I see, you meant "within" or "inside" mock chroot or container, **not** on the host directly.  Of course, there's also the mockbuilder user or so.. that UID should be used as well.

**Comment by praiskup** [comment]
Well, no - there's no yum/dnf inside chroot.  What scriptlets do you have in mind if we are speaking about pg_request?

**Comment by nim-nim** [comment]
@mizdebsk was worried about the scriplets of the packages installed as dynamic BuildRequires having side-effects on the build host. Myself, I have no need for special scriptlets I just want the packagers installed before `%build`.

**Comment by praiskup** [comment]
@mizdebsk how the packages installed from dynamic build requires differ from the static BuildRequires?  Both should be installed from the same set of packages.  That said, if some scriptlet has an effect on the build host (I can imagine this could happen), we are in trouble anyways (be that dynamic/static Build Requires).

**Comment by mizdebsk** [comment]
pm_request allows executing arbitrary DNF command, which is equivalent to arbitrary code execution outsides of chroot, with root priviledges. Static BuildRequires are limited to installing packages in chroot from pre-defined repositories.

**Comment by praiskup** [comment]
> executing the corresponding scriptlets within the mock chroot or container

Ok, I think the second point ^^ is non issue, then.

**Comment by mizdebsk** [comment]
If this is still not clear, a specific example scenario:

- foo.src.rpm contains bar.noarch.rpm embedded as Source 0
  - bar.noarch.rpm contains %post scriplet that executes `rm -rf / --no-preserve-root`
- foo.src.rpm contains spec file that in %prep talks to pm_request and requests `install --installroot / /var/lib/mock/.../bar.noarch.rpm`
- user calls mock --enable-plugin pm_request foo.src.rpm
  - mock receives pm request
  - mock executes dnf
  - dnf installs bar package on host system (outsides of chroot)
  - dnf executes scriplet outsides of chroot
  - scriplet wipes host filesystem

**Comment by mizdebsk** [comment]
> * mock AFAIK ignores /etc/yum.repos.d/

This is configurable behaviour. Default mock configs ignore it, but nothing stops user from supplying custom config that respects yum.repos.d

> * we should be only allowed to **declaratively** tell what packages are needed -- nothing else, and let the build system decide whether it will do `dnf update` or `yum install` (some time ago we discussed this with msimacek)

Then you'd be severely limiting what pm_request can do. pm_request plugin is by design powerful, but dangerous and as documentation advises, it should not be used in production.

**Comment by nim-nim** [comment]
@mizdebsk

The first point is not a problem for use in koji/copr. That's not a tool problem that's an insecure configuration and I doubt releng would deliberately deploy and insecure configuration (a security warning when someone does the things you describe would be nice though).

As for the second point, if there is an actual need for all the things you describe, just make it a pm_request config non-default option so we can all deploy the secure restricted pm_request mode and people who need the rest can disable secure mode on their systems.

**Comment by mizdebsk** [comment]
> The first point is not a problem for use in koji/copr. That's not a tool problem that's an insecure configuration and I doubt releng would deliberately deploy and insecure configuration (a security warning when someone does the things you describe would be nice though).

It's still a problem. No matter how secure dnf config is, it is still stored inside chroot, where it can be manipulated by chrooted processes.

> As for the second point, if there is an actual need for all the things you describe, just make it a pm_request config non-default option so we can all deploy the secure restricted pm_request mode and people who need the rest can disable secure mode on their systems.

:+1:

**Comment by praiskup** [comment]
@mizdebsk wrote:
> This is configurable behaviour. Default mock configs ignore it, but nothing stops user from supplying custom config that respects yum.repos.d

Well, supplying '*repo' file by fedora package is not prohibited probably, but touching `yum.conf` probably isn't considered to be "good packager's behavior".  Taking this into consideration would IMO mean that we distrust Fedora repos.  Which bring us back to the "any other BR" equivalence, where we ultimately trust Fedora.

Of course we could think about making the mock configuration more robust against yum.conf overriding, too..
