### ISSUE TITLE
mockchain on Fedora 29 fails to build localrepo

### ISSUE THREAD

**Issue by duritong** [rpm-software-management/mock#227]
### Short description of the problem

When trying to use mockchain on F29 it fails to create the local repo and hence the buld fails:

```
$ dir=$(mktemp -d)
$ mockchain -r epel-7-x86_64 -l $dir --tmp_prefix=nginx nginx-1.14.1-1.fc29.src.rpm
starting logfile: None
results dir: /tmp/tmp.oWa3pJ0w4z/results/epel-7-x86_64
config dir: /tmp/tmp.oWa3pJ0w4z/configs/epel-7-x86_64
Error making local repo: /tmp/tmp.oWa3pJ0w4z/results/epel-7-x86_64
Err: b'15:45:06: posix_spawn avoided (fd close requested) \n15:45:06: posix_spawn avoided (fd close requested) \n15:45:06: posix_spawn avoided (fd close requested) \n'
```

A mockbuild by itself works fine.

### Output of `rpm -q mock`
```
$ rpm -q mock
mock-1.4.13-1.fc29.noarch
```

**Comment by xsuchy** [comment]
This is not an issue of mock. It is an issue of createrepo_c. Or even precisely an issue of glibc which prints debug messages to stderr.
It is being tracked here https://bugzilla.redhat.com/show_bug.cgi?id=1645897

**Comment by duritong** [comment]
Well it is so far an issue of mock, that although there is an exit code of 0, mockchain still reports an error on anything on stderr. If it would look at exit codes this would not happen.
