### ISSUE TITLE
Scientfic Linux support

### ISSUE THREAD

**Issue by opoplawski** [rpm-software-management/mock#228]
### Short description of the problem

Scientific Linux is a RHEL rebuild, but isn't treated that way.

There are currently two inconsistent listings of "RHEL" clones in the code:

mockbuild/package_manager.py:
        if distribution in ['redhat', 'rhel', 'centos', 'ol']:
mockbuild/util.py:
    epel = ('centos', 'deskos', 'ol', 'rhel')

Couple items:
* We probably want to have a single place in the code to list these.
* We should add 'scientific' to support Scientific Linux
* I'm not sure 'redhat' is valid - my RHEL7.6 machine reports 'rhel'
### Output of `rpm -q mock`
mock-1.4.13-1.el7.noarch

**Comment by xsuchy** [comment]
fixed in 1fed4c7

**Comment by opoplawski** [comment]
Thanks!
