### ISSUE TITLE
root cache unpacking fails with bsdtar

### ISSUE THREAD

**Issue by larchunix** [rpm-software-management/mock#230]
### Short description of the problem

When using `bsdtar` as tar implementation, root cache decompression fails:

```
mock --init
INFO: mock.py version 1.4.13 starting (python version = 3.7.1)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
Start: unpacking root cache
pigz: abort: write error on <stdout> (Broken pipe)
bsdtar: Error opening archive: Child process exited with status 32
ERROR: Command failed:
 # bsdtar --use-compress-program pigz -xf /var/cache/mock/fedora-29-x86_64/root_cache/cache.tar.gz -C /var/lib/mock/fedora-29-x86_64/root
```

### Output of `rpm -q mock`

    mock-1.4.13-1.fc29.noarch

### Steps to reproduce issue

1. Install bsdtar

        sudo dnf install bsdtar

2. Create a buildroot using bsdtar

        mock --config-opts=tar=bsdtar --init

3. Try to re-use the previous buildroot

        mock --config-opts=tar=bsdtar --init

        INFO: mock.py version 1.4.13 starting (python version = 3.7.1)...
        [...]
        Start: unpacking root cache
        pigz: abort: write error on <stdout> (Broken pipe)
        bsdtar: Error opening archive: Child process exited with status 32
        ERROR: Command failed:
        # bsdtar --use-compress-program pigz -xf /var/cache/mock/fedora-29-x86_64/root_cache/cache.tar.gz -C /var/lib/mock/fedora-29-x86_64/root

### Any additional notes

IIUC, when unpacking the root cache, mock should invoke `bsdtar` with `unpigz` or `gunzip` as argument of the option `--use-compress-program` instead of `pigz` or `gzip`.

**Comment by xsuchy** [comment]
Hmm. The problem is that while `gtar` simply call `gzip` and add `-d` for decompression - so we can have the same name for compression and decompression - the bsdtar does not recognize `-d` and we have to call one command for compression and a different one for decompression. Which is a pitty.

**Comment by xsuchy** [comment]
Fixed. However you will have to put in config:
```
config_opts['plugin_conf']['root_cache_opts']['decompress_program'] = "unpigz"
```
and this cannot be done on command line.
