### ISSUE TITLE
RFE: please provide mock configs allowing us to install modular content

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#231]
The `fedora-repos` (resp. `fedora-rawhide-repos`) package provides `fedora-modular.repo` (resp. `fedora-rawhide-modular.repo`) file.  It would be nice if the repos with id `[fedora-modular]` was available in e.g. `fedora-29-x86_64` (no problem to have that disabled by default).

The point of this RFE is to allow me to install e.g. module stream `postgresql:9.6`, and experiment with RPM builds against the RPMs provided by that stream.

**Comment by xsuchy** [comment]
+1 Feel free to open PR if it takes me too long.

**Comment by xsuchy** [comment]
Resolved by 3b3dbec, 8e16713 and c402408.

**Comment by praiskup** [comment]
Testing builds?

**Comment by xsuchy** [comment]
https://copr.fedorainfracloud.org/coprs/g/mock/mock/package/mock/ (ppc failed, but all others are ok)
