### ISSUE TITLE
Don't clean dnf metadata with --no-clean

### ISSUE THREAD

**Issue by QuLogic** [rpm-software-management/mock#242]
### Short description of the problem

Every time I run `mock --no-clean ...` or `fedpkg mockbuild -N`, mock will enable the dnf cache and then clear the dnf metadata anyway. This is a real pain lately since I seem to be hitting a crappy mirror that can't do more than 40 kB/s and metadata is huge (in comparison).

### Output of `rpm -q mock`
mock-1.4.14-1.fc29.noarch

### Steps to reproduce issue

1. mock --clean
2. mock --install gdb
3. mock --install valgrind

(Or really, any two commands that might touch dnf using `--no-clean`)

**Comment by xsuchy** [comment]
This is duplicate of https://github.com/rpm-software-management/mock/issues/216
