### ISSUE TITLE
RFE: Dynamic Build Dependencies

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#245]
See:
rpm-software-management/rpm#593
https://fedoraproject.org/wiki/Changes/BuildRequires_Generators

**Comment by ignatenkobrain** [comment]
Is there any preference how you want to get buildreqs.nosrc.rpm? Should it be emitted by rpmbuild -bb or you are willing to execute rpmbuild -br?

**Comment by ignatenkobrain** [comment]
With patch I have proposed in RPM PR, I could imagine something like this:

```diff
diff --git a/mock/py/mockbuild/backend.py b/mock/py/mockbuild/backend.py
index 7fd3a414..ed50e6e5 100644
--- a/mock/py/mockbuild/backend.py
+++ b/mock/py/mockbuild/backend.py
@@ -510,7 +510,7 @@ class Commands(object):
         if additional_opts == ['']:
             additional_opts = []
         bd_out = self.make_chroot_path(self.buildroot.builddir)
-        command = [self.config['rpmbuild_command']] + mode + \
+        command = [self.config['rpmbuild_command']] + ['-br'] + \
                   ['--target', self.rpmbuild_arch, '--nodeps'] + \
                   check_opt + [spec_path] + additional_opts
         command = ["bash", "--login", "-c"] + [' '.join(command)]
@@ -527,13 +527,17 @@ class Commands(object):
             self.installSrpmDeps(buildreqs)
             for f_buildreqs in buildreqs:
                 os.remove(f_buildreqs)
-            self.buildroot.doChroot(command,
-                                    shell=False, logger=self.buildroot.build_log, timeout=timeout,
-                                    uid=self.buildroot.chrootuid, gid=self.buildroot.chrootgid,
-                                    user=self.buildroot.chrootuser,
-                                    nspawn_args=self._get_nspawn_args(),
-                                    unshare_net=self.private_network,
-                                    printOutput=self.config['print_main_output'])
+        command = [self.config['rpmbuild_command']] + mode + \
+                  ['--target', self.rpmbuild_arch, '--nodeps'] + \
+                  check_opt + [spec_path] + additional_opts
+        command = ["bash", "--login", "-c"] + [' '.join(command)]
+        self.buildroot.doChroot(command,
+                                shell=False, logger=self.buildroot.build_log, timeout=timeout,
+                                uid=self.buildroot.chrootuid, gid=self.buildroot.chrootgid,
+                                user=self.buildroot.chrootuser,
+                                nspawn_args=self._get_nspawn_args(),
+                                unshare_net=self.private_network,
+                                printOutput=self.config['print_main_output'])
         results = glob.glob(bd_out + '/RPMS/*.rpm')
         results += glob.glob(bd_out + '/SRPMS/*.rpm')
         self.buildroot.final_rpm_list = [os.path.basename(result) for result in results]
```

**Comment by ignatenkobrain** [comment]
> Hmm I think that comment in the code is lying. We are calling buildroot.nuke_rpm_db() on several places. I will try to remove the --nodeps option.

@xsuchy yes, but after nuke_rpm_db, chroot version of RPM is not used anywhere.

* self.buildroot.nuke_rpm_db()
* self.install_srpm(srpm) 
* self.rebuild_installed_srpm(spec_path, timeout)
* self.installSrpmDeps(rebuilt_srpm)
* And so on, nothing is using chroot version of RPM there, only host one.

So I think code is not lying.

**Comment by ignatenkobrain** [comment]
Correction: chroot version of RPM, but it uses rpmbuild.

**Comment by xsuchy** [comment]
> Is there any preference how you want to get buildreqs.nosrc.rpm? Should it be emitted by rpmbuild -bb or you are willing to execute rpmbuild -br?

I would prefer not to use `-br` because that will means different code for calling rpmbuild in old (RHEL7, F28) chroots and new chroots (F31+). I would prefer to just call rpmbuild and check the exit code.

**Comment by nim-nim** [comment]
@xsuchy: you can also reference https://pagure.io/fesco/issue/2096 and https://pagure.io/releng/issue/8129 in the root message

**Comment by xsuchy** [comment]
@ignatenkobrain you were right, the `--nodeps` cannot be removed. :(

**Comment by nim-nim** [comment]
@ignatenkobrain your releases are not big enough to be picked up over the rpm version in rawhide

Rawhide is already at release 6
https://koji.fedoraproject.org/koji/packageinfo?packageID=319

**Comment by nim-nim** [comment]
@xsuchy 
```
Wrote: /builddir/build/SRPMS/redhat-rpm-config-128-1.0.fc31.mng.5+20190113pr51.src.rpm
/usr/lib/python3.7/site-packages/mockbuild/util.py:386: UnicodeWarning: decode() called on unicode string, see https://bugzilla.redhat.com/show_bug.cgi?id=1693751
  return tuple(x.decode() if i != 1 else x for i, x in enumerate(ret))
```

**Comment by nim-nim** [comment]
mock-1.4.14-1.git.20.52e4342.fc31.noarch seems to return success (0) even when rpmbuild failed

**Comment by ignatenkobrain** [comment]
@nim-nim, please try https://github.com/rpm-software-management/mock/pull/247

**Comment by ignatenkobrain** [comment]
@xsuchy we are working with Florian on making necessary changes for `--nodeps`. Stay tuned :)

**Comment by nim-nim** [comment]
@ignatenkobrain Thanks
Would it be possible to publish the rpm and mock fixes in one or several coprs, as they land? (At least for rawhide x86_64).

It’s not really efficient if we have to rebuild all the changes separately. I have a ton a checking and gluing to do Go macro & generator side, I'd rather focus on this than rebuilding rpm or mock code.

**Comment by xsuchy** [comment]
> @ignatenkobrain Thanks
> Would it be possible to publish the rpm and mock fixes in one or several coprs, as they land? (At least for rawhide x86_64).


Speaking of mock: https://github.com/rpm-software-management/mock#nightly After every commit is push or PR merged, then build is automatically triggered.

**Comment by nim-nim** [comment]
@xsuchy yes that is the copr I'm testing with. I was confused because @ignatenkobrain seemed to imply I should rebuild something else

**Comment by nim-nim** [comment]
(but I'm easy to confuse)

**Comment by ignatenkobrain** [comment]
So with new changes (which are not implemented yet in RPM), mock workflow should be like this:

```python
while True:
    rc = subprocess.run("rpmbuild -br --nodeps *.spec")
    if rc == 11:
        pkgs_installed = installSrpmDeps(glob.glob("*.buildreqs.nosrc.rpm"))
        if pkgs_installed == 0:
            break
    else:
        break

subprocess.run("rpmbuild -ba --nodeps *.spec")
files_to_store = glob.glob("SRPMS/*.src.rpm") + glob.glob("RPMS/*.rpm")
```

**Comment by xsuchy** [comment]
I guess we can close it now. The code is there. We just need to wait for rpm, which has the support.
