### ISSUE TITLE
mockchain fails on Fedora 30 since createrepo prints to stderr by default

### ISSUE THREAD

**Issue by cheese** [rpm-software-management/mock#249]
### Short description of the problem
On Fedora 30 with createrepo_c-0.12.2-1.fc30.x86_64, createrepo prints to stderr by default. And mockchain determines createrepo failure by its stderr output. So mockchain always fails.
It seems better to test createrepo exit code instead.
### Output of `rpm -q mock`
mock-1.4.14-1.fc30.noarch
### Steps to reproduce issue

1. Run mockchain with -l option

**Comment by xsuchy** [comment]
Indeed, nice catch.

**Comment by xsuchy** [comment]
I temporary remove the sys.exit() when we createrepo_c prints something to STDERR.
Mockchain will still print the error (which may confuse user), but it will proceed further. I will talk to createrepo_c about this. I will leave this open until the final solution, but this error is no more fatal.

**Comment by praiskup** [comment]
Almost year from last update.  I'd propose to close this.  The mockchain.py code
disappeared, and now we only react on exit status.  Which is exactly what this
issue was about....  there's `--error-exit-val` createrepo_c option.  But using that
would be different topic.  Feel free to reopen and provide more data what should
happen here.
