### ISSUE TITLE
Possible UTF error form Fedora 30

### ISSUE THREAD

**Issue by jkonecny12** [rpm-software-management/mock#250]
### Short description of the problem
I'm building my package on copr from a few Fedora's back. And I have a problem, that I'm not able to build this package from Fedora-30 because of failing UTF-8 tests.

The same src.rpm package works great on Fedora 29 mock and Fedora 30 fresh installation on a VM (not mock). So it looks like this is some error in the configuration of mock. 

What came to my mind is that Fedora 30 has a new major version of GCC so maybe it reads some other environment variables from a system, and mock should be adjusted to that.

### Output of `rpm -q mock`
Version what is now used in Fedora copr.
Or my locally installed version: mock-1.4.14-1.fc29.noarch

### Steps to reproduce issue

1. Download ``src.rpm`` from my copr repository:
```
curl -OL https://copr-be.cloud.fedoraproject.org/results/jkonecny/kakoune/fedora-30-x86_64/00884550-kakoune/kakoune-2018.09.04-44.20190417git06d4ee57.fc30.src.rpm
```
2. 
```
mock -r fedora-30-x86_64 --rebuild ./kakoune-2018.09.04-44.20190417git06d4ee57.fc30.src.rpm  --resultdir kak-rpm
```

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes
The same issue is on Rawhide mock.

And as you see [here](https://copr.fedorainfracloud.org/coprs/jkonecny/kakoune/builds/) it is happening from the begining of Fedora-30 branching. There were some other error with the GCC 9 first but then this issue raised so it really looks like related to Fedora-30 branching point.

If it is helpful I've tried also --old-chroot and that didn't helped neither.

**Comment by jkonecny12** [comment]
I tested if it will fail in the mock on the VM where the src.rpm build succeed. The result is it won't so it looks like it is not related to machine configuration but really a mock configuration.

**Comment by praiskup** [comment]
Isn't there a more targeted reproducer, with `mock -r fedora-rawhide-x86_64 --shell python3` e.g.?

**Comment by xsuchy** [comment]
I would say that it is in not a mock issue, but the issue of the target. Something changed between F29 and F30. You will have more luck if you ask on the Fedora devel list.
My wild guess is that you are missing glibc-all-langpacks as BuildRequires. Or some other dependency, which use to be transitively required, but now it is not.

**Comment by praiskup** [comment]
> I would say that it is in not a mock issue,

I tend to agree.

**Comment by jkonecny12** [comment]
OK, I'll ask there. Thanks for your help!

**Comment by jkonecny12** [comment]
> Isn't there a more targeted reproducer, with `mock -r fedora-rawhide-x86_64 --shell python3` e.g.?

Unfortunately, I wasn't able to localize this issue on a small reproducer yet. I'm just a packager not a developer of this project so it could be harder to find out for me.

**Comment by hroncok** [comment]
have you actually tried adding glibc-all-langpacks as BuildRequires?

**Comment by kathenas** [comment]
Just done f30 build and the change suggested by @hroncok works.

**Comment by jkonecny12** [comment]
Thanks a lot! It works now!
