### ISSUE TITLE
RFC: conflicting packages in buildroot with BuildRequires

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/mock#251]
One of Fedora GDB maintainers is working on "gdb-minimal" package which is small subset of gdb which is enough for buildroot purpose (without lot of unneeded dependencies). However that will conflict with with gdb, so if we install minimal version in buildroot, nobody will be able to do BuildRequires: gdb due to way how we install build deps.

## Way 1

Just pass `--allowerasing` to DNF and it will do right thing.

### Pros

* Easy to implement

### Cons

* Doesn't work with YUM (does it really matter?)
* Things which are in default buildroot might be removed (does it really matter?)

## Way 2 (more complicated, but more optimized)

Install `rpm-build` group, generate SRPM, re-initiate 

### Pros

* More correct approach from all POVs
* Faster in terms of installing right packages from first try instead of removing them when installing srpm deps

### Cons

* Harder to implement
* Slower (although all packages are cached so probably doesn't matter)
* (not mock problem) Requires implementing "favoring" mechanism in Koji and PMs to not have conflicting deps (pretty much how Suggests work in RPM)

---

Let me know what do you think and I can try to come up with a patch.

**Comment by xsuchy** [comment]
But `gdb` is not in @buildsys-build group.

**Comment by ignatenkobrain** [comment]
@xsuchy gdb is brought by rpm-build trhough `Req: /usr/bin/gdb-add-index`.... But just think in general, for example `libcurl` vs `libcurl-minimal`, `coreutils` vs `coreutils-minimal`.

**Comment by xsuchy** [comment]
Ahh, it is not `gdb`, but `gdb-headless`:

```
Finish: chroot init
INFO: Installed packages:
Start: shell
<mock-chroot> sh-5.0# rpm -q rpm-build
rpm-build-4.14.2.1-4.fc30.1.x86_64
<mock-chroot> sh-5.0# rpm -q gdb
package gdb is not installed
<mock-chroot> sh-5.0# rpm -q gdb-headless
gdb-headless-8.2.91.20190424-24.fc30.x86_64
```

**Comment by xsuchy** [comment]
`--allowerasing` is probably a good idea anyway. As users do not care about installed packages, but they want to have those packages which are going to install - as they are the BuildRequires.

**Comment by ignatenkobrain** [comment]
Well, this is questionable... Does the buildroot has to be consistent? I mean what is in buildsys-build group.. Is it MUST be installed in buildroot?

**Comment by ignatenkobrain** [comment]
I mean you can e.g. put BuildConflicts: rpm-build and your package won't build :)

**Comment by xsuchy** [comment]
BTW the implementation of `--allowerasing` would be as easy as changing the default from
`config_opts['dnf_common_opts'] = ['--setopt=deltarpm=False']` to `config_opts['dnf_common_opts'] = ['--setopt=deltarpm=False', '--allowerasing']`

**Comment by xsuchy** [comment]
From email I got privately:

```
I just would like to clarify that the change will actually not require
any modification from mock's perspective.  The final split of the GDB
package will work like this:

- gdb-minimal will provide /usr/bin/gdb.minimal.

- gdb will probide /usr/bin/gdb, and /usr/bin/gdb-add-index (which is
  the script the buildroot ultimate uses).

- /usr/bin/gdb-add-index will check if there's a /usr/bin/gdb.minimal
  binary available, and use it.  Otherwise, it will fallback to
  /usr/bin/gdb.

Therefore, no Conflicts was needed, which means that even if a package
being built depends on gdb, no problems should arise.
```

Despite this, I think that `--allowerasing` is good option for DNF in Mock. Unless I get a negative response in a week, I will put it there as new default.

**Comment by Conan-Kudo** [comment]
This is a bad idea, because it allows DNF to do crazy things like rip out parts of the build environment through `BuildConflicts`. This should not be a default behavior in Mock, IMO.

**Comment by xsuchy** [comment]
@Conan-Kudo Do you have specific example? From the above discussion I got an impression that the option to replace part of build environment is a good option.

**Comment by ignatenkobrain** [comment]
As I pointed out, replacing equivalent packages is the feature which I have requested. Like both libcurl-minimal and libcurl have same provides.

But I don't think that being able to remove redhat-rpm-config is good idea. That means you need to install build environment and builddeps of srpm at the same time. In one transaction.

**Comment by praiskup** [comment]
@msuchy wrote:
> @Conan-Kudo Do you have specific example? 

One such example: https://bugzilla.redhat.com/show_bug.cgi?id=2073385
