### ISSUE TITLE
Cannot initialize Fedora >=24 on Debian systems using mock

### ISSUE THREAD

**Issue by mdeguzis** [rpm-software-management/mock#26]
I have made efforst to port over dnf and the required runtime dependencies to Debian. Mock, since dnf is not within Debian repos, will not build Fedora >= 24. Mock on Arch Linux functions just fine, as it has dnf in the AUR. For whatever reason, I get the below error when `dnf install` kicks off. Any help is very appreciated. You may ask why? Well, why on Arch Linux?, well it's convenient to do packaging on one system, especially on the go over SSH, or if you want to avoid paying for extra VPS instances. If this will not be acted upon for any sound reason, please close.

```
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 170, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 119, in _main
    ret = resolving(cli, base)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 138, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python2.7/dist-packages/dnf/base.py", line 564, in resolve
    goal.add_protected(self.sack.query().filter(
AttributeError: 'Goal' object has no attribute 'add_protected'
```

Using dnf: http://paste.debian.net/899866
Using yum: http://paste.debian.net/899860

* AUR Package: https://aur.archlinux.org/packages/dnf/
* Pool: http://packages.libregeek.org/debian/pool/main/
* Package list: http://packages.libregeek.org/debian/package_lists/jessie_main.txt

**Comment by xsuchy** [comment]
It seem you have very fresh dnf (as the goal.add_protected() has been added recently) but old python2-hawkey (which implements the Goal.add_protected())

**Comment by xsuchy** [comment]
Is this issue about supporting Arch or Debian? Can we focus on only one per issue? Feel free to file another issue for the second OS.

**Comment by ProfessorKaos64** [comment]
Debian only, sorry, I was just referencing Arch Linux's build script. So if I compile dnf with python3 support, that may do the trick?

**Comment by ProfessorKaos64** [comment]
Is the alternative to back off dnf (downgrade) / build dnf with python3?

**Comment by xsuchy** [comment]
> So if I compile dnf with python3 support, that may do the trick?

No, you need recent version of hawkey (which provides python bindings to hawkey).

The alternative is to downgrade DNF. E.g. dnf-1.1.10 does not use goal.add_protected()

**Comment by ProfessorKaos64** [comment]
Ok, i'll work on porting over libhif. Thank you. I'll see where that gets me here today.

**Comment by ProfessorKaos64** [comment]
Got it, will do. I am trying to hold off until tomorrow to upload rebuilds with python3 support. My bandwidth already went over my 600 GB, so trying to minimize financial damages for overage :)

**Comment by Conan-Kudo** [comment]
@mdeguzis Have you made any progress on this?

**Comment by mdeguzis** [comment]
I was able to build all the packages I needed, but still would get some strange error when running mock. I dug up the issues post I had on this where I detailed the error:

```
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 170, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 119, in _main
    ret = resolving(cli, base)
  File "/usr/lib/python2.7/dist-packages/dnf/cli/main.py", line 138, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python2.7/dist-packages/dnf/base.py", line 564, in resolve
    goal.add_protected(self.sack.query().filter(
AttributeError: 'Goal' object has no attribute 'add_protected'
ERROR: Command failed. See logs for output.
 # /usr/bin/dnf --installroot /var/lib/mock/fedora-24-x86_64/root/ --releasever 24 --disableplugin=local --setopt=deltarpm=false install @buildsys-build
```

Log: http://paste.debian.net/904284/

You can reference any packages here: http://packages.libregeek.org/debian/pool/main/

I can provide more logs if need be, but this is where I last left things

* dnf_2.0.0+rc1.1
* libsolv0_0.6.21
* glib2.0_2.50
* libcomps_0.1.8
* librepo_1.7.20
* mock_1.2.18
* python-iniparse_0.4
* python-pygpgme_0.3

**Comment by Conan-Kudo** [comment]
@mdeguzis I'm sorry, but nearly all of DNF's library dependencies are built wrong. None of them are built as archful packages that also have their Python bindings built.

You can check the RPM spec files (usually named `<name>.spec` in the root of each project repository) to see how the packages are built.

And if you're building DNF 2.0 (which went GA), you'll also need dnf-plugins-core 1.0.0, and the latest snapshot of libdnf. Substitute libdnf for hawkey if you're using DNF 1.1 and dnf-plugins-core 0.1.21 instead.

**Comment by mdeguzis** [comment]
> DNF's library dependencies are built wrong. None of them are built as archful packages that also have their Python bindings built.

You mean how mine are built? I can re-evaluate them sometime in the near future. And yes, I did model a few after .spec files. I do have the core plugins installed and libdnf. I didn't list them above, as they are sub-packages of the main dnf set.

**Comment by xsuchy** [comment]
I suppose there is nothing on Mock level, we can do. So closing this one. If you (or anyone) want some general help, feel free to write to https://lists.fedoraproject.org/admin/lists/buildsys%40lists.fedoraproject.org/
