### ISSUE TITLE
Remove "BUILDSTDERR" from log

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/mock#266]
I understand the motivation for #8, but it has two undesirable side-effects:

1. The log cannot be reasonably used for upstream without being questioned "what does the BUILDSTDERR means, I can't see it in my output."
2. It bloats the logs. It is 13 additional bytes for every stderr output.

**Comment by voxik** [comment]
IOW, it is nice we can do this, but it should be off by default and enabled only optionally if needed.

**Comment by xsuchy** [comment]
I can make it optionally, or allow to define your own string (even empty one). That is easy. 

I have problem with the default thou. Can you ask people on fedora-devel mailing list? If I will get more votes, I will flip the default, but I do not want to flip the default there and back every year.

**Comment by hroncok** [comment]
I use mock heavily and when I post snippets upstream, I usually remove the BUILDSTDERR part and it is tedious. Not having it by default would work for me better but it is not a strong opinion. I.e. if differentiating between stdout and stderr is important for others, I don't mind keeping the default as is.

**Comment by junaruga** [comment]
I understand BUILDSTDERR to distinguish stderr from stdout.
But I have never faced at the situation that the feature solved a issue. (Just only in my experience).

I would prefer "default: empty" (no prefix "BUILDSTDERR: ") . It's convenient to report the log to upstream project.

**Comment by jaredsmith** [comment]
I prefer to have some sort of STDERR string, but as long as it's configurable, I'm happy.

**Comment by Conan-Kudo** [comment]
I'd prefer to _not_ have a BUILDSTDERR string by default, as it makes it more difficult for upstream to understand logs when I send them.

**Comment by jamesjer** [comment]
I also prefer to _not_ have BUILDSTDERR printed by default, for the reasons others have given above.

**Comment by phmccarty** [comment]
I would prefer to see the STDERR string configurable and set to the empty string by default.

**Comment by ignatenkobrain** [comment]
I do not care whether it is configurable or not, but I would prefer to not see it.
