### ISSUE TITLE
mock --chain does not respect --resultdir

### ISSUE THREAD

**Issue by garybuhrmaster** [rpm-software-management/mock#267]
### Short description of the problem

When using mock --chain, --resultdir is not used as a full results directory.  Instead a directory in /var/tmp is created.  The contents in --resultdir do have the root/build/state logs, but no RPMs, and there is no (obvious) programmatic direct reference to where the RPMs are located.

### Output of `rpm -q mock`

mock-1.4.16-1.git.36.1192de0.fc30.noarch

### Steps to reproduce issue

1. mock --resultdir [directory] --chain [SRPM1] [SRPM2]

**Comment by xsuchy** [comment]
With `mockchain` there was no resultdir, but instead `-l LOCALREPO, --localrepo=PATH`. I tried to preserve this. 
I will just document that resultdir cannot be used together with --chain.
