### ISSUE TITLE
Need an EPEL7 config file for the 64-bit ARM (AArch64) architecture

### ISSUE THREAD

**Issue by damarlin** [rpm-software-management/mock#27]
AArch64 is now included in EPEL7, but there is no EPEL7 AArch64 mock config file, only x86_64 and ppc64le:

   epel-7-ppc64le.cfg
   epel-7-x86_64.cfg

Adding the config file may be contingent on the availability of appropriate distribution-gpg-keys, so an issue has also been filed for that:

  https://github.com/xsuchy/distribution-gpg-keys/issues/5

Please add an epel-7-aarch64.cfg file to mock.

**Comment by damarlin** [comment]
I was able to successfully complete a test EPEL7 AArch64 mock build using the attached epel-7-aarch64.cfg file and distribution-gpg-keys-1.9-1.

Please add this config file to mock (etc/mock/epel-7-aarch64.cfg).

(Note: I appended the '.txt' extension to the config file name so I could attach it to this issue.)

[epel-7-aarch64.cfg.txt](https://github.com/rpm-software-management/mock/files/631971/epel-7-aarch64.cfg.txt)

**Comment by xsuchy** [comment]
committed as 1b3fe8f
Thank you.
