### ISSUE TITLE
--config-opts=releasever=X gives a TypeError when X is a number

### ISSUE THREAD

**Issue by yewwayne** [rpm-software-management/mock#270]
### Short description of the problem
The parsing of --config-opts (80273e1) optimistically converts values from str to int if it looks like an int. I'm using mock with a distro where releasever happens to be a number. Setting this via --config-opts causes a TypeError to be thrown from _PackageManager.execute, when subprocess.Popen encounters a non-str element in its argument list.

### Output of `rpm -q mock`
mock-1.4.16.1-47.x86_64

### Steps to reproduce issue
1. `/usr/bin/mock --buildsrpm --source=./ --spec=mock.spec --result=results/ --no-cleanup-after --uniqueext=mock --config-opts=releasever=1` (any other spec file should do)

Stack trace: https://gist.github.com/yewwayne/7e544f36d83e39618ccb69a089353bb0

### Any additional notes

`mock --debug-config` shows `config_opts['releasever'] = 1`, expecting `'1'`.

Simply removing the int conversion from `set_config_opts_per_cmdline` would solve the immediate issue... at the expense of those who actually need to set integer values. Maybe there should be some way for users to indicate the intended data type.

**Comment by xsuchy** [comment]
I think that the conversion is right. If something looks like int, it should be int.
But when we pass it to something which expects string, we should convert it there.
Fixed in commit f0bff63
Thank you for the report.
