### ISSUE TITLE
--bootstrap-chroot fails with epel-7-x86_64

### ISSUE THREAD

**Issue by RedDwarf69** [rpm-software-management/mock#275]
Fedora 30 with `mock-1.4.16-1.fc30.noarch` and `mock-core-configs-30.3-1.fc30.noarch`.

Running `mock -r epel-7-x86_64 --init --bootstrap-chroot` fails when trying to call `yum` to populate the "non-bootstrap" root, complaining it can not find `libelf.so.1`.

It looks like `devtoolset-3-elfutils-libelf` is being installed instead of the system libelf. And since yum is not being called using `scl` no libelf.so.1 can be found at all.

**Comment by RedDwarf69** [comment]
If `yum` (the old yum RPM package) is installed the problem disappears!
Not sure where the issue is. But if unfixed, somebody should talk with Michal Domonkos about https://fedoraproject.org/wiki/Changes/Retire_YUM_3 before Fedora 31 is released.

**Comment by praiskup** [comment]
Please apply this patch locally https://github.com/rpm-software-management/mock/pull/268

**Comment by xsuchy** [comment]
Addressed in https://github.com/rpm-software-management/mock/pull/268
