### ISSUE TITLE
RFE: %generate_buildrequires should re-run until all dependencies are satisfied

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#276]
https://github.com/rpm-software-management/rpm/issues/755

%generate_buildrequires currently only runs once. it should loop until no new depndencies are needed.

To reproduce:

```
%generate_buildrequires
echo package1
if rpm -q package1 &>/dev/null; then echo package2; fi
```

Actual result:

```
Executing(%generate_buildrequires):
+ umask 022
+ cd /builddir/build/BUILD
+ echo package1
+ rpm -q package1
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
package1
Wrote: /builddir/build/SRPMS/reproducer_dynbrs-0.0-1.fc31.buildreqs.nosrc.rpm
Child return code was: 11

(installs package1)

Executing(%generate_buildrequires):
+ umask 022
+ cd /builddir/build/BUILD
+ echo package1
+ rpm -q package1
+ echo package2
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
package1
package2
Executing(%build):
...
```

Expected results:

```
Executing(%generate_buildrequires):
+ umask 022
+ cd /builddir/build/BUILD
+ echo package1
+ rpm -q package1
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
package1
Wrote: /builddir/build/SRPMS/reproducer_dynbrs-0.0-1.fc31.buildreqs.nosrc.rpm
Child return code was: 11

(installs package1)

Executing(%generate_buildrequires):
+ umask 022
+ cd /builddir/build/BUILD
+ echo package1
+ rpm -q package1
+ echo package2
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
package1
package2
Wrote: /builddir/build/SRPMS/reproducer_dynbrs-0.0-1.fc31.buildreqs.nosrc.rpm
Child return code was: 11

(installs package2)

Executing(%generate_buildrequires):
+ umask 022
+ cd /builddir/build/BUILD
+ echo package1
+ rpm -q package1
+ echo package2
+ RPM_EC=0
BUILDSTDERR: ++ jobs -p
+ exit 0
package1
package2
Executing(%build):
...
```

**Comment by hroncok** [comment]
See https://github.com/rpm-software-management/mock/blob/devel/mock/py/mockbuild/backend.py#L722-L725

**Comment by praiskup** [comment]
Well, we discussed this in original feature request
https://github.com/rpm-software-management/rpm/issues/104#issuecomment-366429346,
but we didn't really found a real use-case to bother with calculating fixed
point.  What is your real use-case?

**Comment by hroncok** [comment]
My real use case is Python's two phased dependency resolution in [PEP 517](https://www.python.org/dev/peps/pep-0517/).

 1. First, dependencies and build backend are parsed from the pyproject.toml file.
 2. Second, a hook is called on the build backend to get the depndencies.

It could look like this:

 1. parse toml, get depndneices: flit, build backend: flit
 2. call flit.get_deps(), get: cython

Surely, without flit, we cannot get the information about cython. in order to make this work, we need to run the dependency check twice.

**Comment by praiskup** [comment]
TBH I'm not familiar with that PEP;  though it sounds like you don't need to iterate -- but (at most) two steps.  Can flit be added to static build requires?

**Comment by hroncok** [comment]
Yes, we need just two.

yes, flit can be added to static BRs to workaround this problem. It is not always flit, there are multiple backends (setuptools, flit, poetry...).

**Comment by xsuchy** [comment]
My main point is that I do not want to have - even potential - infinite loop. And detecting that installSrpmDeps do nothing is hard.
OK. Let's do more loops. Ten loops should be enough for everybody (I am sure this will be quoted with laughter one day).

**Comment by praiskup** [comment]
constant? => config option :-)

**Comment by hroncok** [comment]
will it do 10 loops by default or only if some packages are missing?

**Comment by xsuchy** [comment]
> will it do 10 loops by default or only if some packages are missing?

only if some packages are missing. The constant is the upper limit.

**Comment by hroncok** [comment]
Awesome!

**Comment by hroncok** [comment]
> only if some packages are missing. The constant is the upper limit.

with af02efc this is not true - not only it loops even when no new buildrequires are added, but it also does not stop after 10 runs.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/mock/pull/285

**Comment by xsuchy** [comment]
Nice catch - thank you.
