### ISSUE TITLE
Missing getrandom syscall prevents running Fedora python-3.6.0 on a CentOS host

### ISSUE THREAD

**Issue by TristanCacqueray** [rpm-software-management/mock#28]
When trying to build a fedora-rawhide python3 package on a CentOS-7 host, the python3 process fails with:

```bash
Fatal Python error: failed to get random numbers to initialize Python

Aborted
```
It seems related to the use of the getrandom syscall not included in the CentOS-7 kernel.

For what it worth, I was able to mitigate the failure by setting the PYTHONHASHSEED environment as well as ld_preloading the _PyOS_URandomNonblock function.

**Comment by xsuchy** [comment]
I am not really sure if we can do anything about this on Mock level.

**Comment by ncoghlan** [comment]
CPython attempts to fall back to reading from `/dev/urandom` if the syscall is unavailable (specifically so binaries built on a system with the getrandom syscall can still run on a kernel without it), so it should just be a matter of ensuring that that path is available in the mock chroot.

**Comment by xsuchy** [comment]
/dev/urandom should be present in chroot

**Comment by ncoghlan** [comment]
The one way I could see this happening is if the syscall was failing with an error code other than `ENOSYS` or `EPERM` (as those are the only ones that fall back to reading `/dev/urandom` instead)

**Comment by hroncok** [comment]
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1410175 and https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/UAB7JJ5VPW2W2QEERZ4HIQZZB3QMB2H5/

**Comment by xsuchy** [comment]
According https://bugzilla.redhat.com/show_bug.cgi?id=1410175 it seems to be issue of python itself. So closing this issue. Please follow it under BZ 1410175.

**Comment by TristanCacqueray** [comment]
Thank you folks for the investigation, the python bug makes sense.

**Comment by Chiz3000** [comment]
Hello guys. I faced this problem on my AIX 7.1. I solved it, maybe this solution will help smb:
1. find file <Python dir>/Python/bootstrap_hash.c
2. find row with "failed to get"
3. comment /*res = pyurandom(secret, secret_size, 1, 1);*/

Done.
