### ISSUE TITLE
/dev/loop-control and /dev/loop? not created in nspawn chroot

### ISSUE THREAD

**Issue by sharkcz** [rpm-software-management/mock#298]
### Short description of the problem
/dev/loop-control and /dev/loop? device nodes are not created in the nspawn chroot, but they are in the classic chroot.

### Output of `rpm -q mock`
mock-1.4.16-2.fc30.noarch

### Steps to reproduce issue

1. mock -r fedora-rawhide-s390x --init
2. ll /dev/loop*

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by praiskup** [comment]
Can you please provide an example package which needs this feature?  I'd like to test this.

**Comment by praiskup** [comment]
@sharkcz ^

**Comment by sharkcz** [comment]
@praiskup, IIRC it came from https://bugzilla.redhat.com/show_bug.cgi?id=1707389#c17 when trying to run lorax from a rawhide chroot (nspawn vs classic). Lorax uses loop devices internally for manipulating with the installer image.
