### ISSUE TITLE
Current mock is broken with rebuilding nosrc.rpm

### ISSUE THREAD

**Issue by kwizart** [rpm-software-management/mock#300]
### Short description of the problem
nosrc.rpm are made with the assumption that any of the Source1 cannot be redistributed, so they need to be fetch in %prep (with the network enabled)
But for some reason mock is currently shocked when using NoSource: 1 (and fails on the un-availablity of Source1).

I'm supposed to recover Source1 in %prep (and before %setup).
So any earlier attempt to validate the Sources availability earlier than %prep should check if NoSource: 1 is used.

### Output of `rpm -q mock`
mock-1.4.16-1.fc29.noarch

### Steps to reproduce issue

1.  mock -r fedora-30-x86_64 rebuild my_nosource_package-1.0-1.nosrc.rpm  --enable-network
output:
```
RPM build errors:
error: Bad file: /builddir/build/SOURCES/MY_SOURCE1.tar.gz: No such file or directory
    Bad file: /builddir/build/SOURCES/MY_SOURCE1.tar.gz: No such file or directory
ERROR: Exception(my_nosource_package-1.0-1.nosrc.rpm) Config(fedora-30-x86_64) 0 minutes 13 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-30-x86_64/result
ERROR: Command failed: 
```

**Comment by xsuchy** [comment]
I am aware of nosrc (I wrote https://developers.redhat.com/blog/2014/12/10/how-to-package-proprietary-software/ ), but I never heard that sources are supposed to be downloaded in %prep. In fact, I never seen such spec. E.g. for Oracle DB, it is hard to automate. 

When I was working with nosrc.rpm, I always `copyin` the source and then executed mock.

Can you provide the spec file - or some minimal version, so I can reproduce it.

**Comment by kwizart** [comment]
I've used this one for a sample.
http://dl.kwizart.net/review/chromium-widevine-4.10.1440.18-1.fc28.nosrc.rpm
It works locally (with rpmbuild) either or not there is a Source1 content in _sourcedir (it will dowload it if not available).
But when using mock rebuild my.nosrc.rpm , it fails.

The way forward would be to avoid a download in prep, but then I need to integrate this into the koji workflow, I probably need to have an exeption on the buildfromSCM task to even produce a src.rpm (instead of nosrc.rpm) and pass it to mock. That one will only produce a nosrc.rpm along the rpms binaries...

Currently fedpkg (or alike) srpm cannot force src.rpm instead of nosrc.rpm

**Comment by xsuchy** [comment]
1) This package fails locally. If you wipe your `~/rpmbuild/SOURCES/` and run it again, it will fail for sure. You have to do:
```
--- chromium-widevine.spec.orig 2019-07-29 13:51:08.638586556 +0200
+++ chromium-widevine.spec      2019-07-29 14:08:22.995257708 +0200
@@ -36,6 +36,7 @@
   cp -p %{SOURCE0} .
 else
   spectool -gf -s 0 %{_specdir}/%{name}.spec
+  cp $(basename %{SOURCE0}) %{SOURCE0}
 fi
 sha512sum -c %{SOURCE1}
```
With this patch, I was able to build it with local `rpmbuild`. Let's move to Mock:

2) Mock always rebuilds the package with `rpmbuild -bs`. Obviously this fail, because in this case `%prep` is not yet executed and you did not `mock --copyin google-chrome-stable_current_x86_64.rpm /builddir/SOURCES/`

From my point of view, there is no regression and no bug compared to documented behavior.

What I can do, is to implement new feature - command line option `--skip-srpm-rebuild` which would skip the rebuild. It will have other issues, and I cannot recommend it for ordinary work (SCL, dynamic requires will definitely cause issues), but it may be way to go to make nosrc.rpm packages easily rebuild in Mock.

Though it will not work in Koji as Koji will never pass such option to Mock.

**Comment by kwizart** [comment]
OKay I'm about to close this bug here and assume that anything that need to build content will have to pass a full src.rpm to mock. At least this would allow to avoid to fetch source content in prep and rely on "normal" lookaside cache for source validation.

The current method would be for koji to build both nosrc.rpm and src.rpm in buildSRPMFromSCM and pass the src.rpm to mock. The src.rpm can eventually be rebuilt (1).

There is no mean yet for rpmbuild to avoid producing nosrc.rpm
%{!?force_src_rpm:NoSource: 1}
So if koji detects a nosrc.rpm, it will rebuild it with -D 'force_src_rpm 1'
If mock fetch a full src.rpm and rebuilt it, it will have the "arched" nosrc.rpm but will also have the missing source1 content, so I expect it won't be an issue (and will bypass the need to use --copyin).

Or maybe things need to be set the other way.
koji/mock only build/provides nosrc.rpm and if koji detects a nosrc.rpm it will pass the appropriate --copyin content to mock along the nosrc.rpm
It will allow to have spec using NoSource directive the usual way.

**Comment by kwizart** [comment]
Filled issue on pagure koji bug tracker: https://pagure.io/koji/issue/1584
