### ISSUE TITLE
--old-chroot missing network connection

### ISSUE THREAD

**Issue by jkonecny12** [rpm-software-management/mock#301]
### Short description of the problem
I have ``config_opts['rpmbuild_networking'] = True`` for all the below.

When you run ``--old-chroot --init`` and then ``--old-chroot --shell`` the resulting mock don't have a network connection (missing `/etc/resolv.conf`). However in case of running `--init` and then ``--old-chroot --init`` the network connection is working properly.

### Output of `rpm -q mock`
mock-1.4.16-2.fc30.noarch

### Steps to reproduce issue

1. mock -r fedora-rawhide-x86_64 --old-chroot --init
2. mock -r fedora-rawhide-x86_64 --old-chroot --chroot curl https://github.com/rpm-software-management/mock/wiki

or:

1. mock -r fedora-rawhide-x86_64 --old-chroot --init
2. mock -r fedora-rawhide-x86_64 --old-chroot --shell
3. curl https://github.com/rpm-software-management/mock/wiki

### Any additional notes

Adding ``--enable-network`` on the already initialized mock will resolve the issue.

Attaching ``--debug-config` output.
[debug.log](https://github.com/rpm-software-management/mock/files/3467204/debug.log)

**Comment by praiskup** [comment]
You need to have `config_opts['use_host_resolv'] = True` for `--old-chroot`.

**Comment by jkonecny12** [comment]
Ohh I see, thanks for the info. And why it is working when I run the ``--init`` without the ``--old-chroot`` but the other commands are then working correctly with ``--old-chroot``? Isn't that a bug or at least it could be documented I guess.

**Comment by praiskup** [comment]
> And why it is working when I run the --init without the `--old-chroot`

When you don't specify `--old-chroot`, the default is `--new-chroot` (nspawn).   And since you have ` config_opts['rpmbuild_networking'] = True`, it's expected to work (nspawn generates some resolv.conf file for you, and it **should** work - even though it is a bit racy (rhbz#1710699)).

**Comment by jkonecny12** [comment]
I see. Thanks for all the explanation. It looks it works correctly with the adjusted configuration.

**Comment by jkonecny12** [comment]
Closing this PR.
