### ISSUE TITLE
mock-core-config 30.5 does not build on RHEL 7 due to python2/python3 confusion

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#307]
### Short description of the problem
python3 is not available yet on RHEL 7, except from EPEL as python36, and the python3 dependencies are not yet available.

### Output of `rpm -q mock`
Cannot be built.

### Steps to reproduce issue

1. Obtain mock-core-configs-30.5.tar.gz tarball via git source
2. rpmbuild -ba mock-core-configs-30.5.tar.gz
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes
I've submitted a pull request to address this:

https://github.com/rpm-software-management/mock/pull/306

**Comment by xsuchy** [comment]
```
$ LC_ALL=C rpmbuild -ba /tmp/tito/mock-core-configs-31.1.tar.gz
error: File /tmp/tito/mock-core-configs-31.1.tar.gz does not appear to be a specfile.
```

**Comment by nkadel** [comment]
I'm sorry, that was a typo. I should have said:

rpmbuild -ta  mock-core-configs-30.5.tar.gz

**Comment by nkadel** [comment]
I'll set this aside until after RHEL 7.7 is finally ported to CentOS 7.7, and python3 is directly available as part of the base OS.
