### ISSUE TITLE
RFE: bind mount distribution-gpg-keys for bootstrap chroot

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#308]
Instead of installing the `distribution-gpg-keys` package into bootstrap chroot, it should be enough to just bind-mount (or copy) the host's directory `/usr/share/distribution-gpg-keys/` into bootstrap chroot.

**Comment by nkadel** [comment]
Only if the host's directory is sufficiently recent. This is not predictable, especially for RHEL, which is unlikely to insist on publishing up-to-date GPG keys for bleeding edge fedora entries.

**Comment by praiskup** [comment]
I'd say it is fair to delegate this responsibility on user (keeping the gpg keys up2date).  Also note the benefit of slightly smaller bootstrap chroot.

**Comment by nkadel** [comment]
I'd say that most of us could not care less about such a small increment in the size of the chroot tarball. Reducing the network hit against an offsite RPM repository is more important, and there are some security benefits of *not* updating such packages every time from offsite. Perhaps a small comment saying "if necessary, install this RPM to get the bleeding edge GPG keys" ?

**Comment by xsuchy** [comment]
> This is not predictable, especially for RHEL, which is unlikely to insist on publishing up-to-date GPG keys for bleeding edge fedora entries.

I already do that using package distribution-gpg-keys which is released for EPEL as well.

**Comment by xsuchy** [comment]
As of commit 63ab868 the configs are always copied into bootstrap chroot.
I will leave this open. And once 1.5.0 will be release (still lot of time ahead) we can remove the 'distribution-gpg-keys' package from configs and call it a day.
