### ISSUE TITLE
sparse files handling in root_cache

### ISSUE THREAD

**Issue by ghormoon** [rpm-software-management/mock#309]
recently I've stumbled upon issue that for some reason (most propably some global policy, the build wasn't updated at that time), when building the root cache, /..../var/log/tallylog is written, which is a sparse file -> apparent size is 62gb in my case.
mock then creates cache tarball, for future uses. so far so good, first init goes well and the environment has ~1gb.
when we use --init again with the cache present, then the environment has 62gb, because the tallylog is filled with zeroes up to the used offset. This is invconvenniet as we have multiple users using it with their own --uniqueext -> we're running out of space right away

I've tested, that if i hack in -S in the tar call (by a script doing tar -S $@), it will then expand the sparse file properly when reusing cache. The appearent size will be 62gb, but df -h goes down by ~1GB.

is there any reason not to add the argument in plugins/root_cache.py? (should i pullrequest that)?

**Comment by praiskup** [comment]
> is there any reason not to add the argument in plugins/root_cache.py? (should i pullrequest that)?

With GNU tar 1.28+, this shouldn't cause huge problems.  But with older, `-S` option was pretty expensive (each sparse file needed to be read twice from disk, once for getting info about the holes in the file - and the second time for actually reading the data).

Shouldn't be the /var/log/tallylog rather excluded, and thus put out from the cache?

**Comment by ghormoon** [comment]
i tried it now with  --exclude=./var/log/tallylog instead of -S, seems to be fine, tallylog is created later on it's own as sparse file.

maybe if we're going this way, also exclude thing like lastlog and other known sparse files?

**Comment by xsuchy** [comment]
hmm I think we can exclude whole /var/log when creating the cache

**Comment by ghormoon** [comment]
seems excluding ./var/log works for us, is there some case where that might be an issue? should we do it officially?

**Comment by ghormoon** [comment]
I've tried a PR https://github.com/rpm-software-management/mock/pull/358, how strict is approcach to PEP8 here, should i split it to two lines? it complains it's 4 chars too long :)

**Comment by praiskup** [comment]
On Wednesday, October 2, 2019 1:30:45 AM CEST ghormoon wrote:
> I've tried a PR https://github.com/rpm-software-management/mock/pull/358, how
> strict is approcach to PEP8 here, should i split it to two lines? it complains
> it's 4 chars too long :)

Yes, it's better to not add more warnings.
