### ISSUE TITLE
RFE - optionally install built package

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#314]
It would be nice to allow the option to try to install the package once it is built.

This cannot be default as many packages are only useful in full-stack (KDE, Gnome), but for lots of packages, this will be useful.

This has brought up by python team, where automatic detection can list non-existing dependency. So package can be built, but cannot be installed.

**Comment by QuLogic** [comment]
Isn't that `--postinstall`?

**Comment by xsuchy** [comment]
Right. Thanks for pointing out.
