### ISSUE TITLE
Issues using mock inside Docker

### ISSUE THREAD

**Issue by sirredbeard** [rpm-software-management/mock#318]
I am experiencing errors using mock in Docker on Azure Pipelines to build a Fedora-based image. I provide steps to reproduce this same error on bare metal below.

For background this is our [legacy build script](https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/create-targz.sh) which ran on a bare metal machine. It uses mock and systemd-nspawn to generate our image.

This the [new build script](https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/blob/master/architecture_template.yml) I created in YAML for Azure Pipelines adapted from the script above.

The key difference is that the new build script runs in a Fedora Docker container. I know this can cause issues but did my research and saw documentation mentioned it with some added flags. I gave it a shot. Ran into some issues.

As @Conan-Kudo [predicted in 2016](https://lists.fedoraproject.org/archives/list/buildsys@lists.fedoraproject.org/thread/YUMQIAGX2CEGK5QNYGFTUYO5JR36W6AX/), there is a use case for mock in Docker for these CI/CD builds, like Azure Pipelines.

So let me break down where the failure is occurring with mock in our build in the [new script](https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/blob/master/architecture_template.yml).

First, I am pulling fedora:latest and running docker with --cap-add=SYS_ADMIN --privileged set.
```
  container:
    image: fedora:latest
    options: --cap-add=SYS_ADMIN --privileged
```
[Docker initiation log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=93&view=logs&jobId=e06dbddf-4123-5e01-8ce9-2d64f2185630&taskId=4a8e3146-dcea-40d8-8abb-cb08e09ea7b8&lineStart=1&lineEnd=48&colStart=1&colEnd=1)

Then adding a group for mock due to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1740545). 
```
  steps:
  - script: sudo groupadd mock
    displayName: 'Create mock group'
```
Installing dependencies:
```
  - script: sudo dnf -y install qemu-user-static git mock
    displayName: 'Installing dependencies'
```
Getting our environment ready:
```
 - script: mkdir dist
    displayName: 'Create dist folder'

  - script: mkdir -m 0755 ./dist/dev
    displayName: 'Make sure /dev is created before later mount'
```
(creating /dev may or may not be necessary in this setting, it is a holdover tweak from our legacy script)

Adding the current user to the mock group so that being prompted for the root password doesn't interrupt out CI:
```
  - script: sudo usermod -a -G mock $(whoami)
    displayName: 'Add current user to mock group'
```

And then calling mock:
 ```
  - script: sudo mock --init --dnf --target=$(MOCK_ARCH) --forcearch=$(MOCK_ARCH) --rootdir=$(pwd)/dist --trace
    displayName: 'Use mock to initialise chroot filesystem'
```

MOCH_ARCH is aarch64 or amd64 depending on the CI job.

This results in the following errors.

1. On the amd64 build, it fails with:

```
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M f411f438e2c5456893463dc3d6dbbe56 -D /__w/1/s/dist -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 /usr/sbin/groupadd -g 1003 mock
```
Specifically `/usr/sbin/groupadd -g 1003 mock`. I am curious if this is come kind of collision with the workarounds in place above.

Complete amd64 [mock log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=93&view=logs&jobId=0d465ff4-3326-5cef-3738-80a479f74445&taskId=c210176c-f5ff-52d5-10bf-7cf8a8265fce&lineStart=1&lineEnd=313&colStart=1&colEnd=1)

2. On the aarch64 build, it gets further to attempting dnf install commands but scriplets inside fail:

```
  Running scriptlet: systemd-libs-241-10.git511646b.fc30.aarch64        129/149 
error: failed to exec scriptlet interpreter /bin/sh: Exec format error
warning: %post(systemd-libs-241-10.git511646b.fc30.aarch64) scriptlet failed, exit status 127
```
It also experiences some exceptions on aarch64:
```
INFO: EXCEPTION: [YumError()]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mockbuild/package_manager.py", line 133, in execute
    out = util.do(invocation, env=env, **kwargs)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 641, in do
    return do_with_status(*args, **kargs)[0]
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 736, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
```
Resulting in a failure on arm64.

Complete arm64 [mock log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=93&view=logs&jobId=e06dbddf-4123-5e01-8ce9-2d64f2185630&taskId=9260bc5c-907e-560a-6c62-9b43faa0649a&lineStart=1&lineEnd=10001&colStart=1&colEnd=63).

Stuff I have tried:

- Removing --privileged from the docker options.

This results in the error:
```ERROR: Command failed: 
 # /bin/mount -n --bind /var/cache/mock/fedora-30-x86_64/dnf_cache/ /__w/1/s/dist/var/cache/dnf/
```
See [amd64 log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=91&view=logs&jobId=0d465ff4-3326-5cef-3738-80a479f74445&taskId=dd85cba1-9cb1-551f-b698-800a082aa628&lineStart=1&lineEnd=312&colStart=1&colEnd=63) and [aarch64 log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=92&view=logs&jobId=e06dbddf-4123-5e01-8ce9-2d64f2185630&taskId=9260bc5c-907e-560a-6c62-9b43faa0649a&lineStart=1&lineEnd=286&colStart=1&colEnd=63).

- Using an old version of mock as below. No change.

```
  - script: sudo dnf -y install https://kojipkgs.fedoraproject.org//packages/mock/1.4.13/2.fc30/noarch/mock-1.4.13-2.fc30.noarch.rpm
    displayName: 'Installing old mock'
```

- On the arm64 failure, when I use deboostrap to build cross-platform builds I copy the statically linked qemu binaries into the chroot environment, is that necessary here?

**Comment by Conan-Kudo** [comment]
> Then adding a group for mock due to this bug.

You should probably make sure you create the group as a system user: 
```bash
groupadd -f -g 135 -r mock # workaround RHBZ#1740545
```

> when I use deboostrap to build cross-platform builds I copy the statically linked qemu binaries into the chroot environment, is that necessary here?

It shouldn't be necessary on a sufficiently new enough Linux host environment. Since Linux 4.8, if the right binfmt files are installed along with `qemu-user-static`, it should work as expected.

Mageia has [this process documented](https://wiki.mageia.org/en/Using_DNF#Setting_up_a_container_for_a_non-native_architecture), derived from [the work @npmccallum did](https://npmccallum.gitlab.io/post/cross-architecture-roots-with-dnf/).

I do not know if Debian based distributions ever fixed their qemu package for this to work properly...

**Comment by sirredbeard** [comment]
@Conan-Kudo 

> You should probably make sure you create the group as a system user:

I attempted this:

```
  steps:
  - script: sudo groupadd -f -g 135 -r mock
    displayName: 'Create mock group'
```
In [this build here](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=94).

The amd64 build still failed on:

```
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 862cca8ca4504c9a8f29601020501671 -D /__w/1/s/dist -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 /usr/sbin/groupadd -g 135 mock

```
[amd64 log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=94&view=logs&jobId=0d465ff4-3326-5cef-3738-80a479f74445&taskId=c210176c-f5ff-52d5-10bf-7cf8a8265fce&lineStart=309&lineEnd=310&colStart=1&colEnd=1)

The aarch64 build fails when it reaches dnf stage and scriptlets won't run:

```
  Running scriptlet: p11-kit-trust-0.23.16.1-1.fc30.aarch64             100/149 
error: failed to exec scriptlet interpreter /bin/sh: Exec format error
warning: %post(p11-kit-trust-0.23.16.1-1.fc30.aarch64) scriptlet failed, exit status 127
```
It also shows the exception listed above before attempting to repeat `/usr/bin/dnf --installroot /__w/1/s/dist/ --releasever 30 --setopt=deltarpm=False --disableplugin=local --disableplugin=spacewalk --forcearch aarch64 install @buildsys-build` several times.

[aarch64 log](https://dev.azure.com/whitewaterfoundry/fedora-remix-rootfs-build/_build/results?buildId=94&view=logs&jobId=e06dbddf-4123-5e01-8ce9-2d64f2185630&taskId=9260bc5c-907e-560a-6c62-9b43faa0649a&lineStart=190&lineEnd=204&colStart=1&colEnd=21)

> Since Linux 4.8, if the right binfmt files are installed along with qemu-user-static, it should work as expected.

You would think. It doesn't 'just work' like it should. So I have to do [this here](https://github.com/WhitewaterFoundry/pengwin-rootfs-builds/blob/master/debootstrap_architecture_template.yml#L28).

**Comment by sirredbeard** [comment]
Steps to reproduce on a platform other than Azure Pipelines:

1. Spin up a Ubuntu 16.04 VPS
1. Install docker [per this guide](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04)
1. git pull fedora:latest
1. docker run -ti --privileged fedora
1. sudo groupadd mock 
1. sudo dnf -y install qemu-user-static git mock
1. mkdir dist
1. mkdir -m 0755 ./dist/dev
1.  sudo mock --init --dnf --target=amd64 --forcearch=amd64 --rootdir=$(pwd)/dist --trace

Results:

```
INFO: ENTER ['_unlock_buildroot'](<mockbuild.buildroot.Buildroot object at 0x7fdf83fd7d50>)
ERROR: Command failed:
 # /usr/bin/systemd-nspawn -q -M d739b877ee7040debfde5daf4aef8dcc -D //dist -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 /usr/sbin/groupadd -g 1000 mock
```
[complete log gist](https://gist.github.com/sirredbeard/140033920d0843f9c92bd3cdf4cf5181)

**Comment by Conan-Kudo** [comment]
@sirredbeard You cannot use `qemu-user-static` from the container. It must by installed on the host environment and configured there. binfmt settings have no effect from within the container, but binfmt stuff from the host will affect containers.

**Comment by Conan-Kudo** [comment]
Also, `amd64` is not exactly a valid architecture. While it is true that rpm maintains an alias for `amd64` to `x86_64`, that isn't going to be true for all Debian architectures.

**Comment by sirredbeard** [comment]
@Conan-Kudo So qemu-user-static isn't a dependency for mock or using dnf --forcearch from inside the container?

FWIF, the underlying Ubuntu 16.04 Linux agent kernel is compiled with binfmt support.

Noted regarding amd64.

**Comment by Conan-Kudo** [comment]
> @Conan-Kudo So qemu-user-static isn't a dependency for mock or using dnf --forcearch from inside the container?

It's a dependency of the underlying host environment, because the _host kernel_ needs that information loaded in. If your CI environment won't let you load it, it'll fail every time.

**Comment by sirredbeard** [comment]
> @Conan-Kudo It's a dependency of the underlying host environment, because the _host kernel_ needs that information loaded in. If your CI environment won't let you load it, it'll fail every time.

I *think* I am following you now @Conan-Kudo.

So on our Debian-based image build on Azure Pipelines we install qemu-static directly on the Ubuntu Linux CI agent, use debootstrap, and then do cross-platform chroots.

Here we are spinning up a Fedora Docker image on the Ubuntu agent, installing qemu-static in the Fedora container, and attempting mock.

What I think you’re saying is that qemu-static needs to be installed on the Ubuntu agent first, before the Fedora container is spun up.

I guess I assumed installing qemu-static the Docker container would be sufficient and Docker would handle the rest.

But that might explain the errors on the arm64 build, which as I mentioned resemble errors resulting from missing qemu-static binaries on Debian builds.

I will need to investigate whether I can modify the Ubuntu Linux CI agent to install qemu-static before spinning up the Fedora container with the container task, or in the alternative I can install qemu-static, then install Docker, and spin up the Fedora container manually with shell tasks.

This would not explain the systemd-nspawn error above when attempting x86_64 builds on x86_64 though (or the other issue we encountered with systemd-nspawn in this environment https://github.com/systemd/systemd/issues/13400), would it?

Thank you so much for your help.

**Comment by Conan-Kudo** [comment]
> This would not explain the systemd-nspawn error above when attempting x86_64 builds on x86_64 though (or the other issue we encountered with systemd-nspawn in this environment systemd/systemd#13400), would it?

nspawn historically hasn't worked properly in Docker, so usually I advise to pass `--old-chroot` to mock in these scenarios.

**Comment by sirredbeard** [comment]
@Conan_Kudo

I will look into the qemu-static situation to try and resolve the arm64 build errors.

I will also try —old-chroot to avoid systemd-nspawn errors in amd64 builds.

As an aside, in other parts of our build that explicitly use systemd-nspawn and hitting other issues https://github.com/systemd/systemd/issues/13400 what would you recommend as a substitute in Docker, just chroot?

Thank you

**Comment by sirredbeard** [comment]
@Conan_Kudo

I will look into the qemu-static situation to try and resolve the arm64 build errors.

I will also try —old-chroot to avoid systemd-nspawn errors in amd64 builds.

As an aside, in other parts of our build that explicitly use systemd-nspawn and hitting other issues https://github.com/systemd/systemd/issues/13400 what would you recommend as a substitute in Docker, just chroot?

Thank you

**Comment by Conan-Kudo** [comment]
> As an aside, in other parts of our build that explicitly use systemd-nspawn and hitting other issues systemd/systemd#13400 what would you recommend as a substitute in Docker, just chroot?

Pretty much, yes. Nesting these things has never been supported, but chroots usually work inside of containers.

**Comment by xsuchy** [comment]
I agree with Neal. I amended the documentation to recommend `--old-chroot` with containers

**Comment by praiskup** [comment]
How ugly would be to default to `--old-chroot` if some env variable (say `container=oci` or ``container=podman`) is set?

**Comment by nkadel** [comment]
Part of the whole point of containers, and chroot, is to *not be able to detect or manipulate* that they are inside such restricted workspaces, to hinder people trying to commit meta reasoning about their workspaces. Tests for such workspaces are likely to be unstable.

**Comment by xsuchy** [comment]
@sirredbeard Did the `--old-chroot` resolved your issue?

**Comment by sirredbeard** [comment]
@xsuchy I didn't get a chance to try it. I changed my approach and instead of using a Fedora Docker image on the Ubuntu agent I just spun up a Fedora bare metal instance for a few minutes to do what I need to do on it and then shut it down. I will revisit this in the future. For now we got the documentation amended to list --old-chroot which was good.
