### ISSUE TITLE
modify f31+ i386 chroots to use koji buildroots

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#325]
Per https://fedoraproject.org/wiki/Changes/Noi686Repositories

we should have modified default mock configuration so users (and in turn copr) can still build against i386 chroots.

@nirik, is this what is expected to happen?

**Comment by praiskup** [comment]
At least looking at mirror manager output it looks like we should:

```
$ curl 'https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=i386'
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Wed, 04 Sep 2019 14:47:09 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
  <files>
    <file name="repomd.xml">
      <mm0:timestamp>1567147419</mm0:timestamp>
      <size>6276</size>
      <verification>
        <hash type="md5">ed8c66a86c0776da0dc7c65279503ba8</hash>
        <hash type="sha1">58b8c2533d479c2b1f76979dc148ca17abd91448</hash>
        <hash type="sha256">d44d4c41a5b9c5341e9a15d85727e3e219147cf51779880ef4f5bd2b093c12a1</hash>
        <hash type="sha512">3458ebba71cbae2a022b1f5509b4f47df5fd417b53222afbd79443ae600d1fad1f1a710442feb75fc38a3b6d0a97748413af4e3e1ca41fc751b59f0b2ee61445</hash>
      </verification>
      <resources maxconnections="1">
        <url protocol="http" type="http" location="US" preference="100" >http://dl.fedoraproject.org/pub/fedora-secondary/development/rawhide/Everything/i386/os/repodata/repomd.xml</url>
        <url protocol="https" type="https" location="US" preference="100" >https://dl.fedoraproject.org/pub/fedora-secondary/development/rawhide/Everything/i386/os/repodata/repomd.xml</url>
      </resources>
    </file>
  </files>
</metalink>
```

**Comment by nirik** [comment]
Ah yes, I meant to file something here. ;( 

You want to point the i386 at: https://kojipkgs.fedoraproject.org/repos/rawhide/latest/i386/ (for rawhide) and https://kojipkgs.fedoraproject.org/repos/f31-build/latest/i386/ for f31.

**Comment by praiskup** [comment]
The F31 Everything still seems to be mirrored, though.  Should we really also flip F31?

**Comment by praiskup** [comment]
To temporarily fix copr, I applied those:
https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=d2f189992f5c069b303b88d174c5daf17a571088
https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=a5ab288a3a089962aa62ecab68627292dc5bf727
Let me know if this is not OK.

**Comment by nirik** [comment]
F31 i386 trees should be gone after tomorrow. You can wait for that if you like... 
Yeah, basically they have to point to koji.

In copr it might be good to disable i386 by default and only enable it if someone explicitly enables it?

**Comment by praiskup** [comment]
The i386 chroots are only enabled explicitly in copr projects, what do you mean by the explicit enablement? :-)

**Comment by praiskup** [comment]
F31 worked-around [here](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=3544bc90ed57c00a7b465a8d42124ae774d65800).

**Comment by xsuchy** [comment]
Few notes:
* the koji repo can contain unsigned package, so I will disable gpgcheck for these two config.
* the modular repos are gone, not sure if people will be able to use platform default modules.
* I am really curious how koji will handle the load from various CI systems.
