### ISSUE TITLE
mock doesn't fail builds after rpmbuild_timeout

### ISSUE THREAD

**Issue by nirik** [rpm-software-management/mock#326]
### Short description of the problem

Passing mock a config with: 
config_opts['rpmbuild_timeout'] = 86400
doesn't seem to terminate builds after the timeout. 

### Output of `rpm -q mock`

mock-1.4.16

### Steps to reproduce issue

1. set rpmbuild_timeout to some value
2. start a build that will never finish or has a sleep 100000 at the end of build
3. watch for mock to kill build

The issue can be seen in fedora's koji.

This is using --old-chroot

**Comment by hrnciar** [comment]
Hello, I have tried to reproduce it, but I couldn't. For me the timeout termination forked perfectly. 
I had infinite loop in prep section of .spec file and `config_opts['rpmbuild_timeout'] = 60` in config. 

Here is the log:
```Finish: build setup for hello-2.10-1.fc30.src.rpm
Start: rpmbuild hello-2.10-1.fc30.src.rpm
Start: Outputting list of installed packages
Finish: Outputting list of installed packages
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.yYd0fp
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf hello-2.10
+ /usr/bin/tar -xof -
+ /usr/bin/gzip -dc /builddir/build/SOURCES/hello-2.10.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd hello-2.10
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ COUNTER=0
+ '[' true ']'
+ continue
+ '[' true ']'
+ continue
+ '[' true ']'
...
+ continue
+ '[' true ']'
ERROR: Exception(/home/thrnciar/rpmbuild/SRPMS/hello-2.10-1.fc30.src.rpm) Config(fedora-29-x86_64) 1 minutes 19 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-29-x86_64/result
ERROR: Timeout(60) expired for command:
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/hello.spec

```

**Comment by nirik** [comment]
Can you try with --old-chroot and see if that works also?

**Comment by hrnciar** [comment]
The output above was with --old-chroot.

`mock -r ~/mock/mock-core-configs/etc/mock/fedora-29-x86_64.cfg --rebuild /home/thrnciar/rpmbuild/SRPMS/hello-2.10-1.fc30.src.rpm --old-chroot`

**Comment by praiskup** [comment]
Indeed, I tried as well both with{,out} --old-chroot, and `--rebuild` command worked.
This report needs full command-line options and config file (including site-defaults).

**Comment by nirik** [comment]
ok, lets close this out then for now until I can find a good reproducer?
