### ISSUE TITLE
install device nodes for hw randon number generators

### ISSUE THREAD

**Issue by sharkcz** [rpm-software-management/mock#33]
When looking for the reason why tests for the libica crypto library fail (s390x specific package), I found it's due missing /dev/prandom device.

Citing from the "Device Drivers, Features, and Commands" book (http://www.ibm.com/developerworks/linux/linux390/documentation_dev.html): The pseudorandom number generator (PRNG) device driver provides user-space applications with pseudorandom numbers generated by the z Systems CP Assist for Cryptographic Function (CPACF).
And the interface to the kernel driver is /dev/prandom

Similarly on eg. x86 there is no /dev/hwrng in the chroots. /dev/hwnrg exists on my x86_64, ppc64, s390x machines, maybe it could be always installed.

**Comment by xsuchy** [comment]
Should be fixed now. Can you please check that I use correct mknode numbers for prandom? I do not have s390 on hand to verify.
