### ISSUE TITLE
Conditional build dependencies seem to be resolved on host

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#336]
### Short description of the problem

Conditional BRs (with `if` in them) seem to be evaluated on host.

### Output of `rpm -q mock`

mock-1.4.18-1.fc30.noarch

### Steps to reproduce issue

Run on Fedora 29, 30 or 31. Get this spec:

```
Name:           reproducer_if
Version:        0.0
Release:        1%{?dist}
Summary:        ...
License:        MIT
BuildRequires:  python3
BuildRequires:  (python3dist(importlib-metadata) if python3 < 3.8)

%description
...
```

Create a SRPM:

```
$ rpmbuild -bs reproducer_if.spec
```

See the dependencies:

```
$ rpm -qp --requires ../SRPMS/reproducer_if-0.0-1.fc30.src.rpm 
(python3dist(importlib-metadata) if python3 < 3.8)
python3
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(RichDependencies) <= 4.12.0-1
```

Attempt a rawhide mockbuild:

```
$ mock -r fedora-rawhide-x86_64 ../SRPMS/reproducer_if-0.0-1.fc30.src.rpm 
...
No matching package to install: '(python3dist(importlib-metadata) if python3 < 3.8)'
Package python3-3.8.0~b4-1.fc32.x86_64 is already installed.
Not all dependencies satisfied
Error: Some packages could not be found.
```

### Any additional notes

The conditional works good on Fedora 32. However mock running on Fedora 30 seems to choke on it. The package providing `python3dist(importlib-metadata)` was retired on Fedora 32, because it is not needed with Python 3.8.

cc @encukou

See also https://github.com/msimacek/koschei/issues/295

**Comment by hroncok** [comment]
This also affects dynamic buildrequires. When a rawhide build prints `(python3dist(importlib-metadata) if python3 < 3.8)` in `%generate_buildrequires`, Fedora 30 mock exists with `No matching package to install: '(python3dist(importlib-metadata) if python3 < 3.8)'`

**Comment by xsuchy** [comment]
After quick debugging session with Jarda M. we found that this is DNF bug. https://bugzilla.redhat.com/show_bug.cgi?id=1756902
