### ISSUE TITLE
RFE: Ability to use podman image for a bootstrap root cache

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/mock#339]
The motivation is basically the same as for the [bootstrap feature][bootstrap] itself. We want to be able to build packages for a newer system with new features. The current implementation allows e.g. build packages with rich dependencies on a host system, that doesn't support them. However, there are still limitations. Bootstrap currently can't handle a new compression format or checksum algorithm.

Our plan is to:

- Have a possibility to specify a name of a podman image in mock config
- Once it is set, mock will download the image and extract its content (`podman extract ...`) to a bootstrap root cache
- That means, that `dnf install @buildsys-build --installroot ...` will not be used to create the boostrap root because once the cache exists, then it is omitted. An update before build should be also omitted.
- We will also make the container binary configurable to allow using e.g. docker instead of podman

The prototype implementation seems to be quite straightforward, however, it looks like some polishing will be necessary to get everything working properly. Can anyone with a good knowledge of the mock codebase please elaborate what other changes will be required?

[bootstrap]: https://github.com/rpm-software-management/mock/wiki/Feature-bootstrap

**Comment by FrostyX** [comment]
Modified in PR#342

**Comment by praiskup** [comment]
Merged, can be closed.
