### ISSUE TITLE
after mock 1.4.17 cleanup_on_failure doesn't happen

### ISSUE THREAD

**Issue by bleve** [rpm-software-management/mock#349]
Ater mock 1.4.17 build failure doesn't clean up mock build root even when cleanup_on_failure hasn't been turned off, at least site-defaults.cfg shows that to be enabled by default still. cleanup_on_success still works.

**Comment by bleve** [comment]
Still affects 1.4.20. After failed build proc sys and dev/shm mounts are left behind and directory not cleaned.

**Comment by praiskup** [comment]
I can not reproduce this.  Per documentation, `cleanup_on_failure` has
effect only if `--resultdir` is used.  When I speciified --resultddir,
there's this output:

```
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.cY8Xfw (%install)
ERROR: Exception(/home/praiskup/cpio/cpio-2.12-12.1.fc32.src.rpm) Config(fedora-rawhide-x86_64) 1 minutes 11 seconds
INFO: Results and/or logs in: /tmp/results
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: state finish mismatch: current: rpmbuild cpio-2.12-12.1.fc32.src.rpm, state: build phase for cpio-2.12-12.1.fc32.src.rpm
```

Mount doesn't seem to report leftover mount points.

Can you please provide the reproducer (configuration, commandline
arguments, etc.)?

**Comment by praiskup** [comment]
Ok, the `state finish mismatch` is probably a bug, but I guess a different one, reported as #366.

**Comment by bleve** [comment]
Ah. I actually found the issue after checking root.log of successful and failed builds.

DEBUG util.py:688:  Executing command: ['/bin/umount', '-n', '-l', '/var/lib/mock/foobar-7-x86_64-testoptional-20191006-1825-9jSIQ-2517-x86_64/root/sys'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'C.UTF-8'} and shell False
DEBUG util.py:595:  umount: only root can use "--no-mtab" option
DEBUG util.py:743:  Child return code was: 1
DEBUG util.py:762:  child environment: None

Note the "--no-mtab" error, I guess unmount is not run as root.

Successful build cleanup log:

DEBUG util.py:688:  Executing command: ['/bin/umount', '-n', '-l', '/var/lib/mock/foobar-7-x86_64-testoptional-20191006-2116-GhPsF-2486-x86_64/root/sys'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'C.UTF-8'} and shell False
DEBUG util.py:743:  Child return code was: 0
DEBUG util.py:762:  child environment: None
