### ISSUE TITLE
RFE: include config templates from relative path

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/mock#350]
At this point, mock configs contain a following include

    include('/etc/mock/templates/fedora-rawhide.tpl')

While this works perfectly, it basically disallows having modified mock configs (templates) anywhere outside `/etc/mock`. For example, it is not possible to use mock configs from git repo without installing them. E.g.

    $ mock -r ./mock-core-configs/etc/mock/fedora-rawhide-x86_64.cfg --shell

fails with
    
      File "/home/jkadlcik/git/mock/mock-core-configs/etc/mock/fedora-rawhide-x86_64.cfg", line 1, in <module>
        include('/etc/mock/templates/fedora-rawhide.tpl')

    mockbuild.exception.ConfigError: Could not find included config file: /etc/mock/templates/fedora-rawhide.tpl

    ERROR: Error in configuration

This particular problem can be fixed with upgrading `mock-core-configs` package, but the main issue is that you can't simply (without installing) test changes, that you make in templates. It would be IMHO much better if instead of including

    '/etc/mock/templates/fedora-rawhide.tpl'

we would include something like

    location_of_the_mock_config + '/templates/fedora-rawhide.tpl'

**Comment by praiskup** [comment]
> we would include something like
> location_of_the_mock_config + '/templates/fedora-rawhide.tpl'

Or rather just `include('fedora-rawhide.tpl')` with something like MOCK_TEMPLATE_PATH.

Just note that this needs to be done carefully, so - by accident - we don't include something unexpected (configs python scripts).
