### ISSUE TITLE
scrub command doesn't remove bootstrap data

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/mock#351]
### Short description of the problem

`mock -r <chroot-name> --scrub all` doesn't remove bootstrap data

### Output of `rpm -q mock`

    mock-1.4.19-1.fc30.noarch

### Steps to reproduce issue

1. `mock -r fedora-rawhide-x86_64 --bootstrap-chroot --shell`
2. `mock -r fedora-rawhide-x86_64 --scrub all`
3. `ls /var/lib/mock/ /var/cache/mock/ |grep rawhide`

### Any additional notes

    [jkadlcik@localhost mock]$ mock -r fedora-rawhide-x86_64 --scrub all
    ...
    [jkadlcik@localhost mock]$ ls /var/lib/mock/ /var/cache/mock/ |grep rawhide
    fedora-rawhide-x86_64-bootstrap
    fedora-rawhide-x86_64-bootstrap

**Comment by praiskup** [comment]
On Sunday, September 29, 2019 11:47:06 PM CEST Jakub Kadlčík wrote:
> ### Short description of the problem
> 
> `mock -r <chroot-name> --scrub all` doesn't remove bootstrap data
> 
> ### Output of `rpm -q mock`
> 
>     mock-1.4.19-1.fc30.noarch
> 
> ### Steps to reproduce issue
> 
> 1. `mock -r fedora-rawhide-x86_64 --bootstrap-chroot --shell`
> 2. `mock -r fedora-rawhide-x86_64 --scrub all`
> 3. `ls /var/lib/mock/ /var/cache/mock/ |grep rawhide`
> 
> ### Any additional notes
> 
>     [jkadlcik@localhost mock]$ mock -r fedora-rawhide-x86_64 --scrub all
>     ...
>     [jkadlcik@localhost mock]$ ls /var/lib/mock/ /var/cache/mock/ |grep rawhide
>     fedora-rawhide-x86_64-bootstrap
>     fedora-rawhide-x86_64-bootstrap

I always do `mock -r <chroot> --bootstrap-chroot --scrub=all.  But yes, this is
likely a bug.
