### ISSUE TITLE
mockbuild GID is 135 hardcoded

### ISSUE THREAD

**Issue by gilShin** [rpm-software-management/mock#37]
I have installed mock package inside a mock as a prerequisite of another package that I need.
When mock init tries to assign GID 135 for mockbuild group, it fails with exit code 4 which means "already exists".
I would prefer that mock will look for an empty GID (starting with 135) instead of using 135 hard coded and fail if it is taken

**Comment by xsuchy** [comment]
The reason why mock use static GID is stated here:
https://bugzilla.redhat.com/show_bug.cgi?id=928063

Who use GID 135 on your system? Under 500 or 1000 should be only system GIDs and users one should start above 1000.

**Comment by Frodox** [comment]
Hmmm, both
```bash
# F25
$  mock --root fedora-25-x86_64 --install mock
# CentOS 7
$ mock -r epel-7-x86_64 --install mock
```

works fine now for me. But few years ago (RHEL 6.x, mock 1.2.X) I had such errors sometimes because some program inside using same gid (`497/498`).. so I need to manually change mock's gid to one more.

**Comment by gilShin** [comment]
Maybe I wasn't clear enough. I hadn't used a "private" port as 135. I have installed rhpkg that requires mock that uses GID 135.

**Comment by xsuchy** [comment]
> Maybe I wasn't clear enough. I hadn't used a "private" port as 135. I have installed rhpkg that requires mock that uses GID 135.

But you can get the error only if there is group which has GID 135 and is NOT named "mock". My question is what is name of group with GID 135 on your system (where you are getting this error).

**Comment by gilShin** [comment]
What uses 135 is mock and not mockbuild

**Comment by xsuchy** [comment]
In mock chroot the mock gid is named mockbuild and the UID of current user is also named mockbuild. This is intentionally and should not fail. Unless you provide me exact error and ideally reproducer, there is nothing I can do.

**Comment by gilShin** [comment]
You're funny. I haven't said I can't provide logs. I said I can't remember the exact error from the code.
You can't reproduce? You can reproduce easily by installing the rhpkg package in the init process.
But don't worry, I won't bother you anymore with issues.

**Comment by xsuchy** [comment]
rhpkg does not exists in Fedora. Do you mean rpkg?

And:
`mock install rpkg`
works without problem on my workstation.
