### ISSUE TITLE
--localrepo option has no effect?

### ISSUE THREAD

**Issue by fkooman** [rpm-software-management/mock#375]
### Short description of the problem

when using `mock --localrepo=/var/lib/mock/TEST file.src.rpm` the result is not placed in the specified directory as indicated by the manpage, neither is a repository created:

> --localrepo=REPO
> Set the path to put the results/repo in. This path needs to be somewhere accessible
> to users other than you for reading as the mock process doesn't run as you. Will make a 
> tempdir if not set.

This option only works in combination with `--chain`? 

### Output of `rpm -q mock`

mock-1.4.20-1.fc30.noarch

### Steps to reproduce issue

1. Run command as above

**Comment by praiskup** [comment]
Truth, it works only with --chain now.  It is not expected to create repository in normal mock build.
