### ISSUE TITLE
RFC - define mock scope

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#379]
This is Request For Comments.

During a discussion in https://github.com/rpm-software-management/mock/issues/331 there was not clear what is Mock purpose. It happened several times in the past to me, that people assume that Mock can be run everything, can build anything and is super secure. This is not true and never been.

I guess that the objective is unclear because the current Mock description says:

> A 'simple' chroot build environment manager for building RPMs.

I guess it is time to define this better. So people know what should expect and what does not.

I will try to list some obvious statements (obvious for me):

 * Mock is `rpmbuild` wrapper.
 * Mock runs `rpmbuild` in an isolated environment where is a minimal set of packages.
 * Mock helps you find missing `BuildRequires` - if it is missing and package needs it, then the build fails.
 * Mock can build packages for various platforms and architectures. Some combinations of hosts and targets may need an additional configuration.
 * Mock needs to execute some tasks under `root` privileges and malicious RPMs can put your system at risk. Mock is not safe for unknown RPMs. If you want to build packages from untrusted sources, then use some wrapper around Mock like OBS, Copr or run Mock in a virtual machine.

Any other statements are welcome. Or discussion about it. And any ideas on how to distill them into short (max one paragraph) description.

**Comment by voxik** [comment]
* Mock can prepare fresh build/development environment for specific RPM based OS.

Really, containers sucks in this, because they needs to be composed and they are always lagging behind the most recent packages. I.e. I can't imagine to use any other tool to do something like chain build.

Also, I am using mock not only for building RPMs, but for various other development and testing. It is much better tool for such stuff then [fedora-toolbox](https://github.com/containers/toolbox).

**Comment by voxik** [comment]
Just to illustrate, this is the config I am using for RubyGems development:

~~~
$ cat mock-rubygems.cfg 
config_opts['root'] = 'rubygems'
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)
# Please note the additional dependencies. Of course I could customize the content of the buildroot much more.
config_opts['chroot_setup_cmd'] = 'install @buildsys-build ruby-devel rubygem-minitest rubygem-rake rubygem-bundler rubygem-rdoc git cmake'
config_opts['dist'] = 'rawhide'  # only useful for --resultdir variable subst
config_opts['extra_chroot_dirs'] = [ '/run/lock', ]
config_opts['releasever'] = '32'

config_opts['package_manager'] = 'dnf'

config_opts['yum.conf'] = """
 ... snip ...
"""

config_opts['plugin_conf']['bind_mount_enable'] = True
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/home/vondruch/projects/rubygems', '/rubygems/' ))
~~~

**Comment by jcpunk** [comment]
For some of my small containers, I've been building the images via 'mock' rather than via anaconda->dnf->etc as mock provides a really simple way for me to build repeatable configs that basically run `dnf --installroot=/somedir`

**Comment by hroncok** [comment]
I regularly use mock for testing both RPM packages and upstream code. Somebody reports a bug on rawhide? I try to reproduce in mock. I bet I'm not alone in this.

**Comment by xsuchy** [comment]
I put it on front page. Done. https://github.com/rpm-software-management/mock/wiki#scope
