### ISSUE TITLE
RFE: Create list of packages, which mock needs to be present in the chroot.

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#382]
### Short description of the problem

I have a custom mock config on rawhide:

```
include('/etc/mock/fedora-rawhide-x86_64.cfg')

config_opts['chroot_setup_cmd'] = 'install ansible dnf'
config_opts['use_host_resolv'] = True
config_opts['rpmbuild_networking'] = True
config_opts['use_nspawn'] = False
config_opts['root'] = 'taskotron-python-versions-master'
config_opts['plugin_conf']['root_cache_opts']['dir'] = "%(cache_topdir)s/taskotron-python-versions/root_cache/"
```

### Output of `rpm -q mock`

mock-1.4.20-1.fc32.noarch

### Steps to reproduce issue

1. Get the config
2. Run `mock -r ./mock.cfg --enable-network --config-opts=root=taskotron-python-versions-gw0 --rootdir=/home/travis/build/fedora-python/taskotron-python-versions/mockroots/taskotron-python-versions-gw0 --init`

You get:

```
INFO: mock.py version 1.4.20 starting (python version = 3.8.0)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.20
INFO: Mock Version: 1.4.20
Start: dnf install
Finish: dnf install
ERROR: Could not find useradd in chroot, maybe the install failed?
```

See https://travis-ci.org/fedora-python/taskotron-python-versions/jobs/600474029

### Any additional notes

This works on Fedora 29 and 30, haven't tested 31.

Workaround is to change the config to do:

```
config_opts['chroot_setup_cmd'] = 'install ansible dnf /usr/sbin/useradd'
```

**Comment by xsuchy** [comment]
That is because

    config_opts['chroot_setup_cmd'] = 'install ansible dnf'

it will not install `useradd` command. I highly recommend to keep it untouched to the default:

    config_opts['chroot_setup_cmd'] = 'install @buildsys-build'

and use:

    config_opts['chroot_additional_packages'] = 'ansible dnf'

**Comment by xsuchy** [comment]
This is the set which Packaging guidelines say, that you may assume is installed. And, well, Mock assumes that some of those packages are present in chroot as well (like the shadow-utils). You may modify/shrink this list, but you are just behind the edge. Hic sunt leones. 
If you remove some of those packages, Mock may stop working. Or packages stop to builds. Or not. :)

**Comment by hroncok** [comment]
So using mock for testing and not for rpm builds is not supported? I want to know where I stand.

**Comment by xsuchy** [comment]
It has never been defined. See https://github.com/rpm-software-management/mock/issues/379

**Comment by xsuchy** [comment]
It would be nice to have separate list of packages which need to be presented in chroot so Mock is still operational and different list of packages which Packaging guidelines of distribution expect to be there.

**Comment by hroncok** [comment]
Would you like to hardcode the list in mock, or have a Fedora comps mock group? Would you like me to help determine the list?

**Comment by xsuchy** [comment]
... and document what `chroot_setup_cmd` is expected to do.

**Comment by xsuchy** [comment]
So the minimal list is actually quite small: `shadow-utils rpm-build`. Everything else (e.g. bash) is included using transitive dependencies.
