### ISSUE TITLE
Verbose output only when run from tty

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#383]
### Short description of the problem
When I run mock in a CI system, output lacks the details that I get running from a TTY.

### Output of `rpm -q mock`
mock-1.4.20-1.fc30.noarch

### Steps to reproduce issue

1. Not entirely sure, TBH, hence this issue

Here is the output when run in a CI system:

```
+ mock -r epel-7-x86_64  --define "%relval .711.g6afdf41" --define "%sha1 6afdf4161a613ffbcd4efe3b69d22a9419cb6279"  _topdir/SRPMS/bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8): No such file or directory
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8): No such file or directory
INFO: mock.py version 1.4.20 starting (python version = 3.7.4)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: Start(_topdir/SRPMS/bar-1.5.0-2.711.g6afdf41.fc30.src.rpm)  Config(epel-7-x86_64)
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.20
INFO: Mock Version: 1.4.20
Start: yum install
Finish: yum install
Start: creating root cache
Finish: creating root cache
Finish: chroot init
INFO: Installed packages:
Start: build phase for bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
Start: build setup for bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
Finish: build setup for bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
Start: rpmbuild bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
Start: Outputting list of installed packages
Finish: Outputting list of installed packages
Finish: rpmbuild bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
Finish: build phase for bar-1.5.0-2.711.g6afdf41.fc30.src.rpm
INFO: Done(_topdir/SRPMS/bar-1.5.0-2.711.g6afdf41.fc30.src.rpm) Config(epel-7-x86_64) 2 minutes 43 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-7-x86_64/result
Finish: run
make: Leaving directory '/var/lib/jenkins/jenkins-1/docker_1/workspace/foo-stack_bar_PR-226@3/utils/rpms'
```

But when run from a terminal, I get much much more output showing the entire build phase of the software that `mock` is building.

My gut is telling me that this is mock thinking that the verbose amount of output provided when run from a TTY is only wanted when running from a TTY and so it is suppressed when not running from a TTY.

Is there any way to force mock to display the full build output even when not running from a TTY?

**Comment by xsuchy** [comment]
As you said, this is intentional. The intent is that when you run build system or CI, you should use logs, which mock produce.
If you want to ignore that and just parse output where is mixed everything together (output of mock with rpmbuild etc.) then you can run `unbuffer mock ....`

**Comment by brianjmurrell** [comment]
Hrm.  Yes, I see.  Unfortunately, knowing enough to go look for the logs can be assuming too much knowledge on the part of people who know nothing about mock/rpm building in general, so just having the output in the main log can be more useful.

But I can see it's ugly, with `yum`/`dnf`'s progress meters and such.  :-(

**Comment by Spongman** [comment]
`unbuffer` is not an ideal solution as it causes other commands to produce output that work in a TTY, but not when piped to a file.
it would be _great_ if `mock` could add an override to disable the tty detection.
