### ISSUE TITLE
package CUnit-devel-2.1.3-13.el7.x86_64 is excluded

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#384]
### Short description of the problem
`includepkgs=devtoolset*` in `epel-7-x86_64.cfg` not being honoured thoroughly enough.

### Output of `rpm -q mock`
mock-1.4.20-1.fc30.noarch

### Steps to reproduce issue
1. Create an SRPM that `BR:`s `CUnit-devel`
1. `mock -r epel-7-x86_64  $your.src.rpm`
1. Observe end of output:
```
Package gcc-c++-4.8.5-39.el7.x86_64 is already installed.
Package systemd-219-67.el7_7.2.x86_64 is already installed.
Error: 
 Problem: cannot install the best candidate for the job
  - package CUnit-devel-2.1.3-13.el7.x86_64 is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Finish: build setup for daos-0.6.0-8.2355.g76af15c91.fc30.src.rpm
Finish: build phase for daos-0.6.0-8.2355.g76af15c91.fc30.src.rpm
ERROR: Exception(_topdir/SRPMS/daos-0.6.0-8.2355.g76af15c91.fc30.src.rpm) Config(epel-7-x86_64) 1 minutes 15 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-7-x86_64/result
ERROR: Command failed: 
 # /usr/bin/yum-builddep --installroot /var/lib/mock/epel-7-x86_64/root/ --releasever 7 /var/lib/mock/epel-7-x86_64/root//builddir/build/SRPMS/daos-0.6.0-8.2355.g76af15c91.el7.src.rpm --setopt=tsflags=nocontexts
Last metadata expiration check: 0:00:41 ago on Wed 23 Oct 2019 06:22:53 AM EDT.
Package gcc-c++-4.8.5-39.el7.x86_64 is already installed.
Package systemd-219-67.el7_7.2.x86_64 is already installed.
Error: 
 Problem: cannot install the best candidate for the job
  - package CUnit-devel-2.1.3-13.el7.x86_64 is excluded
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

### Any additional notes
Commenting out:
```
includepkgs=devtoolset*
```
lines in `sclo` and `sclo-rh` repo definitions in `epel-7-x86_64.cfg` and rerunning the above steps results in `CUnit-devel-2.1.3-13.el7` from `sclo-rh` being found and installed.

It seems there is an issue with how excluded packages are being handled.  I would expect that in this case (with `sclo*` only including `devtoolset*` packages) `CUnit-devel-0:2.1.3-8.el7` from EPEL would be installed just as if `sclo-rh` didn't have the package in it at all.

**Comment by xsuchy** [comment]
Please note that this config has

    config_opts['yum_install_command'] += ' --disablerepo=sclo*'

is CUnit-devel comming from this repo?

**Comment by xsuchy** [comment]
and `includepkgs` is a directive of yum (see man yum.conf) not Mock's

**Comment by brianjmurrell** [comment]
@xsuchy Yes, indeed, I did notice that `config_opts['yum_install_command'] += ' --disablerepo=sclo*'` but clearly it's not working when just removing the `includepkgs=` lines from the `sclo*` repos resolves the issue.

**Comment by praiskup** [comment]
This doesn't happen on my box.  Can you confirm that you see the same problems
with latest mock/mock-core-configs?

**Comment by praiskup** [comment]
I mean, with/without bootstrap chroot, I'm able to build package which BuildRequires
CUnit-devel package (it is downloaded from epel repo).  I'm closing, please reopen
if you happen to have the same issues.
