### ISSUE TITLE
mock stops working as soon as I add a local repo to the template

### ISSUE THREAD

**Issue by jfha73** [rpm-software-management/mock#388]
Hey guys,

I created a local repo so mock can find missing packages from the yum repos, I added it to the template the config file uses, but as soon as I enable it, mock says it cannot install perl-generators (a package that has nothing to do with the ones I put in the local repo) and it stops.

Is this allowed to do in mock? or should I do it another way?

Thanks,

**Comment by xsuchy** [comment]
Can you provide the config file?

Generally, I think you are hitting https://bugzilla.redhat.com/show_bug.cgi?id=1673851
and putting best=0 in your config will workaround it for you.

**Comment by ykne** [comment]
General problem is that mock does not provide a method to add custom repositories from command line. Is there a generic way of doing it?

**Comment by xsuchy** [comment]
From a man page:
```
       -a, --addrepo=REPO
              Add this repo baseurl to the yumconfig for the chroot. This can be specified multiple times. Let's  you
              point to multiple paths beyond the default to pull build deps from.
```

**Comment by ykne** [comment]
Thank you, @xsuchy ! I do see it in recent version but not in one provided for CentOS in epel, where I really need it.

**Comment by jfha73** [comment]
I tried adding best=0 to the config file, but I'm still having the same problem, I tried adding -a to mock and it says it doesn't recognize that option, the thing is that this requirement (I saw it after extracting the spec file from the src.rpm) of the package I'm trying to build does have a best version in the CentOS repos, so why is it not taking it from there? it does take it when my local repo is disabled and the -devel rpms I have in my local repo came from rebuilding the src.rpms from the CentOS vault, so I don't get what's going on here.

The config file I'm using is the epel-8-x86_64.cfg, package is for RHEL/CentOS 8, but since RedHat did not include a lot of the -devel pckages in version 8, it has become a pain to build packages for RHEL/CentOS version 8.

**Comment by praiskup** [comment]
@hrnciar, can you take a look at this please?

**Comment by hrnciar** [comment]
Hello @jfha73,

could you please write down step-by-step instructions how to reproduce it? Please include also your config file and copy here whole error you are getting. 

Thank you.

**Comment by hrnciar** [comment]
I am closing this for now, if problem still persists please reopen issue. Thank you.
