### ISSUE TITLE
zstd workaround for building fedora-31 on RHEL requires podman

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#391]
### Short description of the problem
The "use_bootstrap_image" and "use_bootstrap_container" workaround for the zstd requirement for Fedora 31 requires "podman" installed to function.

### Output of `rpm -q mock`
mock-1.4.20-1.el8

### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes
OInly critically necessary for building fedora-31 and fedor-rawhide packages.

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by xsuchy** [comment]
Yes. It requires podman. What is the problem?

**Comment by fkooman** [comment]
It is a suggested dependency:

**Comment by xsuchy** [comment]
Feel free to vote for https://bugzilla.redhat.com/show_bug.cgi?id=1528332
Closing as I do not see anything what I can do on Mock side. If you want to enhance documentation, feel free to do it. Mock's wiki is open to anyone with github account.
