### ISSUE TITLE
yum/dnf cache for mock --bootstrap-chroot is broken

### ISSUE THREAD

**Issue by RomanValov** [rpm-software-management/mock#392]
### Short description of the problem
In contrast to regular mode, when using `--bootstrap-chroot` option yum/dnf cache bind mount is not used, resulting yum/dnf cache re-downloaded on chroot cleanup.

### Output of `rpm -q mock`
mock-1.4.20-1.el7.noarch

### Steps to reproduce issue

1.
``` 
mock --bootstrap-chroot --root epel-6-x86_64 --init
```
2. 
```
mock --bootstrap-chroot --root epel-6-x86_64 --update
```
3.
```
mock --bootstrap-chroot --root epel-6-x86_64 --clean
```
4.
```
mock --bootstrap-chroot --root epel-6-x86_64 --update
```

Expected results: yum/dnf caches obtained on `--init` stage are reused on `--update` stages.
Actual results: yum/dnf caches are redownloaded on `--update` stages and kept inside `rootdir`.

**Comment by fkooman** [comment]
This is also a problem with `use_bootstrap_container`...

**Comment by praiskup** [comment]
Thanks for the report!

> In contrast to regular mode, 

In non-bootstrap scenario, your **host** cache directories are used actually because you are using dnf/yum from host -- and that's why everything works correctly _for free_.

In bootstrap scenario, this isn't resolved yet.  Doing `--clean` actually removes all the caches,
as well as `--init`.

**Comment by praiskup** [comment]
Let's underline the purpose of yum_cache plugin first (that was news for me).

The yum/dnf `--installroot` doesn't use **host's** /var/cache/ directory, but it
creates a new directory below --installroot directory (given by `cachedir`
option, which is different for dnf/yum by default).  That directory would be
cleaned with each `--clean` or `--scrub=chroot` actions, which would cause repo
re-download.  So ... the plugin rather creates additional directory under
/var/cache/mock **on host**, and pre-mounts it into the chroot before executing
the pkg manager action with `--installroot`.

The thing is that nowadays it is hard for yum_cache plugin to pick the
correct `/var/cache/{dnf,yum}` variant:

1. The "target" buildroot has "package_manager" configuration, which is
   "expected" package manager that would be installed by default into buildroot.

2. It's unclear whether /bin/yum is dnf or yum (on newer Fedora boxes, /bin/yum
   is actually symlink to dnf).

3. Bootstrap chroot, when used, has package manager installed according to
   expectations (yum on RHEL <= 7, dnf elsewhere).  But this is given by fact
   that we expect that bootstrap chroot is the same kind chroot as the target
   chroot (I mean if chroot is 'epel-6-x86_64', then the bootstrap is also
   'epel-6-x86_64').  This doesn't have to be correct expectation in future (we
   could need to bootstrap chroot XXX through chroot YYY in future), and maybe
   even nowadays (with bootstrap podman image).

Yes, we can add heuristics on host to detect whether /bin/yum is YUM or
not.  But it is not possible for bootstrap chroot, where we don't have the
/bin/yum in hand in advance.

Taking this into consideration, we have IMO two options:

1. use the same pre-defined cache directory for both DNF and YUM, no
   matter what (and setup the `cachedir=/var/cache/<pick-something>`
   option everywhere), or

2. bindmount blindly both `/var/cache/{dnf,yum}`, and accept fact that one
   of those won't be used

** I need to pick a variant ** before I'll work on the patch, or hear
other proposals.

There's another problem in current implementation; that bootstrap chroot
**shares** the cache directory with normal chroot (which might actually be
two incompatible versions of the same package manager and they can break
the cache dir to each otehr).  This needs to be fixed as well, even though
we'll download the repodata twice (acceptable, bootstrap metadata
should stay cached much longer then for normal chroot).

**Comment by fkooman** [comment]
As a first step, and a big win, it may be helpful to have `mock --chain` use the same cache for all packages and repodata, chroots in the "chain" build, in that case there is no need to worry about different yum/dnf folders/executables as that will be exactly the same for all packages in the chain build.

**Comment by praiskup** [comment]
The `--chain` option IMO doesn't make any difference here;  caches should work fine if proper package manager is used.

**Comment by RomanValov** [comment]
Thanks for the detailed review. I'd agree with second option -- mount two separate directories with the fact only one could be used, because it's plain and simple solution with less unexpected behavior and less chance to get packager conflicts. Moreover `mock` still provides a way to invoke non-standard packager, i.e. `yum` for `dnf`-by-default system and having two directories will behave same way as on deployed (non-chroot) systems.

As of reusing host directories for bootstrap and target cache -- also I agree that's a good idea to separate this caches. Any heuristics IMO is possible only as an optional behavior on top of the simple and plain solutions because it's a subject for break in any unexpected configuration.
