### ISSUE TITLE
bootstrap chroot: opensuse tumbleweed  doesn't have shadow-utils

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#395]
After 8f8863d6a, we install shadow-utils into every bootstrap chroot, but opensuse tumbleweed doesn't have that package.  So builds with --bootstrap fail.

**Comment by xsuchy** [comment]
let's overwrite it in opensuse config then.

**Comment by Conan-Kudo** [comment]
@praiskup The package name is `shadow` on openSUSE.

**Comment by Conan-Kudo** [comment]
@praiskup You also could request `/sbin/useradd`, which works on RH/Fedora and SUSE systems.

**Comment by praiskup** [comment]
It seems there's no need to install it to bootstrap chroot, though.  So we removed it from all configs.
