### ISSUE TITLE
Doesn't work inside podman

### ISSUE THREAD

**Issue by RedDwarf69** [rpm-software-management/mock#403]
While the mock documentation has a section explaining how to make it work inside Docker (https://github.com/rpm-software-management/mock/wiki#mock-inside-docker) it doesn't say anything about podman.

When trying I got this:
```
DEBUG util.py:688:  Executing command: ['/bin/mount', '-n', '-t', 'tmpfs', '-o', 'rprivate', 'tmpfs', '/var/lib/mock/epel-7-x86_64/root/proc'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'C.UTF-8'} and shell False
DEBUG util.py:595:  mount: /var/lib/mock/epel-7-x86_64/root/proc: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.
DEBUG util.py:743:  Child return code was: 32
```

It would be nice to explain in the documentation how to make it work inside podman too.

**Comment by praiskup** [comment]
See #337, which should help in your case.  But good point, we should generalize the docs somehow ( maybe `s/docker/container/`?).

**Comment by RedDwarf69** [comment]
#337 is basically about using --old-chroot, right?

This is what I get:

```
$ podman images | grep fedora
docker.io/library/fedora               31       f0858ad3febd   2 weeks ago     201 MB
$ podman run -ti --rm --cap-add=SYS_ADMIN fedora:31
[root@663bffa7cde5 /]# dnf install mock
....
Complete!
[root@663bffa7cde5 /]# mock -r fedora-31-x86_64 --init --old-chroot
INFO: mock.py version 1.4.21 starting (python version = 3.7.4)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.21
INFO: Mock Version: 1.4.21
ERROR: Command failed: 
 # /bin/mount -n -t tmpfs -o rprivate tmpfs /var/lib/mock/fedora-31-x86_64/root/proc

[root@663bffa7cde5 /]# mock -r fedora-31-x86_64 --init --new-chroot
INFO: mock.py version 1.4.21 starting (python version = 3.7.4)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.21
INFO: Mock Version: 1.4.21
Start: dnf install
ERROR: Command failed: 
 # /bin/mount -n -t tmpfs -o rprivate tmpfs /var/lib/mock/fedora-31-x86_64/root/proc
```

I have tried with `-v` and `--trace` but I have not seen the chroot/systemd-nspawn invocation. But I have no reason to believe `--old-chroot` is not doing what's supposed to.

After adding `config_opts['use_nspawn'] = False` to `/etc/mock/fedora-31-x86_64.cfg` calling mock with `-v` shows `DEBUG:     use_nspawn:  False`, still no luck.

**Comment by praiskup** [comment]
> #337 is basically about using --old-chroot, right?

Yes.

> still no luck.

We tested with `toolbox` (wrapper around `podman`).  But `toolbox` seems to do some magic on top of plain rootless unprivileged container (news for me), so that's the reason why mock doesn't work for you: 
```
$ capsh --print
Current: =
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
Ambient set =
...
```

**Comment by RedDwarf69** [comment]
I honestly barely know anything about containers. But I straced "toolbox create" and saw
```
[pid 14901] execve("/usr/bin/podman", ["podman", "create", "--dns", "none", "--env", "TOOLBOX_PATH=/usr/bin/toolbox", "--group-add", "wheel", "--hostname", "toolbox", "--ipc", "host", "--label", "com.github.containers.toolbox=tr"..., "--label", "com.github.debarshiray.toolbox=t"..., "--name", "fedora-toolbox-31", "--network", "host", "--no-hosts", "--pid", "host", "--privileged", "--security-opt", "label=disable", "--ulimit", "host", "--userns=keep-id", "--user", "root:root", "--volume", ...], 0x55da8a24e0e0 /* 56 vars */ <unfinished ...>
```

So I tried `podman run -ti --rm --privileged fedora:31` and mock now works again... in a less safe than it should way, I suspect.

**Comment by praiskup** [comment]
I suppose mock in toolbox is safer, because toolbox seems to explicitly drop some privileges from the process in `--privileged` container.

**Comment by wenningerk** [comment]
Was recently struggling with mock inside non-privileged containers as well.
Privileged was not an option as the LXD containers that travis offers (everything but AMD64)
don't allow that (at least I didn't find a way how to configure them at least to a point that
proper nesting of containers would work - I understand why it can't be privileged but
sys_admin would have been enough).
So I disabled what was possible in mock. For '/dev/shm' & '/dev/pts' there was e.g.
the 'internal_dev_setup'-switch. What stayed over was /proc & /sys which I pushed in
via container-setup from the LXD container serving as host for the nested container.
Unfortunately there is no switch to prevent mock from trying to mount them which
is why I did that in a very hacky way for the first.
I know this is far from perfect and no real solution but maybe we can go from there
somehow by e.g. having an additional switch to disable the essential-mounts.
(https://github.com/ClusterLabs/sbd/pull/103)

**Comment by Conan-Kudo** [comment]
@wenningerk It works fine inside of privileged podman when using `--old-chroot`.

**Comment by wenningerk** [comment]
> @wenningerk It works fine inside of privileged podman when using `--old-chroot`.

Well, yes if your environment allows starting a container priviledged.
The issue I was facing didn't allow it. In other cases you may just not want to live with the risk.

**Comment by praiskup** [comment]
Ok, I updated [the documentation]( https://github.com/rpm-software-management/mock/wiki#mock-inside-podman-fedora-toolbox-or-docker-container ) for containers, so it mentions rootless Podman and Fedora Toolbox.  These are working nowadays, and are very convenient.  Feel free to correct the wording.

There's a paragraph about unsharing in Docker.  It isn't 100% accurate, because it doesn't say how/what we unshare, and thet we actually attempt to unshare always (and we may not be successful)..  We could probably run the docker in appropriate mode so there wouldn't be the problem, dunno.  I'm not able to test Docker easily because I don't use it.  That said, any help with that paragraph would be awesome.

**Comment by brianjmurrell** [comment]
> Ok, I updated [the documentation](https://github.com/rpm-software-management/mock/wiki#mock-inside-podman-fedora-toolbox-or-docker-container)

This link is broken now that documentation seems to have moved.

**Comment by xsuchy** [comment]
The doc is there. Just on that new page. Only the anchor is not referenced. The full URL is https://rpm-software-management.github.io/mock/#mock-inside-podman-fedora-toolbox-or-docker-container And it would be a Herculian task to go over all old PR and update anything referencing the old doc site.
