### ISSUE TITLE
fedpkg mockbuild freezes my laptop when using nspawn

### ISSUE THREAD

**Issue by D4N** [rpm-software-management/mock#406]
### Short description of the problem

My (very weak) laptop started to freeze very often when running mockbuilds via fedpkg since the upgrade to Fedora 31. 
I have unfortunately not much that I can tell about the freeze, besides that the machine becomes completely unresponsive and ssh sessions drop. Also, the system log contains nothing suspicious/indicating what could be the issue (this might be however because it never makes it to disk: I've connected to the laptop via ssh and saw in `journalctl` that the mockbuild started, but that log entry was missing after the reboot).

Note: I was running `fedpkg mockbuild -N` most of the time. Could this be causing some extraordinary RAM load when called frequently? The machine in question only got 4GB of RAM.

Also, it appears to be related to the usage of systemd-nspawn: I've switched nspawn off in in `/etc/mock/site-defaults.cfg` and so far none of the few mockbuilds caused the freeze (but it might be too early to celebrate).

### Output of `rpm -q mock`

mock-1.4.21-1.fc31.noarch

### Steps to reproduce issue

1. Install Fedora 31
2. Run `fedpkg mockbuild -N` on a package while using nspawn (the default)
3. The involved PC freezes completely

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Consider adding output of `mock --debug-config` this can help developers to reproduce the issue.

**Comment by praiskup** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1767097

**Comment by praiskup** [comment]
There's a note in the bugzilla that the freeze is/could be triggered when systemd.rpm package is installed, is this the same case on your box?

**Comment by D4N** [comment]
Do you mean that `systemd` is being installed during the mock root setup? I don't think so, my laptop usually froze immediately after mock got launched, but not always, sometimes it took longer and sometimes it didn't freeze at all (but it happened most often immediately after launching mock).

**Comment by praiskup** [comment]
Per [1], `systemd.unified_cgroup_hierarchy=0` kernel option is a work-around:
https://bugzilla.redhat.com/show_bug.cgi?id=1767097

**Comment by praiskup** [comment]
I'm closing this since this doesn't look like an issue in mock eventually.
