### ISSUE TITLE
Mock does not clean-up btrfs subvolumes

### ISSUE THREAD

**Issue by CajuM** [rpm-software-management/mock#418]
### Short description of the problem
Mock does not clean-up btrfs subvolumes created inside the chroot

### Output of `rpm -q mock`
mock-1.4.21-1.el8.noarch

### Steps to reproduce issue

1. On a btrfs partition
2. mock -r epel-7-x86_64 --init
3. mock -r epel-7-x86_64 --clean

###
This always happens in CentOS 7 due to systemd's postinstall script calling systemd-tmpfiles --create
The relevant configuration file for systemd-tmpfiles is /usr/lib/tmpfiles.d/var.conf, specifically the line: "v /var/lib/machines 0700 - - -"
`uname -r` is "4.15.0-33-generic" it's in a container on an Ubuntu host

**Comment by xsuchy** [comment]
Do you have `btrfs-progs` installed? It is soft requirements, so you may missed it.

**Comment by CajuM** [comment]
The problem is present on a CentOS 8 guest with a CentOS 7 chroot. Installing btrfs-progs is not an option.
I solved the problem by upgrading the kernel on the lxd host

**Comment by xsuchy** [comment]
I am glad that you solved. 
Thou Mock handle BTRFS via btrfs-progs. If you do not have it, do not expect any BTRFS interaction from Mock side.
