### ISSUE TITLE
resume a build

### ISSUE THREAD

**Issue by az-z** [rpm-software-management/mock#426]
Hello,
 during the build ( mock --rebuild ) the different sections of the spec file fail. It is very expensive (time-consuming) to re-run the entire build just because of one error at the end of the spec file.

Q: Is there a way to resume the build from the same stage of spec file?
thank you

**Comment by xsuchy** [comment]
See `man mock` and look for `--short-circuit=STAGE`. I cannot recommend it for anything else than debugging. The final rpm should be always produced without this shortcut.
