### ISSUE TITLE
mock-scm: Can't find spec file /tmp

### ISSUE THREAD

**Issue by az-z** [rpm-software-management/mock#431]
### Short description of the problem
mock -v --short-circuit=build -n -N -r mock_scm_F30.cfg --rebuild codeblocks-17.12.svn.11925-1.fc30.src.rpm
the Can't find spec file /tmp/tmpokjq40hs.mock-scm.codeblocks/codeblocks/codeblocks.spec
### Output of `rpm -q mock`
mock-1.4.21-1.fc30.noarch
### Steps to reproduce issue
[az@dell5000 SRPMS]$ pwd
/home/az/Work/codeblocks/rpmbuild/SRPMS
[az@dell5000 SRPMS]$ ls
codeblocks-17.12svn11417.tar.bz2  codeblocks-17.12svn11925.tar.bz2  codeblocks.spec  codeblocks.spec0  mock_scm_F30.cfg
[az@dell5000 SRPMS]$ mock -v --short-circuit=build -n -N -r mock_scm_F30.cfg --rebuild codeblocks-17.12.svn.11925-1.fc30.src.rpm

[code]
DEBUG: A    codeblocks-17.12.svn/src/plugins/contrib/PythonPlugins/screenshots/debugger2.png
DEBUG: A    codeblocks-17.12.svn/src/plugins/contrib/PythonPlugins/screenshots/interpreters1.png
DEBUG: A    codeblocks-17.12.svn/src/plugins/contrib/PythonPlugins/screenshots/interpreters2.png
DEBUG: Checked out external at revision 400.
DEBUG: Checked out revision 11925.
DEBUG: Child return code was: 0
DEBUG: Fetched sources from SCM
DEBUG: Preparing SCM sources
ERROR: Can't find spec file /tmp/tmpokjq40hs.mock-scm.codeblocks/codeblocks/codeblocks.spec
DEBUG: Clean SCM checkout directory
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-30-x86_64
DEBUG: kill orphans
[/code]

[code]
more ./mock_scm_F30.cfg 
include('/etc/mock/fedora-30-x86_64.cfg')
config_opts['scm'] = True
config_opts['scm_opts']['method'] = 'svn'
config_opts['scm_opts']['svn_get'] = 'svn co  http://svn.code.sf.net/p/codeblocks/code/trunk/ codeblocks-17.12.svn'
config_opts['scm_opts']['spec'] = 'codeblocks.spec'
#config_opts['scm_opts']['ext_src_dir'] = '/dev/null'
config_opts['scm_opts']['write_tar'] = True
#config_opts['scm_opts']['git_timestamps'] = True
config_opts['scm_opts']['exclude_vcs'] = True
config_opts['scm_opts']['package'] = 'codeblocks'
#config_opts['scm_opts']['branch'] = 'master'
[/code]

**Comment by praiskup** [comment]
You seem to be using `mock -v --short-circuit=build codeblocks-17.12.svn.11925-1.fc30.src.rpm`, I'm not yet much familiar with the scm code, but that isn't the documented way how to use it:
https://github.com/rpm-software-management/mock/wiki/Plugin-Scm

You expect the scm plugin to generate the sources/spec for you.  No need to provide src.rpm.
Please reopen if you think that the code is really broken.
