### ISSUE TITLE
new systemd-nspawn doesn't bypass stdin as pipe to container 

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#432]
This doesn't work on F31+, while it worked fine on F30 (with systemd
systemd-241-12.git323cdf4.fc30.x86_64).

```
$ echo input | mock --shell 'cat > /file'
... hangs indefinitely, since there's no EOF on stdin ...
```

Systemd on 'F31' has `systemd-nspawn --console=pipe` for that.  But we
don't use that option now, and the feature is documented with security
"warning".  Basically, not everyone wants this....  but e.g. it breaks
[copr rpmbuild](https://pagure.io/copr/copr/issue/1123).

So we probably need a new mode, or some toggle option.

**Comment by bryteise** [comment]
I ended up patching mock to always pass the --console=pipe option via the default config_opts. I don't particularly view this as a large risk but our build infrastructure isn't public compared to fedora.

**Comment by praiskup** [comment]
... not only --shell, per
https://github.com/rpm-software-management/rpm/issues/978.  So we could
perhaps "risk" that, and do:

```patch
diff --git a/mock/py/mockbuild/util.py b/mock/py/mockbuild/util.py
index f7972ea4..dc3bdd56 100644
--- a/mock/py/mockbuild/util.py
+++ b/mock/py/mockbuild/util.py
@@ -940,7 +940,7 @@ def setup_default_config_opts(unprivUid, version, pkgpythondir):
     config_opts['online'] = True
     config_opts['use_nspawn'] = True
     config_opts['rpmbuild_networking'] = False
-    config_opts['nspawn_args'] = ['--capability=cap_ipc_lock']
+    config_opts['nspawn_args'] = ['--capability=cap_ipc_lock', '--pipe']
     config_opts['use_container_host_hostname'] = True
     config_opts['use_bootstrap_container'] = False
```

But we'd have to know that `--pipe` is suppported by systemd-nspawn.

**Comment by praiskup** [comment]
Even the live logs in copr seem to be different because of this:
```
rootdir: /builddir/build/BUILD/pip-19.3.1, inifile: setup.cfg
collected 1655 items / 137 deselected / 1518 selected                          [0m

tests/functional/test_broken_stdout.py [32m.[0m[32m.[0m[32m.[0m[36m  
```
(dunno why those special characters aren't filtered out, those should be...)

I'd prefer to flip back mock to use `--pipe` rather soon.  @xsuchy wdyt?
