### ISSUE TITLE
Compatibility with user-configs: config_opts['useradd']

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#448]
This is problem after 2a67d0655357bd070d3bf79389997d1288933210.

I noticed that I can not work with mageia configs anymore, because they still have:
`config_opts['useradd'] = /usr/sbin/useradd -o -m -u %(uid)s -g %(gid)s -d %(home)s %(user)s'`

But we don't expand those, so we
1. need to fix the mock-core-configs
2. perhaps keep the support for %() syntax for some time, and throw a warning

**Comment by praiskup** [comment]
opensuse and openmandriva configs have the same problem.

**Comment by Conan-Kudo** [comment]
I'd suggest going ahead and fixing the configs in mock-core-configs. I copied them from the defaults and removed the unsupported `-n` option (it's Red Hat specific, apparently).

**Comment by praiskup** [comment]
So you wouldn't expect that the `%(foo)` syntax is present in custom user's configs?

**Comment by xsuchy** [comment]
+1 for replacing those option in configs.

**Comment by Conan-Kudo** [comment]
@praiskup I don't, no.
