### ISSUE TITLE
Setting up a default LANG in mock configs

### ISSUE THREAD

**Issue by eclipseo** [rpm-software-management/mock#451]
I'd like you to add:
```
config_opts['environment']['LANG'] = 'C.UTF-8'
```
in default mock configs. When running fedora-review, several errors of the type `Failed to set locale, defaulting to C.UTF-8` appears and adding the above as a default environment for mock fixes it.

**Comment by xsuchy** [comment]
The current default is
```
os.environ.setdefault('LANG', 'C.UTF-8')
```
which is: use current $LANG or 'C.UTF-8' when LANG is not set.

**Comment by praiskup** [comment]
It sounds like user's LANG host configuration shouldn't affect the build,
so think the request is valid.  Rather then instruct fedora-review people
to run LANG=C.utf8 mock.., wdyt?

**Comment by hroncok** [comment]
> user's LANG host configuration shouldn't affect the build

Hear, hear!

**Comment by praiskup** [comment]
Even koji builders have the host's lang overridden:
https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/koji_builder/templates/builders/site-defaults.cfg?id=a6ae71e459f78a39fa29a3766893843392f22abf
