### ISSUE TITLE
some mock chroots are broken

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#452]
Using https://github.com/praiskup/mock-tests/blob/master/test-mock-configs.sh I tested
stuff after #450, and some of the chroots have broken configuration (namely gpg config).

**Comment by praiskup** [comment]
```
amazonlinux-2-aarch64 - build failed
amazonlinux-2-x86_64 - build failed
centos-stream-aarch64 - OK
centos-stream-ppc64le - OK
centos-stream-x86_64 - OK
custom-1-aarch64 - build failed
custom-1-armhfp - build failed
custom-1-i386 - build failed
custom-1-ppc64 - build failed
custom-1-ppc64le - build failed
custom-1-s390 - build failed
custom-1-s390x - build failed
custom-1-x86_64 - build failed
epel-6-i386 - OK
epel-6-ppc64 - build failed
epel-6-x86_64 - OK
epel-7-aarch64 - OK
epel-7-ppc64 - OK
epel-7-ppc64le - OK
epel-7-x86_64 - OK
epel-8-aarch64 - OK
epel-8-ppc64le - OK
epel-8-x86_64 - OK
epelplayground-8-aarch64 - build failed
epelplayground-8-ppc64le - build failed
epelplayground-8-x86_64 - OK
fedora-27-x86_64 - OK
fedora-30-aarch64 - OK
fedora-30-armhfp - OK
fedora-30-i386 - OK
fedora-30-ppc64le - OK
fedora-30-s390x - OK
fedora-30-x86_64 - OK
fedora-31-aarch64 - OK
fedora-31-armhfp - OK
fedora-31-i386 - OK
fedora-31-ppc64le - OK
fedora-31-s390x - OK
fedora-31-x86_64 - OK
fedora-rawhide-aarch64 - OK
fedora-rawhide-armhfp - OK
fedora-rawhide-i386 - OK
fedora-rawhide-ppc64le - OK
fedora-rawhide-s390x - OK
fedora-rawhide-x86_64 - OK
mageia-6-armv5tl - OK
mageia-6-armv7hl - OK
mageia-6-i586 - OK
mageia-6-x86_64 - OK
mageia-7-aarch64 - OK
mageia-7-armv7hl - OK
mageia-7-i586 - OK
mageia-7-x86_64 - OK
mageia-cauldron-aarch64 - OK
mageia-cauldron-armv7hl - build failed
mageia-cauldron-i586 - OK
mageia-cauldron-x86_64 - OK
openmandriva-4.0-aarch64 - build failed
openmandriva-4.0-armv7hnl - build failed
openmandriva-4.0-i686 - build failed
openmandriva-4.0-x86_64 - OK
openmandriva-cooker-aarch64 - OK
openmandriva-cooker-armv7hnl - OK
openmandriva-cooker-i686 - OK
openmandriva-cooker-x86_64 - OK
openmandriva-rolling-aarch64 - OK
openmandriva-rolling-armv7hnl - OK
openmandriva-rolling-i686 - OK
openmandriva-rolling-x86_64 - OK
opensuse-leap-15.0-aarch64 - build failed
opensuse-leap-15.0-x86_64 - OK
opensuse-leap-15.1-aarch64 - build failed
opensuse-tumbleweed-aarch64 - OK
opensuse-tumbleweed-i586 - OK
opensuse-tumbleweed-ppc64 - OK
opensuse-tumbleweed-ppc64le - OK
opensuse-tumbleweed-x86_64 - OK
rhel-6-x86_64 - OK
rhel-7-aarch64 - build failed
rhel-7-ppc64 - build failed
rhel-7-ppc64le - build failed
rhel-7-x86_64 - OK
rhel-8-aarch64 - build failed
rhel-8-ppc64 - build failed
rhel-8-ppc64le - build failed
rhel-8-x86_64 - OK
rhelepel-8-aarch64 - build failed
rhelepel-8-ppc64 - build failed
rhelepel-8-ppc64le - build failed
rhelepel-8-x86_64 - OK
```

**Comment by praiskup** [comment]
> ```
> amazonlinux-2-aarch64 - build failed
> amazonlinux-2-x86_64 - build failed
> ```

Per rpm-software-management/mock/pull/343 this doesn't work on Fedora.
Expected.

```
> custom-1-aarch64 - build failed
> custom-1-armhfp - build failed
> custom-1-i386 - build failed
> custom-1-ppc64 - build failed
> custom-1-ppc64le - build failed
> custom-1-s390 - build failed
> custom-1-s390x - build failed
> custom-1-x86_64 - build failed
```

These don't work without manual tweaks, by design.

```
> epel-6-ppc64 - build failed
```

Seems like there's no CentOS-6 rebuild.  So we should drop this useless
config, perhaps we could add rhelepel-6-ppc64 if anyone requested this.

```
> epelplayground-8-aarch64 - build failed
> epelplayground-8-ppc64le - build failed
```

The `epel-rpm-macros` and `fedpkg-minimal` packages aren't available
there, yet.   I tried blind shot for epel-rpm-macros first
https://bugzilla.redhat.com/show_bug.cgi?id=1793547
but I guess we should drop those for now as well if the response is
negative..  just to not confuse people.

```
> mageia-cauldron-armv7hl - build failed
> openmandriva-4.0-aarch64 - build failed
> openmandriva-4.0-armv7hnl - build failed
> openmandriva-4.0-i686 - build failed
> opensuse-leap-15.0-aarch64 - build failed
> opensuse-leap-15.1-aarch64 - build failed
```

These seem to have non-signed content.  @Conan-Kudo   Is it valid to disable
gpgcheck for them?

```
> rhel-7-aarch64 - build failed
> rhel-7-ppc64 - build failed
> rhel-7-ppc64le - build failed
> rhel-8-aarch64 - build failed
> rhel-8-ppc64 - build failed
> rhel-8-ppc64le - build failed
> rhelepel-8-aarch64 - build failed
> rhelepel-8-ppc64 - build failed
> rhelepel-8-ppc64le - build failed
> ```

For some reason, subscribed x86_64 box isn't able to download
non-supported arches.  I need to take a deeper look here.

**Comment by Conan-Kudo** [comment]
@pterjan Is something up with Cauldron signing for ARM?

@berolinux Can you check what's up with the OpenMandriva Lx4 repos?

@lnussel Is the AArch64 content supposed to not be signed? Or is it signed with a different key? Or what? We're currently using the standard openSUSE GPG key: https://github.com/xsuchy/distribution-gpg-keys/blob/master/keys/opensuse/RPM-GPG-KEY-openSUSE

**Comment by berolinux** [comment]
@Conan-Kudo Looks like the bad signature in OpenMandriva repos is caused by our appstream experiments -- repomd.xml is signed, then appstream metadata is added (of course causing the file to change and the signature indicating that). Got to move package signing, should be fixed soon

**Comment by lnussel** [comment]
all openSUSE repos and images are meant to be signed, please file a bug if that is not the case.

**Comment by praiskup** [comment]
> ```
> > rhel-7-aarch64 - build failed
> > rhel-7-ppc64 - build failed
> > rhel-7-ppc64le - build failed
> > rhel-8-aarch64 - build failed
> > rhel-8-ppc64 - build failed
> > rhel-8-ppc64le - build failed
> > rhelepel-8-aarch64 - build failed
> > rhelepel-8-ppc64 - build failed
> > rhelepel-8-ppc64le - build failed
> ```
> 
> For some reason, subscribed x86_64 box isn't able to download
> non-supported arches. I need to take a deeper look here.

This is probably expected.  I asked officially [1], but if there's no way to
get arch-agnostic subscription, we'll probably have to document this as
expected.

It also makes the configs hard-to-test on single x86_64 host.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1794104

**Comment by pterjan** [comment]
We should have signed packages in Mageia, but there was a bug for optional architectures (that's only armv7hl nowadays) when retrying upload which affected a small number of packages. This should get fixed soon with the coming mass rebuild.

**Comment by praiskup** [comment]
Tested on F31 x86_64, with the current head 62291d5db7a682e8521613728e10ef8a607a3ca1.
Still some failures, but those don't seem to be issues in mock.  I'm going to release now.
```
epel-8-ppc64le - build failed (--bootstrap-chroot)
epelplayground-8-aarch64 - build failed (--no-bootstrap-chroot)
epelplayground-8-ppc64le - build failed (--no-bootstrap-chroot)
mageia-6-armv5tl - build failed (--bootstrap-chroot)
mageia-6-armv7hl - build failed (--bootstrap-chroot)
mageia-6-i586 - build failed (--bootstrap-chroot)
mageia-6-x86_64 - build failed (--bootstrap-chroot)
mageia-7-armv7hl - build failed (--bootstrap-chroot)
mageia-cauldron-i586 - build failed (--bootstrap-chroot)
openmandriva-4.0-aarch64 - build failed (--no-bootstrap-chroot)
openmandriva-4.0-armv7hnl - build failed (--no-bootstrap-chroot)
openmandriva-4.0-i686 - build failed (--no-bootstrap-chroot)
openmandriva-rolling-aarch64 - build failed (--no-bootstrap-chroot)
openmandriva-rolling-armv7hnl - build failed (--no-bootstrap-chroot)
openmandriva-rolling-i686 - build failed (--no-bootstrap-chroot)
openmandriva-rolling-x86_64 - build failed (--no-bootstrap-chroot)
opensuse-leap-15.0-aarch64 - build failed (--no-bootstrap-chroot)
opensuse-leap-15.0-x86_64 - build failed (--bootstrap-chroot)
opensuse-leap-15.1-aarch64 - build failed (--no-bootstrap-chroot)
```

**Comment by praiskup** [comment]
This is also interesting:
https://copr.fedorainfracloud.org/coprs/praiskup/ping/build/1245804/

With the newly released mock-core-configs, some of the chroots still fail in copr
(mirror issues, etc.).   I don't have time now to report this, or resolve.  Feel free
to take a look at this if you are concerned.

**Comment by praiskup** [comment]
Moved to separate issues #530, #529, #527, #525 and #522.
