### ISSUE TITLE
rename config_opts[use_bootstrap_container] to config_opts[bootstrap]?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#458]
Or any better name?

The thing is that we want to flip this ON by default, which means that e.g. Koji might
likely want to turn this OFF.  And, despite the misleading cmdline option is
`--bootstrap-chroot`, they'd need to use even more misleading option
`config_opts['use_bootstrap_container'] = False`.

Neither _chroot_ nor _container_ is correct term 
because it depends on `use_nspawn` option which of them is used.  Also,
since there`s now `--use-bootstrap-image`, people tend to mix-up "containers"
with "images".  So they think `--bootstrap-chroot` is equivalent to
`--use-bootstrap-image` and vice versa.

This isn't probably material for v1.5, but we should do something about it,
ideas?

**Comment by xsuchy** [comment]
Yeah, `use_bootstrap_container` is clumsy name. I think changing it to simple `bootstrap_chroot` will be nice.

The `chroot` in the name is with the outlook that one day we will have to address bootstrapping RPMs  https://docs.fedoraproject.org/en-US/packaging-guidelines/#bootstrapping

I think we can do that for 1.5 without a problem.
