### ISSUE TITLE
mock chain seems to be broken, per testsuite

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#469]
Looking at release notes I totally forgot about this :-(.  I'll have a look first at this
and fix before announcement and official builds.

**Comment by AdamWill** [comment]
This was a bit of a rude change to push to stable releases, because it breaks any config that inherits from one of the changed configs and adds settings to the `[yum.conf]` section - because now that section doesn't exist any more.

This actually broke openQA update testing, because we do exactly that as part of it.

**Comment by praiskup** [comment]
This PR has nothing to do with the status, right?  The yum.conf ->
dnf.conf default change was done long time ago, and we had to push it
eventually one day (or revert).  The only new thing in this PR is that if you specify
both config options mock rants -- that's because (especially with the
changed in mock-core-configs) we need to warn users that they have broken
configuration, instead of not-using and ignoring the additions to
`yum.conf`.

Do you have idea how to mitigate this in mock?  How to make both
config_opts['yum.conf'] / config_opts['dnf.conf'] equivalent?  Patches are
welcome.

I guess you are using `config_opts['yum.conf'] += `.  Now you can do
`config_opts[config_pts['package_manager'] + '.conf'] += """`.

**Comment by praiskup** [comment]
> This actually broke openQA update testing, because we do exactly that as part of it.

Can I help with this somehow?

**Comment by AdamWill** [comment]
I fixed it already, it's just...kinda unexpected to have to do it.
