### ISSUE TITLE
Sign plugin doesn't expand macros since 2.0

### ISSUE THREAD

**Issue by dtucny** [rpm-software-management/mock#476]
### Short description of the problem
With 1.4.21 I had a build workflow running nicely with package signing using the Sign plugin, on updating to 2.0, while building continued to work perfectly, signing almost silently stopped working. The existing configuration used $(rpms)s in opts, which, with 1.4.21 was expanded out to be the list of packages with paths, but, was passed as is in 2.0.
Checking the commit log of the sign plugin lead to the commit d44ec018b59822c8ba6dcffb0002148b57a69457 which indicated that the previous expansions had changed to templates, making the last line in the release note highlights suddenly more relevant, and also clearly showing the change in syntax as applied to the default site-defaults.cfg, i.e. in opts, I need to replace $(rpms)s with {{rpms}}. Unfortunatly with the new jinja version, the template doesn't show up in opts during plugin init output and when actually trying to execute the sign command, there's no list of packages included, which fails.

### Summary 
1) I guess it would be nice to have a more obvious indication of breakage from the change from the old macro expansion to jinja templates.
2) The new jinja templates do not appear to be functional with the sign plugin

### Steps to reproduce issue

1. Enable the sign plugin to execute a command expecting the RPMs to sign
2. In the opts for the sign command, specify {{rpms}}
3. Find that no parameters were passed to the sign command

**Comment by fkooman** [comment]
Is there any workaround for this?

**Comment by fkooman** [comment]
This wiki was also not updated (yet) https://github.com/rpm-software-management/mock/wiki/Plugin-Sign

**Comment by praiskup** [comment]
Sorry, I haven't had a chance to look at this.  We will have a look next week.

**Comment by fkooman** [comment]
Thanks! For now I'm calling `rpmsign` and `createrepo_c` manually after the (chain) build is complete.

**Comment by praiskup** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1806577

**Comment by praiskup** [comment]
There's fundamental problem in jinja config expansion, which I try to
expose in tests in #493.  We are trying to look deeper into this with
@xsuchy.

**Comment by praiskup** [comment]
Ad work-arounds, there are none.  You can revert the change manually (apply patch from #497).
