### ISSUE TITLE
mock init does not set correct permissions after unpacking root_cache

### ISSUE THREAD

**Issue by adamel** [rpm-software-management/mock#48]
When having multiple users using mock the ownership of the /builddir tree is not set to the current user after unpacking the root_cache when doing a simple mock init.

(This worked fine in mock 1.1.41 and earlier, so we've been using that up until now when I finally decided we do not want to keep using an ancient version forever.)

**Comment by xsuchy** [comment]
Merged.

**Comment by adamel** [comment]
Thanks. I'd love to see this go into the 1.3 branch (or more specifically; released for EPEL 7).

**Comment by xsuchy** [comment]
It will be in next release (in ~2 months). And it will be released for EL7 too. But not for EL6.
