### ISSUE TITLE
mock-2.0 broken on Gentoo: "cannot copy tree '/etc/pki/ca-trust/extracted'"

### ISSUE THREAD

**Issue by ganto** [rpm-software-management/mock#492]
### Short description of the problem
Since many years I'm packaging and using mock on my Gentoo box to create and test software packages for EPEL and Fedora. This was working fine until release 1.4.21, but the recent release 2.0, especially commit 2be432603733ce19ee0467bb0534daefd5bf86ed (fix for #397) broke my workflow.

I don't have any requirement to load my local system certificates to the build environment therefore I would welcome if this feature of copying the certificates optionally could be disabled (and/or the path to the certificate directory be specified). Gentoo manages the system certificates a bit different from Fedora/RHEL.

### Output of `rpm -q mock`
Obviously I didn't install mock from the RPM but from source (via ebuild):
```
$ eix -e dev-util/mock
[I] dev-util/mock [1]
     Available versions:  (~)1.4.21-r1 (~)2.0 {PYTHON_SINGLE_TARGET="python3_6 python3_7"}
     Installed versions:  2.0(10:20:37 PM 02/25/2020)(PYTHON_SINGLE_TARGET="python3_7 -python3_6")
     Homepage:            https://github.com/rpm-software-management/mock
     Description:         Builds RPM packages inside chroots

[1] "linuxmonk-overlay" /var/lib/layman/linuxmonk-overlay
```
The ebuild is available in my [linuxmonk-overlay](https://github.com/ganto/linuxmonk-overlay)

**Comment by praiskup** [comment]
Thanks for the report.

**Comment by ganto** [comment]
Thanks for the fix. I can totally live with that. 👍
