### ISSUE TITLE
mock --chain stopped working in Fedora 30 after dnf-related updates, late Feb 2020

### ISSUE THREAD

**Issue by Jpilk** [rpm-software-management/mock#501]
### Output of `rpm -qa | grep -i mock`
mock-core-configs-32.1-1.fc30.noarch
mock-2.0-2.fc30.noarch
mock-rpmfusion-nonfree-31.2-1.fc30.noarch
python2-requests-mock-1.5.2-1.fc29.noarch
mock-rpmfusion-free-32.1-1.fc30.noarch

UTPUT HERE

Attempt to build from 2 'random' rpmfusion src.rpm

[john@HPFed tm2]$ mkdir /tmp/x  ; mock --root=fedora-30-x86_64-rpmfusion_free --chain --localrepo=/tmp/x ../m2vrequantiser-20030929-12.fc30.src.rpm ../dvbcut-0.6.1-29.svn179.fc30.src.rpm
INFO: mock.py version 2.0 starting (python version = 3.7.6)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start(bootstrap): chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 2.0
INFO: Mock Version: 2.0
Finish(bootstrap): chroot init
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start: cleaning package manager metadata
Finish: cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 2.0
INFO: Mock Version: 2.0
Finish: chroot init
INFO: results dir: /tmp/x/results/fedora-30-x86_64-rpmfusion_free
INFO: Start chain build: ../m2vrequantiser-20030929-12.fc30.src.rpm
INFO: Mock Version: 2.0
INFO: Start(../m2vrequantiser-20030929-12.fc30.src.rpm)  Config(fedora-30-x86_64)
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
INFO: enabled HW Info plugin
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
INFO: enabled HW Info plugin
No matches found for the following disable plugin patterns: local, spacewalk
file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free                                                               0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'local_build_repo':
  - Curl error (37): Couldn't read a file:// file for file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml [Couldn't open file /tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml]
Error: Failed to download metadata for repo 'local_build_repo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
ERROR: Exception(../m2vrequantiser-20030929-12.fc30.src.rpm) Config(fedora-30-x86_64) 0 minutes 16 seconds
INFO: Results and/or logs in: /tmp/x/results/fedora-30-x86_64-rpmfusion_free/m2vrequantiser-20030929-12.fc30
INFO: End chain build: ../m2vrequantiser-20030929-12.fc30.src.rpm
INFO: Error building m2vrequantiser-20030929-12.fc30.src.rpm.
INFO: See logs/results in /tmp/x/results/fedora-30-x86_64-rpmfusion_free
INFO: Start chain build: ../dvbcut-0.6.1-29.svn179.fc30.src.rpm
INFO: Mock Version: 2.0
INFO: Start(../dvbcut-0.6.1-29.svn179.fc30.src.rpm)  Config(fedora-30-x86_64)
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
INFO: enabled HW Info plugin
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
INFO: enabled HW Info plugin
No matches found for the following disable plugin patterns: local, spacewalk
file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free                                                               0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'local_build_repo':
  - Curl error (37): Couldn't read a file:// file for file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml [Couldn't open file /tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml]
Error: Failed to download metadata for repo 'local_build_repo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
ERROR: Exception(../dvbcut-0.6.1-29.svn179.fc30.src.rpm) Config(fedora-30-x86_64) 0 minutes 16 seconds
INFO: Results and/or logs in: /tmp/x/results/fedora-30-x86_64-rpmfusion_free/dvbcut-0.6.1-29.svn179.fc30
INFO: End chain build: ../dvbcut-0.6.1-29.svn179.fc30.src.rpm
INFO: Error building dvbcut-0.6.1-29.svn179.fc30.src.rpm.
INFO: See logs/results in /tmp/x/results/fedora-30-x86_64-rpmfusion_free
INFO: Results out to: /tmp/x/results/fedora-30-x86_64-rpmfusion_free
INFO: Packages built: 0
ERROR: state finish mismatch: current: dnf update, state: run
[john@HPFed tm2]$ 

### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes
originally reported un the fedora and rpmfusion users lists, and at

https://bugzilla.redhat.com/show_bug.cgi?id=1806039
<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

  PUT THE OUTPUT HERE

$ mock --debug-config
INFO: mock.py version 2.0 starting (python version = 3.7.6)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'fedora:30'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/default.cfg',
 '/etc/mock/templates/fedora-30.tpl']
config_opts['dist'] = 'fc30'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f30\n'
 'protected_packages=\n'
 '\n'
 '# repos\n'
 '\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing]\n'
 'name=updates-testing\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/f30-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=fedora-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-debuginfo]\n'
 'name=updates-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing-debuginfo]\n'
 'name=updates-testing-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-source]\n'
 'name=updates-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-30-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[fedora-modular]\n'
 'name=Fedora Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-source]\n'
 'name=Fedora Modular $releasever - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular]\n'
 'name=Fedora Modular $releasever - $basearch - Updates\n'
 'failovermethod=priority\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Updates - Debug\n'
 'failovermethod=priority\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-source]\n'
 'name=Fedora Modular $releasever - Updates Source\n'
 'failovermethod=priority\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/SRPMS/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'HPFed.home',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.l73_znz1:/etc/resolv.conf',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-30-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                     'root': 'fedora-30-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-30-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/fedora-30-x86_64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                 'root': 'fedora-30-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/fedora-30-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                      'root': 'fedora-30-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-30-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                        'root': 'fedora-30-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-30-x86_64',
                  'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                  'root': 'fedora-30-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/fedora-30-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                   'root': 'fedora-30-x86_64'},
 'mount_enable': False,
 'mount_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-30-x86_64',
                'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                'root': 'fedora-30-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-30-x86_64',
                    'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                    'root': 'fedora-30-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/fedora-30-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-30-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                        'root': 'fedora-30-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-30-x86_64',
                     'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                     'root': 'fedora-30-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-30-x86_64',
                  'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                  'root': 'fedora-30-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/fedora-30-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-30-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/fedora-30-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                     'root': 'fedora-30-x86_64',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-30-x86_64',
                  'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                  'root': 'fedora-30-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/fedora-30-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign ',
               'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
               'root': 'fedora-30-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-30-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                'root': 'fedora-30-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-30-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-30-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/fedora-30-x86_64/result',
                    'root': 'fedora-30-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '30'
config_opts['root'] = 'fedora-30-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
Finish: run
[john@HPFed tm2]$ 

</details>

**Comment by Jpilk** [comment]
Using the same command line for the individual src.rpms without the --chain and --localrepo options creates the rpms as expected.

$ mkdir /tmp/x  ; mock --root=fedora-30-x86_64-rpmfusion_free  ../m2vrequantiser-20030929-12.fc30.src.rpm
$ mkdir /tmp/x  ; mock --root=fedora-30-x86_64-rpmfusion_free  ../dvbcut-0.6.1-29.svn179.fc30.src.rpm
$ rpm -qa | grep -i dnf
dnfdaemon-0.3.19-6.fc30.noarch
python3-dnf-plugins-core-4.0.13-1.fc30.noarch
python3-libdnf-0.43.1-3.fc30.x86_64
python3-dnfdaemon-0.3.19-6.fc30.noarch
python3-dnf-4.2.18-1.fc30.noarch
dnf-plugins-core-4.0.13-1.fc30.noarch
dnf-yum-4.2.18-1.fc30.noarch
dnfdragora-1.1.1-2.fc30.noarch
dnfdaemon-selinux-0.3.19-6.fc30.noarch
dnf-4.2.18-1.fc30.noarch
dnf-utils-4.0.13-1.fc30.noarch
python3-dnf-plugins-extras-common-4.0.8-1.fc30.noarch
libdnf-0.43.1-3.fc30.x86_64
python3-dnf-plugin-system-upgrade-4.0.8-1.fc30.noarch
dnf-data-4.2.18-1.fc30.noarch
python3-dnf-plugin-versionlock-4.0.13-1.fc30.noarch

**Comment by Jpilk** [comment]
Just updated mock-core-configs (and python3-pyyaml)
$ rpm -qa | grep -i mock
mock-2.0-2.fc30.noarch
mock-rpmfusion-nonfree-31.2-1.fc30.noarch
mock-core-configs-32.3-2.fc30.noarch
python2-requests-mock-1.5.2-1.fc29.noarch
mock-rpmfusion-free-32.1-1.fc30.noarch

but the failure looks much the same:
{{{
INFO: enabled HW Info plugin
No matches found for the following disable plugin patterns: local, spacewalk
file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free                                                               0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'local_build_repo':
  - Curl error (37): Couldn't read a file:// file for file:///tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml [Couldn't open file /tmp/x/results/fedora-30-x86_64-rpmfusion_free/repodata/repomd.xml]
Error: Failed to download metadata for repo 'local_build_repo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
ERROR: Exception(../m2vrequantiser-20030929-12.fc30.src.rpm) Config(fedora-30-x86_64) 0 minutes 36 seconds
}}}

**Comment by sergiomb2** [comment]
mock-rpmfusion-nonfree-32.1-1.fc30 is available 
* Sun Feb 23 2020 Sérgio Basto <sergio@serjux.com> - 32.1-1
- Configurations for Mock-2.0

**Comment by Jpilk** [comment]
On 01/03/2020 16:48, Sérgio Basto wrote:
> mock-rpmfusion-nonfree-32.1-1.fc30 is available
> 

I have installed it, but still see the same error.  That's not 
surprising, because the testcase and my real target (not yet tried) use 
only the -free version - but thanks all the same.

**Comment by praiskup** [comment]
Please use --resultsdir outside from /tmp, /dev/, /run etc, and see #502 for
reasoning.  You can also work-around this and use --isolation=simple.

**Comment by praiskup** [comment]
Another work-around is to use --no-bootstrap-chroot.

**Comment by Jpilk** [comment]
Thank you.  I added the 'Another work-around' to the mock --chain commands in the test case, and then in the target script.  rpms built, installed, and the system is running.

**Comment by Jpilk** [comment]
For info:
The builds above were done under F30 for F30.
A build under F30 for el7 paused for user input with the message below.  I pressed Enter and the build (the real one, not this test case) continued to completion.
{{{
 mkdir /tmp/x  ; mock --root=epel-7-x86_64-rpmfusion_free --chain --no-bootstrap-chroot --localrepo=/tmp/x ../m2vrequantiser-20030929-12.fc30.src.rpm ../dvbcut-0.6.1-29.svn179.fc30.src.rpm
INFO: mock.py version 2.0 starting (python version = 3.7.6)...
WARNING: Not using '/usr/bin/yum', it is symlink to '/usr/bin/dnf-3'
INFO: Using 'dnf' instead of 'yum'
WARNING! WARNING! WARNING!
You are building package for distribution which uses YUM. However your system
does not support YUM. You can continue with DNF, which will likely succeed,
but the installed chroot may look a little different.
  1. Please consider --bootstrap-chroot option, or
  2. install YUM on your host system.
You can suppress this warning when you put
  config_opts['dnf_warning'] = False
in Mock config.
Press Enter to continue.
}}}

**Comment by pghmcfc** [comment]
I think there is a general issue with file:// URLs in the bootstrap mode. I used to use them for GPG keys and repo baseurls but in bootstrap mode I would get errors about packages not having the right signatures or being unable to import GPG keys. I have worked around it (mostly) in my own configurations by setting up a local web server and changing the file:// URLs to http:// URLs that access exactly the same files and now it is mostly working OK.

The only remaining issue I have is being unable to import GPG keys to set up a mock root for Fedora 22 using the bootstrapped root for that release (rather like https://bugzilla.redhat.com/show_bug.cgi?id=1224908) but I don't expect upstream to be interested in debugging that.

**Comment by praiskup** [comment]
@pghmcfc we copy all distribution-gpg-keys from host to bootstrap.  On top of
that, you can define files in `/etc/pki/mock/RPM-GPG-KEY-*`.  Those would be
copied to bootstrap with `copy_gpg_keys()` method (so you need to change
the file:// url).

**Comment by pghmcfc** [comment]
@praiskup, it was problems with packages too. I'd get errors trying to install them saying that the checksums were wrong. I could open a mock shell and do an rpm --checksig on the packages and they were fine. I couldn't figure out what the underlying problem was but changing the file:// URLs to http:// URLs got my builder going again. It also meant I didn't need bind mounts to support my file:// URLs in my mock configs, which was a nice side-benefit.

**Comment by praiskup** [comment]
I wanted to say, if you use `file:///etc/pki/mock/RPM-GPG-KEY*` files (you
can not use different paths), and those don't work for you in bootstrap, please
fill a new issue.  That would be a bug.

**Comment by pghmcfc** [comment]
@praiskup, I've tried GPG keys in `file:///etc/pki/mock/RPM-GPG-KEY*` files and they work fine for me, thanks. I probably had them in `file:///etc/pki/rpm-gpg/RPM-GPG-KEY*` files before and didn't notice the different path. I still have issues with packages not being found with `file://` URLs that are OK with `http://` URLs though.

**Comment by praiskup** [comment]
What do you mean by packages not being found with file://?  baseurl?  With --isolation=nspawn,
there's problem you can not have it below /tmp, etc.  https://github.com/rpm-software-management/mock/wiki/Feature-bootstrap

**Comment by praiskup** [comment]
#502 could help

**Comment by pghmcfc** [comment]
My repos were under /home so it wasn't that. I was able to reproduce this yesterday but I can't seem to do it today, I'll get back to you with a new issue if it crops up again.
