### ISSUE TITLE
amazonlinux-2 config doesn't work

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#522]
There's problem with mirror-list:
```
$ curl http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list
https://cdn.amazonlinux.com/2/core/2.0/x86_64/fb62e6e47871f06a0dca9891ea727d57adf5b04fb19bf034240479da085ca797
$ lftp https://cdn.amazonlinux.com/2/core/2.0/x86_64/fb62e6e47871f06a0dca9891ea727d57adf5b04fb19bf034240479da085ca797
cd: Access failed: 403 Forbidden (/2/core/2.0/x86_64/fb62e6e47871f06a0dca9891ea727d57adf5b04fb19bf034240479da085ca797)
```
Only one and non-working mirror is provided.

**Comment by praiskup** [comment]
@haroldjin, FYI.  Could you please take a look at this?

**Comment by nkadel** [comment]
Are you using this from an AWS Linux host? I found those repos not to be publicly available when I last looked.

**Comment by haroldjin** [comment]
Sorry for the late response. I agree with @nkadel. The mirrorlist is not available publicly and should only be used for Amazon Linux EC2 instances. @praiskup

**Comment by nkadel** [comment]
Note that activating "mock" on an AWS Linux host involves using the "amazon-linux-extras" tool to enable mock from their repos, and avoiding the version on EPEL. The dependencies for tools like "createrepo" get..... a bit peculiar if you try to use the EPEL version.

**Comment by praiskup** [comment]
Ok, I'm going to stop testing those configs.  Thanks.
