### ISSUE TITLE
openmandriva-4.0-x86_64 and Cooker config doesn't work with bootstrap

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#525]
Because we have `package_state` plugin enabled by default, and that
executes `rpm --installroot` command from host when it should run it
from bootstrap chroot.

**Comment by Conan-Kudo** [comment]
Yeah, this is because OpenMandriva's rpm is using BerkeleyDB 18.x (yeah, I know... 😩). I intend to change to a non-BDB rpmdb as soon as RPM 4.16 is available.

**Comment by praiskup** [comment]
Ok, but the point of bootstrap chroot is to actually overcome those differences;  so we need
to fix mock (the plugin) here.
