### ISSUE TITLE
nosync plugin is failing for epel-7-ppc64le chroot

### ISSUE THREAD

**Issue by clime** [rpm-software-management/mock#53]
There is a problem with installing build-root in epel-7-ppc64le when nosync plugin is enabled. The messages  I am getting in the root.log read like this:

    DEBUG util.py:435:    Installing : glibc-2.17-157.el7_3.1.ppc64le                            13/158 
    DEBUG util.py:435:  /usr/sbin/iconvconfig: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /tmp/tmp.mock.pkqww6rf/lib64/nosync.so)
    DEBUG util.py:435:  /usr/sbin/glibc_post_upgrade: While trying to execute /usr/sbin/iconvconfig.ppc64le child exited with exit code 1
    DEBUG util.py:435:  warning: %post(glibc-2.17-157.el7_3.1.ppc64le) scriptlet failed, exit status 1
    DEBUG util.py:435:  Non-fatal POSTIN scriptlet failure in rpm package glibc-2.17-157.el7_3.1.ppc64le

or here is an error instead of just warning:

    DEBUG util.py:435:  /bin/sh: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /tmp/tmp.mock.pkqww6rf/lib64/nosync.so)
    DEBUG util.py:435:  error: %prein(pinentry-0.8.1-17.el7.ppc64le) scriptlet failed, exit status 1
    DEBUG util.py:435:  Error in PREIN scriptlet in rpm package pinentry-0.8.1-17.el7.ppc64le
    DEBUG util.py:435:    Installing : cpp-4.8.5-11.el7.ppc64le                                  60/158 
    DEBUG util.py:435:  error: pinentry-0.8.1-17.el7.ppc64le: install failed

nosync plugin works for epel-7-x86_64, just not for epel-7-ppc64le, which is quite interesting. The whole root.log is attached. This was tested on copr f24 builder cloud instance with mock 1.3.3.
[root.log.txt](https://github.com/rpm-software-management/mock/files/811594/root.log.txt)

**Comment by Frodox** [comment]
Did you install `nosync.rpm` itself before? I'm using this plugin for `ppc64` and it works fine. It is interesting...

**Comment by xsuchy** [comment]
I cannot reproduce. I even tried ppcbuilder from Copr and it works ok there.

**Comment by clime** [comment]
@xsuchy If you have tried it on builders in copr-dev tenant, then these builders have now nosync not enabled by default. You need to enable it manually in site-defaults.cfg. I decided to disable it for ppc64le arch only for the time being to get epel-7-ppc64le working.

@Frodox nosync.rpm is installed

    [root@copr-builder-740288184 ~]# yum info nosync
    Redirecting to '/usr/bin/dnf info nosync' (see 'man yum2dnf')

    Last metadata expiration check: 2:37:14 ago on Wed Mar  1 21:37:08 2017.
    Installed Packages
    Name        : nosync
    Arch        : ppc64le
    Epoch       : 0
    Version     : 1.0
    Release     : 5.fc24
    Size        : 79 k
    Repo        : @System
    From repo   : fedora
    Summary     : Preload library for disabling file's content synchronization
    URL         : http://github.com/kjn/nosync
    License     : ASL 2.0
    Description : nosync is a small preload library that can be used to disable
                : synchronization of file's content with storage devices on GNU/Linux.
                : It works by overriding implementations of certain standard functions

I probably will do more investigation and collect more info on this if it is not otherwise reproducible.

**Comment by xsuchy** [comment]
@clime I tried that on production builder and I checked that nosync was really enabled.

**Comment by xsuchy** [comment]
Got it. It happen only in epel-7-* (reproduced in ppc64le). And it is bug in nosync, which is build only against glibc 2.22, but there is 2.23. So it needs to be rebuild.

**Comment by xsuchy** [comment]
@mizdebsk promised to rebuild the package for epel-7. However it can take 14 days to get it to stable. So please either ignore the error (it makes no actuall harm) or disable it for few days.

**Comment by mizdebsk** [comment]
I've rebuilt nosync in EPEL 7: https://bodhi.fedoraproject.org/updates/nosync-1.0-2.el7
Please let me know if it fixes the issue.

**Comment by clime** [comment]
@mizdebsk This rebuilt package works on the copr builders for both epel-*-ppc64le and fedora-*-ppc64le chroots. The issue is that our builders run on Fedora (24 currently) so it's probably kind of luck that the package (built for el7) works there.

**Comment by mizdebsk** [comment]
@clime Thanks for feedback. I've just requested push to stable.
