### ISSUE TITLE
mock-2.0 regression- mock doesn't remove bootstrap chroots after build

### ISSUE THREAD

**Issue by bleve** [rpm-software-management/mock#540]
With default config which has:

# config_opts['cleanup_on_success'] = True
# config_opts['cleanup_on_failure'] = True

mock doesn't remove bootsrap chroots after build - note bootstrap directory should be removed in this case even when --restultdir is not set.

This affects both with --uniqueext and without.

**Comment by praiskup** [comment]
Thanks for the report, but this is expected.  I tried to start discussion about this in #519,
but bootstrap is sort of "cache", similar to "yum_cache" ... and as such, it probably
shouldn't be removed with clean().
