### ISSUE TITLE
epel-rpm-macros is needed to build mock.spec on RHEL7 + EPEL7

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#545]
I'm not sure I want to fix this, perhaps it is enough to re-define
'%python3_pkgversion 36' macro in mock.spec if it isn't defined, yet.

**Comment by Conan-Kudo** [comment]
Why wouldn't using the `epel-7-x86_64` chroot not already bring in those macros?

**Comment by praiskup** [comment]
When you are on RHEL7, and enable EPEL7 repo, you don's have those macros --
so you can not build mock.
