### ISSUE TITLE
move 'site-defaults' to %doc

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#546]
.. and perhaps keep it as %config file in mock-core-configs, with content
like:

  ```
  # Global (non-user specific) mock configuration.
  # 
  # Please consult configuration examples from
  # /usr/share/doc/mock*/defaults.txt
  # and consider using `$HOME/.config/mock.cfg` file instead if possible.
  ```

I'm not sure.  People are continuously using site-defaults.cfg for
things that should be done in `$HOME/.config/mock.cfg`.  The fact they are
using site-defaults.cfg is often because it is marked %config in spec file
-- and that it is "pre-configured" -- so it is easier for initial tweaks.  But
then, when we update the file (happens all the time, for documentation
purposes) they need to merge `.rpmnew` files ...  and perhaps they never
do that ... so they don't know the new options, etc.

**Comment by Conan-Kudo** [comment]
@praiskup maybe it's better to move it to `/usr/share/mock` and make `/etc/mock/site-defaults.cfg` empty?

**Comment by praiskup** [comment]
Since the site-defaults.cfg isn't anythin else than documentation (and we
don't plan to add there uncommented configs), why `/usr/share/mock` and
not `/usr/share/doc/mock`?

**Comment by amessina** [comment]
site-defaults.cfg has been useful for someone like me, running a private Koji instance, where not all of mock's config options are easy to pass into koji. As long as there can be a drop in where /etc/site-defaults.cfg overrides the one /usr/share, that would help.

**Comment by praiskup** [comment]
Ok, probably understand why we discuss `/usr/share/mock` directory;  but
that is not yet used implemented in mock.  We don't have default
configuration in config file, but in `util.py` file.  That said, I think
the proposal matches your expectation, can you take a look at #555?
