### ISSUE TITLE
should `nuke_rpm_db` remove files like `/var/lib/rpm/sqlite.*`

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#558]
I am a bit confused, because mock on several places does 'rm
/var/lib/rpm/__db*' (on places where we combine running RPM from host, RPM
from bootstrap chroot and RPM from target chroot so they don't collide),
and mock seems to build rawhide just fine even without removing those
files.  Is that because older RPMs create the `__db*` files, and new
creates `sqlite.*` files so they never collide?  Should we remove also
those new files, just to be sure it will work in future?  @pmatilai ?

**Comment by praiskup** [comment]
I tested like this:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RFRPRVLXVIHKTA33L3DYMTPI65QTBB2I/

**Comment by pmatilai** [comment]
The simple rule is: never, ever remove anything from the rpmdb directory. 

The __db* files are the hysterical BDB specific exception to that rule, an exception so common that it has made it seem entirely normal to "nuke stuff" from there. The world will be a better place when that exception will finally be gone.

**Comment by praiskup** [comment]
Thanks for the answer.
