### ISSUE TITLE
Building mock  2.2 rpm on CentOS 8 fails with "patch" error

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#559]
### Short description of the problem
Trying to port the latest Fedora mock-2.1 RPMs to CentOS 8 and 7, a "patc

### Output of `rpm -q mock`
Source RPM: mock-2.1-1.fc32.src.rpm

OUTPUT HERE
Command:
rpmbuild --rebuild mock-2.1-1.fc32.src.rpm

  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python3.6/site-packages/pytest_virtualenv.py", line 15, in <module>
    from pytest_shutil import run, cmdline
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python3.6/site-packages/pytest_shutil/run.py", line 14, in <module>
    from mock import patch
ImportError: cannot import name 'patch'
error: Bad exit status from /var/tmp/rpm-tmp.PYaGhR (%check)

### Steps to reproduce issue

1. Download Fedora 31 SRPM on RHEL 8
2. rpmbuild --rebuild mock-2.1-1.fc32.src.rpm
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

I'm trying to figure out why the "patch" import is failing. RHEL 8 has python 3.6 built-in, The issue looks to be in tests/test_package_manager.py when unning checs.

**Comment by praiskup** [comment]
Please re-try with mock 2.2, it has been built fine against epel7 and epel8:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1487370
https://koji.fedoraproject.org/koji/buildinfo?buildID=1487371

Same as v2.1.  Make sure all the BuildRequires are installed (the stuff
needed by unit tests).

**Comment by praiskup** [comment]
This can be though pretty complicated.  Feel free to reopen if you see some
real life problems.  Namely, the src.rpm should first require you to install:
```
        bash-completion is needed by mock-2.2-1.el8.noarch
        perl-interpreter is needed by mock-2.2-1.el8.noarch
        python3-devel is needed by mock-2.2-1.el8.noarch
        python3-distro is needed by mock-2.2-1.el8.noarch
        python3-jinja2 is needed by mock-2.2-1.el8.noarch
        python3-pyroute2 is needed by mock-2.2-1.el8.noarch
        python3-pytest is needed by mock-2.2-1.el8.noarch
        python3-pytest-cov is needed by mock-2.2-1.el8.noarch
```

**Comment by nkadel** [comment]
The dependencies, and some tweaks for RHEL compilation, are in the Fedora rawhide package. I grabbed that built it for RHEL 7 and 8 with my tools  in github, and it seems to be working much better an dwithout hand-tuning of fedor-branched.tpl.

**Comment by praiskup** [comment]
> The dependencies, and some tweaks for RHEL compilation, are in the Fedora rawhide package.

The src.rpm is probably slightly different for EL, because of
conditionals.  But mock src.rpm for rawhide is generated from byte-by-byte
the same sources as for el7 and el8.  You should either use sources directly
(not src.rpm) or use mock to re-build the mock.src.rpm (mock extracts the
src.rpm first, and re-builds it against the target chroot).

**Comment by nkadel** [comment]
Since mock wasn't working well on my last attempt with mock 2.1, i had to bootstrep the Fedora rawhide sr.crpm with "rpmbuild", insall *that*, and then I could use the lastest mock to build the SRPM.   The source that I use started with the SRPM from rawhide, run thgouth rpm2cpio to extract the tarball and .spec file. There's not a trivially downloadable tarball right now in the github repo, and checkout out git clones and tags and building tarballs from the merged mock and mock-core-configs in the git repo is pesky.

**Comment by praiskup** [comment]
> There's not a trivially downloadable tarball right now in the github repo

Sorry, I'm going to fix this now.

**Comment by xsuchy** [comment]
@nkadel https://github.com/rpm-software-management/mock/releases -> mock-2.1-1 -> assets -> mock-2.1.tar.gz 
https://github.com/rpm-software-management/mock/releases/download/mock-2.1-1/mock-2.1.tar.gz

**Comment by praiskup** [comment]
I uploaded mock-2.2 and mock-core-conifigs-32.6 now.

**Comment by nkadel** [comment]
Ohh. *Thank* you!
