### ISSUE TITLE
mock --postinstall does not work in bootstrap mode

### ISSUE THREAD

**Issue by javierpena** [rpm-software-management/mock#564]
### Short description of the problem
When building a package with --postinstall. In that case, mock fails to find the built package. For example:

$  mock --rebuild -r epel-8-x86_64 --postinstall python-distroinfo-0.3.2-2.el8.src.rpm

Using [1] as test source RPM. I get the following log message:

Can not load RPM file: /var/lib/mock/epel-8-x86_64/result/python3-distroinfo-0.3.2-2.el8.noarch.rpm.
Could not open: /var/lib/mock/epel-8-x86_64/result/python3-distroinfo-0.3.2-2.el8.noarch.rpm
WARNING: Failed install built packages

As a workaround, I can use --no-bootstrap-chroot, but the default configuration is broken.

[1] - https://kojipkgs.fedoraproject.org//packages/python-distroinfo/0.3.2/2.el8/src/python-distroinfo-0.3.2-2.el8.src.rpm

### Output of `rpm -q mock`

mock-2.2-1.el8.noarch (from epel-testing)

### Steps to reproduce issue

1. wget https://kojipkgs.fedoraproject.org//packages/python-distroinfo/0.3.2/2.el8/src/python-distroinfo-0.3.2-2.el8.src.rpm
2. mock --rebuild -r epel-8-x86_64 --postinstall python-distroinfo-0.3.2-2.el8.src.rpm

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>
INFO: mock.py version 2.2 starting (python version = 3.6.8)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'centos:8'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = ('install tar gcc-c++ redhat-rpm-config redhat-release which xz sed make bzip2 '
 'gzip gcc coreutils unzip shadow-utils diffutils cpio bash gawk rpm-build '
 'info patch util-linux findutils grep epel-release epel-rpm-macros '
 'fedpkg-minimal')
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/epel-8-x86_64.cfg',
 '/etc/mock/templates/centos-8.tpl',
 '/etc/mock/templates/epel-8.tpl']
config_opts['dist'] = 'el8'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'metadata_expire=0\n'
 'mdpolicy=group:primary\n'
 'best=1\n'
 'protected_packages=\n'
 'module_platform_id=platform:el8\n'
 '\n'
 '[BaseOS]\n'
 'name=CentOS-$releasever - Base\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=BaseOS&infra=$infra\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[AppStream]\n'
 'name=CentOS-$releasever - AppStream\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=AppStream&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/AppStream/$basearch/os/\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[PowerTools]\n'
 'name=CentOS-$releasever - PowerTools\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=PowerTools&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/PowerTools/$basearch/os/\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[Devel]\n'
 'name=CentOS-$releasever - Devel WARNING! FOR BUILDROOT USE ONLY!\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=Devel&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/$contentdir/$releasever/Devel/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[centosplus]\n'
 'name=CentOS-$releasever - Plus\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=centosplus&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[cr]\n'
 'name=CentOS-$releasever - cr\n'
 'baseurl=http://mirror.centos.org/centos/8/cr/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[base-debuginfo]\n'
 'name=CentOS-$releasever - Debuginfo\n'
 'baseurl=http://debuginfo.centos.org/8/$basearch/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[extras]\n'
 'name=CentOS-$releasever - Extras\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=extras&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[fasttrack]\n'
 'name=CentOS-$releasever - fasttrack\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=fasttrack&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/fasttrack/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[BaseOS-source]\n'
 'name=CentOS-$releasever - BaseOS Sources\n'
 'baseurl=http://vault.centos.org/centos/8/BaseOS/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[AppStream-source]\n'
 'name=CentOS-$releasever - AppStream Sources\n'
 'baseurl=http://vault.centos.org/centos/8/AppStream/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[PowerTools-source]\n'
 'name=CentOS-$releasever - PowerTools Sources\n'
 'baseurl=http://vault.centos.org/centos/8/PowerTools/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[extras-source]\n'
 'name=CentOS-$releasever - Extras Sources\n'
 'baseurl=http://vault.centos.org/centos/8/extras/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[centosplus-source]\n'
 'name=CentOS-$releasever - Plus Sources\n'
 'baseurl=http://vault.centos.org/centos/8/centosplus/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '\n'
 '[epel]\n'
 'name=epel\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-8\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[testing]\n'
 'name=epel-testing\n'
 'enabled=0\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=testing-epel8&arch=$basearch\n'
 'failovermethod=priority\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel8-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=epel-debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-debug-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-source]\n'
 'name=epel-source\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-source-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular]\n'
 'name=epel-modular\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-debuginfo]\n'
 'name=epel-modular-debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-debug-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-source]\n'
 'name=epel-modular-source\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-source-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'centos8-base.example.com',
 '%_netsharedpath': '/proc:/sys',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.96dw57bh:/etc/resolv.conf',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-8-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/epel-8-x86_64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                 'root': 'epel-8-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/epel-8-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                      'root': 'epel-8-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-8-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                        'root': 'epel-8-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/epel-8-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                   'root': 'epel-8-x86_64'},
 'mount_enable': False,
 'mount_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-8-x86_64',
                'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                'root': 'epel-8-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-8-x86_64',
                    'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                    'root': 'epel-8-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-8-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                        'root': 'epel-8-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/epel-8-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/epel-8-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/epel-8-x86_64/result',
               'root': 'epel-8-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-8-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                'root': 'epel-8-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-8-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                    'root': 'epel-8-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '8'
config_opts['root'] = 'epel-8-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
Finish: run

</details>

**Comment by praiskup** [comment]
Thanks for the report.
