### ISSUE TITLE
mock uses outside rpm for some queries in bootstrap mode

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/mock#565]
### Short description of the problem

Mock uses outside rpm for some queries in bootstrap mode, which causes problems if the rpm on the outside doesn't understand the database format of the inside chroot. 

### Output of `rpm -q mock`

mock-2.2-1.fc31.noarch

### Steps to reproduce issue

```
[root@lumikko ~]# rpm -q rpm
rpm-4.15.1-1.fc31.x86_64
[root@lumikko ~]# cat /etc/mock/fedora-sqlite-x86_64.cfg
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)

include('templates/fedora-rawhide.tpl')

config_opts['macros']['%_db_backend'] = 'sqlite'
config_opts['root'] = 'fedora-sqlite-{{ target_arch }}'
[root@lumikko ~]# rm -rf /var/cache/mock/fedora-sqlite-x86_64/root_cache/
[root@lumikko ~]#

$ mock --use-bootstrap-image -r fedora-sqlite-x86_64 <some_srpm>

INFO backend.py:241:  Installed packages:
DEBUG util.py:793:  child environment: None
DEBUG util.py:719:  Executing command: /bin/rpm --root /var/lib/mock/fedora-sqlite-x86_64/root -qa with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell True
DEBUG util.py:621:  error: cannot open Packages index using db5 - Permission denied (13)
DEBUG util.py:621:  error: cannot open Packages database in /var/lib/mock/fedora-sqlite-x86_64/root/var/lib/rpm
```

Any trivial src.rpm will be sufficient to trigger the above "Installed packages:" error after first root population.

### Any additional notes

I spotted two places where the outside rpm is used for queries
1. _show_installed_packages() in backend.py (ie the above case)
2. all_chroot_packages() in buildroot.py during dynamic buildrequires loop, but for that I have no reproducer

I suppose the fix would be to have _show_installed_packages() use  all_chroot_packages() for the query, and have all_chroot_packages() use self.buildroot.doChroot() instead of util.do() for the query, when bootstrapping is enabled. Or something like that. I can attempt a PR if you point me to right direction: what's the right condition for going chroot vs util? self.bootstrap_buildroot?

**Comment by praiskup** [comment]
> _show_installed_packages

Correct, thanks for the report.

> all_chroot_packages

This has been fixed, we use doOutChroot there.

**Comment by pmatilai** [comment]
> This method has been fixed in 2.2, we use doOutChroot there.

Oh, sorry. For some reason I was looking at upstream "devel" branch assuming it's the latest there is, seeing util.do() used, and then wondering why I can't trigger the error with dynamic buildrequires. Oh well :joy: But this is good news as the _show_installed_packages() case is more cosmetical.

**Comment by praiskup** [comment]
> the _show_installed_packages() case is more cosmetical.

It shouldn't fail the build at least.

**Comment by pmatilai** [comment]
> It shouldn't fail the build at least.

Yup, it doesn't - eg https://koji.stg.fedoraproject.org/koji/buildinfo?buildID=1432321
