### ISSUE TITLE
Error: Directory ... doesn't look like it has an OS tree. Refusing.

### ISSUE THREAD

**Issue by bne86** [rpm-software-management/mock#573]
First of all, thanks for providing mock which made our life much easier wrt building software in a clean/reproducible environment!

### Short description of the problem
We have some python wrapper tool around mock that worked well for EL7, with EL8 it also worked after slight adjustments to the config, but with the recent update to Mock 2.2 (via epel) we now face the issue mentioned in the subject. It looks like this is leading to a failing build.

I tried to disable bootstrapping, because I do not want to rely on the yum cache of an external container image. I have to admit that parts of the disable/enable caching and where the caches come from are sometimes a bit confusing.

### Output of `rpm -q mock`
* mock-2.2-1.el8.noarch
* CentOS Linux release 8.1.1911 (Core)
* 4.18.0-147.8.1.el8_1.x86_64

### Steps to reproduce issue

1. /usr/bin/mock --root /tmp/gpfs/config/machine.cfg --resultdir /tmp/gpfs/result --rootdir /tmp/gpfs/root --init --no-bootstrap-chroot
2. /usr/bin/mock --root /tmp/gpfs/config/machine.cfg --resultdir /tmp/gpfs/result --rootdir /tmp/gpfs/root --define KERNEL 4.18.0-147.8.1.el8_1.x86_64 --buildsrpm --spec /tmp/gpfs/i00/SPECS/gpfs.gplbin.spec --source /tmp/gpfs/i00/SOURCES
3. DEBUG util.py:621:  Directory /tmp/gpfs/root doesn't look like it has an OS tree. Refusing.
```
ls -l /tmp/gpfs/root/
total 12
lrwxrwxrwx  1 root root      7 May 11  2019 bin -> usr/bin
dr-xr-xr-x  4 root root     30 May 10 07:39 boot
drwxrwxr-x  3 bne  jscadm   37 May 10 07:43 builddir
drwxr-xr-x  4 root root   4096 May 11  2019 dev
drwxr-xr-x 52 root root   4096 May 10 07:42 etc
drwxr-xr-x  2 root root      6 May 11  2019 home
lrwxrwxrwx  1 root root      7 May 11  2019 lib -> usr/lib
lrwxrwxrwx  1 root root      9 May 11  2019 lib64 -> usr/lib64
drwxr-xr-x  2 root root      6 May 11  2019 media
drwxr-xr-x  2 root root      6 May 11  2019 mnt
drwxr-xr-x  2 root root      6 May 11  2019 opt
drwxrwxr-x  2 root root      6 May 10 07:37 proc
dr-xr-x---  2 root root      6 May 11  2019 root
drwxr-xr-x 12 root root    149 May 10 07:41 run
lrwxrwxrwx  1 root root      8 May 11  2019 sbin -> usr/sbin
drwxr-xr-x  2 root root      6 May 11  2019 srv
drwxrwxr-x  2 root root      6 May 10 07:37 sys
drwxrwxrwt  4 root root     32 May 10 07:43 tmp
drwxr-xr-x 12 root root    144 May 10 07:38 usr
drwxr-xr-x 17 root root    227 May 10 07:43 var
```
[root.log](https://github.com/rpm-software-management/mock/files/4605268/root.log)
[mock.config](https://github.com/rpm-software-management/mock/files/4605270/machine_config.log)

### Any additional notes

**Comment by praiskup** [comment]
Thank you for the report!

Can you please check if your command 2. is correct, you seem to be missing
`--no-bootstrap-chroot` option there.  If adding the option helps, there's
bug #560/#561 which will be fixed in v2.3.

**Comment by bne86** [comment]
Thanks for the swift response!

Looks like this solved my problem. Feel free to close this issue.

**Comment by praiskup** [comment]
Glad it helped!
