### ISSUE TITLE
Missing CentOS (non-EPEL) configs

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/mock#575]
### Short description of the problem

For some reason we are missing centos (non-EPEL) configs, we have only template files for them.

### Output of `rpm -q mock`

`mock-core-configs-32.6-1.fc32.noarch`

### Steps to reproduce issue

1. `ls /etc/mock/centos-8-x86_64.cfg`
2. `ls /etc/mock/centos-7-x86_64.cfg`

### Any additional notes

We have a template file available but you cannot use it directly. I would expect `mock-core-configs` to provide something like this

    include('templates/centos-8.tpl')

    config_opts['root'] = 'centos-8-x86_64'
    config_opts['target_arch'] = 'x86_64'
    config_opts['legal_host_arches'] = ('x86_64',)

**Comment by praiskup** [comment]
Yes, we never had plain centos configs, even though we could.
Patches are welcome!

**Comment by xsuchy** [comment]
For historic reason they are named epel-* which is centos+epel.

**Comment by praiskup** [comment]
@FrostyX wanted to have config for CentOS without EPEL.

**Comment by FrostyX** [comment]
It was a one-time thing, it is not blocking me or anything. I just thought it would be a good idea to file an issue because it surprised me.

**Comment by hsn10** [comment]
I also want to have base centos configs.
