### ISSUE TITLE
--with option replaces - with space in defined macro

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#582]
### Short description of the problem
Using `--with=` option incorrectly creates the `%_with` macro with a space in it's value where a `-` should be.

### Output of `rpm -q mock`
mock-2.2-1.fc31.noarch

### Steps to reproduce issue
1. With an RPM spec file that has %bcond_with build_option and %{error:%_with_build_option} to display that macro's value
2. Use `rpmbuild -bb --with=build-option` and observe the value that the `%{error:%_with_build_option}` displays
3. Now use `mock --with=build-option` and observe the value that the `%{error:%_with_build_option}` displays and/or look at the value of that macro in `/builddir/.rpmmacros`

Observe that `rpmbuild`'s value for the macro is `--with-build-option` (with no spaces) and that `mock`'s value is `--with build-option` (with a space).
### Any additional notes

<details>
  <summary>
    <p>
Output of `mock --debug-config`</p>
  </summary>
options.rpmmacros: []
config_opts['macros']: {'%_topdir': '/builddir/build', '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm', '%_netsharedpath': '/proc:/sys', '%_buildhost': 'host.example.com'}
INFO: mock.py version 2.2 starting (python version = 3.7.7)...
INFO: Using 'dnf' instead of 'yum' for bootstrap chroot
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'centos:7'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'epel-7-x86_64'
config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/epel-7-x86_64.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/epel-7-x86_64.cfg',
 '/etc/mock/templates/epel-7.tpl']
config_opts['dist'] = 'el7'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'metadata_expire=0\n'
 'mdpolicy=group:primary\n'
 'best=1\n'
 'protected_packages=\n'
 '\n'
 '{% set epel_7_gpg_keys = '
 "'file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7' %}\n"
 "{% if target_arch in ['ppc64le', 'ppc64'] %}\n"
 '{%   set epel_7_gpg_keys = epel_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-AltArch-7-' "
 '+ target_arch %}\n'
 "{% elif target_arch in ['aarch64'] %}\n"
 '{%   set epel_7_gpg_keys = epel_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7-aarch64' "
 '%}\n'
 '{% endif %}\n'
 '\n'
 '# repos\n'
 '[base]\n'
 'name=BaseOS\n'
 '#mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=os\n'
 'baseurl=http://pkgs.example.com:3142/centos/7/os/$basearch/\n'
 'failovermethod=priority\n'
 'gpgkey={{ epel_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'enabled=1\n'
 '#mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=updates\n'
 'baseurl=http://pkgs.example.com:3142/centos/7/updates/$basearch/\n'
 'failovermethod=priority\n'
 'gpgkey={{ epel_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel]\n'
 'name=epel\n'
 '#mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch\n'
 'baseurl=http://pkgs.example.com:3142/epel/7/$basearch\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-7\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[extras]\n'
 'name=extras\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=extras\n'
 'failovermethod=priority\n'
 'gpgkey={{ epel_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 "{% if target_arch == 'x86_64' %}\n"
 '[sclo]\n'
 'name=sclo\n'
 'baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/sclo/\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 "{% if target_arch in ['x86_64', 'ppc64le', 'aarch64'] %}\n"
 '[sclo-rh]\n'
 'name=sclo-rh\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=sclo-rh\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 '[testing]\n'
 'name=epel-testing\n'
 'enabled=0\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=testing-epel7&arch=$basearch\n'
 'failovermethod=priority\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel7-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=epel-debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-debug-7&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '\n'
 '[automake]\n'
 'name=automake\n'
 'baseurl=https://build.example.com/job/foo-stack/job/automake/job/master/lastSuccessfulBuild/artifact/artifacts/centos7/\n'
 'enabled=1\n'
 'gpgcheck=False\n'
 'proxy=http://proxy-us.example.com:912/\n'
 '\n'
 '[libtool]\n'
 'name=libtool\n'
 'baseurl=https://build.example.com/job/foo-stack/job/libtool/job/master/lastSuccessfulBuild/artifact/artifacts/centos7/\n'
 'enabled=1\n'
 'gpgcheck=False\n'
 'proxy=http://proxy-us.example.com:912/\n'
 '\n'
 '[foo-stack-el-7-x86_64-stable-local]\n'
 'name=foo-stack-el-7-x86_64-stable-local\n'
 'baseurl=https://repo.dc.example.com/repository/foo-stack-el-7-x86_64-stable-local/\n'
 'enabled=1\n'
 'gpgcheck=False\n'
 '\n'
 '[foo-stack-external-el-7-x86_64-stable-group]\n'
 'name=foo-stack-external-el-7-x86_64-stable-group\n'
 'baseurl=https://repo.dc.example.com/repository/foo-stack-external-el-7-x86_64-stable-group/\n'
 'enabled=1\n'
 'gpgcheck=False\n')
config_opts['enable_disable_repos'] = []
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'host.example.com',
 '%_netsharedpath': '/proc:/sys',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.j0dxaujn:/etc/resolv.conf',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['package_manager'] = 'yum'
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-7-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/epel-7-x86_64/ccache/u1001/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                 'root': 'epel-7-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/epel-7-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                      'root': 'epel-7-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/epel-7-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                   'root': 'epel-7-x86_64'},
 'mount_enable': False,
 'mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/epel-7-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/epel-7-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/epel-7-x86_64/result',
               'root': 'epel-7-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '7'
config_opts['root'] = 'epel-7-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
config_opts['yum_install_command'] = 'install yum yum-utils --disablerepo=sclo*'
Finish: run
</details>

**Comment by praiskup** [comment]
It took me some time to understand the problem ... so you claim the
problem is this:

```patch
- %global _with_bulid_option --with-build-option
+ %global _with_build_option --with_build_option
```

I didn't catch you care about the value of the macro, I only ever depended
on the fact if it is or if it is not defined (boolean).

But indeed https://rpm.org/user_doc/conditional_builds.html documents the
use of underscored varians in `%configure` calls...

**Comment by praiskup** [comment]
Well, no, even `rpmbuild --with build-options` expands to `--with-build-options`.  Mock just seems to behave in accordance with rpmbuild.  Can you please more elaborate more on the problem?

**Comment by praiskup** [comment]
$ mock --with=a-b --with=c_d --without=b-a-c --with ahoj

shows these options.rpmmacros:
```
['_with_a_b --with-a-b', '_with_c_d --with-c_d', '_with_ahoj --with-ahoj', '_without_b_a_c --without-b-a-c']
```

**Comment by brianjmurrell** [comment]
> It took me some time to understand the problem ... so you claim the
> problem is this:
> 
> ```diff
> - %global _with_bulid_option --with-build-option
> + %global _with_build_option --with_build_option
> ```

Hrm.  I'm not sure how to interpret this.  

What I am claiming is that given a spec file that has `%bcond_with build_option`:

1. `rpmbuild --with=build-option` creates a macro `%_with_build_option` == `--with-build-option`
1. `mock --with=build-option` creates a macro `%_with_build_option` == `--with build-option`

> I didn't catch you care about the value of the macro,

Yes, absolutely.

> I only ever depended
> on the fact if it is or if it is not defined (boolean).

The `%_with...` is not boolean, but a `--with-*` string suitable for `configure`.  But `--with` also produces a `%with...` that is boolean.
 
> But indeed https://rpm.org/user_doc/conditional_builds.html documents the
> use of underscored varians in `%configure` calls...

Yes, per above.  The `%_with*` has the option in it, the `%with*` has the boolean value.

And in fact, I don't even see the `%with*` (boolean) macro in `/builddir/.rpmmacros` so I am not even sure where that is coming from when `mock` builds the RPM.

**Comment by brianjmurrell** [comment]
> $ mock --with=a-b --with=c_d --without=b-a-c --with ahoj
> 
> shows these options.rpmmacros:
> 
> ```
> ['_with_a_b --with-a-b', '_with_c_d --with-c_d', '_with_ahoj --with-ahoj', '_without_b_a_c --without-b-a-c']
> ```

How did you get this result so that I can reproduce here and see if I get the same values?

**Comment by praiskup** [comment]
I've added `import ipdb; ipdb.set_trace()` on [this line](
https://github.com/rpm-software-management/mock/blob/e80a3be9f85135a07e9bbb7fb2dfa9bf427bea28/mock/py/mockbuild/util.py#L1320)

**Comment by brianjmurrell** [comment]
> I've added import ipdb; ipdb.set_trace() on this line

Did you have an example specfile you used with that test?

Did you look in `/builddir/.rpmmacros` to see the values of the macros added there?

**Comment by praiskup** [comment]
You may try:
```
$ mock --scrub chroot,root-cache
$ mock --with=xyz --with=a-b-c --shell 'cat /builddir/.rpmmacros
...
%_with_xyz --with-xyz
%_with_a_b_c --with-a-b-c
```

**Comment by brianjmurrell** [comment]
```
$ mock -r epel-7-x86_64 --scrub chroot,root-cache
Usage: mock [options]

mock: error: option --scrub: invalid choice: 'chroot,root-cache' (choose from 'chroot', 'cache', 'root-cache', 'c-cache', 'yum-cache', 'dnf-cache', 'lvm', 'overlayfs', 'bootstrap', 'all')
```

**Comment by praiskup** [comment]
Sorry, I meant `mock -r epel-7-x86_64 --scrub chroot --scrub root-cache`

**Comment by brianjmurrell** [comment]
```
$ mock -r epel-7-x86_64 --with=xyz --with=a-b-c --shell 'cat /builddir/.rpmmacros'
...
%_with_xyz --with xyz
%_with_a_b_c --with a-b-c
Finish: shell
```

Notice on my system, they both have spaces in them after the `--with`.

**Comment by praiskup** [comment]
Not reproducible. :-(  Can you `mock -r epel-7-x86_64 --scrub=all` and re-run the command?

**Comment by brianjmurrell** [comment]
> Not reproducible.

I assume you are trying to reproduce with the same version of mock that I am using, yes?

```
$ mock -r epel-7-x86_64 --scrub=all
$ mock -r epel-7-x86_64 --with=xyz --with=a-b-c --shell 'cat /builddir/.rpmmacros'
...
%_with_xyz --with xyz
%_with_a_b_c --with a-b-c
Finish: shell
```

**Comment by praiskup** [comment]
It's weird, I can not find any place in code which could be responsible
for removing the `-`, see [the code](https://github.com/rpm-software-management/mock/blob/7fa0c742c46640be173b26509b02d0846a9ced0e/mock/py/mockbuild/util.py#L1313-L1320).

After those lines it's clear that at least `--with-` is always there...
I need you to provide more info, or ideally use debugger to find what is
happening there :-( or maybe ssh access to the broken machine.

**Comment by praiskup** [comment]
> I assume you are trying to reproduce with the same version of mock that I am using, yes?

Well, I for some reason can not spawn F31 box, only F32 ... there I tried
the default v2.2 version, and the latest variant from git `master` branch.

**Comment by praiskup** [comment]
Hm, finally I started fresh f31, and installed the mock v2.2 from repositories.  Still
no hit.  Can you please provide ssh to that affected box?

**Comment by brianjmurrell** [comment]
[ Apologies.  I authored this patch yesterday, but forgot to hit the **Comment** button ]

I just re-installed the rpm on my local node and it changed the ` ` to a `-` on line 1313 which in my copy is:

```
        options.rpmmacros.append("_with_%s --with-%s" %
```

It's certainly quite puzzling indeed.  I will make sure this works also in our CI system.

Quite puzzling indeed.

**Comment by brianjmurrell** [comment]
This can probably be closed.
