### ISSUE TITLE
common mock commands fail on Rawhide with `ImportError: cannot import name 'Context' from 'gpg' (unknown location)`

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/mock#587]
### Short description of the problem

Trying to do common mock stuff on current Fedora Rawhide - e.g. just `mock -r fedora-rawhide-x86-64 --shell` - fails with some import errors:

    [adamw@adam fedora-kickstarts (master %)]$ mock -r openqa --shell
    INFO: mock.py version 2.3 starting (python version = 3.8.3)...
    Start(bootstrap): init plugins
    INFO: selinux enabled
    Finish(bootstrap): init plugins
    Start: init plugins
    INFO: selinux enabled
    Finish: init plugins
    INFO: Signal handler active
    Start: run
    Start(bootstrap): chroot init
    INFO: calling preinit hooks
    INFO: enabled root cache
    INFO: enabled package manager cache
    Start(bootstrap): cleaning package manager metadata
    Finish(bootstrap): cleaning package manager metadata
    INFO: enabled HW Info plugin
    Finish(bootstrap): chroot init
    Start: chroot init
    INFO: calling preinit hooks
    INFO: enabled root cache
    INFO: enabled package manager cache
    Start: cleaning package manager metadata
    Finish: cleaning package manager metadata
    INFO: enabled HW Info plugin
    Start: dnf install
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/dnf/crypto.py", line 35, in <module>
        from gpg import Context
    ImportError: cannot import name 'Context' from 'gpg' (unknown location)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/bin/dnf", line 57, in <module>
        from dnf.cli import main
      File "/usr/lib/python3.8/site-packages/dnf/__init__.py", line 30, in <module>
        import dnf.base
      File "/usr/lib/python3.8/site-packages/dnf/base.py", line 34, in <module>
        from dnf.db.history import SwdbInterface
      File "/usr/lib/python3.8/site-packages/dnf/db/history.py", line 28, in <module>
        from dnf.yum import misc
      File "/usr/lib/python3.8/site-packages/dnf/yum/misc.py", line 30, in <module>
        import dnf.crypto
      File "/usr/lib/python3.8/site-packages/dnf/crypto.py", line 38, in <module>
        import gpgme
    ModuleNotFoundError: No module named 'gpgme'
    ERROR: Command failed: 
     # /usr/bin/systemd-nspawn -q -M 66f2946526ef42b8a7dd0b9eaf5885f4 -D /var/lib/mock/fedora-rawhide-x86_64-bootstrap/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.x46ncb9y:/etc/resolv.conf --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/fedora-rawhide-x86_64/root/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 /usr/bin/dnf --installroot /var/lib/mock/fedora-rawhide-x86_64/root/ --releasever 33 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install @buildsys-build --setopt=tsflags=nocontexts
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/dnf/crypto.py", line 35, in <module>
        from gpg import Context
    ImportError: cannot import name 'Context' from 'gpg' (unknown location)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/bin/dnf", line 57, in <module>
        from dnf.cli import main
      File "/usr/lib/python3.8/site-packages/dnf/__init__.py", line 30, in <module>
        import dnf.base
      File "/usr/lib/python3.8/site-packages/dnf/base.py", line 34, in <module>
        from dnf.db.history import SwdbInterface
      File "/usr/lib/python3.8/site-packages/dnf/db/history.py", line 28, in <module>
        from dnf.yum import misc
      File "/usr/lib/python3.8/site-packages/dnf/yum/misc.py", line 30, in <module>
        import dnf.crypto
      File "/usr/lib/python3.8/site-packages/dnf/crypto.py", line 38, in <module>
        import gpgme
    ModuleNotFoundError: No module named 'gpgme'

### Output of `rpm -q mock`

    [adamw@adam fedora-kickstarts (master %)]$ rpm -q mock
    mock-2.3-1.fc33.noarch

### Steps to reproduce issue

1. Install Fedora Rawhide
2. Install mock
3. Try `mock -r fedora-rawhide-x86_64 --shell`

### Any additional notes

From the host environment I can happily do `from gpg import Content` and `import gpgme`, so this seems like some sort of environment problem - like it's running the command inside the mock environment, perhaps?

**Comment by AdamWill** [comment]
Also happens with `--old-chroot`.

**Comment by AdamWill** [comment]
This seems to happen only with rawhide-y targets. `mock -r fedora-32-x86_64 --shell` and `mock -r fedora-32-x86_64 --install nano` work fine.

**Comment by AdamWill** [comment]
huh, seems that wiping `/var/cache/mock/*rawhide*` and `/var/lib/mock/*rawhide*` has cleared this up. No idea what was causing it.

**Comment by praiskup** [comment]
> From the host environment I can happily do from gpg import Content and import gpgme, 

With bootstrap on, you don't execute /bin/dnf on host, but from bootstrap,
the chroot is in `/var/lib/mock/*-bootstrap/root`.   We don't invalidate cached
bootstrap chroot automatically, you can do `mock --scrub=bootstrap -r <chroot>`.
