### ISSUE TITLE
nosync produce error with the new bootstrap chroot

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#59]
I have enabled tmpfs and nosync and I'm getting:
```
Start: dnf update
ERROR: ld.so: object '/tmp/tmp.mock.i2ulf5q3/$LIB/nosync.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
This should be harmless but should be fixed.

**Comment by Frodox** [comment]
Gdnerally, Does nosync have avy effects with tmpfs plugin? Since all in ram

**Comment by xsuchy** [comment]
I suppose that it can have an effect when most of the tmpfs is in swap. But I do not have hard data.

**Comment by xsuchy** [comment]
This happen only wilt multiarch, i.e on 64bit when building for 32 bits. Can be fixed by `config_opts['chroot_additional_packages'] = 'nosync.i686'`

**Comment by Frodox** [comment]
should be in docs somewhere I think

**Comment by xsuchy** [comment]
At the end the error was somewhere else. There were two issues and commits 3e15fc0 and 75e3f8a address them.
