### ISSUE TITLE
Copr is misparsing a spec file that works in plain rpmbuild

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/mock#593]
### Short description of the problem

Mock (copr mock and rawhide mock) refuses to build a spec file that works fine in plain F33 rpmbuild.

[copr:1469705](https://copr.fedorainfracloud.org/coprs/nim/auto-fonts-packaging/build/1469705/) fails with:
  error: License field must be present in package: (main package)

Ok, copr does not see the the same License line as rpmbuild, let’s add one to the spec file
[copr:1469829](https://copr.fedorainfracloud.org/coprs/nim/auto-fonts-packaging/build/1469829/) now fails with:
  warning: line 59: second License
  error: Duplicate License entries in package: (main package)

So now mock sees the License it did not see before (identical spec file, just one line added). You need a second License line to de-block the parsing of the Line that existed in the first place for rpmbuild, this can not work.

Somewhere in its code, mock creates a temporary srpm using an incomplete build root, and then gates the creation of the real srpm in the real buildroot over this broken srpm.

### Output of `rpm -q mock`

mock-2.3-2.fc33.noarch & copr mock

### Steps to reproduce issue

Take the srpms in the copr issues, try to build them (the second srpm needed some trafficking to produce since rpmbuild does see the License line and did not want a duplicate line added)

### Any additional notes

The spec is one of the test specs for Fedora 33 i18n & Fonts Changes, and it contains most of the macro logic that will serve as base for Fedora 34 Go SIG changes. The 3 SIGs that depend on me need me to find a solution before F33 Change deadlines.

**Comment by xsuchy** [comment]
On my F32 `mock -r fedora-rawhide-x86_64`  prints:
```
Start: build setup for adf-accanthis-fonts-1.8-24.fc33.src.rpm
error: line 58: Unknown tag: %auto_init
```

**Comment by xsuchy** [comment]
What is that auto_init macro? From where it comes?

**Comment by nim-nim** [comment]
@xsuchy it’s some new redhat-rpm-config code I am finishing to polish before merge requesting it

You have the redhat-rpm-config package with the additionnal code in the copr

**Comment by nim-nim** [comment]
One of the things the new code does is full generation of the preamble tags since rpm broke backwards compatibility on preamble tags evaluation in rpm 4.15 and Panu told me I just had to generate everything in the order he expected in rpm, instead of expecting him to honor old rpm parser behaviour forever

**Comment by nim-nim** [comment]
I'm pretty sure the code is hitting a dark mock corner where mock assume some things do not depend on buildroot state, whereas this spec has nothing in the preamble except generated parts

**Comment by xsuchy** [comment]
> Would it help if I produced an F32 variant of the redhat-rpm-config changes?

It will be **big** help if you can provide a full reproducer just on command line. I.e., `mock -r ./my-config.cfg foo.src.rpm` and provide the content of the config. I bet you have to tune 
```
# config_opts['chroot_setup_cmd'] = 'install buildsys-build'                                                                                            
# config_opts['chroot_additional_packages'] = ''
```
so the custom redhat-rpm-config is present.

It would take me a hell of a time to come with the reproducer.

**Comment by nim-nim** [comment]
@xsuchy not really, that’s a deliberately un-tuned setup, because if it was tuned it would be unsafe to test macro code which is untended to be deployed in future Fedora default buildroots (the macro code itself is fairly involved as you may have noticed – there’s a lot of things in there, some of which I would have told you were impossible to attain in the short term just six months ago)

My mock config is just

```
include('templates/fedora-rawhide.tpl')

config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)

config_opts['root'] = 'fonts-rpm-macros'
config_opts['macros']['%dist'] = '%{?distprefix}.fc{{ releasever }}.mng%{?with_bootstrap:~bootstrap}'

config_opts['dnf.conf'] += """
[fonts-rpm-macros]
name=fonts-rpm-macros
baseurl=file:///srv/rpm/fonts-rpm-macros
cost=0
enabled=1
metadata_expire=1

[local]
enabled=1
"""
```

The `config_opts['macros']['%dist']` is just here to produce a custom dist to track what I build myself, and the local repo to expose built things to the next build. Plop the custom redhat-rpm-config and fonts macro packages in there, createrepo_c  and you’re set.

Because it’s a deliberately un-tuned system, it’s not too surprising copr mock fails the exact same way with a vanilla rawhide repo.
 
My site-defaults mock config is just as uninteresting

```
config_opts['plugin_conf']['tmpfs_enable'] = True
config_opts['plugin_conf']['tmpfs_opts']['required_ram_mb'] = 1536
config_opts['plugin_conf']['tmpfs_opts']['max_fs_size'] = '8192m'
```

**Comment by nim-nim** [comment]
(alternatively you can just reference the copr repo in your mock config since it already contains the two macro packages. I use a local repo because copr is sloooow and it’s faster to rebuild locally when I make syntax errors in the lua code)

**Comment by nim-nim** [comment]
[copr:1484983](https://copr.fedorainfracloud.org/coprs/nim/auto-fonts-packaging/build/1484983/) shows the rest of the spec file working

**Comment by praiskup** [comment]
You expect to have `fonts-rpm-macros` in minimal buildroot?  As long as
the macros are used for generating the src.rpm, you have to put it into
`chroot_additional_packages` as Mirek mentioned.  Or the
`redhat-rpm-config` package needs to `Requires: fonts-rpm-macros`.

**Comment by nim-nim** [comment]
@praiskup `fonts-srpm-macros` is already in the default Fedora buildroot (since FC31)

The code here is the next major version of the macro set

**Comment by nim-nim** [comment]
So, the issue is not about buildroot configuration. The issue is mock assuming some processing can be done outside the target buildroot (that probably worked so far because no one hit the intersection between mock assumptions and doing things that depend on buildroot state).

Or maybe it’s a not a problematic mock assumption, just a mock bug that no one hit before.

**Comment by nim-nim** [comment]
Ok I found the problem. There was a stray rename leftover file left in the redhat-rpm-config package, and this file was masking newer code (though, strangely, not in the same way in rpmbuild and various mock stages).

Sorry for the bother, it was pbkac on my part in the end. Too much pressure to hit deadlines, and too little sleep.
