### ISSUE TITLE
Mass disable keepcache

### ISSUE THREAD

**Issue by srakitnican** [rpm-software-management/mock#60]
Hello,

Since I have my own cache server, I would like to disable mock storing installed packages to /var/lib/mock . Is this currently possible, and if not can this be added?

I know I could just mass replace `s/^keepcache=1/keepcache=0/` `/etc/mock/*` but I was wondering if there could be some nicer solution.

**Comment by xsuchy** [comment]
No. There is no better solution. It is not possible to flip one variable in `config_opts['yum.conf'] = ""`

**Comment by xsuchy** [comment]
There is nothing I can do about this. Closing.
