### ISSUE TITLE
mock to run newer gcc

### ISSUE THREAD

**Issue by petrmalkov** [rpm-software-management/mock#61]
host centos 7
mock -r epel-7-x86_64 --init
installs
libgcc-4.8.5-11.el7.x86_64
while on host I installed
gcc --version
gcc (GCC) 5.4.0

How run / to pass into a newer gcc?

**Comment by xsuchy** [comment]
I do not know from where you get gcc-5.4.0. Centos has greatest version 4.8.5. You can query: `rpm -qif /usr/bin/gcc` and check Vendor tag.
Additionally you may check which repos you have enabled in `/etc/yum.repos.d/` These does not propagate into chroot.

**Comment by petrmalkov** [comment]
I want to compile nginx in mock with gcc-5.4.0
Question is about not why 4.8.5 insight but how technically to pass another packet?
may be downloaded compiler in local folder with passed into?
is there any info about it?

**Comment by xsuchy** [comment]
```
cp /etc/mock/epel-7-x86_64.cfg ~/my-epel-7-x86_64.cfg
vim ~/my-epel-7-x86_64.cfg
# add repo with your gcc to `config_opts['yum.conf']` (it is multiline value)
mock -r ~/my-epel-7-x86_64.cfg foo.src.rpm
```
