### ISSUE TITLE
Builds that use `unshare` don't work in mock

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/mock#612]
### Short description of the problem

openQA likes to use `unshare -r -n` in some of its tests to test what happens when there's no network connection. Problem being, this doesn't work in mock, I think because we run the build as user `mock` not `root`: it fails with `unshare: unshare failed: Operation not permitted`

### Output of `rpm -q mock`

mock-2.4-1.fc33.noarch

### Steps to reproduce issue

1. Have a package build do `unshare -r -n <something>` and expect it to run as intended
2. Run the build in mock, observe that it doesn't

### Any additional notes

I've been dealing with this so far by just patching out the use of `unshare`, but it's getting progressively harder because they've started adding tests that expect a specific result that doesn't happen unless the `unshare` command works. e.g. a test that expects a network failure fails because instead it gets a 404. I suspect that might actually work when run in Koji, but I need it to work in local Mock too.

**Comment by AdamWill** [comment]
to be clear, this isn't about openQA-in-use, it's about the openqa package build, which runs the code's own test suite. That's the thing that's using `unshare`. e.g. [here](https://github.com/os-autoinst/openQA/blob/master/t/40-openqa-clone-job.t#L28). My current problem is that [the last subtest there](https://github.com/os-autoinst/openQA/blob/master/t/40-openqa-clone-job.t#L35) fails if I patch out the use of `unshare` because it gets a 255 exit code instead of 22.

**Comment by praiskup** [comment]
> I think because we run the build as user mock not root

It's so old rule to switch to non-privileged user inside mock so I don't
think it is possible to change this.  It is never a good idea to run rpmbuild
as privileged user **without mock**, and doing so **inside mock** would make
the build too much different..

> I suspect that might actually work when run in Koji,

What leads you to this suspicion?  Koji only does `--isolation=simple`,
locally (default) mock uses `--isolation=nspawn`, otherwise, the build
process shouldn't differ too much.

Btw., `mock --shell` gives you a root user inside mock chroot.  And with
Mock's default, the network doesn't work (unshared, there's
`--enable-network` and `--disable-network`).  Perhaps you could use
`--shell` then, instead?

**Comment by AdamWill** [comment]
> What leads you to this suspicion?

Koji seems to have an additional layer of network access nerfing beyond anything mock does, which sometimes avoids problems with stuff like this. And indeed it seems to be the case: I ran a scratch build of [a .src.rpm which fails in a local mock](https://www.happyassassin.net/temp/openqa-4.6-53.20200805gite9b4474.fc33.src.rpm) and [it worked](https://koji.fedoraproject.org/koji/taskinfo?taskID=48773595).

I'm using `--isolation=simple` locally too, BTW (partly because `--isolation=nspawn` appears to be broken in Rawhide ATM). I know about `mock --shell`, but I'm not sure what you're suggesting about "using it instead". There is no `--disable-network`, only `--enable-network`, and network disabled is the default (for builds as well as shells).

**Comment by AdamWill** [comment]
To reproduce:

* `mock -r fedora-rawhide-x86_64 --isolation=simple --rebuild openqa-4.6-53.20200805gite9b4474.fc33.src.rpm` (fails)
* `koji build --scratch rawhide openqa-4.6-53.20200805gite9b4474.fc33.src.rpm` (succeeds)

note the build needs the latest os-autoinst which I only built yesterday, so you *may* need to add a side repo with that os-autoinst in it for mock if it hasn't reached mirrors yet.

**Comment by praiskup** [comment]
> I ran a scratch build of a .src.rpm which fails in a local mock and it worked.

Weird.

> I know about mock --shell, but I'm not sure what you're suggesting about "using it instead".

I thought you could move some of the logic before `mock --rebuild `.  But you can not, this is no go.

> There is no --disable-network

Correct.

Thanks for the reproducers.  I need to take a closer look ... could there be some special kernal
on koji builders, so it would allow us to run unshare inside `--isolation=simple`?  I mean, unless
koji does some special host/buildroot tweaks, there's no reason mock should behave differently
locally... (as I believe Koji neither runs the build as root user).

**Comment by AdamWill** [comment]
Like I said, AIUI the difference is that there's *additional* isolation from the network done on the Koji builder hosts, outside of what mock does. I think whatever additional thing we do to the Koji builders to ensure they can't talk to the network is the difference here. nirik or smooge could probably give more detail on that if you're interested.

**Comment by praiskup** [comment]
@nirik / @smooge any more info about the _additional_ isolation?  Years back when I tried, there were nothing like that.

**Comment by nirik** [comment]
The only additional isolation on builders is that they have a very restrictive firewall... OUTPUT is only allowed to some ip's and rejected for most. 

Otherwise they run normal f32 kernel, normal mock. They do use isolation simple (old chroot). Nothing else comes to mind.

**Comment by AdamWill** [comment]
It's probably the firewalling that changes the test's behaviour, then.

**Comment by praiskup** [comment]
Is this somehow related to https://bugzilla.redhat.com/show_bug.cgi?id=1873856 ?

At least I am trying to build the [src.rpm](https://www.happyassassin.net/temp/openqa-4.6-53.20200805gite9b4474.fc33.src.rpm)
you mentioned above and it seems to be doing something.  Previously it failed really fast.

Tested with  mock-2.6-1.git.6.a24dbfa.fc32.noarch  from (dnf copr enable @mock/mock).  Can you please retry at least with mock 2.6 from updates-testing?

**Comment by AdamWill** [comment]
I don't think it can have been that bug, because that bug's newer than this issue, I think? But something else could've fixed it, I guess. I'll try this again later today if I get time.

**Comment by praiskup** [comment]
OK, per my previous attempt it was not reproducible anymore, so I suppose *something* in the system git fixed.  Feel free to reopen if you continue to see this problem, thank you for the report!
