### ISSUE TITLE
Fedora ELN mock config

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#614]
Could you please include a fedora-eln mock config?

The repo files are available in `fedora-repos-eln` package (component fedora-repos). The local repo is https://kojipkgs.fedoraproject.org/repos/eln-build/latest/

For completnes:

```
[eln]
name=Fedora - ELN - Developmental modular packages for the next Enterprise Linux release
baseurl=https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/
#metalink=https://mirrors.fedoraproject.org/metalink?repo=eln&arch=$basearch
enabled=0
countme=1
metadata_expire=6h
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[eln-debuginfo]
name=Fedora - ELN - Debug
baseurl=https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/debug/tree
#metalink=https://mirrors.fedoraproject.org/metalink?repo=eln-debug&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[eln-source]
name=Fedora - ELN - Source
baseurl=https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/source/tree/
#metalink=https://mirrors.fedoraproject.org/metalink?repo=eln-source&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

**Comment by praiskup** [comment]
> Could you please include a fedora-eln mock config?

Why not, do you want to take a look at PR?

**Comment by hroncok** [comment]
> do you want to take a look at PR?

I'm not sure what are the conventions wrt templates, locations and stuff, hence I'd rather not. I can certainly provide a review and/or test it before it is shipped.

**Comment by praiskup** [comment]
Ok, I'll try to take a look

**Comment by hroncok** [comment]
Note that `https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/` includes the metadata but all packages give error 403. Is that intentional @sgallagher @bookwar?

**Comment by praiskup** [comment]
What should mock set as `%dist`, or `%eln` respectively?  Koji seems to set there `.eln103`.  What does that mean?

**Comment by hroncok** [comment]
https://fedoraproject.org/wiki/Changes/ELN_Buildroot_and_Compose#Detailed_Description

See "The RPM variables"

**Comment by praiskup** [comment]
Thanks for the reference, per docs then:
```
%{eln} will be set and will expand to a MAJOR.MINOR value (starting at
100.0). The MAJOR number will be increased any time we make a change to
the ELN build configuration that necessitates a mass-rebuild (such as new
security compiler flags). The MINOR number will be increased any time we
make a change to the ELN build configuration that can safely be picked up
at the next regular package build.
```

Hm, I'm afraid that we'll have to bump the %eln too often in
mock-core-configs, and re-release :-( considering we have right now 103.
The major/minor is wrong (I don't think rpm can compare floating point
numbers with `%if %eln > sth`).  But there doesn't seem to any minor part
ATM.

```
The %{eln} variable will be set primarily to allow for the possibility of
needing conditionals that apply to ELN only and should not carry over to
RHEL, but we expect its use to be exceptionally rare. 
```

Hehe, if it is like that, can we be a brave -- and assume in mock that
no-one will actually use the variable?  And define it to something like
`%eln UNSET` and `%dist .eln` (without number)?

**Comment by sgallagher** [comment]
> Note that `https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/` includes the metadata but all packages give error 403. Is that intentional @sgallagher @bookwar?

The compose is currently broken. None of the packages are actually present. I'll look into that today.




> Thanks for the reference, per docs then:
> 
> ```
> %{eln} will be set and will expand to a MAJOR.MINOR value (starting at
> 100.0). The MAJOR number will be increased any time we make a change to
> the ELN build configuration that necessitates a mass-rebuild (such as new
> security compiler flags). The MINOR number will be increased any time we
> make a change to the ELN build configuration that can safely be picked up
> at the next regular package build.
> ```

Can you point me at which docs still say that? We discovered the fractional comparison problem and moved to just XYY (e.g. 103) as the numbering scheme.

> 
> Hm, I'm afraid that we'll have to bump the %eln too often in
> mock-core-configs, and re-release :-( considering we have right now 103.
> The major/minor is wrong (I don't think rpm can compare floating point
> numbers with `%if %eln > sth`). But there doesn't seem to any minor part
> ATM.

Why do you care about the tag at all? It doesn't change the repo URL in any way. I'm not sure why you would care if it changed.

> 
> ```
> The %{eln} variable will be set primarily to allow for the possibility of
> needing conditionals that apply to ELN only and should not carry over to
> RHEL, but we expect its use to be exceptionally rare. 
> ```
> 
> Hehe, if it is like that, can we be a brave -- and assume in mock that
> no-one will actually use the variable? And define it to something like
> `%eln UNSET` and `%dist .eln` (without number)?

I might suggest using `%eln 001` and leaving %dist as `%dist .eln%{eln}` so that no matter what, an official package will always supersede it, but I can't see any problem with that. If anyone uses the `if 0{%eln}` construct, as long as it doesn't compare to zero, it should be fine.

**Comment by praiskup** [comment]
> None of the packages are actually present.

The [link](https://fedoraproject.org/wiki/Changes/ELN_Buildroot_and_Compose#Detailed_Description) mentioned by @hroncok above.  That's actually a change proposal, so it may get outdated, I don't claim it is a bug :-)

> Why do you care about the tag at all? It doesn't change the repo URL in any way. I'm not sure why you would care if it changed.

Because `koji mock-config` defines it, and because `%dist` affects the NVR of built packages.  Seems like something in buildroot defines this appropriately, so mock doesn'ŧ have to care....  let me try.  But the `koji mock-config` output contains something which raised my eyebrows:
```
config_opts['macros']['%dist'] = '%{!?distprefix0:%{?distprefix}}%{expand:%{lua:for i=0,9999 do print("%{?distprefix" .. i .."}") end}}.eln%{eln}%{?with_bootstrap:~bootstrap}'
config_opts['macros']['%eln'] = 103
```
Why Koji cares about that tag?

> no matter what, an official package will always supersede it

That would be precedent.  We always try to provide the exact same NVR as is produced by Koji.

**Comment by praiskup** [comment]
> If anyone uses the if 0{%eln} construct,

I'd expect use-cases like `%if 0%{?eln} > 102`, e.g.

**Comment by hroncok** [comment]
%{!?distprefix0:%{?distprefix}}%{expand:%{lua:for i=0,9999 do print("%{?distprefix" .. i .."}") end}}.eln%{eln}%{?with_bootstrap:~bootstrap}

...is basically a copy of Fedora's definition of dist, which is:

    %{!?distprefix0:%{?distprefix}}%{expand:%{lua:for i=0,9999 do print("%{?distprefix" .. i .."}") end}}.fc%{fedora}%{?with_bootstrap:~bootstrap}

**Comment by hroncok** [comment]
I see this in the rawhide template/config:

```
config_opts['dist'] = 'rawhide'  # only useful for --resultdir variable subst
```

Which also isn't true definition of rawhide's `%dist`, or is it?

**Comment by sgallagher** [comment]
> > If anyone uses the if 0{%eln} construct,
> 
> I'd expect use-cases like `%if 0%{?eln} > 102`, e.g.

Do not expect these use-cases. I'll make the docs clearer, but this is meant to be treated as a boolean, with the number itself being an internal implementation detail.

**Comment by praiskup** [comment]
Thank you for the info.  There's one additional question;  what about the $releasever?  We seem to use it in:
`gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch`

Is that just `eln`?

**Comment by praiskup** [comment]
Also, is the metalink variant supposed to work ATM?  Or is there ETA?

**Comment by hroncok** [comment]
There are no `/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-eln...` keys at my machine, I suppose the package are signed with rawhide keys.

**Comment by sgallagher** [comment]
> Thank you for the info. There's one additional question; what about the $releasever? We seem to use it in:
> `gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch`
> 
> Is that just `eln`?

The ELN packages are signed by the Rawhide key.



> Also, is the metalink variant supposed to work ATM? 
No

> Or is there ETA?

It's not planned for right now. We aren't going to bother unless the load gets too great for odcs.fedoraproject.org.

**Comment by praiskup** [comment]
FWIW, I now tried:

`$ mock -r fedora-eln-x86_64 --shell --no-bootstrap-chroot  --enablerepo=local`

And nothing inside the buildroot defines %dist or %eln correctly:
```
<mock-chroot> sh-5.0# rpm --eval "%eln %dist"
%eln .fc33
```

It really looks like we *have to* define those macros explicitly in mock's config.

**Comment by sgallagher** [comment]
> FWIW, I now tried:
> 
> `$ mock -r fedora-eln-x86_64 --shell --no-bootstrap-chroot --enablerepo=local`
> 
> And nothing inside the buildroot defines %dist or %eln correctly:
> 
> ```
> <mock-chroot> sh-5.0# rpm --eval "%eln %dist"
> %eln .fc33
> ```
> 
> It really looks like we _have to_ define those macros explicitly in mock's config.

That's getting fixed this week. Up to now, we've been defining them as options on the Koji target, but we are going to have them set by the fedora-release-common package. @tdawson is looking into that.

**Comment by praiskup** [comment]
> I'll make the docs clearer, but this is meant to be treated as a boolean,

Shouldn't it be defined define as `1` then, and its use-case documented as `%if %{?eln:1}`?

**Comment by sgallagher** [comment]
> > I'll make the docs clearer, but this is meant to be treated as a boolean,
> 
> Shouldn't it be defined define as `1` then, and its use-case documented as `%if %{?eln:1}`?

The short answer is that we need to have it be incrementable so that we can rebuild the same package if we need to change the buildroot configuration. Otherwise, we'd be trying to build the same ENVRA again, which Koji prohibits.

Consider: you build `mock-2.4-2.fc33` in Rawhide. Our automation sees that and automatically builds `mock-2.4-2.eln103`. However, tomorrow we realize that we have to do an ELN mass-rebuild because it turns out that we have to pass `-fdontcrash` for things to compile properly. We didn't want to force Rawhide to accept a version bump because we're trying to keep ELN non-disruptive to packagers. In this case, we'd bump the `%{eln}` version and just do a rebuild. It would have a different ENVRA, so Koji would accept it.



> > I'll make the docs clearer, but this is meant to be treated as a boolean,
> 
> Shouldn't it be defined define as `1` then, and its use-case documented as `%if %{?eln:1}`?

I think I answered this above, but the proper comparison would be `%if 0%{?eln}`.

**Comment by sgallagher** [comment]
> Note that `https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/` includes the metadata but all packages give error 403. Is that intentional @sgallagher @bookwar?

There was a bug in the compose. It should be fixed now.

**Comment by hroncok** [comment]
> There was a bug in the compose. It should be fixed now.

Indeed.

**Comment by praiskup** [comment]
I see problems when initializing bootstrap chroot (installing dnf && dnf-utils):
```
Error: 
 Problem 1: package dnf-4.2.23-2.eln103.noarch requires python3-dnf = 4.2.23-2.eln103, but none of the providers can be installed
  - package python3-dnf-4.2.23-2.eln103.noarch requires dnf-data = 4.2.23-2.eln103, but none of the providers can be installed
  - conflicting requests
  - nothing provides libreport-filesystem needed by dnf-data-4.2.23-2.eln103.noarch
 Problem 2: package python3-dnf-plugins-core-4.0.16-4.eln103.noarch requires python3-dnf >= 4.2.22, but none of the providers can be installed
  - package dnf-plugins-core-4.0.16-4.eln103.noarch requires python3-dnf-plugins-core = 4.0.16-4.eln103, but none of the providers can be installed
  - package python3-dnf-4.2.23-2.eln103.noarch requires dnf-data = 4.2.23-2.eln103, but none of the providers can be installed
  - conflicting requests
  - nothing provides libreport-filesystem needed by dnf-data-4.2.23-2.eln103.noarch
```

**Comment by hroncok** [comment]
One think is that ELN inherits from rawhide, so probably the rawhide repo should be there as well?

**Comment by praiskup** [comment]
Also, maybe this is normal for all Fedora buildroots..., but `@build` group seems to exist only
in `local` repo, while in the `@buildsys-build` is only in the `eln` repo (I'm refering to the PR).

**Comment by mmathesius** [comment]
If it's any help, I recently posted a mock config file for ELN x86_64 that has been working for me at [https://docs.fedoraproject.org/en-US/eln/buildroot/#_testing_environment](https://docs.fedoraproject.org/en-US/eln/buildroot/#_testing_environment). It started out as the output from running `koji mock-config --target eln --arch x86_64` and got cleaned up a lot.

**Comment by mmathesius** [comment]
FYI, PR https://src.fedoraproject.org/rpms/fedora-release/pull-request/137 will be taking care of setting the ELN macros external to the mock configs.

**Comment by praiskup** [comment]
> One think is that ELN inherits from rawhide, so probably the rawhide repo should be there as well?

@sgallagher can you confirm this is correct?

> If it's any help, I recently posted a mock config file for ELN x86_64 ...

I started with `koji mock-config`, see above.

[That](https://docs.fedoraproject.org/en-US/eln/_attachments/eln-x86_64.cfg) is heavily based on
Koji's internal repo, in mock we usually name it `local` (see the pull request #615 here) -- and it
is opt-in.

I can not install `dnf` using the public repo though, should we only depend on the Koji repo?

**Comment by praiskup** [comment]
> > Also, is the metalink variant supposed to work ATM?
> 
> No
> 
> >  Or is there ETA?
> 
> It's not planned for right now. We aren't going to bother unless the load gets
> too great for odcs.fedoraproject.org.

I don't know what is going on now, but I get:

Errors during downloading metadata for repository 'eln':
  - Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/repodata/repomd.xml (IP: 67.219.144.68)

Can we re-consider the mirroring?  @sgallagher

**Comment by praiskup** [comment]
New error:
```
[MIRROR] basesystem-11-10.eln103.noarch.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/Packages/basesystem-11-10.eln103.noarch.rpm (IP: 140.211.169.206)       
[MIRROR] alternatives-1.14-3.eln103.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/Packages/alternatives-1.14-3.eln103.x86_64.rpm (IP: 140.211.169.206) 
[MIRROR] audit-libs-3.0-0.21.20191104git1c2f876.eln103.x86_64.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/Packages/audit-libs-3.0-0.21.20191104git1c2f876.eln103.x86_64.rpm (IP: 140.211.169.206)
[MIRROR] basesystem-11-10.eln103.noarch.rpm: Status code: 403 for https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/x86_64/os/Packages/basesystem-11-10.eln103.noarch.rpm (IP: 140.211.169.206)       
[FAILED] basesystem-11-10.eln103.noarch.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                                        
(2-3/132): audit-libs-3.0-0.21.20191104git1c2f876.eln103.x86_64.rpm                                  0% [                                                                                                  ] 320 kB/s | 6.9 kB     02:44 ETA
Error: Error downloading packages:
  Cannot download Packages/basesystem-11-10.eln103.noarch.rpm: All mirrors were tried
```
I planned to enable those chroots in Fedora Copr, but I'm not sure it is wise.  WDYT, @mmathesius @sgallagher, is this just 
a temporary problem or Koji isn't able to hold the additional traffic?

**Comment by praiskup** [comment]
Seems to work fine **ATM**, so I enabled it in Copr.  But still I'd like to hear opinions about what the failures were about.

**Comment by mmathesius** [comment]
> I planned to enable those chroots in Fedora Copr, but I'm not sure it is wise. WDYT, @mmathesius @sgallagher, is this just
> a temporary problem or Koji isn't able to hold the additional traffic?

I experienced that error, too. It is my understanding there were some temporary compose issues. I presume that was it.

**Comment by sgallagher** [comment]
That was a temporary issue; an upgrade of ODCS resulted in the repositories being created with the wrong permissions. It's my understanding that it has been fixed.

**Comment by praiskup** [comment]
Ok, thank you. JFTR, there was another problem in the meantime,  https://pagure.io/releng/issue/9757
