### ISSUE TITLE
Concurrent mock runs don't share the mountpoints

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#627]
Doing `mock -r <chroot> --shell` in one terminal, and e.g. `mock -r <chroot> --install vim` in another doesn't work when bootstrap is enabled.
I mean, yeah - it does something - but the vim package isn't installed to the same <basedir>/root mountpoint as one would expect.

**Comment by praiskup** [comment]
This is a pretty complicated problem if I interpret it correctly.  At this moment, we have very problematic
design of executing nspawn'ed package manager in bootstrap "on demand".
The bootstrap nspawn containers start/end several times during the mock run, when bootstrapped
package manager is needed to be run.

So when one mock is running nspawn with `mock --shell`, another mock can do `--install`, but it
re-initializes the bootstrap (it's own) mountpoints.

It would be ideal to run all the requested commands in one container, not to try to run multiple
containers (with systemd-nspawn -D) at the same time.  That would simplify the chroot preparation
a lot, and the overall code.

Btw., `systemd-nspawn -D` can not be run multiple times against the same directory (unless
we disable root locking by an ugly/hackish environment variable).  That's why we should start
the container once using systemd-nspawn, and then use `nsenter` to execute the commands inside
the container.  `Systemd-nspawn` + `nsenter` is equivalent pair as `podman run` + `podman exec`.
One might argue that `systemd-nspawn shell` can be used, but it can not because there's
no systemd process running inside our chroots.

Changing the abstraction of command calls according to previous paragraph would open doors
to implement other --isolation mechanisms (docker/podman).

**Comment by xsuchy** [comment]
Running two mock on the same chroot was never supported. Honestly, I would expect that the second instance will print `Build root is locked by another process.` which we already in a code on some place.

**Comment by praiskup** [comment]
The locking mechanism with "readers/writers like" behavior though really look like these
things should work.  It is there just to protect against accidental concurrent initialization.

I mean, there's IMO no sane reason to block users from doing this, except that we don't know
how to implement this correctly in all cases.

**Comment by praiskup** [comment]
> I mean, there's IMO no sane reason to block users from doing this,

And not even saying the fact that having this working is extremely useful when debugging in `--shell`.
Work-around is to do `mock --isolation=simple --install` or disable bootstrap I believe.
