### ISSUE TITLE
Please copy in Satellite CA certificate if present and redhat_subscription_required set to true

### ISSUE THREAD

**Issue by pcfe** [rpm-software-management/mock#638]
### Short description of the problem
while [rhelchroots](https://github.com/rpm-software-management/mock/wiki/Feature-rhelchroots) seem to be aimed at connecting to redhat.com, it also works with one work-around against a Satellite server

I only need to copy /etc/rhsm/ca/katello-server-ca.pem into my bootstrap

As such, would you please consider doing that if 
config_opts['redhat_subscription_required'] = True

### Output of `rpm -q mock`

mock-2.4-1.el7.noarch

### Steps to reproduce issue

1. be in a network where my mock host can *not* connect to https://cdn.redhat.com/content/dist/…
2. have a working Satellite server in this network
3. attempt to have mock use the Satellilte server
4. take the REPOS section for the mock config and the client certificate from a machine that uses Satellite successfully

using a self created `/etc/mock/rhel-8-x86_64.cfg` with;
config_opts['use_nspawn'] = False

`mock --init --root rhel-8-x86_64`

leads to error about missing …/etc/rhsm/ca/katello-server-ca.pem

Copying that file into the bootstrap makes mock work both in --init mode and also in --rebuild mode. These two are what I use for [soe-ci](https://github.com/RedHatSatellite/soe-ci/)

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

INFO: mock.py version 2.4 starting (python version = 3.6.8)...
INFO: Using 'yum' instead of 'dnf' for bootstrap chroot
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'ubi8/ubi'
config_opts['bootstrap_redhat_subscription_required'] = True
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = ('install tar gcc-c++ redhat-rpm-config redhat-release which xz sed make bzip2 '
 'gzip gcc coreutils unzip shadow-utils diffutils cpio bash gawk rpm-build '
 'info patch util-linux findutils grep')
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg', '/etc/mock/rhel-8-x86_64.cfg']
config_opts['dist'] = 'el8'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=1\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:el8\n'
 'protected_packages=\n'
 '\n'
 '### REPOS\n'
 '[rhel-8-for-x86_64-baseos-rpms]\n'
 'name = Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/content/dist/rhel8/$releasever/x86_64/baseos/os\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n'
 '\n'
 '[Sat_Test_EPEL_repo-custom-rhel-8-epel]\n'
 'name = repo-custom-rhel-8-epel\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/custom/EPEL/repo-custom-rhel-8-epel\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = '
 'https://satellite.sattest.pcfe.net/katello/api/v2/repositories/1455/gpg_key_content\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n'
 '\n'
 '[codeready-builder-for-rhel-8-x86_64-rpms]\n'
 'name = Red Hat CodeReady Linux Builder for RHEL 8 x86_64 (RPMs)\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/content/dist/rhel8/$releasever/x86_64/codeready-builder/os\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n'
 '\n'
 '[satellite-tools-6.7-for-rhel-8-x86_64-rpms]\n'
 'name = Red Hat Satellite Tools 6.7 for RHEL 8 x86_64 (RPMs)\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/content/dist/layered/rhel8/x86_64/sat-tools/6.7/os\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n'
 '\n'
 '[rhel-8-for-x86_64-appstream-rpms]\n'
 'name = Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/content/dist/rhel8/$releasever/x86_64/appstream/os\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n'
 '\n'
 '[ansible-2-for-rhel-8-x86_64-rpms]\n'
 'name = Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)\n'
 'baseurl = '
 'https://satellite.sattest.pcfe.net/pulp/repos/Sat_Test/eng/ccv-rhel8-with-epel/content/dist/layered/rhel8/x86_64/ansible/2/os\n'
 'enabled = 1\n'
 'gpgcheck = 1\n'
 'gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/katello-server-ca.pem\n'
 'sslclientkey = /etc/pki/entitlement/8044504670992648638-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/8044504670992648638.pem\n'
 'metadata_expire = 1\n'
 'enabled_metadata = 0\n')
config_opts['dnf_install_command'] = 'install dnf dnf-plugins-core subscription-manager'
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'jenkins.sattest.pcfe.net',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.6vzv84fr:/etc/resolv.conf']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel-8-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                     'root': 'rhel-8-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/rhel-8-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/rhel-8-x86_64/ccache/u996/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                 'root': 'rhel-8-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/rhel-8-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                      'root': 'rhel-8-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/rhel-8-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                        'root': 'rhel-8-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                  'root': 'rhel-8-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/rhel-8-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                   'root': 'rhel-8-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/rhel-8-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                'root': 'rhel-8-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/rhel-8-x86_64',
                    'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                    'root': 'rhel-8-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/rhel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/rhel-8-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                        'root': 'rhel-8-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel-8-x86_64',
                     'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                     'root': 'rhel-8-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                  'root': 'rhel-8-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/rhel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel-8-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/rhel-8-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                     'root': 'rhel-8-x86_64',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                  'root': 'rhel-8-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/rhel-8-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
               'root': 'rhel-8-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/rhel-8-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                'root': 'rhel-8-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/rhel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/rhel-8-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/rhel-8-x86_64/result',
                    'root': 'rhel-8-x86_64'}}
config_opts['print_main_output'] = True
config_opts['redhat_subscription_key_id'] = '8966364552636864513'
config_opts['redhat_subscription_required'] = True
config_opts['releasever'] = '8'
config_opts['root'] = 'rhel-8-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['use_nspawn'] = False
config_opts['verbose'] = 1
config_opts['yum_install_command'] = 'install yum yum-utils subscription-manager'
Finish: run

</details>

**Comment by praiskup** [comment]
> I only need to copy /etc/rhsm/ca/katello-server-ca.pem into my bootstrap

No problem, are you able to prepare the patch?

**Comment by pcfe** [comment]
> No problem, are you able to prepare the patch?

Not in the short term. Sorry.

**Comment by bcg62** [comment]
Cant seem to get this to work, can someone help me figure out what I am missing?

```
INFO: ENTER ['_setup_katello_ca'](<mockbuild.buildroot.Buildroot object at 0x7f7ca52a5bb0>)
INFO: ENTER ['_copy_config'](<mockbuild.buildroot.Buildroot object at 0x7f7ca52a5bb0>, 'rhsm/ca/katello-server-ca.pem', warn=False)
INFO: ENTER ['make_chroot_path'](<mockbuild.buildroot.Buildroot object at 0x7f7ca52a5bb0>, '/etc/rhsm/ca/katello-server-ca.pem')
INFO: EXCEPTION: [FileNotFoundError(2, 'No such file or directory')]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/buildroot.py", line 305, in _copy_config
    shutil.copy2(orig_conf_file, conf_file)
  File "/usr/lib64/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mock/rhel-8-x86_64-bootstrap/root/etc/rhsm/ca/katello-server-ca.pem'
INFO: EXCEPTION: [FileNotFoundError(2, 'No such file or directory')]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/buildroot.py", line 320, in _setup_katello_ca
    self._copy_config('rhsm/ca/katello-server-ca.pem', warn=False)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/buildroot.py", line 305, in _copy_config
    shutil.copy2(orig_conf_file, conf_file)
  File "/usr/lib64/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mock/rhel-8-x86_64-bootstrap/root/etc/rhsm/ca/katello-server-ca.pem'
```

**Comment by praiskup** [comment]
We need to take a closer look.

**Comment by praiskup** [comment]
Can you try `mock -r <your-config> --scrub=bootstrap` and then retry?

**Comment by dpward** [comment]
@praiskup At the time this code is called, the directory /etc/rhsm/ca does not exist in the buildroot (or even /etc/rhsm). So it's trying to copy a file into a directory that doesn't exist, and is failing.

**Comment by praiskup** [comment]
This is weird.  We don't try to copy /etc/rhsm/ca to buildroot, but to bootstrap chroot from where we
install stuff into the buildroot...  Is this the issue you have?

**Comment by praiskup** [comment]
Ok, you are right ... we should make sure that `/etc/rhsm/ca` exists first.

**Comment by praiskup** [comment]
Can you please test the #711 one-liner?

**Comment by dpward** [comment]
While that addresses that particular error, it reveals the next problem:

```
Start(bootstrap): dnf install
No matches found for the following disable plugin patterns: local
Updating Subscription Management repositories.
Unable to read consumer identity
4 local certificates have been deleted.

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
...
```

So /etc/pki/consumer needs to be mounted [in addition to](https://github.com/rpm-software-management/mock/blob/mock-2.9-1/mock/py/mock.py#L750-L754) /etc/pki/entitlement. If that is fixed, then I get:

```
Start(bootstrap): dnf install
No matches found for the following disable plugin patterns: local
Updating Subscription Management repositories.
Red Hat Enterprise Linux - BaseOS                                                                                                                                                  192  B/s | 360  B     00:01    
Errors during downloading metadata for repository 'rhel-baseos':
  - Status code: 403 for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml (IP: #.#.#.#)
Error: Failed to download metadata for repo 'rhel-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
ERROR: Command failed: 
 # /usr/bin/dnf --installroot /var/lib/mock/rhel-8-x86_64-bootstrap/root/ --releasever 8 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install dnf dnf-plugins-core subscription-manager --setopt=tsflags=nocontexts
```

Note that it's trying to download from cdn.redhat.com here, even though the host is pointing to a local Satellite server.

**Comment by praiskup** [comment]
That's something we can not solve though, I'm afraid you need a custom mock configuration.
Or is there a way (from mock POV) to guess the local mirror?

**Comment by dpward** [comment]
The DNF subscription-manager plugin generates /etc/yum.repos.d/redhat.repo every time `dnf` is run. This would have to be used instead of the repository configuration [in the template](https://github.com/rpm-software-management/mock/blob/mock-core-configs-34.2-1/mock-core-configs/etc/mock/templates/rhel-8.tpl#L34-L63).

But there are several things that would need to be changed. For starters, the directory /etc/yum.repos.d is [deleted](https://github.com/rpm-software-management/mock/blob/mock-2.9-1/mock/py/mockbuild/package_manager.py#L428) before `dnf` is run, which prevents this file from being written. The template currently [ignores](https://github.com/rpm-software-management/mock/blob/mock-core-configs-34.2-1/mock-core-configs/etc/mock/templates/rhel-8.tpl#L19) this directory even if it exists. It also seems to need additional files in /etc/rhsm (likely at least /etc/rhsm/rhsm.conf), and perhaps this entire directory should be mounted as well — which would eliminate the need to copy /etc/rhsm/ca/katello-server-ca.pem in the first place...

**Comment by dpward** [comment]
@pcfe Did the change in #670 make it possible for you to use a local Satellite server? What version of RHSM, etc.?

@praiskup @xsuchy If not, then I would suggest reverting #670 — unless it actually enabling this use case somehow with the right configuration.

**Comment by praiskup** [comment]
> The DNF subscription-manager plugin generates /etc/yum.repos.d/redhat.repo every time dnf is run. This would have to be used instead of the repository configuration in the template.

The `redhat.repo` can not be used, unfortunately.  The `rhel-8` templates are operating with rhel-8 repositories,
while redhat.repo is related to the host system (be that RHEL7, RHEL8 or subscribed Fedora).

**Comment by dpward** [comment]
> The `redhat.repo` can not be used, unfortunately. The `rhel-8` templates are operating with rhel-8 repositories,
> while redhat.repo is related to the host system (be that RHEL7, RHEL8 or subscribed Fedora).

Just to clarify, it is generating `/var/lib/mock/rhel-8-x86_64-bootstrap/root/etc/yum.repos.d/redhat.repo`, based on the configuration it is accessing inside the bootstrap chroot.

Perhaps someone at @RedHatSatellite knows the right approach here?

**Comment by sideangleside** [comment]
Note: `/etc/yum.repos.d/redhat.repo` is used in both the RHSM and Satellite use-cases.  Basically, for host connected to Satellite, its subscription-manager configuration is changed to include the public cert of the local Satellite's CA, and the `/etc/rhsm/rhsm.conf`  is changed with the URL of the local Satellite. 

The rhsm.conf file will change over time as the user enables/disables repos, attaches subscriptions, or gets access to new repositories.  (depending on server or client configuration), so it might be useful to mount all of `/etc/rhsm` as stated above. 

cc: @cnsnyder (who maintains subscription-manager)

**Comment by praiskup** [comment]
> Just to clarify, it is generating /var/lib/mock/rhel-8-x86_64-bootstrap/root/etc/yum.repos.d/redhat.repo, based on the configuration it is accessing inside the bootstrap chroot.

No, **that** redhat.repo isn't used at all.  I think it deserves a few words on how mock works inside.  As we already have a [howto work with mock](https://github.com/rpm-software-management/mock/wiki/Feature-rhelchroots).

Mock isn't doing any magic with redhat.repo, or any other dnf/yum repositories.  It only gets the configuration files from /etc/mock/* directory.  If user tells `-r rhel-8-x86_64`, mock jus toperats with the `/etc/mock/rhel-8-x86_64.cfg` file  which transitivel brings `/etc/mock/templates/rhel-8.tpl`.  You can see there what repositories are used, and except for `--addrepo`, there's not much to do about that.

As you can see, `rhel-8.tpl` uses CDN repositories only.  Mock can not download from there without having the required SSL client certificate.  Therefore it is up to end-user to obtain the client certificate for mock, and the easiest way is to use `subscription-manager register` on host.

So all mock is doing is that it downloads, using dnf/yum, from CDN - from a precise set of repositories using your client certificate.  When bootstrap feature is enabled (and it is by default), mock uses dnf/yum from bootstrap chroot - and so
mock needs to one additional step - copy the client certificate into bootstrap chroot.  Mock never executes subscription-manager.

The reason why `redhat.repo` file is installed in bootstrap chroot is that mock installs `subscription-manager` into
the bootstrap chroot.  That package contains the default (all repos disabled) variant of `redhat.repo`.  If I remember correctly, mock does that because the packages brings stuff in `/etc/rhsm/ca` like `/etc/rhsm/ca/redhat-uep.pem`.
Yes, this isn't ideal  - the redhat-uep.pem file is owned by `subscription-manager-rhsm-certificates` (not by `subscription-manager`) and mock could surely just copy the needed file inside chroot instead of installing an additional (set of) package(s).
We can fix this, but I doubt it is what matters here.  Patches are welcome!

With all that said, we are unlikely to teach mock to call subscription-manager in bootstrap chroot (as long as we can not do this on host directly..). So mock can not easily guess the correct set of repositories.  If the local satellite repositories use the same patterns as the default CDN, we could implement some **configurable** template magic to substitute e.g. the hostname in the repourls.  Patches in this direction are welcome!

**Comment by dpward** [comment]
I agree with much of this, but a couple of points are not consistent with what I am seeing.

> So all mock is doing is that it downloads, using dnf/yum, from CDN - from a precise set of repositories using your client certificate. When bootstrap feature is enabled (and it is by default), mock uses dnf/yum from bootstrap chroot - and so
mock needs to one additional step - copy the client certificate into bootstrap chroot.

The file `/etc/rhsm/ca/katello-server-ca.pem` is not used when downloading from a CDN — it is only used when the host is registered with a Satellite server. Note the original issue description at the top of this page. Using the CDN was working fine without this file.

> Mock never executes subscription-manager.
> 
> The reason why `redhat.repo` file is installed in bootstrap chroot is that mock installs `subscription-manager` into
> the bootstrap chroot. That package contains the default (all repos disabled) variant of `redhat.repo`.

Mock is calling yum/dnf from the host to build the bootstrap chroot. The host may have the yum/dnf subscription-manager plugin installed and configured — and [unlike the 'local' and 'spacewalk' plugins](https://github.com/rpm-software-management/mock/blob/mock-2.9-1/mock/py/mockbuild/config.py#L305), mock does not disable the subscription-manager plugin when it runs yum/dnf.

The subscription-manager plugin will generate the file `/var/lib/mock/rhel-8-x86_64-bootstrap/root/etc/yum.repos.d/redhat.repo`; this happens **before** yum/dnf actually scans any repositories or installs the subscription-manager package inside the bootstrap chroot. I saw this file actually contain custom local repositories from the Satellite server. (Note again that you won't observe this behavior unless you manually change or remove [this line](https://github.com/rpm-software-management/mock/blob/mock-2.9-1/mock/py/mockbuild/package_manager.py#L428), which is deleting the /etc/yum.repos.d directory itself and not just its contents. I believe that is a bug since mock [explicitly creates](https://github.com/rpm-software-management/mock/blob/mock-2.9-1/mock/py/mockbuild/buildroot.py#L557) that directory in the buildroot prior to this.)
