### ISSUE TITLE
mockchain does not understand 'include' in mock configs

### ISSUE THREAD

**Issue by belegdol** [rpm-software-management/mock#65]
Hello,
it appears that mockchain is having issues parsing 'include' statements in mock config files. RPM Fusion mock config contains the following line:
`include('/etc/mock/fedora-rawhide-x86_64.cfg')`
using `-r fedora-rawhide-x86_64-rpmfusion_free` parameter works perfectly fine when using with standalone mock, but with mockchain the following happens:
`Traceback (most recent call last):`
`  File "/usr/bin/mockchain", line 416, in <module>`
`    sys.exit(main(sys.argv))`
`  File "/usr/bin/mockchain", line 298, in main`
`    res, msg = add_local_repo(config_opts['config_file'], my_mock_config, local_baseurl, 'local_build_repo')`
`  File "/usr/bin/mockchain", line 142, in add_local_repo`
`    exec(code)`
`  File "/etc/mock/fedora-rawhide-x86_64-rpmfusion_free.cfg", line 1, in <module>`
`    include('/etc/mock/fedora-rawhide-x86_64.cfg')`
`NameError: name 'include' is not defined`
This is with mock-1.3.4-1.fc25.noarch

Best regards,
Julian

**Comment by praiskup** [comment]
What if `add_local_repo()` generated `my_mock_config` using `include()` statement too, instead of copy-paste-and-edit the `config_opts['config_file']`?

**Comment by belegdol** [comment]
Would you be kind enough to create a patch I could test?

**Comment by praiskup** [comment]
@belegdol I'd like to (once the time permits), but I bet someone with higher motivation will be faster..? :)

**Comment by hobbes1069** [comment]
I'm running into this issue as well trying to do test chain builds for RPM Fusion. Since the site-defaults.cfg file specifically states this should work I would hope it would be more of a priority...

```
# It's possible to use include statement in order to make one config included to another:
# include('/path/to/included/config.cfg')
```

**Comment by garybuhrmaster** [comment]
In the case this is useful for one of the core team, while it probably is not the right solution (it includes the included config, rather than generating my_mock_config file with the copied include statement(s)), this at least seems to sort of work as a temporary workaround (code adapted from existing mock support for include support) for my simple test cases.

```
--- /usr/bin/mockchain	2017-09-15 21:32:30.000000000 +0000
+++ /tmp/mockchain	2017-10-22 23:51:15.440611984 +0000
@@ -127,6 +127,20 @@
     REPOS_ID.append(repoid)
     return repoid
 
+def include(config_file):
+    global config_opts
+    if os.path.exists(config_file):
+        if config_file in config_opts['config_paths']:
+            """ Skip multiple inclusion of config_file """
+            return
+        config_opts['config_paths'].append(config_file)
+        with open(config_file) as f:
+            code = compile(f.read(), config_file, 'exec')
+        # pylint: disable=exec-used
+        exec(code)
+    else:
+        print("Could not find included config file: %s" % config_file)
+        sys.exit(1)
 
 def add_local_repo(infile, destfile, baseurl, repoid=None):
     """take a mock chroot config and add a repo to it's yum.conf
```

**Comment by sergiomb2** [comment]
And I arrive here from here: https://pagure.io/FedoraReview/issue/286#comment-488571, fedora-review also breaks with includes ...

**Comment by sergiomb2** [comment]
The code that includes "include" is here [1] and here [2] is the minimum code that I could do to support the include . 

[1] https://github.com/rpm-software-management/mock/commit/2f147d08c1fced873246e163ed8552283dc5160f 

 [2]  [filename.py.txt](https://github.com/rpm-software-management/mock/files/1650640/filename.py.txt)

**Comment by sergiomb2** [comment]
can you test https://github.com/sergiomb2/mock/commit/5b4f37a8d1bc8e299f014fa90525fd45942f22cc ? please .  
In your machine , is just edit /usr/bin/mockchain  and replace the code .

Thanks

**Comment by xsuchy** [comment]
I marked mockchain as obsoleted. Starting from next version, you should use
  mock --chain
where this issue will not happen.
