### ISSUE TITLE
fedora-33-xyz.cfg: simple chroot couldn't resolve hosts

### ISSUE THREAD

**Issue by AkiraNorthstar** [rpm-software-management/mock#654]
### Short description of the problem
If you try to use a "simple" chroot with activated network, "Couldn't resolve host name" appears.

### Output of `rpm -q mock`

mock-2.6-1.fc32.noarch

### Steps to reproduce issue

1. Init a mock chroot with:
mock -r fedora-33-x86_64 --init --no-bootstrap-chroot --isolation=simple --enable-network

2. Build a package that needs additional dependencies from the internet during build (in this case): 
mock -r fedora-33-x86_64 --rebuild SRPMS/kodi-18.9.703-1.fc32.src.rpm --no-bootstrap-chroot --isolation=simple --enable-network

### Any additional notes

This behavior occurs under fedora 32 and fedora 33, regardless of whether you do this in a real system or inside a docker container. - If you take a fedora-33 configuration file.

With the same parameters, repositories, source rpms and with a fedora-32 configuration, it works smoothly.

My thought would be that in the "simple" chroot the resolution of domain names is currently not working properly.
"config_opts ['rpmbuild_networking'] = True" is apparently ignored, so I use --enable-network as a parameter.
Could the newly introduced systemd-resolved under fedora 33 be involved?

Best regards,
AkiraNorthstar a.k.a. Christian

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

INFO: mock.py version 2.6 starting (python version = 3.8.6)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'fedora:{{ releasever }}'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/fedora-33-x86_64-plus.cfg',
 '/etc/mock/templates/fedora-branched-plus.tpl']
config_opts['dist'] = 'fc{{ releasever }}'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f{{ releasever }}\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '# repos\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/f{{ releasever '
 '}}-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled={{ not mirrored }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if mirrored %}\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing]\n'
 'name=updates-testing\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=fedora-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-debuginfo]\n'
 'name=updates-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing-debuginfo]\n'
 'name=updates-testing-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-source]\n'
 'name=updates-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[fedora-modular]\n'
 'name=Fedora Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-source]\n'
 'name=Fedora Modular $releasever - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular]\n'
 'name=Fedora Modular $releasever - $basearch - Updates\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Updates - Debug\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-source]\n'
 'name=Fedora Modular $releasever - Updates Source\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/SRPMS/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 '[rpmfusion-free]\n'
 'name=RPM Fusion for Fedora $releasever - Free\n'
 '#baseurl=http://download1.rpmfusion.org/free/fedora/development/$releasever/Everything/$basearch/os/\n'
 'metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch\n'
 'enabled=1\n'
 'metadata_expire=1d\n'
 'gpgcheck=0\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever\n'
 'skip_if_unavailable=False\n'
 'exclude=kodi*\n'
 '\n'
 '[rpmfusion-free-updates]\n'
 'name=RPM Fusion for Fedora $releasever - Free - Updates\n'
 '#baseurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/\n'
 'metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch\n'
 'enabled=1\n'
 'gpgcheck=0\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever\n'
 'skip_if_unavailable=False\n'
 'exclude=kodi*\n'
 '\n'
 '[rpmfusion-nonfree]\n'
 'name=RPM Fusion for Fedora $releasever - NonFree\n'
 '#baseurl=http://download1.rpmfusion.org/nonfree/fedora/development/$releasever/Everything/$basearch/os/\n'
 'metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch\n'
 'enabled=1\n'
 'metadata_expire=1d\n'
 'gpgcheck=0\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever\n'
 'skip_if_unavailable=False\n'
 'exclude=kodi*\n'
 '\n'
 '[rpmfusion-nonfree-updates]\n'
 'name=RPM Fusion for Fedora $releasever - NonFree - Updates\n'
 '#baseurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/\n'
 'metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch\n'
 'enabled=1\n'
 'gpgcheck=0\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever\n'
 'skip_if_unavailable=False\n'
 'exclude=kodi*\n'
 '\n'
 '[fractalis-release]\n'
 'name=Fractalis $releasever - $basearch\n'
 'baseurl=https://repos.linux-ino.de/$releasever/$basearch/fractalis/\n'
 'enabled=1\n'
 'gpgcheck=0\n'
 'metadata_expire=10s\n'
 'failovermethod=priority\n'
 'priority=50\n'
 'skip_if_unavailable=True\n'
 '#exclude=kodi*\n'
 '\n'
 '[fractalis-updates]\n'
 'name=Fractalis $releasever - $basearch updates\n'
 'baseurl=https://repos.linux-ino.de/$releasever/$basearch/fractalis-updates/\n'
 'enabled=1\n'
 'gpgcheck=0\n'
 'metadata_expire=10s\n'
 'failovermethod=priority\n'
 'priority=50\n'
 'skip_if_unavailable=True\n'
 '#exclude=kodi*\n'
 '\n'
 '[fractalis-source]\n'
 'name=Fractalis $releasever - source\n'
 'baseurl=https://repos.linux-ino.de/$releasever/$basearch/fractalis-source/\n'
 'enabled=0\n'
 'gpgcheck=0\n'
 'metadata_expire=10s\n'
 'failovermethod=priority\n'
 'priority=50\n'
 'skip_if_unavailable=True\n'
 '#exclude=kodi*\n'
 '\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'enterprise.fritz.box',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.l8mxehl5:/etc/resolv.conf',
 '--bind=/dev/btrfs-control',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                     'root': 'fedora-33-x86_64-plus'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                 'compress': None,
                 'dir': '/var/cache/mock/fedora-33-x86_64-plus/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                 'root': 'fedora-33-x86_64-plus'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                      'root': 'fedora-33-x86_64-plus'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                        'root': 'fedora-33-x86_64-plus'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                  'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                  'root': 'fedora-33-x86_64-plus'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                   'root': 'fedora-33-x86_64-plus'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                'dirs': [],
                'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                'root': 'fedora-33-x86_64-plus'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                    'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                    'root': 'fedora-33-x86_64-plus'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                        'root': 'fedora-33-x86_64-plus'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                     'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                     'root': 'fedora-33-x86_64-plus'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                  'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                  'root': 'fedora-33-x86_64-plus'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/fedora-33-x86_64-plus/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                     'root': 'fedora-33-x86_64-plus',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                  'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                  'root': 'fedora-33-x86_64-plus'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                 'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                 'root': 'fedora-33-x86_64-plus'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
               'root': 'fedora-33-x86_64-plus'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                'root': 'fedora-33-x86_64-plus'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-33-x86_64-plus',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-33-x86_64-plus',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/fedora-33-x86_64-plus/result',
                    'root': 'fedora-33-x86_64-plus'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '33'
config_opts['root'] = 'fedora-{{ releasever }}-{{ target_arch }}-plus'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
Finish: run

</details>

Build.log:
[fedora-33-x86_64-build.log](https://github.com/rpm-software-management/mock/files/5487154/fedora-33-x86_64-build.log)

**Addendum:**
In the meantime I've played around a little and found that there is no /etc/resolv.conf in a fedora 33 build environment.

```Finish: build setup for test-1.2.3-666.fc32.src.rpm
Start: Outputting list of installed packages
Finish: Outputting list of installed packages
Start: rpmbuild test-1.2.3-666.fc32.src.rpm
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Rt2yXw
+ umask 022
+ cd /builddir/build/BUILD
+ cat /etc/hosts
127.0.0.1 localhost localhost.localdomain
::1       localhost localhost.localdomain localhost6 localhost6.localdomain6
+ cat /etc/resolv.conf
cat: /etc/resolv.conf: No such file or directory


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.Rt2yXw (%prep)
    Bad exit status from /var/tmp/rpm-tmp.Rt2yXw (%prep)
Finish: rpmbuild test-1.2.3-666.fc32.src.rpm
Finish: build phase for test-1.2.3-666.fc32.src.rpm
ERROR: Exception(SRPMS/test-1.2.3-666.fc32.src.rpm) Config(fedora-33-x86_64) 0 minutes 24 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-33-x86_64/result
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M cf393e1029554b08a6bd22c0b7731667 -D /var/lib/mock/fedora-33-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/dev/btrfs-control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/test.spec
```

This file is created / managed on a real system (since fedora 33) with systemd-resolved. This is retrospective for a build environment, as systemd-resolved is not started in a chroot. So /etc/resolv.conf is missing.

If you specify a bind-mount from /etc/resolv.conf (host) to /etc/resolv.conf (chroot), then everything works as intended.
```
config_opts['plugin_conf']['bind_mount_enable'] = True
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/etc/resolv.conf', '/etc/resolv.conf' ))
```

As already written above, this behavior can only be determined with a simple chroot.

A chroot with nspawn works fine and as expected.

[test.spec](https://github.com/rpm-software-management/mock/files/5500253/test.spec.txt)

**Comment by AkiraNorthstar** [comment]
fix config (fedora-33-x86 -> fedora-33-x86_64)

**Comment by praiskup** [comment]
Thank you for the report!

`cat: /etc/resolv.conf: No such file or directory`

Seems like when systemd is installed into the chroot, it replaces the resolv.conf file we pre-created by mock.
@msekletar can we somehow disable this behavior, or what are we expected to do in mock?

**Comment by praiskup** [comment]
(the /etc/resolv.conf is replaced with a symlink to non-existing destination, that's why `cat` says ENOENT)

**Comment by praiskup** [comment]
Probably the same problem reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1891423

**Comment by praiskup** [comment]
Probably better contact @keszybz, guessing by git blame in systemd.spec.

**Comment by praiskup** [comment]
https://src.fedoraproject.org/rpms/systemd/blob/5acb5c4c08f7fb8668f797b2b9a689a7be2b63c2/f/systemd.spec#_664-672

The thing is that `systemctl -q is-enabled systemd-resolved.service` ends with exit status 0 even in mock chroot.

**Comment by keszybz** [comment]
This should be fixed by the change I prepped for https://bugzilla.redhat.com/show_bug.cgi?id=1891847. It would be fixed already, but I can't build the new systemd version because of selinux blockage. But either way, this should be resolved within a few days.

**Comment by praiskup** [comment]
Ok, the test `if test -d /run/systemd/system/` will likely help.  Thank you.

**Comment by AkiraNorthstar** [comment]
Thanks for the great support.
Also a big thank you for the background informations, which I didn't know until now.

**Comment by praiskup** [comment]
> This should be fixed by the change I prepped for https://bugzilla.redhat.com/show_bug.cgi?id=1891847. It would be fixed already, but I can't build the new systemd version because of selinux blockage. But either way, this should be resolved within a few days.

How is the fix going?  Can you cite what selinux blockage you mean?

**Comment by praiskup** [comment]
@keszybz has this been fixed in systemd?

**Comment by keszybz** [comment]
Yes, that update with the fix for  https://bugzilla.redhat.com/show_bug.cgi?id=1891847 was built a while back (2020-12-10).

> Can you cite what selinux blockage you mean?

The selinux policy needed to be updated, it's all solved now.

**Comment by praiskup** [comment]
Ok, thanks.  Closing this issue then.
