### ISSUE TITLE
EPEL5 repos are broken

### ISSUE THREAD

**Issue by tkopecek** [rpm-software-management/mock#66]
All epel-5-*.cfg files contains urls which are no longer working as RHEL/CentOS 5 is EOLed. For core x86_64/i386 packages http://vault.centos.org/5.11/os/$arch/, http://vault.centos.org/5.11/updates/$arch/ could be used and epel from fedora archives https://archives.fedoraproject.org/pub/archive/epel/5/ $arch/ (which has also ppc version). 
`testing/local` repos should be removed completely?

**Comment by xsuchy** [comment]
Hmm, but since it is EOLed should we remove those files completely?

**Comment by tkopecek** [comment]
Yep, also makes sense.
Anyway, I would like to keep it alive (for koji copr build), but it probably makes more sense to kill them.

**Comment by praiskup** [comment]
Right, if those were removed, there's still space for package like `mock-eol-configs` or so; the question is whether Fedora Copr guys would be willing to support such mock configs :)

**Comment by xsuchy** [comment]
mirrors for epel5 still works, @ausil do you have idea how long it should work? Should I leave mirrors for epel5 or rather point it to https://archives.fedoraproject.org/pub/archive/epel/5/ ?

**Comment by ausil** [comment]
The epel mirrorlists will continue to work indefinitely. However the configs for epel 5 should just be removed entirely
