### ISSUE TITLE
libcap-ng 0.8.1 upgrade leads to weird errors with mock

### ISSUE THREAD

**Issue by fedya** [rpm-software-management/mock#661]
### Short description of the problem
libcap-ng 0.8.1 upgrade leads to weird errors with mock

### Output of `rpm -q mock`
mock-2.6-1.noarch

### Steps to reproduce issue

1. upgrade libcap-ng to 0.8.1
2. try to build something with mock
3. ERROR
```

Mon Nov 23 15:55:52 2020 LOG [INFO] | INFO: Mock Version: 2.5
Mon Nov 23 15:55:52 2020 LOG [INFO] | Start: dnf install
Mon Nov 23 15:57:31 2020 LOG [INFO] | Finish: dnf install
Mon Nov 23 15:57:32 2020 LOG [INFO] | ERROR: Exception(/home/omv/hdparm/hdparm.spec) Config(rosa2019.1-x86_64) 1 minutes 42 seconds
Mon Nov 23 15:57:32 2020 LOG [INFO] | INFO: Results and/or logs in: /home/omv/output
Mon Nov 23 15:57:32 2020 LOG [INFO] | ERROR: Command failed:
Mon Nov 23 15:57:32 2020 LOG [INFO] |  # /usr/sbin/groupadd -g 135 mock
Mon Nov 23 15:57:32 2020 LOG [INFO] |
Mon Nov 23 15:57:32 2020 LOG [INFO] | INFO: mock.py version 2.5 starting (python version = 3.8.5)...
Mon Nov 23 15:57:32 2020 LOG [INFO] | Start: init plugins
Mon Nov 23 15:57:32 2020 LOG [INFO] | WARNING: Tmpfs plugin disabled. System does not have the required amount of RAM to enable the tmpfs plugin. System has 15986.6953125MB RAM, but the config specifies the minimum required is 64000MB RAM.
```

it's every time failing at 
`/usr/sbin/groupadd -g 135 mock`
if i run by hands 
`/usr/sbin/useradd -o -m -u 135 -g 135 -d /var/lib/mock//rosa2019.1-x86_64/root mock`
everything fine. culrpit is libcap-ng, because of if i rollback it to 0.8 everything okay again.

And for some reasone in /var/lib/mock//rosa2019.1-x86_64/root/ i see a lot of coredumps, about ~500.

**Comment by xsuchy** [comment]
For the record, the 0.8.1 version is in rawhide only and there are two releases. 0.8.1-1 and 0.8.1-2. Which exact version cause this issue? Or both ones?

**Comment by tpgxyz** [comment]
@xsuchy we are talking about OpenMandriva Linux distribution. @fedya  tracked down that libcap-ng update causes mock issue.

**Comment by fedya** [comment]
@xsuchy OMV libcap-ng synced with fedora's one.

**Comment by praiskup** [comment]
I can not reproduce this with fedora chroots, we must be missing something.

Note that we execute the `grupadd` binary inside mock chroot, not on host.
So this problem shouldn't be affected by libcap-ng on Fedora Rawhide host.

Also note that you claim you have Mock 2.6, but the log says:
> Mon Nov 23 15:55:52 2020 LOG [INFO] | INFO: Mock Version: 2.5

There are two interesting patches in libbcap-ng, but as I said, that binary isn't called on Rawhide:
https://src.fedoraproject.org/rpms/libcap-ng/blob/49e3114cf75fabe9919300e42f7b151eee9e37d1/f/libcap-ng.spec#_9-10

> And for some reasone in /var/lib/mock//rosa2019.1-x86_64/root/ i see a lot of coredumps, about ~500.

If you see other coredumps, it is likely that groupadd in chroot fails with coredump, too.  Btw.,
I don't know what `rosa2019.1` chroot is, I bet you have to report bug there.

Possible cure can be `mock -r <your-rosa-chroot> --scrub=all` and re-try.

**Comment by fedya** [comment]
Probably problem not in mock. but somewhere else in thr system
libcap-ng upgraded causes screenshot:

![screenshot_2020-11-24-123541](https://user-images.githubusercontent.com/598477/100075894-9dd2d200-2e51-11eb-8dc3-e03fb6fb9198.png)

**Comment by praiskup** [comment]
> Probably problem not in mock. but somewhere else in thr system

What system do you mean?  My bet is the chrooted system, not the host system running mock.

**Comment by fedya** [comment]
I think issue in chrooted system too.

**Comment by fedya** [comment]
now again

```
DEBUG: ['/usr/bin/dnf', '--installroot', '/var/lib/mock//rosa2019.1-x86_64/root/', '--releasever', '0', '--refresh', '--disableplugin=local', '--setopt=deltarpm=False', '--forcearch=x86_64', '--disableplugin=local', '--disableplugin=spacewalk', 'install', 'basesystem-build']
INFO: Finish: dnf install
ERROR: Exception(/var/lib/mock//src/hdparm.spec) Config(rosa2019.1-x86_64) 0 minutes 44 seconds
INFO: Results and/or logs in: /var/lib/mock//rosa2019.1-x86_64/result
ERROR: Command failed:
 # /usr/sbin/groupadd -g 135 mock
```

```
[omv@b0ca2445d6d0 hdparm]$ sudo chroot /var/lib/mock//rosa2019.1-x86_64/root/
[root@b0ca2445d6d0 /]# /usr/sbin/groupadd -g 135 mock
[root@b0ca2445d6d0 /]# echo $?
0
[root@b0ca2445d6d0 /]#
```

it's not working invoked by mock, but everything okay if i run it manually

**Comment by fedya** [comment]
Culrpit is 
`config_opts['nosync_force'] = True`
Such option in ROSA and OMA is enabled by default and causes segfaults.

**Comment by praiskup** [comment]
Glad to hear you found the problem.  This appears to be problem in the non-default mock configuration,
so can I close this?
