### ISSUE TITLE
mock kuberntes question

### ISSUE THREAD

**Issue by odra** [rpm-software-management/mock#669]
### Short description of the problem

Not a problem but a question!

I am trying to run mock in a kubernetes container and I was taking look at some mock plugins.

I wanted to ask if those assumptions make sense before digging further into it.

I started to wonder if I would be able to add a new "isolation mechanism" specific for kubernetes/openshift but I thought that it might be better to raise this question here before digging further into it!

My basic idea would be something like this:

* create a pod from a given image;
* The pod becomes the isolated environment to run tasks
* tasks/commands would be executed by "bashing" into the pod container
* delete the pod after running everything

Do you think it would be possible to accomplish those basic requirements in a mock plugin?

Thanks!

**Comment by praiskup** [comment]
Thanks for the question!

If you want to implement something like `--isolation=kubernetes` (so mock goes and starts containers in kubernetes) I don't think it makes much sense.  The main reason why I think so is that you may run mock inside the container..., so if you can run a rootless (user-namespaced) "privileged" OCI container in your Kubernetes stack, you can just fine run the [mock process inside the container](https://github.com/rpm-software-management/mock/wiki#mock-inside-podman-fedora-toolbox-or-docker-container).

**Comment by praiskup** [comment]
> Do you think it would be possible to accomplish those basic requirements in a mock plugin?

No, at least not without rewriting the plugin concept.  So you would have to update the mock base code.

I mean, it would be an interesting kind-of research, and I believe it would be possible -  but it would be a really hard task.
You need to e.g. copy files to/from kube, mimic the bind-mounts from host, bootstrap, etc.  It is much easier to try to run mock in the POD.

**Comment by odra** [comment]
The problem is that mock is not the only process I am running in my current pod, also, if I understood correctly, it just uses chroot which is not as "secure" as nsspawn, which means that I would not be a good idea to run more than one "mocked process" per pod, correct?

**Comment by praiskup** [comment]
> The problem is that mock is not the only process I am running in my current pod,

Why not?  It sounds more secure if you dedicated one container run for one build, and throw it away.

>  also, if I understood correctly, it just uses chroot which is not as "secure" as nsspawn

Yes, but if you run mock in a container, there's no need to add another level of containerization.

**Comment by odra** [comment]
Yeah I was in doubt between "mock spawning containers" vs  "spawn one container per build", the later makes more sense to me as well.

Gonna close this issue since I got my answer, thanks for the quick reply  :-)

**Comment by xsuchy** [comment]
The general discussion is better to happen here: https://github.com/rpm-software-management/mock#communication

> "spawn one container per build"

This is what we do in Copr. We spawn a new VM per each build. Plus some optimizations (e.g., not respawn VM if next build is from the same user).

Technically you can create new isolation using docker. This was initially the idea when we started with nspwan. But it definitely cannot be done as a plugin. And utilizing nspawn took us a few years. And there was a hell of bugs about it. So using podman/Kubernets/docker as another isolation would be a multi-month project. And you will be on your own as we do not have resources/priorities for this.
