### ISSUE TITLE
Optional support for polkit (additionally to usermode)?

### ISSUE THREAD

**Issue by robert-scheck** [rpm-software-management/mock#684]
I wonder if there is a chance for optional polkit support (at least additionally to existing usermode support) at mock?

**Comment by xsuchy** [comment]
I tried that - not so long time ago. I hit the lack of documentation and IIRC lack of some features. After discussion with package maintainer of polkit, I decided to stay with usermode.

If anyone want to try to investigate current situation, file PR and discuss potentially missing features with polkit developers - feel free to do it.

**Comment by robert-scheck** [comment]
So what are the missing features at polkit?

**Comment by xsuchy** [comment]
IIRC we need to handle ENV. Propagate some, filter out some, set some.
