### ISSUE TITLE
bind_mount_opts doesn't work

### ISSUE THREAD

**Issue by Miceldars** [rpm-software-management/mock#687]
Hello

I use mock-2.8-1.el8.noarch on RHEL8. When I do mock --init, I need some directories to be mounted : they contain .pem files I need to access to yum repositories. But it seems mock doesn't even try to mount them.
I have the following in my config file : 

config_opts['plugin_conf']['bind_mount_enable'] = True
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/etc/dir1', '/etc/dir1/' ))
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/etc/dir2', '/etc/dir2/' ))
config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/etc/dir3', '/etc/dir3/' ))

When I look in the result/root.log, I don't see any mount command for those directories (and the --init fails when it tries to install package, because it doesn't find the pem files to access to the repositories). If I search "dir1" in all log files in the result dir, I don't find anything.

Thanks for your help

**Comment by Miceldars** [comment]
Solved by using config_opts['use_bootstrap'] = False

**Comment by praiskup** [comment]
The bind-mount plugin doesn't bind-mount to bootstrap chroot, but to the final
chroot and it works just fine.  So this behavior is kind of expected.

There are certain paths which we already copy/bind-mount into bootstrap in
order to make the pre-existing default `rhel-8-x86_64` chroot config work --
so perhaps we can tweak that concept and add something more?  What are
the directories we talk about?

**Comment by praiskup** [comment]
Entitlements/CA configuration for RHEL chroots is done here:
https://github.com/rpm-software-management/mock/blob/2ae77b8393174c78286197673c283e5a40b025fe/mock/py/mockbuild/util.py#L991-L1005
https://github.com/rpm-software-management/mock/blob/2ae77b8393174c78286197673c283e5a40b025fe/mock/py/mockbuild/buildroot.py#L316-L320

**Comment by Miceldars** [comment]
The directories are /etc/pki/entitlement and /etc/rhsm/ca/. I also mount /etc/pki/rpm-gpg/ for GPG-keys, but the error was on SSL connection.

**Comment by praiskup** [comment]
> I also mount /etc/pki/rpm-gpg/ for GPG-keys

Could you use /usr/share/distribution-gpg-keys/ perhaps?  Mock is automatically copying files from there.

> but the error was on SSL connection.

Then I guess some problem is with /etc/pki/entitlement ... can you try `mock --scrub=bootstrap -r <your config>`?  It may be some caching problem in bootstrap chroot.

**Comment by huapox** [comment]
ok with 


```bash
  config_opts['plugin_conf']['bind_mount_enable'] = True
  config_opts['plugin_conf']['bind_mount_opts']={
    'create_dirs': True,'dirs': [('/host/path', '/bind/mount/path/in/chroot/' )]
  }
```
