### ISSUE TITLE
Feature --use-bootstrap-image doesn't work in container

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#691]
Running mock in rootless container works fine by default, but the problem comes in el7 container, e.g. `podman run --rm -ti --privileged centos:7`.  EL7 RPM doesn't have the zstd compression, so we can not initialize bootstrap easily - we have to download the image.

But currently it fails like:
```
INFO: Using bootstrap image: fedora:rawhide
INFO: Pulling image: fedora:rawhide
time="2021-01-27T07:16:26Z" level=error msg="'overlay' is not supported over <unknown> at \"/var/lib/containers/storage/overlay\""
Error: could not get runtime: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver
ERROR: Command failed: 
 # podman pull fedora:rawhide
```

Perhaps we should use something which doesn't need overlayfs support;  we in Mock anyway only want to download tarball and extract it.

**Comment by praiskup** [comment]
Everything though could, in principle, be done without using Podman. We could download the
image manually, extract it, and install dnf with normal systemd-nspawn or man (2) chroot
abstraction (aka --isolation=nspawn|simple as with the other tasks we do).

**Comment by praiskup** [comment]
Hm, seems like Podman can now be run in Podman, per https://www.redhat.com/sysadmin/podman-inside-container (thanks @kdudka for the reference).

**Comment by praiskup** [comment]
Seems like this could help: https://github.com/containers/podman/issues/12657

IOW: Mount the image, copy (through tar??) the contents to a final bootstrap root directory the contents and install the package manager (util.do()).

**Comment by praiskup** [comment]
Said that, while podman container can be run "nested", it still requires some additional configuration, see https://github.com/containers/podman/blob/main/contrib/podmanimage/stable/Containerfile

All these steps are kind off too much for us to require for running Mock in container.  For mounting
the image - we already have a documented that `podman run --privileged` is needed.

**Comment by FrostyX** [comment]
Triage time: Wanted by covscan
