### ISSUE TITLE
Let --forcearch builds define %_mock_forcearch

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#697]
Context: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/IO2ZFXQ4ZSPT6DKG65OCPMZD35EF5WXS/

I think it would be useful if builds done with  `--forcearch` exposed the information to rpmbuild by defining a macro, e.g. `%_mock_forcearch`  (or any other name). So in that case, maintainers could do things like:

```
# The tests should fail the build if they run for 10+ minutes (or 100+ minutes on emulated arhcitecture)
%make_build tests TIMEOUT=600%{?_mock_forcearch:0}
```

**Comment by berrange** [comment]
I do wonder if it is worth making it a little more general purpose by exposing the notion of an environment performance multiplier.  Something that could define to "1" for native arches and "10" for emulated arches, but with the ablity of the admin to override it in the /etc/mock config files. eg I'm thinking that if "x86_64" sets the benchmark for native, then even a native s390x or arm7 builder might benefit from a x2 multiplier if the admin knows the hardware is particularly slow.

**Comment by xsuchy** [comment]
+1
I think we can call it `_platform_multiplier` as it can be even used for native builds. E.g. you can have Koji with armhpf with small  amount of memory and single core. And on such systems you may want to specify higher timeout. Even when they are build natively. I agree with settings in config file.

**Comment by hroncok** [comment]
performance multiplier is also an option, described in the thread. I've started with an easier option here.
