### ISSUE TITLE
mockchain: regression of local repo functionality from 1.3.4-1 to 1.4.1-1 on F25

### ISSUE THREAD

**Issue by xenithorb** [rpm-software-management/mock#70]
##### Command used: 

```
 mockchain -r fedora-25-x86_64 -l /tmp/myrepo  compat-libgcrypt-1.5.3-4.fc25.src.rpm brackets-1.9-1.fc25.src.rpm
```
(Note: changing -r or -l or not using -l has zero effect on the outcome. As well as using/not using: nosync, nspawn) 

##### Expected results with 1.3.4-1:

```
starting logfile: None
results dir: /tmp/myrepo/results/fedora-25-x86_64
config dir: /tmp/myrepo/configs/fedora-25-x86_64
Start build: compat-libgcrypt-1.5.3-4.fc25.src.rpm
building compat-libgcrypt-1.5.3-4.fc25.src.rpm
End build: compat-libgcrypt-1.5.3-4.fc25.src.rpm
Success building compat-libgcrypt-1.5.3-4.fc25.src.rpm
Start build: brackets-1.9-1.fc25.src.rpm
building brackets-1.9-1.fc25.src.rpm
End build: brackets-1.9-1.fc25.src.rpm
Success building brackets-1.9-1.fc25.src.rpm
Results out to: /tmp/myrepo/results/fedora-25-x86_64
Pkgs built: 2
Packages successfully built in this order:
compat-libgcrypt-1.5.3-4.fc25.src.rpm
brackets-1.9-1.fc25.src.rpm
```

##### Actual results with 1.4.1-1:
```
starting logfile: None
results dir: /tmp/myrepo/results/fedora-25-x86_64
config dir: /tmp/myrepo/configs/fedora-25-x86_64
Start build: compat-libgcrypt-1.5.3-4.fc25.src.rpm
building compat-libgcrypt-1.5.3-4.fc25.src.rpm
End build: compat-libgcrypt-1.5.3-4.fc25.src.rpm
Success building compat-libgcrypt-1.5.3-4.fc25.src.rpm
Start build: brackets-1.9-1.fc25.src.rpm
building brackets-1.9-1.fc25.src.rpm
INFO: mock.py version 1.4.1 starting (python version = 3.5.3)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(brackets-1.9-1.fc25.src.rpm)  Config(fedora-25-x86_64)
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
Start: unpacking root cache
Finish: unpacking root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.1
INFO: Mock Version: 1.4.1
Start: dnf update
Finish: dnf update
Finish: chroot init
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
Start: unpacking root cache
Finish: unpacking root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.1
INFO: Mock Version: 1.4.1
Start: dnf update
Finish: dnf update
Finish: chroot init
Start: build phase for brackets-1.9-1.fc25.src.rpm
Start: build setup for brackets-1.9-1.fc25.src.rpm
ERROR: Exception(brackets-1.9-1.fc25.src.rpm) Config(fedora-25-x86_64) 0 minutes 23 seconds
INFO: Results and/or logs in: /tmp/myrepo/results/fedora-25-x86_64/brackets-1.9-1.fc25
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: Command failed:
 # /usr/bin/systemd-nspawn -q -M 334f6fd37c7c403eaba83de2c3a74246 -D /var/lib/mock/fedora-25-x86_64-bootstrap-xenith-16011/root -a --setenv=TERM=vt100 --setenv=HOME=/builddir --setenv=SHELL=/bin/bash --setenv=LANG=en_US.UTF-8 --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=HOSTNAME=mock --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=LC_MESSAGES=C /usr/bin/dnf builddep --installroot /var/lib/mock/fedora-25-x86_64-xenith-16011/root/ --releasever 25 /var/lib/mock/fedora-25-x86_64-xenith-16011/root//builddir/build/SRPMS/brackets-1.9-1.fc25.src.rpm
Failed to synchronize cache for repo 'local_build_repo', disabling.
No matching package to install: 'compat-libgcrypt'
Not all dependencies satisfied
Error: Some packages could not be found.

End build: brackets-1.9-1.fc25.src.rpm
Error building brackets-1.9-1.fc25.src.rpm.
See logs/results in /tmp/myrepo/results/fedora-25-x86_64
Results out to: /tmp/myrepo/results/fedora-25-x86_64
Pkgs built: 1
Some packages successfully built in this order:
compat-libgcrypt-1.5.3-4.fc25.src.rpm
```

I didn't see any guidelines for logs, so I'm not really sure which ones you want! Please advise, thanks.

**Comment by xenithorb** [comment]
[mockchain_local_repo_fail.tar.gz](https://github.com/rpm-software-management/mock/files/983032/mockchain_local_repo_fail.tar.gz)

**Comment by xsuchy** [comment]
See https://github.com/rpm-software-management/mock/wiki#using-file-urls-in-configs

**Comment by xenithorb** [comment]
So mockchain is broken then? 

The whole point of mockchain is to give it two or more SRPMs and build them in series. 

Why isn't mockchain handling that? (the bind mounting)

Why hasn't the documentation been updated? 

Why did you close this ticket? It's a valid bug the command is broken as described in the manual.

**Comment by Frodox** [comment]
@xsuchy it should be noticed in Release Notes then, it is important change!
Can I still use `file://` in baseurls without systemd-nspawn and bootstrap options?

**Comment by xsuchy** [comment]
@Frodox I set --no-bootstrap-chroot as default (in master) as the proposed solution with bind mounting does not work either. So in next version it should work again (with default settings).

**Comment by spstarr** [comment]
Note this breaks the ability to build RPMs that require dependencies from other RPMs being built, for example building Mesa + LLVM/clang for i686 you need LLVM/clang built before you can build Mesa against the correct LLVM/clang libraries..

Please provide an example as to how to do this before closing this bug.

**Comment by xenithorb** [comment]
@xsuchy are you ever going to answer to these inquiries? Can you just remove mockchain altogether then if you're not going to support it?

**Comment by xsuchy** [comment]
@xenithorb ??? This issue happens only with the bootstrap feature turned on. This feature was enabled in mock 1.4.0, but I quickly disabled it in 1.4.1. So it should not happen right now unless you explicitly enable it. Therefore it is not the priority for me right now.

**Comment by xenithorb** [comment]
Ok understood, so to reiterate:

1. 1.4.0 enabled the bootstrap feature by default and you backtracked from that in 1.4.1 and now it is **off** for the time being 
2. This bug is affected by the bootstrap feature being on/off and it should work ok now, but should boostrapping be turned on later, it would then break again

Is that correct?

**Comment by xsuchy** [comment]
This issue will have to be resolved before this feature will be enabled on again. Definitelly
