### ISSUE TITLE
Mock kernel build leads to unbootable kernel

### ISSUE THREAD

**Issue by vvfedorenko** [rpm-software-management/mock#707]
### Output of `rpm -q mock`
<devvm>:~$ rpm -q mock
mock-2.9-1.el7.noarch

### Steps to reproduce issue

1. `mock -r epel-7-x86_64 --init`
2. `mock -r epel-7-x86_64 --update`
3. `mock -r epel-7-x86_64 --installdeps kernel-ml-5.10.16-1.el7.elrepo.nosrc.rpm`
4. `mock -r epel-7-x86_64 --no-clean kernel-ml-5.10.16-1.el7.elrepo.nosrc.rpm`

simple `rpmbuild -ba kernel-ml-5.10.spec` produces normal kernel which could be used to boot VM.
`kernel-ml-5.10.16-1.el7.elrepo.nosrc.rpm` could be downloaded from https://mirror.imt-systems.com/elrepo/archive/kernel/el7/SRPMS/
### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

INFO: mock.py version 2.9 starting (python version = 3.6.8, NVR = mock-2.9-1.el7)...
Start(bootstrap): init plugins
Finish(bootstrap): init plugins
Start: init plugins
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'registry.centos.org/centos:7'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = ('install @buildsys-build autoconf bc devtoolset-9 gd-devel libtool pcre-devel '
 'wget zlib-devel')
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/epel-7-x86_64.cfg',
 '/etc/mock/templates/epel-7.tpl',
 '/etc/mock/templates/centos-7.tpl']
config_opts['dist'] = 'el7'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'metadata_expire=0\n'
 'mdpolicy=group:primary\n'
 'best=1\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '{% set centos_7_gpg_keys = '
 "'file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7' %}\n"
 "{% if target_arch in ['ppc64le', 'ppc64'] %}\n"
 '{%   set centos_7_gpg_keys = centos_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-AltArch-7-' "
 '+ target_arch %}\n'
 "{% elif target_arch in ['aarch64'] %}\n"
 '{%   set centos_7_gpg_keys = centos_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7-aarch64' "
 '%}\n'
 '{% endif %}\n'
 '\n'
 '# repos\n'
 '[base]\n'
 'name=CentOS-$releasever - Base\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=os\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=CentOS-$releasever - Updates\n'
 'enabled=1\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=updates\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[extras]\n'
 'name=CentOS-$releasever - Extras\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=extras\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/os/\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fastrack]\n'
 'name=CentOS-$releasever - fasttrack\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=fasttrack\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 'enabled=0\n'
 '\n'
 '[centosplus]\n'
 'name=CentOS-$releasever - Plus\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 '\n'
 "{% if target_arch == 'x86_64' %}\n"
 '[centos-sclo-sclo]\n'
 'name=CentOS-$releasever - SCLo sclo\n'
 'baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/sclo/\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 "{% if target_arch in ['x86_64', 'ppc64le', 'aarch64'] %}\n"
 '[centos-sclo-rh]\n'
 'name=CentOS-$releasever - SCLo rh\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=sclo-rh\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 '[epel]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-7\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch\n'
 'enabled=0\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=testing-epel7&arch=$basearch\n'
 'failovermethod=priority\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel7-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-debug-7&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n')
config_opts['enable_disable_repos'] = []
config_opts['isolation'] = 'simple'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'repo.dev',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['package_manager'] = 'yum'
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-7-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/epel-7-x86_64/ccache/u1004/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                 'root': 'epel-7-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/epel-7-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                      'root': 'epel-7-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/epel-7-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                   'root': 'epel-7-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/epel-7-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64',
                     'tar': 'gnutar'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/epel-7-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                            'root': 'epel-7-x86_64'},
 'selinux_enable': False,
 'selinux_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-7-x86_64',
                 'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                 'root': 'epel-7-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/epel-7-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/epel-7-x86_64/result',
               'root': 'epel-7-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '7'
config_opts['root'] = 'epel-7-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['use_host_resolv'] = True
config_opts['use_nspawn'] = False
config_opts['verbose'] = 1
config_opts['yum_install_command'] = ("install yum yum-utils{% if target_arch in ['x86_64', 'ppc64le', 'aarch64'] "
 '%} --disablerepo=centos-sclo*{% endif %}')
Finish: run

</details>

**Comment by praiskup** [comment]
Thank you for the report!  But unfortunately, we are not able to provide reasonable
help here.  We are not kernel developers to decide where the build problem is.
This really needs some expert on kernel field to tell what caused the kernel package
miscompilation.

If this really is a problem in Mock (it is unlikely) - please provide a minimal reproducer,
using a supported configuration (something from mock-core-configs).
