### ISSUE TITLE
Stray check for config_opt instead of USE_NSPAWN or similar configuration value?

### ISSUE THREAD

**Issue by deryni** [rpm-software-management/mock#709]
I don't have a functionality bug to report about this but I was testing some "should be a no-op" configuration changes locally and noticed that using `--isolation=simple` (in both mock 2.6 and 2.9) resulted in _slightly_ different output from `--debug-config` than using `config_opts['isolation'] = simple` did.

From some quick poking around it looks like this bit of code
https://github.com/rpm-software-management/mock/blob/13391f03657add1a1ed1a857df1a08d8c7b87dde/mock/py/mockbuild/util.py#L834
is specifically checking the configuration value but the command line option doesn't set that.

I assume this should either check `USE_NSPAWN` or the config option parsing code should set `config_opts['isolation'] = simple` manually or something like that.

**Comment by praiskup** [comment]
Thanks for the report.

> using --isolation=simple (in both mock 2.6 and 2.9) resulted in slightly different output from --debug-config

We misuse the internal `config` dictionary (result of parsing of the config file tree) on many places to actually
reflect the command-line options.  Having a fix here is nice to have, though it would be a lot of work that we don't
have.  Feel free to submit a patch that fixes this.
