### ISSUE TITLE
rpkg is missing on f26+

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#71]
Mock scm plugin now depends on `rpkg` binary (and `copr-builder` too) to work with dist-git lookaside cache, but that script was removed from Fedora (see https://bugzilla.redhat.com/1400592).  IOW: starting from mock.fc26 this feature won't work as host machine won't have rpkg script available.

As I sort of agree that reintroducing `rpkg` package doesn't make much sense, I propose temporary work-around -> providing `rpkg` script as part of mock package.

Long term solution:  Koji (and Brew) uses `fedpkg-minimal` vs. `rhpkg-simple` packages. Those packages are installed _only_ for the purpose of building source RPM (those packages explicitly collide with `fedpkg` and `rhpkg` respectively.  So, ideally we should have something like `rpkg-minimal` package which would suite all: Koji, Brew, Copr, Mock...  So `rpkg-minimal` should be:
- written in shell (or very simple C), to allow installation into minimal buildroot without dependancy pollution)
- should have some trivial plug-in mechanism, so distributions can package upstream code and add one distribution-specific plugin file for distro-specific issues
- rpkg-minimal must be non-colliding with fedpkg, rpkg, rhpkg, and so on ... so instead of calling `/usr/bin/rpkg` one should explicitly ask for `/usr/bin/rpkg-minimal`.

@xsuchy, @clime, @pbabinca wdyt?

**Comment by pbabinca** [comment]
Fine with me. @tkdchen FIY.

**Comment by clime** [comment]
I am ok with rpkg-minimal.

**Comment by tkdchen** [comment]
Fine with me too.

What else can ``rpkg-minimal`` do besides downloading sources files from lookaside?

**Comment by clime** [comment]
I would like to see it launching builds in COPR.

**Comment by praiskup** [comment]
I mean -> `rpkg-minimal` should be really "minimal". Ideally, there should be no copr-related code (only distribution-specific code, as a plugin).

**Comment by clime** [comment]
From the point of mock-scm plugin, it only needs to be able to download sources.

Please, see also https://bugzilla.redhat.com/show_bug.cgi?id=1400592.

**Comment by praiskup** [comment]
@pbabinca, while `rpkg` package is probably needed -- asynchronously I'm thinking about "how to merge fedpkg-minimal and rhpkg-simple" idea.  What are the reasons to install those packages into "chroot" instead of having them installed on host (side-by-side with mock)?

**Comment by clime** [comment]
rpkg-client-0.8 (providing 'rpkg' command-line utitility) has been pushed to stable for Fedora. It will also be available on EPEL7.

**Comment by xsuchy** [comment]
So this should be resolved now.
