### ISSUE TITLE
CentOS 7, centos-7.tpl: All packages are exlcuded from centos-sclo-sclo

### ISSUE THREAD

**Issue by prymar56** [rpm-software-management/mock#710]
### Short description of the problem
In CentOS 7, centos-7.tpl, trying to use sclo-git212 or any other  package in the centos-sclo-sclo repo, everything is excluded.
Problem occurs in Copr or using mock locally.

### Output of `rpm -q mock`
mock-2.9-1.el8.noarch

### Steps to reproduce issue
yum repolist 
[mockbuild@c80pv:~/.config/mock]$ mock -r epel-7-x86_64 --yum-cmd list available --disablerepo=\* --enablerepo=centos-sclo-sclo
INFO: mock.py version 2.9 starting (python version = 3.6.8, NVR = mock-2.9-1.el8)...

Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start: cleaning package manager metadata
Finish: cleaning package manager metadata
INFO: enabled HW Info plugin
Mock Version: 2.9
INFO: Mock Version: 2.9
Finish: chroot init
No matches found for the following disable plugin patterns: local, spacewalk
CentOS-7 - SCLo sclo                                                  8.4 kB/s | 3.0 kB     00:00    
Finish: run

results in 0 packages found

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes
the offending line in the centos-7.tpl
includepkgs=devtool*
<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
 "{% if target_arch == 'x86_64' %}\n"
 '[centos-sclo-sclo]\n'
 'name=CentOS-$releasever - SCLo sclo\n'
 'baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/sclo/\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'

  </summary>

  PUT THE OUTPUT HERE
</details>

**Comment by praiskup** [comment]
Thank you for the report!

> In CentOS 7, centos-7.tpl, trying to use sclo-git212 or any other package in
> the centos-sclo-sclo repo, everything is excluded. Problem occurs in Copr or
> using mock locally.

This is expected behavior.  The chroot is supposed to be "Centos 7", not
sclo-centos7;  IOW we try to mimic the CentOS 7 + EPEL 7 build root that is used
inside Koji (or in CentOS build system), and the sclo repository is added only
to support the "external" DTS gcc (and friends).

So you can either create another config file, and re-add the same repository
once more without the `includepkgs=` filter, or e.g. use `--addrepo` option.
