### ISSUE TITLE
what is java-1.8.0-openjdk change to java-1.7.0-openjdk

### ISSUE THREAD

**Issue by gitlky9** [rpm-software-management/mock#714]
dear friends:
  I'm meed a bitter of things, and  building this package "felix-bundlerepository-1.6.6-15.el7.src.rpm" faited(used java-1.8.0-openjdk), that It changed  java-1.7.0-openjdk successed.
 Now, I need assign java-1.7.0-openjdk to  "felix-bundlerepository-1.6.6-15.el7.src.rpm", and why I to do......
 I wanted assign version of  package.

**Comment by praiskup** [comment]
Thank you for the question, but you probably wanted to raise a question in some
distribution specific channel, e.g. for Fedora I would use use https://discussion.fedoraproject.org/ 

This issue tracker is for problems with the mock tool (upstream), and we don't know the details about
the distribution you build for (or against) and we don't know the packages you are trying to build.

> I wanted assign version of package.

Normally mock installs the latest available version of the package in `BuildRequires`, but you may
add things like `BuildRequires: foo <= X.Y`.  See e.g. https://docs.fedoraproject.org/en-US/packaging-guidelines/#_buildrequires_and_isa

**Comment by gitlky9** [comment]
think you, my friend.
why the mock changing configure, and appoint  java-1.7.0-openjdk in configure file.

**Comment by gitlky9** [comment]
think you, my friend.
why the mock changing configure, and appoint java-1.7.0-openjdk in configure file.

**Comment by gitlky9** [comment]
> Thank you for the question, but you probably wanted to raise a question in some
> distribution specific channel, e.g. for Fedora I would use use https://discussion.fedoraproject.org/
> 
> This issue tracker is for problems with the mock tool (upstream), and we don't know the details about
> the distribution you build for (or against) and we don't know the packages you are trying to build.
> 
> > I wanted assign version of package.
> 
> Normally mock installs the latest available version of the package in `BuildRequires`, but you may
> add things like `BuildRequires: foo <= X.Y`. See e.g. https://docs.fedoraproject.org/en-US/packaging-guidelines/#_buildrequires_and_isa

think you, my friend.
why the mock changing configure, and appoint java-1.7.0-openjdk in configure file.
