### ISSUE TITLE
Doesn't work inside a CentOS 7 toolbox

### ISSUE THREAD

**Issue by cheese** [rpm-software-management/mock#715]
### Short description of the problem
Mock failed at bind mount when run inside a CentOS 7 toolbox. Maybe the version of util-linux is too low?

Output of `mock -r epel-7-x86_64 shell`

```
INFO: mock.py version 2.9 starting (python version = 3.6.8, NVR = mock-2.9-1.el7)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start(bootstrap): chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: enabled HW Info plugin
ERROR: Command failed: 
 # /bin/mount -n --rbind -o nodev,noexec,nosuid,readonly,rprivate /proc /var/lib/mock/epel-7-x86_64-bootstrap/root/proc
```

Output of `sudo /bin/mount -n --rbind -o nodev,noexec,nosuid,readonly,rprivate /proc /var/lib/mock/epel-7-x86_64-bootstrap/root/proc`

```
mount: wrong fs type, bad option, bad superblock on /proc,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

### Output of `rpm -q mock`
mock-2.9-1.el7.noarch

### Steps to reproduce issue

1. build a Toolbox-compatible image from `images/centos/7` of https://github.com/kronenpj/toolbox.git branch centos-7 as `localhost/centos-toolbox:7`
2. Create a toolbox: toolbox create --image localhost/centos-toolbox:7 centos-toolbox-7
3. toolbox enter centos-toolbox-7
4. sudo yum install -y epel-release
5. sudo yum install -y mock
6. mock -r epel-7-x86_64 shell

### Any additional notes

- mock works inside a Fedora 34 toolbox
- mock works inside a root podman privileged container

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>
config_opts['bootstrap_image'] = 'registry.centos.org/centos:7'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/epel-7-x86_64.cfg',
 '/etc/mock/templates/epel-7.tpl',
 '/etc/mock/templates/centos-7.tpl']
config_opts['dist'] = 'el7'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'metadata_expire=0\n'
 'mdpolicy=group:primary\n'
 'best=1\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '{% set centos_7_gpg_keys = '
 "'file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7' %}\n"
 "{% if target_arch in ['ppc64le', 'ppc64'] %}\n"
 '{%   set centos_7_gpg_keys = centos_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-AltArch-7-' "
 '+ target_arch %}\n'
 "{% elif target_arch in ['aarch64'] %}\n"
 '{%   set centos_7_gpg_keys = centos_7_gpg_keys + '
 "',file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7-aarch64' "
 '%}\n'
 '{% endif %}\n'
 '\n'
 '# repos\n'
 '[base]\n'
 'name=CentOS-$releasever - Base\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=os\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=CentOS-$releasever - Updates\n'
 'enabled=1\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=updates\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[extras]\n'
 'name=CentOS-$releasever - Extras\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=extras\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/os/\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fastrack]\n'
 'name=CentOS-$releasever - fasttrack\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=fasttrack\n'
 'failovermethod=priority\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 'enabled=0\n'
 '\n'
 '[centosplus]\n'
 'name=CentOS-$releasever - Plus\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/\n'
 'gpgkey={{ centos_7_gpg_keys }}\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 '\n'
 "{% if target_arch == 'x86_64' %}\n"
 '[centos-sclo-sclo]\n'
 'name=CentOS-$releasever - SCLo sclo\n'
 'baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/sclo/\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 "{% if target_arch in ['x86_64', 'ppc64le', 'aarch64'] %}\n"
 '[centos-sclo-rh]\n'
 'name=CentOS-$releasever - SCLo rh\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=sclo-rh\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-SIG-SCLo\n'
 'gpgcheck=1\n'
 'includepkgs=devtoolset*\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n'
 '\n'
 '[epel]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-7\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch\n'
 'enabled=0\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=testing-epel7&arch=$basearch\n'
 'failovermethod=priority\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel7-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-debug-7&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n')
config_opts['enable_disable_repos'] = []
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'toolbox',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.y2tz3cae:/etc/resolv.conf']
config_opts['package_manager'] = 'yum'
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-7-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/epel-7-x86_64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                 'root': 'epel-7-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/epel-7-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                      'root': 'epel-7-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/epel-7-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                   'root': 'epel-7-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/epel-7-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-7-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                        'root': 'epel-7-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/epel-7-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-7-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/epel-7-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                     'root': 'epel-7-x86_64',
                     'tar': 'gnutar'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/epel-7-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                            'root': 'epel-7-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-7-x86_64',
                  'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                  'root': 'epel-7-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-7-x86_64',
                 'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                 'root': 'epel-7-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/epel-7-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/epel-7-x86_64/result',
               'root': 'epel-7-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-7-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                'root': 'epel-7-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/epel-7-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-7-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/epel-7-x86_64/result',
                    'root': 'epel-7-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '7'
config_opts['root'] = 'epel-7-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
config_opts['yum_install_command'] = ("install yum yum-utils{% if target_arch in ['x86_64', 'ppc64le', 'aarch64'] "
 '%} --disablerepo=centos-sclo*{% endif %}')
</details>

**Comment by LyesSaadi** [comment]
I now have the same issue for a fedora-34 toolbox :/...

**Comment by praiskup** [comment]
Thank you for the reports, though I can not reproduce at least on fedora-34 toolbox.  I have an up2date fedora 34 box.

> build a Toolbox-compatible image from images/centos/7 of https://github.com/kronenpj/toolbox.git branch centos-7 as localhost/centos-toolbox:7

This is a long shot for me.  Don't you have the built image somewhere?

Honestly, if you want to use mock to build Fedora inside CentOS 7 toolbox - that's not a supported case.
Mock needs podman (container tooling) to actually make the Fedora builds on CentOS possible, but this
is not supported inside another containerization level (toolbox).

**Comment by praiskup** [comment]
Well, I'd like to reproduce - mostly out of curiosity (this is on the edge of our support) - but I fail to find the way how to generate the image..   maybe you can provide some more info here.

**Comment by LyesSaadi** [comment]
Hello,

So it seems my issue is unrelated to mock. My toolbox kind of corrupted itself somehow?

**Comment by LyesSaadi** [comment]
Never mind, it's still there. My toolbox issue is unrelated...

Also, creating a new toolbox still makes it fail...

**Comment by LyesSaadi** [comment]
Also, I discovered that downgrading mock to `mock-2.9-2.fc34.noarch` solves the issue.

**Comment by cheese** [comment]
> Also, I discovered that downgrading mock to `mock-2.9-2.fc34.noarch` solves the issue.

Also tested and failed with mock-2.11-1.fc34.noarch in fedora-34 toolbox. Downgraded version works.

**Comment by cheese** [comment]
May be related with #317

**Comment by praiskup** [comment]
I tested in Fedora 34 now, and I still can not reproduce this.  Default config, default mock mock-2.11-1.fc34.noarch.  Tested by:
```
mock --scrub=all && mock https://kojipkgs.fedoraproject.org//packages/mock/2.12/1.fc35/src/mock-2.12-1.fc35.src.rpm
```

**Comment by cheese** [comment]
The regression seems introduced in 163b24e77c

Skipping the mount with `remount` option works around the error:

```
diff --git a/mock/py/mockbuild/mounts.py b/mock/py/mockbuild/mounts.py
index f67871ea..f6cd7df7 100644
--- a/mock/py/mockbuild/mounts.py
+++ b/mock/py/mockbuild/mounts.py
@@ -112,8 +112,8 @@ class BindMountPoint(MountPoint):
         # Userspace must implement this as separate system calls anyway.
         if self.options:
             options = ','.join(['remount', self.options, bind_option])
-            util.do(['/bin/mount', '-n', '-o', options, self.srcpath,
-                     self.bindpath])
+            # util.do(['/bin/mount', '-n', '-o', options, self.srcpath,
+            #          self.bindpath])
         return True
 
     @traceLog()
```

**Comment by praiskup** [comment]
Thanks for bisecting, but apparently something is wrong with your environment - as
everything works just fine in my toolbox.  We need to understand why the remount
action fails (permissions, operation problem, filesystem problem), do you have more
info?  Could you perhaps report that problem against toolbox?

**Comment by debarshiray** [comment]
Thanks for sorting this out, @praiskup & @cheese!
