### ISSUE TITLE
gpg-agent keeps running after signing when using `sign` plugin

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/mock#718]
### Short description of the problem

gpg-agent keeps running after signing when using `sign` plugin.

Mock must ensure that it kills all its processes afterwards. I suppose this can be improved by the #717 but it probably would be good to have some solution even before that gets implemented.

### Output of `rpm -q mock`

`mock-2.9-1.el8.noarch`

### Steps to reproduce issue

1. Enable `sign` plugin (and configure it)
2. Try to build and RPM

### Any additional notes

In my specific case, I run it via Koji. But it is standard behavior of GPG. Even simple `rpmsign --addsign …` will keep it running.

```
kojibui+ 1354166  0.0  0.0 169016  1300 ?        Ss   19:39   0:00 gpg-agent --homedir /etc/rpm/.gnupg --use-standard-socket --daemon
```

**Comment by praiskup** [comment]
> Mock must ensure that it kills all its processes afterwards. 

If GPG people think it is the desired behavior, should we actually care?  As far as I understand it, it's not duplicated for subsequent /bin/gpg executions ... so it shouldn't really hurt us too much.

**Comment by praiskup** [comment]
I'm closing this for low motivation, at least for now.  We should IMO concentrate on #717
