### ISSUE TITLE
add CentOS Stream 9

### ISSUE THREAD

**Issue by TomasTomecek** [rpm-software-management/mock#719]
This is a request to add CentOS Stream 9 as a chroot to mock. Sadly, it seems this can't be fulfilled yet since the composes are not public. I just wanted to open this issue so people can subscribe and we can post more info here.

**Comment by sandrobonazzola** [comment]
Composes are public: https://composes.stream.centos.org/test/latest-CentOS-Stream/

**Comment by Conan-Kudo** [comment]
They are not GPG signed yet.

**Comment by TomasTomecek** [comment]
Is it a requirement to have them signed in order to include a config for Stream 9 in mock? I understand this could be improved in future once they become signed. (just checked and they are still not signed)

**Comment by xsuchy** [comment]
gpgcheck can be turned on later. The question is: is the URL final, will it be able to get the traffic?

**Comment by Conan-Kudo** [comment]
I believe that @bstinson is going to have it producing signed content from a stable (e.g. mirrorable) URL soon.

**Comment by Conan-Kudo** [comment]
I believe that @bstinsonmhk is going to have it producing signed content from a stable (e.g. mirrorable) URL soon.

**Comment by TomasTomecek** [comment]
Looks fixed to me :)

https://github.com/rpm-software-management/mock/releases/tag/mock-core-configs-34.5-1

Thanks, Pavel!
