### ISSUE TITLE
installing local packages into the buildroot broken since 1.4.1

### ISSUE THREAD

**Issue by decathorpe** [rpm-software-management/mock#72]
Installing local packages (i.e., `mock --install ./PACKAGE.rpm` doesn't work with `mock 1.4.1` (even with an absolute path), since dnf doesn't have access to the filesystem containing the file. For example, I get the following error (I chose the package only for demonstration purposes):

```
INFO: installing package(s): /home/deca/filesystem-3.2-40.fc26.x86_64.rpm
Last metadata expiration check: 0:00:00 ago on Tue May 09 16:39:56 2017 CEST.
Can not load RPM file: /home/deca/filesystem-3.2-40.fc26.x86_64.rpm.
Could not open: /home/deca/filesystem-3.2-40.fc26.x86_64.rpm
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M b9596376f5d54fadad45b4e64a0e66a3 -D /var/lib/mock/fedora-rawhide-x86_64-bootstrap/root -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 --setenv=LC_MESSAGES=C /usr/bin/dnf --installroot /var/lib/mock/fedora-rawhide-x86_64/root/ --releasever 27 --disableplugin=local --setopt=deltarpm=false install /home/deca/filesystem-3.2-40.fc26.x86_64.rpm
```

Installing packages from repositories still works as expected (for example, `mock install golang`), but local packages don't work anymore without reverting to the old behavior. This makes it impossible to build packages with dependencies that *aren't yet present in fedora repositores* with the new bootstrap environment.

Maybe local files should first be copied into the container's file system, where they can then be found and installed successfully?

**Comment by Frodox** [comment]
I'm sure it is corresponding to https://github.com/rpm-software-management/mock/wiki#using-file-urls-in-configs and workaround just same.
+1 that is is harder to test/use local in this case

**Comment by decathorpe** [comment]
As a side note, this change in behavior also broke tests executed by fedora-review (installing built packages in a mock chroot).

**Comment by mich181189** [comment]
As a workaround, you can use --no-bootstrap-chroot for the install command even if everything else is using the bootstrap chroot

Well, this seems to work for me anyway. I'll look at a proper fix if I get chance

**Comment by decathorpe** [comment]
Since the default behavior (`--no-bootstrap-chroot`) has been restored with one of the latest releases, this issue is moot.

**Comment by xsuchy** [comment]
I will keep it open as this need to be resolved. It has low priority thou.

**Comment by xsuchy** [comment]
I am going closing this in favour of https://bugzilla.redhat.com/show_bug.cgi?id=1447627
