### ISSUE TITLE
"mock --help" outputs "Usage: 4 [options]" instead of "Usage: mock [options]"

### ISSUE THREAD

**Issue by scfc** [rpm-software-management/mock#738]
On Fedora 33 and 34, `mock --help` outputs:

    [root@666197b30641 /]# mock --help | head -5
    Usage: 4 [options]
    
    Options:
      --version             show program's version number and exit
      -h, --help            show this help message and exit
    [root@666197b30641 /]#

The first line should probably be `Usage: mock [options]`.

**Comment by praiskup** [comment]
Agreed, I already started working on this .. but it is not a 2-minute thing as I thought :-( so I'll try to take a look later today.

**Comment by praiskup** [comment]
Eventually no, the problem was with the `__doc__` variable in the ` OptionParser(usage=__doc__, version=__VERSION__)` call.
But I still think we should move to argparse (but let's leave this for the next release).

**Comment by praiskup** [comment]
Oh, well, see also this report against usermode 1.114 https://bugzilla.redhat.com/show_bug.cgi?id=1969918
