### ISSUE TITLE
Add Rocky Linux 8

### ISSUE THREAD

**Issue by robert-scheck** [rpm-software-management/mock#745]
This is a kind request to ask whether Rocky Linux 8 could be added to the default mock configurations (similar like CentOS Linux currently is) from mock upstream perspective. Right now Rocky Linux upstream is not driving this forward themself, because they would like to finish a -devel repository first. But I guess it's still not wrong to ask already for a general opinion?

**Comment by Conan-Kudo** [comment]
Well, we already have AlmaLinux and OEL, so if PR shows up for Rocky, sure. But whoever contributes the Rocky one is on the hook for issues with it in the future.

**Comment by robert-scheck** [comment]
> But whoever contributes the Rocky one is on the hook for issues with it in the future.

Does this necessarily mean an individual person or could this also be a team (multiple persons)?

**Comment by Conan-Kudo** [comment]
Whoever contributes the mock configs is on the hook.

**Comment by xsuchy** [comment]
FYI rocky's gpg keys are in distribution-gpg-keys-1.55-1.fc34, which I just submitted to bodhi.

**Comment by Conan-Kudo** [comment]
Rocky Linux 8 configs are now included as of aa8d33062eff82bdc74735c644474455d927544b.
