### ISSUE TITLE
Drop the failovermethod=priority option from configs?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#752]
... from DNF-only configs?  Or from all configs?  Seems like DNF loudly warns it is a useless option nowadays, annoying.

Still, there's a chance that EL8 bootstrap chroot is installed by yum on EL7, and the default roundrobin may delay the installation.

Ideas?

**Comment by Conan-Kudo** [comment]
The risk is relatively low these days, I think it's fine to go ahead and drop it from everything.

**Comment by xsuchy** [comment]
+1
drop it

**Comment by praiskup** [comment]
I'll try to wait for some discussion in #755.

**Comment by praiskup** [comment]
Finally removed (in mock 3).  For the bootstrapping purpose, we keep this option in EL7 configs (YUM is used to install the chroots).
