### ISSUE TITLE
Freeze mock features for mock.rpm shipped in EPEL 7 in 2021

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#755]
Meaning that we will do releases that will be not available (not installable and non-working) on any EL7 variant.
This is not about removing a support for building software for EL7 (on newer releases).

Can you please give thumbs down, and argue if you strongly disagree?

**Comment by wolfy67** [comment]
In the company I work for we use commercial EDA tools ( with licenses worth 6 digits/year ) which are not available for anything newer than RHEL7. For uniformity and ease of maintenance,  it makes no sense to us to use some boxes on EL7 while others ( e.g. builders ) run something else.

**Comment by hroncok** [comment]
I don't know what "support policy" mock has, but what about releasing new versions for EL8+ only but keeping a bugfix-only branch for EL7\*? That way, users of mock on EL7 can keep using it until EPEL7 goes EOL and you don't need to worry about EL7 support in new releases.

\* Not all bugfixes need to be backported, just the ones reported by EL7 users, which could as well be 0.

**Comment by pajamian** [comment]
I'm quite sure that lots of people still use EL7 as a building platform, and considering that it doesn't go EOL for another four years what's the purpose of forcing these people to upgrade to EL8 now?  This is just sheer stupidity.

**Comment by gerdesas** [comment]
I'm not quite sure why you expect any of us to argue; this is a monumentally poor idea.  If you go this route you alienate _even more people_ on EL than Red Hat has already done.

**Comment by praiskup** [comment]
Sure, we are not going to remove Mock from EPEL 7.  And we are not going
to stop doing fixes there.  The proposal is to stop doing new releases with
new features. 

What @hroncok proposes sounds good to me.  I think we could wrap the last
2.x release that will be shipped to Fedora and EPEL 7, and then move to
3.x versioning that will not be available on EPEL 7.

We'll keep bugfixes in say `mock-2` branch, if any fixes are needed.
On a best effort basis, we could ship mock-core-configs in `mock-2` branch,
too.

**Comment by pajamian** [comment]
> Sure, we are not going to remove Mock from EPEL 7. And we are not going
> to stop doing fixes there. The proposal is to stop doing new releases.
> 
> What @hroncok proposes sounds good to me. I think we could wrap the last
> 2.x release that will be shipped to Fedora and EPEL 7, and then move to
> 3.x versioning that will not be available on EPEL 7.

I'm good with that, in fact stabilizing the version in EPEL 7 means that I don't have to work about my own tooling breaking when features are added down the line.

> We'll keep bugfixes in say `mock-2` branch, if any fixes are needed.
> On a best effort basis, we could ship mock-core-configs in `mock-2` branch,
> too.

I think we need to do this.  It would break mock 2 if we attempt to ship config files with it that are designed to take advantage of mock 3 features.

**Comment by Conan-Kudo** [comment]
> I'm quite sure that lots of people still use EL7 as a building platform, and considering that it doesn't go EOL for another four years what's the purpose of forcing these people to upgrade to EL8 now? This is just sheer stupidity.

To be blunt, your builders should be _further ahead_ of your production infrastructure, because building for the _past_ is easier than building for the _future_. For example, rich dependencies are used heavily in EL8 and EL9, and EL7 has _zero_ support for that. A lot of features to improve the isolation and performance of builds rely on features that exist only in EL8+.

In my case, I run my builders on Fedora, even if I'm mostly building for RHEL, because using RHEL to build Fedora packages just leads to weird or broken results.

**Comment by nkadel** [comment]
Please, retitle this. It looks like building for EL7 will be discarded, rather than building *on* EL7.

**Comment by nkadel** [comment]
I've been on a fedora-devel mailing list about this. EL7 is a primary industry standard for at least another 3 years. EL8 is *loathed* in many environments, for a stack of reasons described in various CentOS and RHEL mailing lists. And I see no technology reason why simply getting the SRPMs for mock v3 from epel-8, and rebuilding them for EL7, would not produce a working mock v3 set of tools. Is there a technology disparity? Some architectural hindrance? Or some conceptual architectural goal of "we don't want anyone to continue to use EL7, we want to compel them to EL8, because that is how Red Hat does things now"? That would seem to fly in the face of EPEL providing access to leading edge tools from Fedora.

**Comment by praiskup** [comment]
Re-titled, if that really makes you confused - even though I think you got
what this is about.  There's no point in slowing-down mock development
because of EL7.  Anyone is OK to invest the efforts/time/etc into bringing
mock fork in v3 onto EL7 platform, at least as long as reasonably?? possible.

No, EL7 should not be considered the primary choice for a build platform.
Older kernel, older RPM/YUM, older glibc/systemd/containers, and so on.
Mock users should move to newer systems.  There are many Mock hacks even
now, and more will have to come to keep everything working.  But I share
this sentiment, so fingers crossed!  Note even that **a lot** good new
features and compatibility work-hours had to happen in the recent Mock v2
versions so we can bootstrap Fedora chroots on EL7.

I don't like saying that, but please don't do attacks on this tracker, and
don't spread a FUD and conspiracy here.  It really feels so.

**Comment by nkadel** [comment]
Retitling helps clarify the issues, thank you very much.

I believe you that building F35 on EL7 had various adventures, I see the traces of some of them with the "podman" integration. Where is the v3 development, if anywhere? I'd be happy to give it a smoke test on EL7, to see if a desire not to backport to EL7 is something I can help address.

**Comment by praiskup** [comment]
At this moment, everything (to be) v3 == v2 == mock-2.16 (released last week).  So you can test just that.

During the next working week, we'll cut-out `mock-2` branch, which will only get bug fixes, if needed.

**Comment by Conan-Kudo** [comment]
Basically, consider mock-2.16 tag the branch point for Mock v2.

**Comment by xsuchy** [comment]
> And I see no technology reason why simply getting the SRPMs for mock v3 from epel-8, and rebuilding them for EL7, would not produce a working mock v3 set of tools. Is there a technology disparity?

Yes. There are. See commits 76f846b39df201ca7b1832c2f9746161e331497b 34fe0d5b80a12d3a7ebdcbe4f977dbf136dc54fa 500e005f05e557afa3c041657adcec1f91bb0903 5f265f16

And this is just an example of code that already got into code and we had to fix it. There are tons of ideas we would like to implement, but we cannot because EL7 cannot do that (no/old DNF, old rpm, old nspawn, ...)

**Comment by praiskup** [comment]
One can visualize the branching point:
```
$ git log --oneline --abbrev-commit origin/mock-2 origin/main --graph --decorate --color 89048fef..HEAD
... main continues here ...
* d663c220 (praiskup/main) Split Mock v3+ from v2
* 64f3ba84 Migrate from Travis CI to GitHub Actions
* a08e0e99 Test Python matrix via Fedora Tox container
| * 40be576f (origin/mock-2) Disable SECCOMP in Podman, too, and invent opt-in config
| * 6fe0b23a (tag: mock-core-configs-36.7-1) Automatic commit of package [mock-core-configs] release [36.7-1].
| * 306856ba config: Update CentOS Stream 9 Extras repo to use correct key
| * 7741d724 config: Add AlmaLinux+EPEL 8 for POWER (ppc64le)
| * 59a77159 config: Add AlmaLinux 8 for POWER (ppc64le)
| * 8ac18d1d Delete Fedora 37/Rawhide armhfp configs
| * b07fa4f3 (tag: mock-core-configs-36.6-1) Automatic commit of package [mock-core-configs] release [36.6-1].
| * 6d85c85f Add CentOS Stream 8 + EPEL 8 configs
| * f266abf6 github-actions: setup pull/push projects automatically
| * 6b30e6bb (tag: mock-core-configs-36.5-1) Automatic commit of package [mock-core-configs] release [36.5-1].
| * 1bc959c0 configs: move CentOS/EPEL 8 configs to eol/
| * 32dca3f1 configs: Fedora 36 branching
| * eb906abd configs: depend on distribution-gpg-keys 1.63
| * f3e4c7a5 config: Add Extras repo for CentOS Stream 9
| * 89b65a4e (michel-slm/mock-2) Split Mock v3+ from v2
| * 90a73cfd Migrate from Travis CI to GitHub Actions
| * d8b7aecc Test Python matrix via Fedora Tox container
|/  
* 1193912c (tag: mock-core-configs-36.4-1) Automatic commit of package [mock-core-configs] release [36.4-1].
* 578c444e (tag: mock-2.16-1) Automatic commit of package [mock] release [2.16-1].
* b91b9429 Update Release-Notes-2.16, mention them on index page
* a548c9ac tests: don't try to build mock in OracleLinux+EPEL 7
* 7c6e0f85 Typofix in Mageia 7 template
* 9011d816 tests: fix config testsuite
... common history ...
```
This proposal is already implemented, so closing.
