### ISSUE TITLE
[RFE] Support microdnf as a package manager

### ISSUE THREAD

**Issue by sgallagher** [rpm-software-management/mock#76]
When working with ultra-minimal environments such as the modularity base runtime, we do not have a complete yum or dnf implementation in the available repositories. Right now, we are working around this by disabling the new bootstrapping mechanism, but it would be vastly preferable if we could work with microdnf in the bootstrap chroot.

**Comment by Conan-Kudo** [comment]
@sgallagher Why not set `config_opts['system_dnf_command'] = '/usr/bin/microdnf'` in your mock config? That should allow you to do what you want.

**Comment by sgallagher** [comment]
I think I tried that and was told that microdnf wasn't a supported tool. Maybe that was a different option?

**Comment by Conan-Kudo** [comment]
You need at least mock 1.4.1. It doesn't work on older versions.

Also, separate issue is that microdnf needs to be slightly more graceful about `--setopt`.

```
[ngompa@mgacauldron-dev ~]$ mock -r mageia-cauldron-x86_64-microdnf.cfg microdnf-2-2.fc26.src.rpm
INFO: mock.py version 1.4.1 starting (python version = 3.5.3)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(microdnf-2-2.fc26.src.rpm)  Config(mageia-cauldron-x86_64)
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: mageia-cauldron-x86_64-microdnf.cfg newer than root cache; cache will be rebuilt
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.1
INFO: Mock Version: 1.4.1
Start: dnf install
error: (--setopt) Unable to handle: deltarpm=false
ERROR: Exception(microdnf-2-2.fc26.src.rpm) Config(mageia-cauldron-x86_64) 0 minutes 9 seconds
INFO: Results and/or logs in: /var/lib/mock/mageia-cauldron-x86_64/result
ERROR: Command failed:
 # /usr/bin/microdnf --installroot /var/lib/mock/mageia-cauldron-x86_64-bootstrap/root/ --releasever 6 --disableplugin=local --setopt=deltarpm=false install dnf dnf-plugins-core distribution-gpg-keys
error: (--setopt) Unable to handle: deltarpm=false
```

**Comment by Conan-Kudo** [comment]
Issue filed as rpm-software-management/microdnf/issues/22.

**Comment by Conan-Kudo** [comment]
I made [a PR to fix the issue with `--setopt`](https://github.com/rpm-software-management/microdnf/pull/23), but unfortunately microdnf doesn't support installing into an alternate root: rpm-software-management/microdnf/issues/19

**Comment by xsuchy** [comment]
I discussed that with Contyk from Modularity and he proposed that every Module should have as BuildRequire some module which contains DNF (or YUM). If you do that and pass that Module (and its repo to mockchain as `-a` it will became available in buildtime and DNF (or YUM) will be installed from that repo.

**Comment by Conan-Kudo** [comment]
I made a preliminary attempt to add support for this to microdnf: https://github.com/rpm-software-management/microdnf/pull/28

**Comment by ArrayMy** [comment]
#185
