### ISSUE TITLE
Missing use of $releasever?

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#769]
Should the hard-coded `8` in
https://github.com/rpm-software-management/mock/blob/9bdc2f1020047b9a14d72d4dc6a6aebd6dc6288a/mock-core-configs/etc/mock/templates/centos-8.tpl#L30 actually be `$releasever`?

Speaking of which, what is the least invasive way to specify an alternate `releasever` for, say, CentOS if one didn't want to build with the latest `8`?

**Comment by Conan-Kudo** [comment]
The template is for CentOS 8 itself, so being hard-coded isn't that big of a deal.

**Comment by xsuchy** [comment]
In configs, we always try to copy the original `.repo` files from distribution. It is not always possible. But unless the change brings big benefits, we copy from the original.
The least invasive change is to use your own config :) https://github.com/rpm-software-management/mock/wiki#generate-custom-config-file

**Comment by brianjmurrell** [comment]
Actually it seems there are many cases where `s/=8/=$releasever/g` could be used.  Interestingly this one https://github.com/rpm-software-management/mock/blob/9bdc2f1020047b9a14d72d4dc6a6aebd6dc6288a/mock-core-configs/etc/mock/templates/centos-8.tpl#L52 has it done correctly.

So at minimum, the use is inconsistent.  Even the commented out `baseurl`s use `$releasever`.

Same could be applied to https://github.com/rpm-software-management/mock/blob/9bdc2f1020047b9a14d72d4dc6a6aebd6dc6288a/mock-core-configs/etc/mock/templates/centos-7.tpl as it has a lot of `7`s hard-coded.
