### ISSUE TITLE
Install additional packages when building SRPM

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#774]
### Short description of the problem
It would be useful to be able to specify a list of packages to be installed in the chroot before building, exactly as if they were `BuildRequires:` specified in the specfile.  This could be used to build/test SRPMs that are in fact missing BR:s, in the least to narrow down missing BR:s without having to continually cycle through specfile edits and SRPM builds.

But also useful in rebuilding badly packaged SRPMs supplied from a third-party supplier, in the least while bug reporting to them and waiting for an updated release.

This would basically just be a streamlined [Building packages that depend on packages not in a repository](https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds#Building_packages_that_depend_on_packages_not_in_a_repository).

**Comment by praiskup** [comment]
There's `--config-opts=chroot_additional_packages=`, if that works I wouldn't add a special option.

**Comment by praiskup** [comment]
Patches are welcome, though, if it is really worth it.

**Comment by brianjmurrell** [comment]
`--config-opts=chroot_additional_packages=` is effectively what I am looking for, but it's pretty obscure and thus really only accessible to people intimate with `mock`.

That said, it doesn't seem to actually work when specifying an SRPM with `mock -r epel-8-x86_64 --config-opts=chroot_additional_packages=perl foo-1.2.src.rpm`.  foo's `configure` still finds `perl` missing.  The [Building packages that depend on packages not in a repository](https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds#Building_packages_that_depend_on_packages_not_in_a_repository) procedure confirms that installing `perl` makes `foo-1.2.src.rpm` build ok so clearly the `chroot_additional_packages` is not being effected when building an SRPM.

**Comment by praiskup** [comment]
Can you test the option `--build-requires` in #776.

**Comment by brianjmurrell** [comment]
Works well in a `--scrub=all`'d chroot.  Any other tests you want me to try?

**Comment by praiskup** [comment]
Cool, thanks for testing (`--scrub=all` shouldn'ŧ be needed).
