### ISSUE TITLE
Splitting stdout and stderr

### ISSUE THREAD

**Issue by fkluknav** [rpm-software-management/mock#8]
Currently, build.log contains both stdout and stderr. A possibility to either split them into separate logs or mark lines coming from stderr would be great.

Some compilers do not prefix their error messages with any fixed pattern. Searching for such messages in build.log is painful.

**Comment by xsuchy** [comment]
This is now merged. So closing.

**Comment by junaruga** [comment]
I suppose this change makes us to understand the order of below mixed stdout and stderr messages from the log?

For example, below example commands (named as program "foo")

```
$ (echo "stdout1" && echo 1>&2 "stderr1" && echo "stdout2")
stdout1
stderr1
stdout2
```

Below log simulates stdout's log file.

```
$ (echo "stdout1" && echo 1>&2 "stderr1" && echo "stdout2") 2> /dev/null
stdout1
stdout2
```

Below log simulates stderr's log file.

```
$ (echo "stdout1" && echo 1>&2 "stderr1" && echo "stdout2") > /dev/null
stderr1
```

How do we know the order of the below message from the stdout and stderr log files?

```
stdout1
stderr1
stdout2
```

**Comment by junaruga** [comment]
Sorry I did misunderstood this feature. This is to distinguish stdout and stderr message in a same log file by BUILDSTDERR mark.
