### ISSUE TITLE
Document minimum supported Python version

### ISSUE THREAD

**Issue by scop** [rpm-software-management/mock#80]
I cannot seem to find the minimum supported Python version specified/documented anywhere. One place where it could be added would be to make "Requires: python" in mock.spec versioned. No strong opinions as long as it's doumented somewhere where it can be found.

(grepping for 2. or sys.version doesn't yield anything useful, except a changelog entry of mine dropping pre 2.5 support, but I doubt the minimum supported version would be 2.5 nowadays).

**Comment by xsuchy** [comment]
Well. We do not support EL6 anymore. We build just for EL7. So that makes python2.7+
