### ISSUE TITLE
memory Issue with default path : /var/lib/mock/

### ISSUE THREAD

**Issue by srpatcha** [rpm-software-management/mock#81]
Please suggest the way to change Mock default path /var/lib/mock/ to my particular folder 
/source/user/mock
i tried creating cfg file to change  Path for where the chroot  builts
how to use option to change the path
config_opts[?]

**Comment by xsuchy** [comment]
See `man mock`:

-rootdir=ROOTDIR
              Path for where the chroot should be built. By default it is created in /var/lib/mock/<CONFIG>/root/.

I.e.:
`--rootdir=/source/user/mock`

**Comment by srpatcha** [comment]
awesome it worked today....i tried this when i was testing with different options. 
Thank you
