### ISSUE TITLE
bsdtar doesn't work with --use-bootstrap-image

### ISSUE THREAD

**Issue by justinvreeland** [rpm-software-management/mock#818]
### Short description of the problem
When specifying --use-bootstrap-image bsdtar fails because it reads from the default tape drive by default when there's no file specifier.

### Output of `rpm -q mock`
rpm -q mock
mock-2.12-2.fc35.noarch
### Steps to reproduce issue

1.  Use bsd tar for tar in you mock config (config['tar'] = 'bsdtar')
2.  Ensure there's no cached roots on your system for whichever config you're using, i cleared /var/{lib,cache}/mock/<rootname>
3. run: mock -r centos-8-x86_64 --use-bootstrap-image init

### Any additional notes

The error you'll receive is:
INFO: Copy content of container quay.io/centos/centos:8 to /var/lib/mock/centos-8-x86_64-bootstrap/root
bsdtar: Error opening archive: Failed to open '/dev/st0'

Followed later by:

execv(/usr/bin/dnf) failed: No such file or directory

This seems to be because the commands listed in podman.py don't account for differences between gnu and bsdtar and the image is never properly decompressed.

https://github.com/rpm-software-management/mock/blob/9ee8bb7a8f2edc2205c5f1b532b2f2eb923ea15e/mock/py/mockbuild/podman.py#L69

**Comment by praiskup** [comment]
So we should use `tar -x -C out -f -`, thank you for the report.
