### ISSUE TITLE
memory Issue with default path : /var/lib/mock/* #81

### ISSUE THREAD

**Issue by srpatcha** [rpm-software-management/mock#83]
Please suggest the way to change Mock default path /var/lib/mock/ to my particular folder
/source/user/mock
I tried this when i was testing with different options.these three folders inside : 
buildroot.lock
result
root

--rootdir=/source/user/mock is only creating root directory still default copy in /var/lib/mock/<CONFIG>root
 who creates buildroot.lock file ? 
I want everything inside  /var/lib/mock/* should move to /source/user/mock
help in this case. Could someone guide me a way
any change suggestion for .cfg

**Comment by xsuchy** [comment]
You can change it by:
```
config_opts['basedir'] 
```
in `.config/mock.cfg` or `site-defaults.cfg`
config_opts['basedir']  + /root/ can be  overriden by --rootdir
config_opts['basedir']  + /result/ can be  overriden by --resultdir
