### ISSUE TITLE
Env missing when bootstraping with podman

### ISSUE THREAD

**Issue by dani** [rpm-software-management/mock#831]
### Short description of the problem

Running on ALmaLinux 8.5, trying to build packages for AlmaLinux 8.5. My build server has no direct Internet access, and must use a proxy (those trying direct web access are intercepted and redirected to an error page, which produce a cert error for https, as expected). Relevant mock config :

```
config_opts['environment']['http_proxy'] = 'http://10.99.8.10:3128'
config_opts['environment']['https_proxy'] = 'http://10.99.8.10:3128'
config_opts['use_bootstrap_image'] = True
config_opts['bootstrap_image'] = 'docker.io/almalinux/almalinux:8'
```

When trying to build (mock -r almalinux-8-x86_64 mypackage.src.rpm)
```
INFO: mock.py version 2.15 starting (python version = 3.6.8, NVR = mock-2.15-1.el8)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: Start(patrix-0.1.12-1.el8.dbd.src.rpm)  Config(almalinux-8-x86_64)
Start: clean chroot
Finish: clean chroot
Start(bootstrap): chroot init
WARNING: nosync is enabled but the library wasn't found on the system
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: enabled HW Info plugin
INFO: Using bootstrap image: docker.io/almalinux/almalinux:8
INFO: Pulling image: docker.io/almalinux/almalinux:8
Trying to pull docker.io/almalinux/almalinux:8...
Getting image source signatures
Copying blob sha256:ba2c2d4a4d0ca1691970182077ace9c179f385b7d34d21680a1554639a3b82c7
Copying config sha256:6adabb67011e05c75e826c4cf37d5efc18ea3aeb57926a861a08d9671713b20d
Writing manifest to image destination
Storing signatures
6adabb67011e05c75e826c4cf37d5efc18ea3aeb57926a861a08d9671713b20d
AlmaLinux 8 - BaseOS                            0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'baseos':
  - Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://mirrors.almalinux.org/mirrorlist/8/baseos [SSL certificate problem: self signed certificate]
Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://mirrors.almalinux.org/mirrorlist/8/baseos [SSL certificate problem: self signed certificate]
ERROR: Exception(patrix-0.1.12-1.el8.dbd.src.rpm) Config(almalinux-8-x86_64) 0 minutes 11 seconds
INFO: Results and/or logs in: /var/lib/mock/almalinux-8-x86_64/result
ERROR: Command failed:
 # podman exec 98eba1ad480ee0d5e19ee3456cbfa3e29590fe0d5eef799b07503bff01729f25 /usr/bin/dnf -y install dnf dnf-plugins-core
```

I get the cert error, showing the proxy isn't used. It looks like the issue is that env vars aren't passed when creating the container (https://github.com/rpm-software-management/mock/blob/main/mock/py/mockbuild/podman.py#L29). They are passed just before (for podman pull) and just after (for podman exec), but not for the podman run.

If I change this line https://github.com/rpm-software-management/mock/blob/main/mock/py/mockbuild/podman.py#L29 to
```
        container_id = util.do(cmd, returnOutput=True, env=self.buildroot.env)
```
Then everything is working

### Output of `rpm -q mock`

mock-2.15-1.el8.noarch
mock-core-configs-36.3-1.el8.noarch

### Steps to reproduce issue

1. Run in an environment where a web proxy is mandatory
2. Set use_bootstrap_image = True
3. Build with AlmaLinux 8 as target (probably any el8 will be the same, but el7 doesn't have the problem for some reason)

**Comment by praiskup** [comment]
That said, I don't see how the environment for Podman command affects the **containerized command*-...
and neither I see how that can be related to ssl certifíicats **inside container**, but certainly don't
see any problem in specifying the env variables.

I also tried "clean environment":

    env -i PATH=/usr/bin podman run --rm -ti docker.io/almalinux/almalinux:8 bash

And DNF seems to work.

**Comment by dani** [comment]
Not sure either why passing the env to podman run is necessary (while they are already passed to the podman exec command just after), but at least in my env, it's the case. The cert validation error is specific to my environment though, but it just shows that dnf/yum isn't using the proxy.
