### ISSUE TITLE
Tag and discard, or discard, 10 year old branches

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#837]
### Short description of the problem

Various 9 year old or older branches clutter list of available branches.

### Steps to reproduce issue

Review list of available branches at:

    https://github.com/rpm-software-management/mock/issues/new

### Any additional notes

It's just cleanup, to avoid developers seeing or being confused by obsolete branches. Create matching tags first, if desired, for reference to obsolete branches in peculiar embedded git repo setups.

**Comment by praiskup** [comment]
Generally, no.  There's no better place to archive the history than the branches.

There's just one branch `gh-pages`, @xsuchy can that be removed?  In general
we shouldn't add more of them except for `mock-<version>` in the future.

Then there's `buildorder` which is referenced by an opened bug, and I don't really
see a better way to continue than leave the branch alone till some volunteer takes
a look at finishing that idea.

**Comment by nkadel** [comment]
Permit me, please, to disagree that "archiving history" in branches is helpful. And as really old branches, they're vulnerable to merges being attempted with dangerously obsolete software, and leaves CI/CD systems that test branches and bull requests vulnerable to unnecessary clutter. "mock" is pretty well behaved about it: I've recently encountered repos with more than 1500 branches that shattered CI/CD systems that tried to deal with rebuilds of ridiculously old branches.

**Comment by Conan-Kudo** [comment]
We can mark truly old branches as protected and block them from easily being merged into, but we're not deleting branches or tags.

**Comment by nkadel** [comment]
Please, do. I've elsewhere found it very effective to set aside such obsolete branches as tags, to achieve a similar effect.

**Comment by Conan-Kudo** [comment]
It will change nothing in your view of the repo, all it does is change things for us.

**Comment by xsuchy** [comment]
```
$ git push origin :gh-pages
To github.com:rpm-software-management/mock.git
 - [deleted]           gh-pages
```
It is gone. It was left over from setting up GitHub pages. We build it from main now.
