### ISSUE TITLE
mock-2.16 fails initializing fedora-35-x86_64.cfg on EL7

### ISSUE THREAD

**Issue by nkadel** [rpm-software-management/mock#840]
### Short description of the problem
mock-2.16 fails building fedora-35-x86_64.cfg on EL7

### Output of `rpm -q mock`
mock-2.16-0.el8.noarch

### Steps to reproduce issue

1. Build mock 2.16 and mock-core-config 36.4 with https://github.com/nkadel/mockrepo
2. Install updated mock and mock-core-configs on CentOS 7
3. mock -r /etc/mock/fedora-35-x86_64.cfg init

### Any additional notes

The init command for fedora 35 fails on CentOS 7. It works fine on CentOS 8 Stream and on Fedora 35 with the updated mock and mock-core-configs.

Getting image source signatures
Copying blob sha256:4545346f2a492b62d5a82682efe19b0e8e7583d5c19f75a74c81d62ec536c32d
Copying config sha256:3059bef432ebb91a6a51d8f5cf20b033041dbddb3cab79628c1eb3412cbde0ae
Writing manifest to image destination
Storing signatures
3059bef432ebb91a6a51d8f5cf20b033041dbddb3cab79628c1eb3412cbde0ae
Fedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: non zero exit code: 1: OCI runtime error
ERROR: Command failed: 
 # podman exec 41020af97fc6c7e4ae9a097cbceb87b17d1c5510723c0c7eb78ed1844dd49f57 /usr/bin/dnf -y install dnf dnf-plugins-core

**Comment by praiskup** [comment]
> mock-2.16-0.el8.noarch

This doesn't look like el7 package?

**Comment by nkadel** [comment]
Sorry, I had two windows upen. Put "rpm -q mock" in the wrong window! The full transcript is:

`[nkadelgarcia@nkadel-c7-1 mock]$ rpm -q mock
mock-2.16-0.el7.noarch
[nkadelgarcia@nkadel-c7-1 mock]$ mock -r /etc/mock/fedora-35-x86_64.cfg init
INFO: mock.py version 2.16 starting (python version = 3.6.8, NVR = mock-2.16-0.el7)...
INFO: Using 'yum' instead of 'dnf' for bootstrap chroot
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
Finish: clean chroot
Start(bootstrap): chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled package manager cache
Start(bootstrap): cleaning package manager metadata
Finish(bootstrap): cleaning package manager metadata
INFO: enabled HW Info plugin
INFO: Using bootstrap image: registry.fedoraproject.org/fedora:35
INFO: Pulling image: registry.fedoraproject.org/fedora:35
Trying to pull registry.fedoraproject.org/fedora:35...
Getting image source signatures
Copying blob sha256:4545346f2a492b62d5a82682efe19b0e8e7583d5c19f75a74c81d62ec536c32d
Copying config sha256:3059bef432ebb91a6a51d8f5cf20b033041dbddb3cab79628c1eb3412cbde0ae
Writing manifest to image destination
Storing signatures
3059bef432ebb91a6a51d8f5cf20b033041dbddb3cab79628c1eb3412cbde0ae
Fedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64&countme=1 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: non zero exit code: 1: OCI runtime error
ERROR: Command failed: 
 # podman exec f26ca35784fdb60c3336f965688be8971deb9834af116cf81a8e2c66065dc025 /usr/bin/dnf -y install dnf dnf-plugins-core

`

**Comment by nkadel** [comment]
This has been going on since f35 was listed among mock-core-configs for EL7: I'd hoped the various EL7 fixes for mock-2.16 might have addressed it.

**Comment by praiskup** [comment]
Indeed, reproducible.  This should be fixed in podman likely :-/ the seccomp.json rules.  I checked that `--privileged` works.
I'll try to forward this upstream.

**Comment by Conan-Kudo** [comment]
This is the same issue that affects running EL9 builds on EL7. Both Podman and Docker on EL7 is affected.

**Comment by praiskup** [comment]
I tried to report this: https://bugzilla.redhat.com/show_bug.cgi?id=2034209
This is a work-around:
```
diff --git a/mock/py/mockbuild/podman.py b/mock/py/mockbuild/podman.py
index 44901f33..ae1976a5 100644
--- a/mock/py/mockbuild/podman.py
+++ b/mock/py/mockbuild/podman.py
@@ -25,7 +25,7 @@ class Podman:
     @traceLog()
     def get_container_id(self):
         """ start a container and detach immediately """
-        cmd = ["podman", "run", "--quiet", "-i", "--detach", self.image, "/bin/bash"]
+        cmd = ["podman", "run", "--privileged", "--quiet", "-i", "--detach", self.image, "/bin/bash"]
         container_id = util.do(cmd, returnOutput=True, env=self.buildroot.env)
         self.container_id = container_id.strip()
         return self.container_id
```

So perhaps we could ship that patch in mock-2.17, if needed...

**Comment by praiskup** [comment]
Note that we execute podman as under root user (insecure), so adding `--privileged` isn't a wise
think to do in general:
- in v3.X we should start using non-root podman
- in v2.X we can accept --privileged, as RHEL 7 is in `Maintenance Support 2 Phase` thus Podman from extras is not very likely to receive the update (IMVHO)

Of course, this is not blocking the mock 2.16 update, it's not **a new problem/bug** in Mock.

**Comment by Conan-Kudo** [comment]
> in v3.X we should start using non-root podman

I don't think we can do this, given the other constraints we have around volume mounts and networking. If Mock always ran under its own user and owned all of its own directories, we probably could do this.

**Comment by nkadel** [comment]
The patch seems to work well on EL7. Good!

**Comment by praiskup** [comment]
> I don't think we can do this, given the other constraints we have around volume mounts and networking.

The only thing we do using `podman exec`/`podman run` is `dnf install dnf-plugins-core`.  Then we extract
the tarball using `podman export`, and any follow-up actions are done using `systemd-nspawn`.

**Comment by Conan-Kudo** [comment]
Oh, then we're fine, yeah.

**Comment by praiskup** [comment]
Fixed in `mock-2` branch. [40be576](https://github.com/rpm-software-management/mock/commit/40be576fe4c37788d32b270c7f01368e7abb778e)
