### ISSUE TITLE
Incomplete `df -H` ouptut from hw_info plugin?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#849]
In Fedora Copr, the Storage info provided by hw_info is too short:
```
Storage:
Filesystem         Size  Used Avail Use% Mounted on
mock_chroot_tmpfs  151G  706M  150G   1% /var/lib/mock/fedora-rawhide-ppc64le-1641189118.903741/root
```

E.g. https://download.copr.fedorainfracloud.org/results/@fedora-llvm-team/llvm-snapshots/fedora-rawhide-ppc64le/03122011-mlir/hw_info.log.gz

**Comment by xsuchy** [comment]
note, we should report /var/cache/mock and likely a few others. (if they are on different volume)
