### ISSUE TITLE
Docs: missing 'Using file:// URLs in configs' section

### ISSUE THREAD

**Issue by jmlich** [rpm-software-management/mock#850]
It looks like, there is an dead link in documentation: https://rpm-software-management.github.io/mock/#using-file-urls-in-configs

Unfortunately, I wasn't able to find required information in history.

**Comment by praiskup** [comment]
Thank you for the report!

This is how the link destination looked before (when we had the docs on GitHub wiki):
https://github.com/rpm-software-management/mock/wiki/Home/_compare/bd7efb5bc0bac036151844ee0c698fb628554eb2...d3ded16a7aa23c833f88b4e2639864f8b9f448af

You can calmly use file:// repositories now.
