### ISSUE TITLE
mock config for alma+epel-8 has issue with gpg keys when running on EL7

### ISSUE THREAD

**Issue by CamJN** [rpm-software-management/mock#877]
### Short description of the problem

Trying to rebuild a src rpm, in an alma+epel-8 mock env throws a missing key issue while it is installing gnupg2-2.2.20-2.el8.x86_64

### Output of `rpm -q mock`

`mock-2.16-1.el7.noarch`

### Steps to reproduce issue

1. install mock from epel 7 on centos 7
2. add `config_opts['chroot_setup_cmd'] += ' selinux-policy'` to the end of `/etc/mock/alma+epel-8-x86_64.cfg`
3. run `/usr/bin/mock --verbose  -r alma+epel-8-x86_64 --resultdir '/work/el8-x86_64' --uniqueext passenger-el8-x86_64 --enable-plugin=ccache rebuild /work/el8-x86_64/passenger-6.0.13-1.el8.src.rpm` (i assume you can just sub in any src rpm for this purpose, and don't need mine, but i can provide it if needed).

### Any additional notes

<details>
  <summary>
    <p>Output of <code>mock --debug-config</code></p>
  </summary>
<pre>
WARNING: config_opts['use_bootstrap_container'] is deprecated, please use config_opts['use_bootstrap'] instead
INFO: mock.py version 2.16 starting (python version = 3.6.8, NVR = mock-2.16-1.el7)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
ERROR: Namespace unshare failed.
</pre>
</details>

<details>
  <summary>
    <p>Truncated output of <code>/usr/bin/mock --verbose  -r alma+epel-8-x86_64 --resultdir '/work/el8-x86_64' --uniqueext passenger-el8-x86_64 --enable-plugin=ccache rebuild /work/el8-x86_64/passenger-6.0.13-1.el8.src.rpm</code></p>
  </summary>
<pre>
Transaction Summary
     ================================================================================
     Install  2 Packages (+121 Dependent packages)

     Total download size: 51 M
     Installed size: 175 M
     Downloading packages:
     warning: /cache/mock_lib/alma+epel-8-x86_64-bootstrap-passenger-el8-x86_64/root/var/cache/yum/baseos/packages/audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID c21ad6ea: NOKEY
     Public key for audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64.rpm is not installed
     --------------------------------------------------------------------------------
     Total                                               18 MB/s |  51 MB  00:02     
     Retrieving key from file:///usr/share/distribution-gpg-keys/alma/RPM-GPG-KEY-AlmaLinux
     Importing GPG key 0x3ABB34F8:
      Userid     : "AlmaLinux <packager@almalinux.org>"
      Fingerprint: 5e9b 8f56 17b5 066c e920 57c3 488f cf7c 3abb 34f8
      From       : /usr/share/distribution-gpg-keys/alma/RPM-GPG-KEY-AlmaLinux

     Public key for gnupg2-2.2.20-2.el8.x86_64.rpm is not installed

      Failing package is: gnupg2-2.2.20-2.el8.x86_64
      GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/alma/RPM-GPG-KEY-AlmaLinux

 \*\*\* Command failed: /usr/bin/mock --verbose  -r alma+epel-8-x86_64 --resultdir '/work/el8-x86_64' --uniqueext passenger-el8-x86_64 --enable-plugin=ccache rebuild /work/el8-x86_64/passenger-6.0.13-1.el8.src.rpm
</pre>
</details>

**Comment by CamJN** [comment]
I guess this is the same as https://bugzilla.redhat.com/show_bug.cgi?id=2017069

**Comment by Conan-Kudo** [comment]
Does working with dnf instead for the bootstrap chroot fix the issue?

**Comment by CamJN** [comment]
`config_opts['package_manager'] = 'dnf'` is already set in the `/etc/mock/alma+epel-8-x86_64.cfg` (by way of `/etc/mock/templates/almalinux-8.tpl`) is there something else to do to make that change?

**Comment by Conan-Kudo** [comment]
Oh sorry, yeah, I mean does using the bootstrap image fix the issue. You can trigger this with `--use-bootstrap-image`.

**Comment by CamJN** [comment]
That gives me `FileNotFoundError: [Errno 2] No such file or directory: 'podman': 'podman'` probably because of `DEBUG: Executing command: ['podman', 'pull', 'quay.io/almalinux/almalinux:8'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False` 

And since (in my case) this is already all running inside a docker container, trying to run podman is probably going to be difficult.

**Comment by Conan-Kudo** [comment]
Well if you're already running in a Docker container, then don't use EL7. Try an EL8 or EL9 container?

**Comment by CamJN** [comment]
I think that might introduce other issues with the other steps in our automation. Anyway, I managed to get rocky linux working in mock so I think i'll be fine rebuilding using that instead. Hopefully if someone else has this issue your suggestions can help them.

**Comment by xsuchy** [comment]
I am afraid there is nothing we can do. I pinned it to issues as a known issue. The workaround may be to use `rocky+epel-8-x86_64` config. Or in `/etc/mock/templates/almalinux-8.tpl` disable `gpgcheck`. Or the host where mock is running to RHEL8 or newer.

**Comment by praiskup** [comment]
> I think that might introduce other issues with the other steps in our automation.

I agree with @Conan-Kudo here, and I would really advise you to switch over to newer containers.
Building on EL7 (even non-containerized) has a lot of problems with newer distributions, and there
are no good reasons to stay there.  Running mock in EL7 container is not tested use-case.
