### ISSUE TITLE
mock doesn't inherit proxy settings for "mockbuild" user

### ISSUE THREAD

**Issue by arrfab** [rpm-software-management/mock#883]
### Short description of the problem
We use koji to build packages, and we have to suddenly let our builders access remote git repositories, not in the internal vlan where the build happen. While we don't use default route to reach internet (for obvious reasons) on our koji builders, we wanted to explore the http_proxy and https_proxy variables, to ensure that it would reach (allowed) URLs to do the git checkout.
Unfortunately, while config is set in site-defaults.cfg, or though env variables directly, it's not preserved for the "mockbuild" user created in the buildroot by koji, and so can't do a simple "git clone <url>" as https_proxy isn't set

### Output of `rpm -q mock`

mock-2.8-1.el8.noarch

### Steps to reproduce issue

Here is the snippet from site-defaults.cfg and how it doesn't work for mockbuild user :

```
cat /etc/mock/site-defaults.cfg 
# Managed by ansible
config_opts['http_proxy'] = 'http://proxy.domain:8080'
config_opts['https_proxy'] = 'http://proxy.domain:8080'
```

Trying now the mock call to just have a shell : 

```
mock -r /etc/mock/infra9s-infra-common-el9s-build.cfg --isolation=simple shell 
```

<mock-chroot> sh-5.1# set |grep -i proxy
http_proxy=http:/proxy.domain:8080
https_proxy=http://proxy.domain:8080
<mock-chroot> sh-5.1# su - mockbuild 
Last login: Tue Mar 22 14:36:22 UTC 2022
[mockbuild@x86-1 ~]$ set |grep -i proxy

```

**Comment by xsuchy** [comment]
???
When you do `su -` (in your reproducer) you explicitly say to drop all environment variables (it is alias to --login)

When I try:

```
$ export http_proxy=foo
$ mock shell
<mock-chroot> sh-5.1# echo $http_proxy
foo
^D
$ mock --unpriv shell
<mock-chroot> sh-5.1$ echo $http_proxy
foo
<mock-chroot> sh-5.1$ id
uid=1000(mockbuild) gid=135(mock) groups=135(mock)
^D
```
I see no problem.

**Comment by xsuchy** [comment]
Hmm, in your reproducer, you have to use `--enable-network` to use network. Otherwise, the network is disabled. With simple isolation, it means just DNS resolution is switched off in etc/host, but in nspawn it is more complex.

**Comment by arrfab** [comment]
I'll try again with koji directly (was trying with mock shell to see why it wasn't obeying https_proxy in our koji builds). worth knowing that we have network enabled, and use --isolation=simple but I'll give it another try.
When I tested in koji, I saw in proxy log that all rpm packaged (to init the buildroot) were downloaded through proxy, but the scm checkout (doing git clone) wasn't even trying, and through mock logs one can see that it's using some http_proxy/https_proxy for some commands but not for the others.

**Comment by arrfab** [comment]
Have to search deeper, as it works indeed fine with mock shell, but probably the way koji creates the buildroot is the issue.
From root.log left behind in koji task, I see clearly that it's using https_proxy in *some* (but not all) command :
But in checkout.log, it's just showing 
```
$ git clone -n https://git.centos.org/rpms/time.git /var/lib/mock/infra9s-infra-common-el9s-build-94560-893767/root/chroot_tmpdir/scmroot/time
Cloning into '/var/lib/mock/infra9s-infra-common-el9s-build-94560-893767/root/chroot_tmpdir/scmroot/time'...
fatal: unable to access 'https://git.centos.org/rpms/time.git/': Couldn't connect to server
```
Still trying to see the diff

**Comment by arrfab** [comment]
Ouch ... realizing now that the checkout operation happens *outside* of mock so it's not a mock issue, but rather how koji is doing the checkout : from previous line it's doing it outside mock chroot and pointing to full path to chroot, and then try to rebuild the src.rpm from inside chroot, but it's failing at git clone step.

So instead, I just  modified kojid systemd .service file to use Environment="https_proxy=http://proxy:port" and reloaded systemd and kojid and *then* it's able to do the checkout and then build the rpm.

Sorry for the noise and I'll see with koji folks about that, as it wasn't documented. Thanks for the help/pointer btw :-)
