### ISSUE TITLE
CentOS-8-Stream chroot is broken

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#889]
### Short description of the problem
Builds on COPR and locally (per FrostyX) fail for the centos-stream-8-x86_64 chroot

### Output of `rpm -q mock`
I don't know.  It's on copr.fedorainfracloud.org which I don't have access to.  Output log says:
```
INFO: mock.py version 2.16 starting (python version = 3.10.2, NVR = mock-2.16-1.fc35)...
```

### Steps to reproduce issue

1. Try to build https://download.copr.fedorainfracloud.org/results/brianjmurrell/jellyfin-prerelease/centos-stream-8-x86_64/03903024-jellyfin-web/jellyfin-web-v10.8.0~beta1-1.el8.src.rpm

Resulting log:
https://download.copr.fedorainfracloud.org/results/brianjmurrell/jellyfin-prerelease/centos-stream-8-x86_64/03903024-jellyfin-web/builder-live.log.gz

**Comment by kaiwetlesen** [comment]
Also seeing the same issue with Erigon build in COPR and locally.

Source RPM: https://download.copr.fedorainfracloud.org/results/kwetlesen/Erigon/srpm-builds/03904119/erigon-2022.03.02-1.fc35.src.rpm

Results: https://download.copr.fedorainfracloud.org/results/kwetlesen/Erigon/centos-stream-8-x86_64/03904119-erigon/builder-live.log.gz

**Comment by praiskup** [comment]
Just to copy-paste the error message:
```
ERROR: Source RPM is not installable:
Failed to resolve user mockbuild.
Child died too early.
```

**Comment by praiskup** [comment]
The problem seems to happen when mock updates the chroot:

```
CentOS Stream 8 - PowerTools                                                                                                                                                                                 15 kB/s | 4.4 kB     00:00    
Dependencies resolved.
============================================================================================================================================================================================================================================
 Package                                                           Architecture                                       Version                                                     Repository                                           Size
============================================================================================================================================================================================================================================
Upgrading:
 centos-gpg-keys                                                   noarch                                             1:8-5.el8                                                   extras                                               14 k
Removing dependent packages:
 centos-stream-release                                             noarch                                             8.6-1.el8                                                   @baseos                                              26 k
 centos-stream-repos                                               noarch                                             8-4.el8                                                     @baseos                                              26 k
 setup                                                             noarch                                             2.12.2-6.el8                                                @baseos                                             708 k
 shadow-utils                                                      x86_64                                             2:4.6-16.el8                                                @baseos                                             3.9 M
```

When `shadow-utils` is removed, Mock can not continue with other tasks inside
the chroot.

There are two versions of the `centos-gpg-keys` package, one from ` baseos` and one from `extras`.

**Comment by praiskup** [comment]
Submitted as: https://bugzilla.redhat.com/show_bug.cgi?id=2069548

**Comment by praiskup** [comment]
The bug above is closed => tested locally and seems to work now (both srpm builds above fail, but for a different reason) => closing.  Thank you for the report!
