### ISSUE TITLE
centos8-stream-x86_64 copr builds fail due to removed rpm-build, gcc

### ISSUE THREAD

**Issue by jeredfloyd** [rpm-software-management/mock#893]
### Short description of the problem

(At least my) copr builds are failing on centos8-stream-x86_64, and this arch only.  dnf pulls updated glibc (2.28-196.el8) from baseos which un-installs rpm-build, gcc, etc from appstream. 

Local (f35-hosted) mock builds are successful.

### Output of `rpm -q mock`

In Copr, appears to be: mock-3.0-1.fc35.noarch
In f35 local: mock-2.16-1.fc35.noarch

### Steps to reproduce issue

Resubmit this build for centos8-stream-x86_64:
 https://copr.fedorainfracloud.org/coprs/jered/trafficserver/build/4199835/

I assume this should fail on any project since it doesn't get as far as attempting build steps, but have not yet checked.

### Any additional notes

The only weird "smell" to me here is the rpm-build (etc) packages coming in from @appstream.  This copr project is configured to generate AppStream metadata, which I do not think (or know how to make) happen locally.

**Comment by jeredfloyd** [comment]
See this builder-log for an example.  It doesn't get as far as including the project build dependencies, so I assume this problem is universal: https://download.copr.fedorainfracloud.org/results/jered/trafficserver/centos-stream-8-x86_64/04199835-trafficserver/builder-live.log.gz

**Comment by praiskup** [comment]
Thank you for the report.  This is being discussed here:
https://bugzilla.redhat.com/show_bug.cgi?id=2073385

**Comment by praiskup** [comment]
I believe this was some temporary mirror inconsistency, but honestly, I wasn't able to fully understand the problem in bug 2073385.  But fortunately, this problem is over.  Please reopen if not.
