### ISSUE TITLE
Mock directory clean after 

### ISSUE THREAD

**Issue by srpatcha** [rpm-software-management/mock#90]
mock   --rootdir=$MOCK_LIBEN    --resultdir  $PACKGS --cleanup-after
cleanup-after option not cleaning the directory : --cleanup-after
I defined different path in my local $MOCK_LIBEN 
i can be able to delete with script "results" directory not able to delete "root" directory 
so i'm looking for solution cleanup --rootdir=$MOCK_LIBEN

**Comment by xsuchy** [comment]
I cannot reproduce.

$ mock -r fedora-26-x86_64 --new-chroot /tmp/tito/mock-1.4.3-1.git.2.4b3eabb.fc26.src.rpm  --resultdir=/tmp/foo --cleanup-after
$ LC_ALL=C ls /var/lib/mock/fedora-26-x86_64/
ls: cannot access '/var/lib/mock/fedora-26-x86_64/': No such file or directory

**Comment by Frodox** [comment]
@xsuchy try with `--rootdir` option also

**Comment by xsuchy** [comment]
Indeed.
