### ISSUE TITLE
Request: set `VARIANT_ID=mock` in /etc/os-release in mock chroot

### ISSUE THREAD

**Issue by mattdm** [rpm-software-management/mock#903]
As it is, VARIANT_ID is not set. Having it set would make it possible to distinguish mock environments from "real" systems in my statistics.

This could just be modified/injected manually -- or we could make a fedora-release-mock RPM and make sure that's installed.

**Comment by Conan-Kudo** [comment]
I'd rather have a `fedora-release-*` subpackage.

**Comment by Conan-Kudo** [comment]
I'd rather have a `fedora-release-buildenv` subpackage, but also couldn't you identify by the lack of variant anyway? At this point, systems that lack a variant that show up for a short period of time are basically all Mock or OBS builds.

**Comment by xsuchy** [comment]
Note that Mock already uses a different user agent. See https://github.com/rpm-software-management/mock/pull/608 Is this sufficient for you?

**Comment by mattdm** [comment]
> I'd rather have a fedora-release-buildenv subpackage, but also couldn't you identify by the lack of variant anyway? At this point, systems that lack a variant that show up for a short period of time are basically all Mock or OBS builds.

Maybe the are. But maybe they are systems that people installed with a kickstart, or from the everything netinstall, or have been upgrading forever, or something else. This is about 15% of all systems, so I'd like to have more granularity if I can.

> Note that Mock already uses a different user agent. See https://github.com/rpm-software-management/mock/pull/608 Is this sufficient for you?

Hmmm. Maybe -- it's possible actually that these are getting excluded already -- that part is in the log parsing code which I don't normally touch.

**Comment by mattdm** [comment]
Smooge has confirmed for me that that different user agent means it isn't showing up, even if it does trigger in the mock environment. So that answers part of my question — _none_ of those "generic" stats are mock builds.
