### ISSUE TITLE
best=1 means packages with BR: foo-devel >= 1, foo-devel < 2 cannot be built

### ISSUE THREAD

**Issue by brianjmurrell** [rpm-software-management/mock#906]
### Short description of the problem
If I have a specfile that specifies: `BuildRequires: foo-devel >= 1, foo-devel < 2` when mock tries to build that SRPM when both `foo-devel-1.1` and `foo-devel-2.1` are available in repos available during the build, mock fails to build this as the default `best=1` means `dnf builddep` actually tries to install both `foo-devel-1.1` and `foo-devel-2.2` and fails.

Doesn't this ultimately mean that the default of `best=1` means that no SRPM with a `BuildRequires:` range can be built (without messing around with options)?

### Output of `rpm -q mock`
mock-3.0-1.fc35.noarch

### Steps to reproduce issue
1. Create a specfile per the above
2. create an SRPM from above
3. mock -r <cfg> SRPM

Initially I am just trying to verify my findings above rather than overloading this issue with outputs and debug info, etc.  If my conclusions are not the intended behaviour, I am happy to provide more data to get to the bottom of it.

**Comment by Conan-Kudo** [comment]
cc: @j-mracek

**Comment by xsuchy** [comment]
It would be awesome if you can prepare a Copr project with such two packages for testing this reproducer.

**Comment by brianjmurrell** [comment]
Is that to say then that the behaviour I describe is not what you would expect, even with `best=1`?  I ask because I have run into this behaviour before with just regular `dnf install` and was told that `--no-best` may need to be used to allow DNF to install the inferior version even when `Requres:` is telling it to install the inferior version.  That is, DNF prefers to create an error than install an inferior version even when `Requires:` tells it to, without `--no-best`.

This is a behaviour I find rather counter-intuitive to be honest.  To my mind the _best_ package is the newest one that meets `Requires:` specification (even if that specification is an upper version limitation) even if that's not the newest one in the repos.

In any case, yes, if you think the behaviour I describe above is not what you'd expect even with `best=1` I will see if I can create a reproducer.

**Comment by brianjmurrell** [comment]
Isn't the behaviour I am seeing effectively what is explained here: https://bugzilla.redhat.com/show_bug.cgi?id=2074569#c1?

**Comment by praiskup** [comment]
This sounds like the expected behavior to me, from `dnf.conf`:
```
best   boolean
      True instructs the solver to either use a package with the high‐
      est available version or fail. On False, do not fail if the lat‐
      ...
```
Perhaps we could document a bit more what the "available" term means.  It looks like "available in all enabled repositories", but things would have changed if that was "available in the transaction".

**Comment by praiskup** [comment]
This can be worked-around by a custom mock config:
```python
include("/etc/mock/fedora-rawhide-x86_64.cfg")
config_opts['dnf.conf'] += """
[main]
best=0
"""
```
But you have to know what you are doing;  this is not typically wanted (we normally want to build against the latest available package set).

**Comment by brianjmurrell** [comment]
Ultimately the default of `best=1` just seems odd to me as it directly conflicts (and causes a failure) with any `[Build]Requires: ... <[=] x.y.z` when a version `> x.y.z` exists.  Surely when a package writer writes a `<[=]` specification it's because they know any version higher than that simply will not work.  Defaulting to breaking on such specifications does not seem to be embracing the principle of least surprise.  Moreover even if you want to default to `best=1`, in the case of a `<[=]` specification the concept of _best_ really is the highest version, but no  higher than `x.y.z` so why should `best=1` cause breakage for that case?

But all of that aside, does the suggestion of `best=0` in `config_opts['dnf.conf']`->`[main]` work for CentOS 7 with `yum`?  If not `yum` how about if `config_opts['package_manager'] = 'dnf'` is used on CentOS 7?  I ask because I did already try:
```
config_opts['dnf_builddep_opts'] = ['--nobest']
```
which seems to work-around the issue on EL8 and Leap15 but even with:

```
config_opts['package_manager'] = 'dnf'
```

on CentOS 7, `dnf builddep` complains of `--nobest` not being a valid option:

```
[2022-05-31T20:14:03.622Z] DEBUG file_util.py:17:  ensuring that dir exists: /var/lib/mock/centos+epel-7-x86_64/root/installation-homedir
[2022-05-31T20:14:03.622Z] DEBUG package_manager.py:197:  ['/usr/bin/dnf', 'builddep', '--installroot', '/var/lib/mock/centos+epel-7-x86_64/root/', '--releasever', '7', '--disablerepo', '*', '--enablerepo', '*-artifactory', '--enablerepo', 'spdk:PR-47:34', '--enablerepo', 'dpdk:PR-22:22', '--disablerepo', '*-debug*', '--disablerepo', 'sclo*', '--setopt=deltarpm=False', '--allowerasing', '--disableplugin=local', '--disableplugin=spacewalk', '--disableplugin=versionlock', '--disableplugin=local', '--disableplugin=spacewalk', '--disableplugin=versionlock', '--nobest', '/var/lib/mock/centos+epel-7-x86_64/root//builddir/build/SRPMS/daos-2.0.3-1.7633.g0147ef11.el7.src.rpm']
[2022-05-31T20:14:03.622Z] DEBUG util.py:622:  child environment: None
[2022-05-31T20:14:03.622Z] DEBUG util.py:540:  Executing command: ['/usr/bin/dnf', 'builddep', '--installroot', '/var/lib/mock/centos+epel-7-x86_64/root/', '--releasever', '7', '--disablerepo', '*', '--enablerepo', '*-artifactory', '--enablerepo', 'spdk:PR-47:34', '--enablerepo', 'dpdk:PR-22:22', '--disablerepo', '*-debug*', '--disablerepo', 'sclo*', '--setopt=deltarpm=False', '--allowerasing', '--disableplugin=local', '--disableplugin=spacewalk', '--disableplugin=versionlock', '--disableplugin=local', '--disableplugin=spacewalk', '--disableplugin=versionlock', '--nobest', '/var/lib/mock/centos+epel-7-x86_64/root//builddir/build/SRPMS/daos-2.0.3-1.7633.g0147ef11.el7.src.rpm'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/var/lib/mock/centos+epel-7-x86_64/root/installation-homedir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8', 'LC_MESSAGES': 'C.UTF-8'} and shell False
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:  Failed to set locale, defaulting to C
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:  usage: dnf builddep [-c [config file]] [-q] [-v] [--version]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--installroot [path]] [--nodocs] [--noplugins]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--enableplugin [plugin]] [--disableplugin [plugin]]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--releasever RELEASEVER] [--setopt SETOPTS]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--skip-broken] [-h] [--allowerasing] [-b] [-C]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [-R [minutes]] [-d [debug level]] [--debugsolver]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--rpmverbosity [debug level name]] [-y] [--assumeno]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--enablerepo [repo]] [--disablerepo [repo] | --repo
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [repo]] [--enable | --disable] [-x [package]]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--disableexcludes [repo]] [--repofrompath [repo,path]]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--noautoremove] [--nogpgcheck] [--color COLOR]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--refresh] [-4] [-6] [--destdir DESTDIR] [--downloadonly]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--comment COMMENT] [--bugfix] [--enhancement]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--newpackage] [--security] [--advisory ADVISORY]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--bzs BUGZILLA] [--cves CVES]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--sec-severity {Critical,Important,Moderate,Low}]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      [--forcearch ARCH] [-D 'MACRO EXPR'] [--spec | --srpm]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:                      package [package ...]
[2022-05-31T20:14:03.622Z] DEBUG util.py:443:  dnf builddep: error: unrecognized arguments: --nobest
```

Which seems odd to me as clearly that `dnf` is being run from outside the buildroot on the host that mock is running on which in this case is Fedora 35.  The same host that the same `--nobest` option works fine for EL8 and Leap15.

**Comment by praiskup** [comment]
I would rather wait for some DNF/YUM expert to answer the "best=1" related
design questions.  But sure it would be better to discuss this in DNF
namespace.

> But all of that aside, does the suggestion of best=0 in
> config_opts['dnf.conf']->[main] work for CentOS 7 with yum?

I'm not sure how YUM behaves by default, but the best=0 would be ignored
by yum definitely because the best= option is not implemented there.

> how about if config_opts['package_manager'] = 'dnf' is used on CentOS 7? 

This is a non-default configuration.  Generally, we discourage building
packages on CentOS 7 hosts.  It's really too old.  If there's "dnf"
(extras) it is too old.  It has best= option, but not --best command-line
option.

That said, it could work, if you disable the bootstrap chroot feature (which
will bring other issues on EL7 very likely).


Side note: The normal distro buildroot mechanisms (Koji, but including
mock) expect there's only one version for each package.  Instead of having
multiple versions of the same package in repository(ies), we implemented
"modules" that protect us from the "multiple versions available"
situation.  With this mindset, best=1 is a much safest solution - because
if there is one package in multiple versions, then it is from (a) stable
and (b) updates, and it must be compatible-and-safe-to-update.

The overall `BuildRequires: foo <= STH` concept in Fedora is rather an
explicit "guard" against building my package in the future against an
incompatible `foo` version.  Read it like: I want to fail explicitly,
instead of decrypting some weird build failures in the future.  That said,
this use of `<=` operator doesn't give you a way to choose.

**Comment by brianjmurrell** [comment]
> I would rather wait for some DNF/YUM expert to answer the "best=1" related design questions. But sure it would be better to discuss this in DNF namespace.

Fair enough.

> I'm not sure how YUM behaves by default, but the best=0 would be ignored by yum definitely because the best= option is not implemented there.

As I was thinking.

> This is a non-default configuration. Generally, we discourage building packages on CentOS 7 hosts. It's really too old.

Sure.  Ideally.  But customers still use it so we don't really have a choice.

> If there's "dnf" (extras) it is too old. It has best= option, but not --best command-line option.

But as I asked before, isn't it the `dnf` that is on the system that `mock` is being run on (i.e. a Fedora system) that is used (with `--installroot`), not the `dnf` that is inside the given (i.e. CentOS 7) buildroot?  Or is that the `dnf` that is installed in the bootstrap-chroot, so really, an EL7 (extras) one?

> Side note: The normal distro buildroot mechanisms (Koji, but including mock) expect there's only one version for each package.

Yeah, again, while I can agree that that is ideal, in an environment where you have to support multiple historic release streams where newer releases need newer packages and older ones are constrained to using only older, compatible ones, this becomes difficult.

> Instead of having multiple versions of the same package in repository(ies), we implemented "modules" that protect us from the "multiple versions available" situation.

Indeed.  I suppose this is an alternative solution that we could investigate.

> The overall `BuildRequires: foo <= STH` concept in Fedora is rather an explicit "guard" against building my package in the future against an incompatible `foo` version.

Exactly!

> Read it like: I want to fail explicitly, instead of decrypting some weird build failures in the future.

I guess I read it differently.  I read it as I want to only build with the most recent and compatible version of foo, but I do want to build and not fail just because something newer is available even though it's beyond the compatibility bounds the specfile specifies.

**Comment by j-mracek** [comment]
I am sorry for my late answer. The finding how `BuildRequires: foo-devel >= 1, foo-devel < 2` is handled is correct. DNF handles both request as separate request and with best=True there is no solution. There are two ways how to handle the problem. The fist is the change of build requirements to use richdeps `BuildRequires: foo-devel >= 1 with foo-devel < 2`. Then the request will be handled in the one job (see https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html). I hope that I used the correct operator. The other possibility would be to use `best=False` but it will create a lot of issue in distribution but it will allow to perform the build.

**Comment by nkadel** [comment]
My experiences from decades of RPM building is that the "best=1" operation is actively destructive to stable builds. It's gotten much, much worse with the occasional overlaps of EPEL with RHEL, the inconsistent and confusing publication  of "python%{python3_pkgversuon}" packages as "python3" packages, and the disaster that is "modularity".

One of the best examples of this right now is the "lmdb" SRPM from RHEL 8. Red Hat has consistently refused to publish the lmdb-devel package as part of their OS distribution, though they rely on it internally for compiling Samba and the sssd and freeipa packages which rely on Samba. To rebuild *any* of those packages, the developer must compile lmdb for local use. But if the version and release do not exceed that of the latest RHEL SRPM, leaving "best=1" defined for mock means that mock will not be able to find an lmdb-devel that matches the RHEL published, updated version of lmdb.

This wastes people time. Frankly, I'd prefer to see the "best" option disabled, set to "best=0" everywhere, to avoid just this sort of resolution problem, and stop spending so much of my time generating local .cfg files to avoid this. Or, and this would work equally well, get the "mock --dnf-cmd --nobest" command to actually work.

**Comment by j-mracek** [comment]
> My experiences from decades of RPM building is that the "best=1" operation is actively destructive to stable builds. It's gotten much, much worse with the occasional overlaps of EPEL with RHEL, the inconsistent and confusing publication of "python%{python3_pkgversuon}" packages as "python3" packages, and the disaster that is "modularity".
> 
> One of the best examples of this right now is the "lmdb" SRPM from RHEL 8. Red Hat has consistently refused to publish the lmdb-devel package as part of their OS distribution, though they rely on it internally for compiling Samba and the sssd and freeipa packages which rely on Samba. To rebuild _any_ of those packages, the developer must compile lmdb for local use. But if the version and release do not exceed that of the latest RHEL SRPM, leaving "best=1" defined for mock means that mock will not be able to find an lmdb-devel that matches the RHEL published, updated version of lmdb.
> 
> This wastes people's time. Frankly, I'd prefer to see the "best" option disabled, set to "best=0" everywhere, to avoid just this sort of resolution problem, and stop spending so much of my time generating local .cfg files to avoid this. Or, and this would work equally well, get the "mock --dnf-cmd --nobest" command to actually work.

I understand your point. The building process is sometimes very complicated and painful. But it is like a pyramid. We have 1 package, few maintainers and packages (let say 5), and thousands of users. If packages are built with `best=False` than the build process is less painful for few people but the pain is moved to consumers level therefore thousands of people are affected. It means setting `best=True` for build will not resolve anything. It only makes the problem bigger and affecting more people.

**Comment by praiskup** [comment]
Thank you everyone for the discussion, and for the report.  Switching to `best=False` is not a good idea by default.  There's a possibility to setup `best=0` on top of the mock's configuration, see https://github.com/rpm-software-management/mock/issues/906#issuecomment-1143106829.  But it has a limited scope (e.g. EL7 YUM has no such option).

**Comment by nkadel** [comment]
When, precisely, does "best=1" help anyone at all? Why start the foundation of the pyramid with such a flawed stone? I've not found any instances where it's actually helpful at all, demanding that every related component of the dependency all be at the same revision rather than falling back to an older and demendency compatible suite of packages for successful compilation? Since CentOS is now the beta testing, rather than a RHEL rebuild, I expect the problem to keep recurring with any updates of the capriciously and partially published packages like lmdb.

In theory, and according to the man page, it should be possible to use "mock pkg.rpm --dnf-cmd --nobest" syntax to disable the "best" option for dnf. Unfortunately, the syntax does not work at all, not even with:

     mock init --dnf-cmd --nobest
      mock install glibc --dnf-comd --nobest

Nor does it work with any other order of arguemnts, on RHEL 8 with the EPEL published version of mock and of mock-core-configs.

**Comment by xsuchy** [comment]
> When, precisely, does "best=1" help anyone at all? Why start the foundation of the pyramid with such a flawed stone? 

It is the other way round. We had cases with `best=0` and the newest dependencies cannot be resolved, then the build was done with some old packages as build dependencies, which resulted in an invalid package. E.g., the Python team was hit by this.

**Comment by nkadel** [comment]
Then it sounds like the new python software's dependency list needs revision broken,. I'd suggest that allowing the build to continue with the older, more complete software suite is preferable to breaking the build because someone messed up a linked module or set of software updates, such as lmdb and lmdb-devel, the python38-packing modularized package, or the version linked awscli and python-botocore software. I've run into all of those, in the last few weeks, as I updated my ansible tools, awscli, and samba.

That said, I think that getting the "mock install --dnf-cmd --nobst" syntax working correctly would address my personal needs. It's also helpful for resolving the unfortunately frequent modularity conflicts of minor updates.

**Comment by praiskup** [comment]
Even with python38 (modular) packaging, it is not desired to use `best=0`.
Modular packages have precedence, so non-modular packages shouldn't
be installed instead of them (with or without best).  I'll create a documentation
how-to page on this topic.

The `lmdb-devel` is a separate issue, but it appears to be shipped in RHEL 8
nowadays, try `mock -r rhel-8-x86_64 --install lmdb-devel`.

**Comment by praiskup** [comment]
>  I think that getting the "mock install --dnf-cmd --nobst" syntax working correctly would address my personal needs

See #922 for this.  `--dnf-cmd` executes an isolated DNF command (is not used for altering Mock's DNF commands).

**Comment by nkadel** [comment]
I think I have a better fix. in a local reference to the .cfg file, such as I use for activating python38 to build ansible components:

$ cat ansiblerepo-8-x86_64.cfg 
include('/etc/mock/centos-stream+epel-8-x86_64.cfg')
config_opts['root'] = 'ansiblerepo-{{ releasever }}-{{ target_arch }}'
# Enable python38 modules
config_opts['module_setup_commands'] = [ ('enable', 'python38-devel') ]
# Disable best
config_opts['dnf_vars'] = { 'best': 'False' }

The dnf_vars seem to do the right things, getting me past the modularity broken ansible-packaging. lmdb-devel has been resolved upstream in RHEL, but I'm afraid the modularity and "best" keep confusing each other.

**Comment by praiskup** [comment]
What you miss in the config is `config_opts['macros']['%python3_pkgversion'] = 38` IMO.
The `dnf_vars` seems redundant.  Otherwise looks good.

**Comment by nkadel** [comment]
I'd not thought to set pkg_version in the mock files. It's insufficient for my needs, which also use local compilation for debugging: I  set that for my .spec files as a requirement for RHEL 8 compilation, for other reasons.

I'm still seeing issues with resolving modularity provided versions of python38-packaging with "best=True" left as a default mock setup. Since the default in various mock configs is for "best=1" this does seem to be a cleaner way to set it for me and for othrrs as needed.

**Comment by praiskup** [comment]
The `%python3_pkgversion` is not a package version, it is rather a module version (the module being currently built).  That said, every official python38-foo package is built with this macro explicitly defined by the module build system.  

Building against modules is an important topic, and best=0 at build-time is just a dangerous workaround (as said above).  We need to discuss best practices.  But let's move on though, feel free to submit a more detailed use case in a separate issue (modularity is far from the original question).
