### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by qhaas** [rpm-software-management/mock#907]
### Short description of the problem
[There is a typo in an error message](https://github.com/rpm-software-management/mock/blob/mock-3.0-1/mock/py/mockbuild/util.py#L1005) that manifest when subscription-manager is not installed.  Those of us who blindly copy/paste error messages for missing files into `dnf provides` will find that `/etc/pki/entitlment` does not exist, but `/etc/pki/entitlement` does.

### Output of `rpm -q mock`
$ rpm -q mock
mock-3.0-1.el8.noarch

### Steps to reproduce issue

1. On an EL8 system without subscription-manager installed, run `mock -r /etc/mock/rhel+epel-8-x86_64.cfg --init`
2. Observe the resulting error message has a typo (`entitlment` vs `entitlement`): `ERROR: /etc/pki/entitlment is not a directory, is subscription-manager installed?`

**Comment by praiskup** [comment]
Thank you for the report, and sorry for delay.
