### ISSUE TITLE
Heads up: lots of PR to /docs section (outreach workshop)

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#920]
On 2022-07-12, I will organize an outreach workshop for women in IT. My goal is to show them how they can contribute to open-source projects. I want to show it on some real project and real changes. I have chosen Mock. I identified a bunch of one-liners in /docs section. 
This is just a heads up that on that day, this project may receive up to 13 pull requests to this directory. I will work on them and either merge them or close them by the very next day.

**Comment by praiskup** [comment]
Labeled by "workshop".

**Comment by praiskup** [comment]
And this event is over.
