### ISSUE TITLE
build mock for ubuntu package remove to repository on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by amidevous** [rpm-software-management/mock#923]
hello i currently have a multi system package compilation system which can compile both deb packages with pbuilder and rpm packages with mock

however this system and base on ubuntu 18.04 LTS

which is obsolete since April 2022

if at the time I had chosen this system it is because it was the only linux system where pbuilder and mock were found in the repositories

but when installing the surprise update the mock package

is no longer in the repositories and the old version being in python 2

therefore incompatible with python 3 uninstall during the upgrade

I therefore come here to recompile it from the source code

and surprise no indication to know how to do

just told us how to compile mock in rpm but nothing else

no indication on how to install it on a non red hat system or on how to copy it to deb

no correct makefile either because the makefile

present also and only allows to create an rpm package of mock

so there is no indication on how to install it on a non red hat system

Thanks for your help

ps file generated on ubuntu

[mock-ubuntu-build.zip](https://github.com/rpm-software-management/mock/files/8953934/mock-ubuntu-build.zip)

**Comment by xsuchy** [comment]
We have a Makefile https://github.com/rpm-software-management/mock/blob/main/mock/Makefile but it uses Tito https://github.com/rpm-software-management/tito which is not available for Debian.

I am not aware of anyone from current contributors who either has the knowledge of DEB packaging or is willing to maintain it for Debian/Ubuntu. If you, or anyone else, is willing to maintain the package, we can help you with what needs to be done (basically https://github.com/rpm-software-management/mock/blob/main/mock/mock.spec#L142 ) but that is all.

Are you willing to maintain the DEB package?

**Comment by amidevous** [comment]
yes the install part I saw but what blocks it is his

https://github.com/rpm-software-management/mock/blob/main/mock/mock.spec#L126

setup and prep part

could not apply this type of modification

in debian builds

unless you have them in a patch file

should be created

debian/patches/version.patch

file content patch on this file

and create file

debian/patches/series

content

version.patch

and those for each version of mock

**Comment by amidevous** [comment]
you should also put yum or dnf back

because yum was also removed

it is false first to see from this side too

**Comment by Conan-Kudo** [comment]
We can use a spec file for building Debian packages, that's not a big deal (cf [debbuild](https://github.com/debbuild/debbuild)). But the real problem is that `rpm` in Debian/Ubuntu is broken out of the box, since it creates the rpmdb in `$HOME`. Additionally, we'd need to package the DNF package manager stack. If we started at 22.04 LTS, we could avoid packaging DNF, since it's already there. But there's still the matter of a broken RPM package.

**Comment by Conan-Kudo** [comment]
Note that you could also choose to use CentOS Stream 8 and be able to build Debian/Ubuntu packages and Fedora packages. Both `mock` and `pbuilder` are available in [EPEL](https://docs.fedoraproject.org/en-US/epel/) for CentOS Stream 8.

**Comment by amidevous** [comment]
yes but precisely it is not normal that this is possible in one direction and not in the other

if pbuilder and on red hat distributions

mock must also be on debian distributions

especially since it has always been the case

**Comment by xsuchy** [comment]
> mock must also be on debian distributions

It must not. Debian (and Fedora) is a volunteer-based distro. There needs to be a volunteer. If there is no volunteer then there is no package.

**Comment by amidevous** [comment]
I more or less find it but I'm stuck with it

https://github.com/rpm-software-management/mock/blob/main/mock/mock.spec#L152

consolehelper file not found

**Comment by Conan-Kudo** [comment]
If you want to package it Debian-style, go talk to the Debian RPM packaging team and ask to help them upgrade Mock. DNF is already packaged in the latest versions of Debian, so they should be able to ship Mock again.

**Comment by Conan-Kudo** [comment]
If you want to package it Debian-style, go talk to [the Debian RPM packaging team](https://wiki.debian.org/Teams/pkg-rpm) and ask to help them upgrade Mock. DNF is already packaged in the latest versions of Debian, so they should be able to ship Mock again.
