### ISSUE TITLE
not solved build mock for ubuntu package

### ISSUE THREAD

**Issue by amidevous** [rpm-software-management/mock#925]
https://github.com/rpm-software-management/mock/issues/923

I have this problem here when I want to make the package there are 2 files that do not exist in the project

consolehelper

https://github.com/rpm-software-management/mock/blob/mock-3.0-1/mock/mock.spec#L152

not found here

https://github.com/rpm-software-management/mock/blob/mock-3.0-1/mock/consolehelper

mock

https://github.com/rpm-software-management/mock/blob/mock-3.0-1/mock/mock.spec#L166

not found here

https://github.com/rpm-software-management/mock/blob/mock-3.0-1/mock/mock

file and folder found online

COPYING
docs
pylintrc
Makefile
etc
requirements.txt
README.md
integration-tests
run-tests.sh
contrib
mock.spec
scripts
create_default_route_in_container.sh
mockchain
setup.cfg
py
tests

```
wget https://github.com/rpm-software-management/mock/releases/download/mock-3.0-1/mock-3.0.tar.gz -O mock_3.0.orig.tar.gz

tar -xvf mock_3.0.orig.tar.gz

cd mock-3.0

dh_make -e email@example.com -s -y

nano debian/rules
```

for information we cannot use a symbolic link in a deb so must copy the file but we cannot copy an existing file

file content

```
#!/usr/bin/make -f
%:
	dh $@
override_dh_auto_install:
	mkdir -p debian/mock/etc/mock/eol/templates
	mkdir -p debian/mock/etc/mock/templates
	install -d debian/mock/usr/bin
	install -d debian/mock/usr/libexec/mock
	install mockchain debian/mock/usr/bin/mockchain
	install py/mock-parse-buildlog.py debian/mock/usr/bin/mock-parse-buildlog
	install py/mock.py debian/mock/usr/libexec/mock/mock
	cp consolehelper debian/mock/usr/bin/mock
	install create_default_route_in_container.sh debian/mock/usr/libexec/mock/
	install -d debian/mock/etc/pam.d
	cp -a etc/pam/* debian/mock/etc/pam.d/
	install -d debian/mock/etc/mock
	cp -a etc/mock/* debian/mock/etc/mock/
	install -d debian/mock/etc/security/console.apps/
	cp -a etc/consolehelper/mock debian/mock/etc/security/console.apps/mock
	install -d debian/mock/usr/share/bash-completion/completions/
	cp -a etc/bash_completion.d/* debian/mock/usr/share/bash-completion/completions/
	cp mock debian/mock/usr/share/bash-completion/completions/mock-parse-buildlog
	install -d debian/mock/etc/pki/mock
	cp -a etc/pki/* debian/mock/etc/pki/mock/
	install -d debian/mock/usr/lib/python3/dist-packages/
	cp -a py/mockbuild debian/mock/usr/lib/python3/dist-packages/
	install -d debian/mock/usr/share/man/man1
	cp -a docs/mock.1 docs/mock-parse-buildlog.1 debian/mock/usr/share/man/man1/
	install -d debian/mock/usr/share/cheat
	cp -a docs/mock.cheat debian/mock/usr/share/cheat/mock
	install -d debian/mock/var/lib/mock
	install -d debian/mock/var/cache/mock
	mkdir -p debian/mock/usr/share/doc/mock
	install -p -m 0644 docs/site-defaults.cfg debian/mock/usr/share/doc/mock
	sed -i 's/^_MOCK_NVR = None$/_MOCK_NVR = "mock-3.0-1"/' debian/mock/usr/libexec/mock/mock
override_dh_test:
	./run-tests.sh --no-cov
```

try build

`debuild`

result

```
dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package mock
dpkg-buildpackage: info: source version 3.0-1
dpkg-buildpackage: info: source distribution jammy
dpkg-buildpackage: info: source changed by amidevous <amidevous@example.com>
dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
debian/rules clean
dh clean
dh_clean
dpkg-source -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building mock using existing ./mock_3.0.orig.tar.gz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: building mock in mock_3.0-1.debian.tar.xz
dpkg-source: info: building mock in mock_3.0-1.dsc
debian/rules binary
dh binary
dh_update_autotools_config
dh_autoreconf
create-stamp debian/debhelper-build-stamp
dh_prep
debian/rules override_dh_auto_install
make[1]: Entering directory '/root/mock/mock-3.0'
mkdir -p debian/mock/etc/mock/eol/templates
mkdir -p debian/mock/etc/mock/templates
install -d debian/mock/usr/bin
install -d debian/mock/usr/libexec/mock
install mockchain debian/mock/usr/bin/mockchain
install py/mock-parse-buildlog.py debian/mock/usr/bin/mock-parse-buildlog
install py/mock.py debian/mock/usr/libexec/mock/mock
cp consolehelper debian/mock/usr/bin/mock
cp: cannot stat 'consolehelper': No such file or directory
make[1]: *** [debian/rules:33: override_dh_auto_install] Error 1
make[1]: Leaving directory '/root/mock/mock-3.0'
make: *** [debian/rules:17: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
```

```
cp consolehelper debian/mock/usr/bin/mock
cp: cannot stat 'consolehelper': No such file or directory
```

same thing with mock impossible to copy in

debian/mock/usr/share/bash-completion/completions/mock-parse-buildlog

since this one does not exist in the project I want to make the package but it is wrong for that to clearly indicate to you where it is 2 files because in the project it does not exist

**Comment by Conan-Kudo** [comment]
consolehelper is a separate tool entirely, part of the `usermode` package, which already exists in Debian/Ubuntu.

**Comment by amidevous** [comment]
ok wrong change libexec by sbin

and there is another problem there are dependencies that are not indicated in the spec file

like for example python3-gtar

**Comment by amidevous** [comment]
on ubuntu

`ls -ld /usr/bin/gtar
ls: cannot access '/usr/bin/gtar': No such file or directory

ls -ld /usr/bin/tar
-rwxr-xr-x 1 root root 517952 Mar 25 09:52 /usr/bin/tar

apt-get -y install gtar

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gtar

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bsdtar
`

if it's the same why not use tar directly

because your gtar does not exist

**Comment by praiskup** [comment]
Ad tar, take a look at PR#926.  I'm sure it is not ideal state (e.g. for `config_opts['tar'] = 'gnutar'` we blindly use `tar`).  But once we find a distribution where this causes problems, we can fix the `config_opts['tar']` option appropriately.
