### ISSUE TITLE
How to update the generated chroot?

### ISSUE THREAD

**Issue by misterhsp** [rpm-software-management/mock#949]
### Short description of the problem

How to update the generated chroot?
The man page does not give any information or I am blind.

thanks...

**Comment by praiskup** [comment]
Thank you for the question.  Try just `mock --update`.

**Comment by misterhsp** [comment]
Thanks, the man page is not clear about this

...

**Comment by praiskup** [comment]
I can see this in the man mock(1):
```
       --update [PACKAGE...]
              Do  a  package update inside the chroot. The package list is op‐
              tional, if omitted, all packages will be updated. No 'clean'  is
              performed.

```
