### ISSUE TITLE
Results files for bootstrap are appended to rather than overwritten

### ISSUE THREAD

**Issue by pghmcfc** [rpm-software-management/mock#959]
### Short description of the problem

The results files (root.log, build.log etc.) for the bootstrap root are only ever appended to, never overwritten. Hence, over a long period of time they grow very large,

### Output of `rpm -q mock`

mock-3.1-1.fc36.noarch

### Steps to reproduce issue

1. Remove the results directory for a bootstrap chroot
2. Do a mock build using that chroot
3. Do "ls -l results" for that bootstrap chroot
4. Touch the config file for the choot so that existing caches won't be used
5. Repeat the mock build
6. Do "ls -l results" for that bootstrap chroot

When I do this, the "ls -l results" after the second build shows files that are twice as large as after the first build.
I'd expect the refreshing of a bootstrap chroot to overwrite the existing files rather than append to them.

### Any additional notes

If there are any issues reproducing this then I can repeat it and provide more details but I suspect that won't be necessary,

**Comment by pghmcfc** [comment]
In fact it's worse than I thought. Looking at the contents of the results files in the bootstrap directory, I see that the root.log and build.log also include the details of the actual build (in the non-bootstrap chroot) in addition to the population of the bootstrap chroot itself. It's as if logging handles have been left open at the end of the bootstrap phase and inherited by the main build.

**Comment by praiskup** [comment]
Thank you for the report, and I agree - this deserves a fix.  It is on a track in another issue #539 already so I'm going to close.
Patches would be nice!
