### ISSUE TITLE
Add Oracle Linux 9 support

### ISSUE THREAD

**Issue by Mno-hime** [rpm-software-management/mock#962]
Add Oracle Linux 9 and their EPEL support to Mock configurations.

We build Enterprise Linux RPMs in Oracle Linux chroots and can't provide EL9 packages unless Oracle Linux 9 and their EPEL support is added.

(I hope someone from Oracle works on it already but knowing it for sure and having a timeline always helps.)

**Comment by xsuchy** [comment]
We are not going to actively work on this, but we will happily review pull-request.

**Comment by Mno-hime** [comment]
Implemented by https://github.com/xsuchy/distribution-gpg-keys/pull/72 and https://github.com/rpm-software-management/mock/pull/963.
