### ISSUE TITLE
Bind mount /dev/fuse to mock environment

### ISSUE THREAD

**Issue by andraspatka** [rpm-software-management/mock#971]
### Short description of the problem

Hi guys, I saw that bind mounting directories is supported, and also bind mounting files is also kinda supported. Is there a way to write the config file, so that it automatically bind mounts a devices file to the chroot?

Snippet from the config file that I've used:

```
config_opts['plugin_conf']['bind_mount_enable'] = True
config_opts['plugin_conf']['bind_mount_opts']['files'].append(('/dev/fuse', '/dev/fuse'))
```

This gives:
```
KeyError: 'files'

ERROR: Error in configuration
```

I've also tried to use the key 'file' but I got the same error.

As a workaround I've tried to manually copy the device file with:
```
cp -a /dev/fuse /var/lib/mock/<mock_config>/root/dev/fuse
```

But it disappears any time that I run a subsequent mock command.

As another workaround, I tried to create the special file in the mock env, but it always give permission denied, even if it's ran with root:

```
mknod -m a=rw /dev/fuse c 10 229
```

### Output of `rpm -q mock`

`mock-3.0-1.el8.noarch`

### Steps to reproduce issue

1. Create config file with the above mentioned snippet
2. Run: `sudo mock -r <config> --init --yum`

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

  config_opts['additional_packages'] = []
config_opts['bootstrap_image'] = 'registry.access.redhat.com/ubi8/ubi'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = ('install tar gcc-c++ redhat-rpm-config redhat-release which xz sed make bzip2 '
 'gzip gcc coreutils unzip shadow-utils diffutils cpio bash gawk rpm-build '
 'info patch util-linux findutils grep epel-rpm-macros')
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/chroot-aliases.cfg',
 '/etc/mock/rhel+epel-8-x86_64.cfg',
 '/etc/mock/rhel-8-x86_64.cfg',
 '/etc/mock/templates/rhel-8.tpl',
 '/etc/mock/templates/epel-8.tpl']
config_opts['description'] = 'RHEL 8 + EPEL'
config_opts['dist'] = 'el8'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=1\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:el8\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '# repos\n'
 '[rhel-baseos]\n'
 'name = Red Hat Enterprise Linux - BaseOS\n'
 'baseurl = '
 'https://cdn.redhat.com/content/dist/rhel8/$releasever/$basearch/baseos/os\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/redhat-uep.pem\n'
 'sslclientkey = /etc/pki/entitlement/{{ redhat_subscription_key_id '
 '}}-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/{{ redhat_subscription_key_id }}.pem\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/redhat/RPM-GPG-KEY-redhat8-release\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[rhel-appstream]\n'
 'name = Red Hat Enterprise Linux - AppStream\n'
 'baseurl = '
 'https://cdn.redhat.com/content/dist/rhel8/$releasever/$basearch/appstream/os\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/redhat-uep.pem\n'
 'sslclientkey = /etc/pki/entitlement/{{ redhat_subscription_key_id '
 '}}-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/{{ redhat_subscription_key_id }}.pem\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/redhat/RPM-GPG-KEY-redhat8-release\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[codeready-builder]\n'
 'name = Red Hat Enterprise Linux - CodeReady Linux Builder\n'
 'baseurl = '
 'https://cdn.redhat.com/content/dist/rhel8/$releasever/$basearch/codeready-builder/os\n'
 'sslverify = 1\n'
 'sslcacert = /etc/rhsm/ca/redhat-uep.pem\n'
 'sslclientkey = /etc/pki/entitlement/{{ redhat_subscription_key_id '
 '}}-key.pem\n'
 'sslclientcert = /etc/pki/entitlement/{{ redhat_subscription_key_id }}.pem\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/redhat/RPM-GPG-KEY-redhat8-release\n'
 'skip_if_unavailable=False\n'
 '\n'
 '\n'
 '[epel]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-source]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=testing-epel$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch - '
 'Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=testing-debug-epel$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing-source]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch - '
 'Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=testing-source-epel$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-modular-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch - '
 'Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-source]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch - '
 'Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-$releasever\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if koji_primary_repo != None and koji_primary_repo != "epel" %}\n'
 '[local-epel]\n'
 '{% else %}\n'
 '[local]\n'
 '{% endif %}\n'
 'name=Extra Packages for Enterprise Linux $releasever - Koji Local - '
 'BUILDROOT ONLY!\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel$releasever-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n')
config_opts['dnf_install_command'] = 'install dnf dnf-plugins-core subscription-manager'
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'lt-infra-ci-lin.swinfra.net',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
                                                             'AlmaLinux 8 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-8': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '8 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '8) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL 8 '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'circlelinux+epel-8': {'description': ['Builds '
                                                                    'against '
                                                                    'Circle '
                                                                    'Linux 8 '
                                                                    'repositories, '
                                                                    'together '
                                                                    'with the '
                                                                    'official '
                                                                    'EPEL '
                                                                    'repositories.',
                                                                    'Project '
                                                                    'page: '
                                                                    'https://cclinux.org/']},
                             'rhel+epel-8': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '8 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-8': {'description': ['Builds against '
                                                              'Rocky Linux 8 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}},
 'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
                                                             'AlmaLinux 9 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-9': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '9 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '9) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'rhel+epel-9': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '9 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-9': {'description': ['Builds against '
                                                              'Rocky Linux 9 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}}}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.d0awwzly:/etc/resolv.conf',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                     'root': 'rhel+epel-8-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                 'compress': None,
                 'dir': '/var/cache/mock/rhel+epel-8-x86_64/ccache/u274015373/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                 'root': 'rhel+epel-8-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                      'root': 'rhel+epel-8-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                        'root': 'rhel+epel-8-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                  'root': 'rhel+epel-8-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                   'root': 'rhel+epel-8-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                'root': 'rhel+epel-8-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                    'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                    'root': 'rhel+epel-8-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                        'root': 'rhel+epel-8-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                     'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                     'root': 'rhel+epel-8-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                  'root': 'rhel+epel-8-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/rhel+epel-8-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                     'root': 'rhel+epel-8-x86_64',
                     'tar': 'gnutar'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                            'root': 'rhel+epel-8-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                  'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                  'root': 'rhel+epel-8-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                 'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                 'root': 'rhel+epel-8-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
               'root': 'rhel+epel-8-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                'root': 'rhel+epel-8-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/rhel+epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/rhel+epel-8-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/rhel+epel-8-x86_64/result',
                    'root': 'rhel+epel-8-x86_64'}}
config_opts['print_main_output'] = True
config_opts['redhat_subscription_key_id'] = '5713545858910854925'
config_opts['redhat_subscription_required'] = True
config_opts['releasever'] = '8'
config_opts['root'] = 'rhel+epel-8-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
config_opts['yum_install_command'] = 'install yum yum-utils subscription-manager'

</details>

**Comment by andraspatka** [comment]
So I've found the solution, but thought that I would open this issue regardless, hopefully it will benefit somebody else.
The following line seems to work great with binding the host's /dev/fuse to chroot /dev/fuse:

```
config_opts['nspawn_args'].append('--bind=/dev/fuse')
```

Maybe could you guys complement the documentation with this scenario?
Thanks!

**Comment by xsuchy** [comment]
It is documented here:
https://rpm-software-management.github.io/mock/Plugin-BindMount

> config_opts['plugin_conf']['bind_mount_enable'] = True
> config_opts['plugin_conf']['bind_mount_opts']['files'].append(('/dev/fuse', '/dev/fuse'))

You have several problems here:

1) the option is 'dirs' even for files (this should be documented)
2) the KeyError is because the 'files' does not exist. So

```
config_opts['plugin_conf']['bind_mount_opts']['files'] = [('/dev/fuse', '/dev/fuse')]
```
would work. At least not produce error, but no code operates with 'files' so it will not do what you want.

**Comment by andraspatka** [comment]
Thanks! Could you maybe also document the use-case of wanting to bind device files?

so something like this:
```
config_opts['nspawn_args'].append('--bind=/dev/fuse')
```

Or maybe it's already documented, and I just couldn't find it. If so, please ignore this.

**Comment by xsuchy** [comment]
just do

    config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/dev/fuse', '/dev/fuse'))
