### ISSUE TITLE
Is it possible to run inside docker container that doesn't have SYS_ADMIN capability

### ISSUE THREAD

**Issue by achal1012** [rpm-software-management/mock#984]
### Short description of the problem
I have been looking at the unshare namespace failed issue when the mock is run inside a docker container that doesn't have SYS_ADMIN capability. 

I have tried updating the logic for running_in_docker() to support cgroup v2: 

```
def running_in_docker():
    """ Returns True if we are running inside of Docker container """
    # Docker container has different cgroup than PID 1 of host.
    # And have "docker" in that tree.
    with open('/proc/self/cgroup') as f:
        for line in f:
            items = line.split(':')
            if 'docker' in items[2]:
                return True
    # For containers with cgroupv2
    with open('/proc/self/mountinfo') as f:
        for line in f:
            if '/docker/containers/' in line:
                return True
    return False
```
This change should go to master if you folks think this is accurate. 

However, my question is can I use mock inside docker without giving SYS_ADMIN capability to it? 

### Output of `rpm -q mock`
```
rpm -q mock
mock-2.17-1.el7.noarch
```

**Comment by praiskup** [comment]
Thank you for the question.

The code was originally added for https://bugzilla.redhat.com/show_bug.cgi?id=1336750
Where @xsuchy claims SYS_ADMIN is needed for mounting /proc filesystem.

This might not be truth at least for the user-namespaces scenario.  It is possible to run
Mock in rootless container (podman, not docker).

> mock-2.17-1.el7.noarch

Just a warning, mock for EL7 is not likely to get any major updates.  Building RPMs requires a reasonably new RPM/DNF stack, please use EL9 or at least EL8 (even for building EL7 packages).

**Comment by achal1012** [comment]
Hi @praiskup thank you for confirming that it is not possible to run mock inside a docker container without SYS_ADMIN capability.

**Comment by praiskup** [comment]
Well, with the --privileged user namespaces you actually have sys_admin in that namespace (!= the host sys_admin).

**Comment by achal1012** [comment]
Sorry I didn't understand that. After I circumvent "Namespace Unshate Failed" I hit this error: 
```
read(9, 0xc000302000, 32768)            = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(4, [], 128, 0, NULL, 2)     = 0
epoll_pwait(4, [{EPOLLIN, {u32=3668807072, u64=139774789520800}}], 128, -1, NULL, 0) = 1
futex(0xc932b8, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xc931b8, FUTEX_WAKE_PRIVATE, 1)  = 1
read(9, "ERROR: Command failed: \n # /bin/"..., 32768) = 114
write(2, "ERROR: Command failed: \n # /bin/"..., 114ERROR: Command failed: 
 # /bin/mount -n -t tmpfs -o rprivate tmpfs /var/lib/mock/el7-x86_64-bootstrap/root/proc

) = 114
```
I need to use docker for the build.

**Comment by achal1012** [comment]
Added a pull request: https://github.com/rpm-software-management/mock/pull/986 for updating running_in_docker function.
