### ISSUE TITLE
[RFE] option for "best effort" enabling/disabling of internet with(out) nspawn

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#99]
Copr has a button named "enable networking" for builds.  Currently we need to have hacks per-chroot in copr tooling since the "enable networking" needs to be mapped either to `use_host_resolv` or to `rpmbuild_networking` mock options.

It would be nice to have some general option like  `avoid_networking = 0/1` that would automatically enable/disable `use_host_resolv` or `rpmbuild_networking` (or both if that isn't problem).

**Comment by praiskup** [comment]
See also #89.

**Comment by avikivity** [comment]
Additionally, I would like a command-line option for `rpmbuild_networking`.

**Comment by praiskup** [comment]
I'm fine with `--enable-network` which does this.

**Comment by praiskup** [comment]
> Additionally, I would like a command-line option for rpmbuild_networking.

There is `--config-opts=KEY=VALUE`.
