### ISSUE TITLE
Can no longer run mock as root

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/mock#990]
With the new release of mock - 3.2 - it seems that one can no longer run mock as root. If you try to do so, you get an error `Can't parse Mock configuration under root`.

This has always been possible before, and openQA tests rely on doing it. With this change in Rawhide, two openQA tests fail on every Rawhide update.

I wouldn't be surprised if others also run mock as root. If this is meant to be a 'security measure' against the use of `exec` in the code, well, that seems questionable. `exec` is a security risk and a code smell whether run as a regular user or as root; regular users have lots of important data and secrets too. The comment even acknowledges this...

**Comment by praiskup** [comment]
Thank you for the early report, right - running Mock as root is probably a widely used pattern.  Relaxing this in #991

**Comment by hroncok** [comment]
This is from Fedora CI:

```
mock.noarch                                   3.2-1.fc38                                  @distro-build
mock-core-configs.noarch                      37.8-1.fc38                                 @distro-build
mock-filesystem.noarch                        3.2-1.fc38                                  @distro-build
...
+ mock --isolation=simple -r /tmp/fedora-38-x86_64-ci.cfg --enablerepo=local init
ERROR: Can't parse Mock configuration under root
```

**Comment by praiskup** [comment]
> exec is a security risk and a code smell whether run as a regular user
> or as root; regular users have lots of important data and secrets too.
> The comment even acknowledges this...

Yes, long-term we should migrate out from the format of configuration
files have now (python code with exec()), but that will be a huge change,
and a lot of stuff will need to be changed in all the infrastructure using
Mock.

> This has always been possible before, and openQA tests rely on doing it.

Still, many parts of Mock logic are done non-privileged normally even now,
for good.  If not for security reasons, it is good to run the QA tasks the
same way they are normally done in production.  E.g. in Copr, we also
use disposable VMs, but we build non-root.

**Comment by hroncok** [comment]
Due to unfortunate design choices in the Fedora CI, running tests under non-root user is very tedious. We've done it before to test a regression/fix involving unwanted PermissionErrors, but  with mock it would require manually creating users and adding them o the mock group in every package we test. I understand that this would be nicer, so I'll look into it, but if mock wants to drop support for running under root, it should probably deprecate it first.

**Comment by praiskup** [comment]
Understood.  Running Mock-as-root continues to be a supported thing.  Once my time permits, I'll try to take a look at #992 (unless somebody is faster).

**Comment by praiskup** [comment]
See also: https://bugzilla.redhat.com/show_bug.cgi?id=2135203
