### ISSUE TITLE
36.13 el7 depends on rolled-back distributed-gpg-key

### ISSUE THREAD

**Issue by dhawton** [rpm-software-management/mock#994]
### Short description of the problem

I hope I am posting this in the correct place...

Yesterday, distribution-gpg-keys rolled back to 1.75 in EPEL 7 (https://bodhi.fedoraproject.org/updates/?packages=distribution-gpg-keys and https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-deb54655a2). This breaks the mock-core-config 36.13 version in EPEL:

#7 85.36 Error: Package: mock-core-configs-36.13-1.el7.noarch (epel)
#7 85.36            Requires: distribution-gpg-keys >= 1.77
#7 85.36            Available: distribution-gpg-keys-1.75-1.el7.noarch (epel)
#7 85.36                distribution-gpg-keys = 1.75-1.el7

[root@3269763bf22d /]# yum --showduplicates list distribution-gpg-keys
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.hoobly.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: repo1.sea.innoscale.net
 * updates: mirror.team-cymru.com
Available Packages
distribution-gpg-keys.noarch                                                                                                  1.75-1.el7                                                                                                  epel
[root@3269763bf22d /]# yum --showduplicates list mock-core-configs
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.hoobly.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: repo1.sea.innoscale.net
 * updates: mirror.team-cymru.com
Available Packages
mock-core-configs.noarch                                                                                                   36.13-1.el7                                                                                                    epel

### Output of `rpm -q mock`

N/A

### Steps to reproduce issue

1. Fresh install CentOS 7, install `epel-release`
2. Try to install mock

Do not forget to mention full commandline with the mock command you executed.

**Comment by praiskup** [comment]
Thank you for the report!
Updated package is here, please leave a karma: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-318362b0c0
